### ISSUE TITLE
Another memory leak in simple code despite using !/0

### ISSUE THREAD

**Issue by stefan-kral** [trealla-prolog/trealla#103]
Consider this:
<pre>
q.
q.

p :- q, !, p.
</pre>

I expected a query `?- p.` runs in constant memory.

At the moment this is not like that.
There seems to be a problem reclaiming memory in code with deep-cuts.

**Comment by infradig** [comment]
Yes there is.

**Comment by stefan-kral** [comment]
IMO solving this problem should be doable for someone who knows the nuts and bolts of Traella Prolog (-> not me).

But if this is not important to you *now*, I'd be willing to close the issue for now (so the list of open issues is shorter).

**Comment by infradig** [comment]
No, I hope to address it. I think once it did handle it.

**Comment by infradig** [comment]
Fix is just for the trivial case as above.

**Comment by stefan-kral** [comment]
OK, more comprehensive cutting would be better. But if the fix doesn't break anything, I consider it better. Closing...
