### ISSUE TITLE
Not all argument number checks done in format/[2,3]

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#104]
I am comparing Trealla Prolog with SWI-Prolog. It
seems SWI-Prolog does two checks, although the
error term isn't extremly standard:
```
/* SWI-Prolog 9.1.2 */
?- catch(format('abc ~w def', []), error(E,_), true).
E = format('not enough arguments').

?- catch(format('abc ~w def', [a,b]), error(E,_), true).
E = format('too many arguments').
```
In Trealla Prolog, I see a nicer error term, but the 
second check seems to be currently missing. I get 
the following results:
```
/* Trealla Prolog 2.7.30 */
?- catch(format('abc ~w def', []), error(E,_), true).
   E = domain_error(missing_args,[]).

?- catch(format('abc ~w def', [a,b]), error(E,_), true).
abc a def   true.
```
Could be a bug or feature?

**Comment by infradig** [comment]
SWI is the only one I have that does that check. It seems like an excessive
restriction.

**Comment by Jean-Luc-Picard-2021** [comment]
Thats kind of a rumor that only SWI Prolog does the check.
I find that Scryer Prolog does the check as well:
```
$ target/release/scryer-prolog -v
"v0.9.1-65-gf9e3bdb6"
$ target/release/scryer-prolog
?- use_module(library(format)).
   true.
?- catch(format("abc ~w def", [a,b]), error(E,_), true).
   E = domain_error(empty_list,"b").
```
Java printf doesn't do the check:
```
?- catch(printf('abc %s def', []), error(E,_), true).
Error: Unknown template: representation_error('Format specifier ''%s''')
/* java.util.MissingFormatArgumentException extends IllegalFormatException */

?- catch(printf('abc %s def', [p,q]), error(E,_), true).
abc p def 
```

**Comment by infradig** [comment]
Mine doesn't,  must have changed.

**Comment by infradig** [comment]
Ok, I updated Scryer and you're right.

**Comment by pmoura** [comment]
> SWI is the only one I have that does that check. It seems like an excessive restriction.
> […](#)

Other systems perform these checks. E.g. ECLiPSe, LVM, and SICStus Prolog. Unfortunately,  there's no de facto standard for the exceptions that are throw in these cases. Related, Logtalk's `format` abstraction library defines (compile time) linter checks that include too few/many arguments.

**Comment by Jean-Luc-Picard-2021** [comment]
Now it wurks:
```
Trealla Prolog (c) Infradig 2020-2022, v2.7.32
?- format('abc ~w def', []).
   error(domain_error(non_empty_list,[]),format/2).
?- format('abc ~w def', [a,b]).
   error(domain_error(empty_list,"b"),format/2).
```
What about version numbers that do not explode. Like
instead 2.7.31 and now 2.7.32, something like
2.7.30-NNNN. For bug fixes inside a minor release?

Is there a cut over from release candidate to release?
Everything I get via "git pull" is release? For example my
Chrome Browser just went from Version 109.0.5414.74 to

Version 109.0.5414.75. I am following a slightly different
strategy, I don't change release numbers that are for example
display in the top-level welcome sermon, if people want

to know the effective release, i.e. release plus fixes,
they need to inspect the Git automatic tag. Which anyway
happens only for the head, and the archive releases

remain all unchanged, there is no devel and stable.

Disclaimer: Don't take this as a non-acceptance of what
you are doing with Trealla, you are doing a great job. Maybe
your rapid versions are tied to some develelopment environment,

I just wanted to share an observation. Don't worry, be happy.
