### ISSUE TITLE
tplgt working as tplgt -q

### ISSUE THREAD

**Issue by pmoura** [trealla-prolog/trealla#105]
```text
$ tplgt
Trealla Prolog (c) Infradig 2020-2022, v2.7.32
?- current_logtalk_flag(report, Value).
   Value = warnings.
?- current_prolog_flag(verbose, Value).
   Value = true.
```

But `tplgt` is expected to output the default Logtalk messages at startup (flags and banner).

The relevant code (in the Trealla adapter file) is:

```logtalk
'$lgt_default_flag'(report, Report) :-
	(	catch(current_prolog_flag(verbose, false), _, fail) ->
		Report = warnings
	;	Report = on
	).
```

This is a recent regression. Not using `catch/3`, which is there for users of older version of Trealla before the `verbose` flag was added, doesn't solve the problem.

**Comment by pmoura** [comment]
If I make the following change:

```logtalk
'$lgt_default_flag'(report, Report) :-
	(	current_prolog_flag(verbose, false) ->
		write('HERE\n'),
		Report = warnings
	;	Report = on
	).
```

I get:

```text
$ tplgt
HERE
Trealla Prolog (c) Infradig 2020-2022, v2.7.32
?- 
```

This suggest some recent order change in Trealla when processing command-line options as Logtalk is loaded by the `tplgt.sh` integration script using the `-l` option:

```bash
if ! [ "$TPL_LIBRARY_PATH" ] || [ -d "$TPL_LIBRARY_PATH" ]; then
	exec tpl --library "$(dirname "$(which tpl)")/library" -l "$LOGTALKHOME/integration/logtalk_tp.pl" "$@"
else
	exec tpl -l "$LOGTALKHOME/integration/logtalk_tp.pl" "$@"
fi
```

**Comment by infradig** [comment]
I'll do some regression testing on it.

**Comment by infradig** [comment]
2148d23640f00e1f771b5dc2adadbad8bf97d917 is the first bad commit
commit 2148d23640f00e1f771b5dc2adadbad8bf97d917
Author: Andrew Davison ***@***.***>
Date:   Thu Nov 17 09:58:34 2022 +1000

    Add verbose as a Prolog flag to indicate whether or not -q command-line
option used

 src/predicates.c | 14 ++++++--------
 1 file changed, 6 insertions(+), 8 deletions(-)
~/trealla ((no branch, bisect started on devel)) $

I will look at it tomorrow.

**Comment by infradig** [comment]
I see this...

~/trealla (devel) $ tplgt
Trealla Prolog (c) Infradig 2020-2022, v2.7.33
?- '$lgt_default_flag'(report, Report).
   Report = on.
?- current_prolog_flag(verbose,F).
   F = true.

But still no banner.

~/trealla (devel) $ tplgt -q
?- current_logtalk_flag(report, Value).
   Value = warnings.
?- current_prolog_flag(verbose,F).
   F = false.

**Comment by infradig** [comment]
Actually...

~/trealla (devel) $ tplgt
Trealla Prolog (c) Infradig 2020-2022, v2.7.33
?- current_logtalk_flag(report, Value).
   Value = warnings.
?- '$lgt_default_flag'(report, Report).
   Report = on.

**Comment by infradig** [comment]
Just to clarify, this is what I see...

/trealla (devel) $ tplgt
Trealla Prolog (c) Infradig 2020-2022, v2.7.33
?- current_prolog_flag(verbose,F).
   F = true.
?- '$lgt_default_flag'(report, F).
   F = on.
?- current_logtalk_flag(report, F).
   F = **warnings.**

~/trealla (devel) $ tplgt -q
?- current_prolog_flag(verbose,F).
   F = false.
?- '$lgt_default_flag'(report, F).
   F = warnings.
?- current_logtalk_flag(report, F).
   F = warnings.
?- 
~/trealla (devel) $

**Comment by pmoura** [comment]
Confirmed that 0d0695ae3ec7e4eef5ffb99bd6ca6deebac1d0b6 (v2.7.34) fixes this issue. Thanks!
