### ISSUE TITLE
Conversion integer to float during comparison should throw error

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#106]
From this example I am judging that Trealla Prolog does coercion to
float when comparing integer with float:
```
/* Trealla Prolog 2.7.34 */
?- 18014398509481985 =:= 18014398509481984.0.
   true.
```
But then this here should throw a float_overflow exception and
not succeed:
```
/* Trealla Prolog 2.7.34 */
?- 2^1024 > 0.0.
   true.
````

**Comment by infradig** [comment]
I see your point, but Trealla agrees with both Scryer & Swi-Prolog on this.

**Comment by Jean-Luc-Picard-2021** [comment]
I don't know whether Trealla is consistent. I cannot yet test:
```
?- X is min(2^1024, 0.0).
```
See other defect. Or maybe I should do a git pull?

**Edit 23.01.2023**
I did a git pull and make. It has still some glitches, see also:

https://github.com/trealla-prolog/trealla/issues/107

**Comment by Jean-Luc-Picard-2021** [comment]
Also there are some doubts that Scryer Prolog or SWI-Prolog are
authorative for the ISO core standard. You can look up the
ISO core standard, it explicitly requires a float overflow error:

![Unbenannt](https://user-images.githubusercontent.com/95891213/213947036-51c4f08c-02a4-42a3-8c5e-0ef3257e628c.PNG)

There is even a footnote hiliting the behaviour:

![Unbenannt2](https://user-images.githubusercontent.com/95891213/213947077-82f64506-5df4-40ed-956c-38335e7fbe05.PNG)

**Comment by Jean-Luc-Picard-2021** [comment]
I did some regression testing. Now I see a float_overflow error.
But min does still compute max:
```
Trealla Prolog (c) Infradig 2020-2023, v2.8.6
?- X is min(2^1024, 0.0).
   error(evaluation_error(float_overflow),min/2).
?- X is min(2^1023, 0.0).
   X = 89884656743115795....
```
The expectation is rather that the min evaluable function returns 0.0,
because 0.0 < 2^1023. Even Trealla Prolog agrees here:
```
?- 0.0 < 2^1023.
   true.
?- 0.0 > 2^1023.
   false.
```

**Comment by Jean-Luc-Picard-2021** [comment]
Its gone! 
```
Trealla Prolog (c) Infradig 2020-2023, v2.9.4
?- X is min(2^1023, 0.0).
   X = 0.0.
```
Closing this ticket.
