### ISSUE TITLE
What if cleanup fails?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#122]
Now I get a little disagreement:
```
/* Trealla Prolog */
?- call_cleanup(throw(foo), fail).
   false.

/* Scryer Prolog */
?- call_cleanup(throw(foo), fail).
   throw(foo).
```
Which one is the desired behaviour?

**Comment by infradig** [comment]
I think failure in the cleanup should re-throw, so Scryer (like SWI-Prolog)
is right.

**Comment by infradig** [comment]
XSB doesn't, however, re-throw on failure.
CxProlog does re-throw.

**Comment by infradig** [comment]
What branch of Scryer are you running that has call_cleanup?

**Comment by Jean-Luc-Picard-2021** [comment]
For Scryer Prolog, you need to first invoke:
```
?- use_module(library(iso_ext)).
```

**Comment by Jean-Luc-Picard-2021** [comment]
Works different now:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.11.11
?- call_cleanup(throw(foo), fail).
   throw(foo).
```
Closing the ticket.
