### ISSUE TITLE
abort/0 possibly too strong

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#123]
It seems that abort/0 is a kind of synonymous to halt/0.
Now I get in Trealla Prolog:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.9.4
?- catch(abort, E, true).
$
```
On the other hand the SWI-Prolog abort/0 is less penetrating.
It gets handled by the toplevel and I can continue with queries:
```
?- catch(abort, E, true).
% Execution Aborted
?- 
```

**Comment by infradig** [comment]
Good point.

**Comment by Jean-Luc-Picard-2021** [comment]
This is also interesting. SWI-Prolog hands around abort
into cleanup I guess:
```
/* SWI-Prolog 9.1.4 */
?- call_cleanup((repeat, fail), (write(gotcha), nl)).
^C Action (h for help) ? abort
gotcha
% Execution Aborted
```
So the abort can close resources. Scryer Prolog does the same.
Seems to be missing in Trealla Prolog currently:
```
/* Trealla Prolog 2.9.4 */
?- call_cleanup((repeat, fail), (write(gotcha), nl)).
^C
Action or (h)elp: e
   false.
```

**Comment by Jean-Luc-Picard-2021** [comment]
Works different now:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.11.11
?- catch(abort, E, true).
   E = error('$aborted'(abort_error,abort),top_level/0).
```
Closing the ticket.
