### ISSUE TITLE
Linux build releases are not static

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#125]
fyi, bin-builds are distro  dependent
Example:
tpl-linux-x64$ ldd tpl
	libffi.so.8 => not found

tpl-linux-x64$ ./tpl
./tpl: error while loading shared libraries: libffi.so.8: cannot open shared object file: No such file or directory

**Comment by guregu** [comment]
Yeah, I'm a little afraid to static build the Linux binaries because they rely on readline which is GPL. However, libffi is MIT so it might be OK to include it.

**Comment by guregu** [comment]
Or maybe I should look into flatpak or something. Any suggestions? 🤔

**Comment by infradig** [comment]
If it's just libffi then include it i suppose.

**Comment by flexoron** [comment]
In this case it's just libffi, which might be problematic(perhaps many applications depending on it).

AppImage might be an option in the future(fast and no root privileges required).

For now I  would say: Just include libffi if possible.
