### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#127]
?- = = X.  % Syntax error, see #124 (Comment Markus Triska)
   X = (=).

**Comment by flexoron** [comment]
I don't care and if you don't care, pls fix that:
```
$ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.13.4
?- X = / .
   X = (/).
?- X = / , Y is 1 X 2 .
Error: syntax error, near 'X', operator expected, user:1 % unexpected, expecting Y = 0.5.
 
?- (/) = / .
   true.
?-
```

**Comment by infradig** [comment]
It;s a syntax error, X is not an operator at parse time.

**Comment by flexoron** [comment]
X is a variable proved to be ineffective.
Symbolic processing should allow symbols everywhere.

**Comment by infradig** [comment]
I don't know what that means. If you have an *actual* issue here please let
me know. No Prolog system will compile the code you provided.

**Comment by flexoron** [comment]
``` 
Ops = [+,-,*,/], append(X,[Y|Z],Ops), A is 1 Y 2 .
```

**Comment by flexoron** [comment]
Perhaps Trealla rank first.

**Comment by infradig** [comment]
Variable functors in Prolog is an old concept, it's not part of ISO Prolog
however. What you're wanting is to do...

?- Ops = [+,-,*,/], append(X,[Y|Z],Ops), F =.. [Y,1,2], A is F.
   Ops = "+-*/", X = [], Y = (+), Z = "-*/", F = 1+2, A = 3
;  Ops = "+-*/", X = "+", Y = (-), Z = "*/", F = 1-2, A = -1
;  Ops = "+-*/", X = "+-", Y = (*), Z = "/", F = 1*2, A = 2
;  Ops = "+-*/", X = "+-*", Y = (/), Z = [], F = 1/2, A = 0.5
;  false.
?-

**Comment by flexoron** [comment]
Highly professional answer.
Thank you very much for giving me a helping hand.

**Comment by flexoron** [comment]
?- = = = .
   true.
?- 
I don't know why this is a syntax error.
