### ISSUE TITLE
Graham Suttons count down hangs

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#128]
Hi, I tried to run Jan Ws solution to [Graham Suttons count down](http://www.cs.nott.ac.uk/~pszgmh/pgp-countdown.hs)
with Trealla Prolog. But it hangs. I get:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.11.2
?- ['janw2'].
   true.
?- time((solve([1,3,5,10,25,50], 999, X), write(X), nl, fail; true)).
(3*(5+10)-25)*50-1
10*((5-3)*25+50)-1
...
5*50+(25*(3*10)-1)
5*50+25*(3*10)-1
%%% here it hangs
```
The code is:

[janw2.pl.log](https://github.com/trealla-prolog/trealla/files/10825775/janw2.pl.log)

**Comment by infradig** [comment]
It works with tpl -O0 ... FWIW

**Comment by Jean-Luc-Picard-2021** [comment]
Somehow I think it also works if I remove the write and nl.
Not 100% sure, saw it working sometimes.

**Comment by Jean-Luc-Picard-2021** [comment]
Hurray, now it works, runs till the end:
```
/* Trealla Prolog 2.11.11 */
...
25*(50-10)-1
   % Time elapsed 0.814489s
   true.
```
Closing this ticket.
