### ISSUE TITLE
Top-level abort doesn't trigger cleanup handler

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#129]
I get this discrepancy, I hope I didn't raise this issue already?
```
/* Trealla Prolog 2.11.2 */
?- catch(setup_call_cleanup(true, between(1,5,N), throw(error)), E, true).
   N = 1
;  N = 2
;  ... .
?-
```
On the other hand another Prolog system gives me:
```
/* Scryer Prolog 0.9.1-173 */
?- catch(setup_call_cleanup(true, between(1,5,N), throw(error)), E, true).
   N = 1
;  N = 2
;  ... .
E = error.
```

**Comment by Jean-Luc-Picard-2021** [comment]
I guess the other Prolog system behaviour is the desired behaviour.
But the other Prolog system has also still some bugs, for example
it doesn't show the error in the top-level when I remove the catch/3:
```
/* Scryer Prolog 0.9.1-173 */
?- setup_call_cleanup(true, between(1,5,N), throw(error)).
   N = 1
;  N = 2
;  ... .
```
Compare with yet another Prolog system, which shows the error:
```
/* SWI-Prolog 9.1.4 */
?- setup_call_cleanup(true, between(1,5,N), throw(error)).
N = 1 ;
N = 2 .

ERROR: Unhandled exception: Unknown message: error
```

**Comment by infradig** [comment]
$ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.11.2-17-g4d4b
?- catch(setup_call_cleanup(true, between(1,5,N), throw(error)), E, true).
   N = 1
;  N = 2
;  N = 3
;  N = 4
;  E = error.
?-

For me the latest Scryer agrees with Trealla on this, as does SWI-Prolog.

**Comment by Jean-Luc-Picard-2021** [comment]
You have to press return after the second solution or some other solution
that is not the last one, and not press the semicolon `;`, so that you see a difference.

I have reported the issue as such, now using `%%%` to better show what I did:
```
/* Trealla Prolog 2.11.2 */
?- catch(setup_call_cleanup(true, between(1,5,N), throw(error)), E, true).
   N = 1
;  N = 2 %%% here I pressed semicolon ;
;  ... . %%% here I pressed return
?-
```

**Comment by infradig** [comment]
Since the top-level is undefined it's hard to say what *should* be done. It
would be nice if cleanup handlers were called, but no guarantee that a
catch would work. SWI defines <NL> as (soft, call cleanups) exit, Scryer
defines it as stop enumeration, which explains the difference there.
Trealla defines it as hard exit.

**Comment by Jean-Luc-Picard-2021** [comment]
It should call the cleanup, otherwise streams might stay open etc.

Take this example:
```
?- setup_call_cleanup(open(file, read, S), enum_lines(S, L), close(S)).
L = 'foo' ;
L = 'bar' 
```
You get it for free if the top level is implemented as follows, only a sketch:
```
top_level :- 
    repeat,
    write('?- '), flush_output,
    read(G),
    top_level(G).

top_level(G) :-
    G
    ...
    get_code(C),
    ( C = 0';  -> fail;
      C = 0'\n    -> !, fail).    /* the effect of return, the cut will invoke any
                        cleanup that was created when calling G */
```
if-then-else is cut transparent, should reach G.

**Comment by infradig** [comment]
Absolutely agree.

**Comment by Jean-Luc-Picard-2021** [comment]
But a 100% Prolog implementation of a top-level according to
the above scheme would require that this here works. Not sure 
whether its the same issue as here?

https://github.com/trealla-prolog/trealla/issues/130

**Comment by Jean-Luc-Picard-2021** [comment]
Works different now:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.11.11
?- catch(setup_call_cleanup(true, between(1,5,N), throw(error)), E, true).
   N = 1
;  N = 2
;  ... .
  throw(error).
```
Closing the ticket.
