### ISSUE TITLE
Feature request engines, or should it be callbacks and tasks?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#135]
> Do you have an engine abstraction in Trealla Prolog? Like this here from SWI-Prolog:
> 
> > 11.3 Engine predicate reference
> > https://www.swi-prolog.org/pldoc/man?section=engine-predicates
> 
> So everybody can write an event loop in Prolog itself? Well the API is not perfect, a lot is missing right now.

Engines compatible with SWI-Prolog was added. They share the Database (like SWI) and so are not thread-safe. Consider it experimental at this stage. Also my understanding of all the calls may be imperfect. I think engine_yield/1 is wrong... it should yield/block until the term is read.

_Originally posted by @infradig in https://github.com/trealla-prolog/trealla/issues/134#issuecomment-1459658445_

**Comment by Jean-Luc-Picard-2021** [comment]
engine_yield/1 blocks. You will not go beyond
engine_yield/1 if there is not a pairing engine_next/2.
Its not related in any way to the usual Thread.yield().

But its related to the yield of a generator. You
can implement engines independent of threads,
they are also available in single thread. Also the

yield semantics is copy term. Since you can abandon
the continuation of a engine_next/2, making it subject
to garbage collection? SWI-Prolog has no automatic

garbage collection of engines? You need to call engine_destroy/1.
This is the copy term example by Paul Tarau:
```
copy_term(X,CX):-first_solution(X,true,the(CX)).
`````
From this paper:

> The BinProlog Experience
> Paul Tarau - 2011
> https://arxiv.org/pdf/1102.1178.pdf

if you want another semantics, without copy term, you would 
need to look into shift/reset. Maybe you have shift/reset already?
Don't know. Didn't follow shift/reset so much.

**Comment by Jean-Luc-Picard-2021** [comment]
Also I was asking for an engine API, I could also ask for a callback and task API.
Currently I don't know whether somebody has already used the engine
API to introduce auto-yield, and for example code callbacks and tasks, i.e.

an event loop in pure Prolog. There are a lot of problems when introducing
an engine API and not a callback and task API. For example this shiny Paul
Tarau example doesn't work anymore with auto-yield:
```
find_all(Template, Goal, List) :-
    engine_create(Template, Goal, Engine),
    collect_all(Engine, List0),
    engine_destroy(Engine),
    List = List0.

collect_all(Engine, [X| Xs]) :-
    engine_next(Engine, X),
    !,
    collect_all(Engine, Xs).
collect_all(_, []).
```
I get a currious result:
```
/* SWI-Prolog 9.1.4 */
?- findall(X, (X=1,engine_yield(heartbeat);X=2), L).
ERROR: No permission to execute vmi `'I_YIELD'' (not an engine)

?- find_all(X, (X=1,engine_yield(heartbeat);X=2), L).
L = [heartbeat, 1, 2].
```

**Comment by Jean-Luc-Picard-2021** [comment]
In Dogelog Player the heartbeat is transparent, it amounts to
sleep(0) but executed via a yield. But not some yield that would
be visible to the end-user. In as far Dogelog Player has no engines

for the end-user, only callbacks and tasks:
```
/* Dogelog Player */
?- findall(X, (X=1,'$YIELD'(0);X=2), L).
L = [1, 2].
```

**Comment by infradig** [comment]
Made some engine_yield/1 yield until engine_next/2 reads the term.

**Comment by infradig** [comment]
/trealla (devel) $ swipl
?- engine_create(X,(writeln(here2),engine_yield(123456),writeln(here4)),E), writeln(here1), engine_next(E,R), writeln(here3), engine_next(E,_), writeln(here5).
here1
here2
here3
here4
here5
E = <engine>(3,0x556791b3bdb0),
R = 123456.

?- ^D
% halt
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.12.5
?- engine_create(X,(writeln(here2),engine_yield(123456),writeln(here4)),E), writeln(here1), engine_next(E,R), writeln(here3), engine_next(E,_), writeln(here5).
here1
here2
here3
here4
here5
   E = '<$stream>'(4), R = 123456.
?-

**Comment by Jean-Luc-Picard-2021** [comment]
I now have complete my take on Task Contexts, there is
an implementation, will soon write a medium article about it.
They are different from Engines. Not sure whether Task

Contexts will be adopted by some Prolog system. It requires
a new and different thinking. You need to think beyond engines.
Actually Task Contexts are independent of engines.

You can add Task Contexts to a Prolog system with engines or
to a Prolog system without engines. All you need is an event loop
and stackless (non-fibers) and stackfull coroutines (fibers).

No engines needed, unless you might want to implement the
event loop and the non-fibers and fibers from engines? Would
it perform? The problem is a `call_later/2` or `create_task/1`

as a side effect on the current engine loop is much more efficient
then yielding for such a command. Thats why these methods in
JavaScript are not some sort of promises that can be awaited:
```
setTimeout()
clearTimeout()
```
They have an immediate effect on the event loop.

**Comment by Jean-Luc-Picard-2021** [comment]
Not sure, does Trealla Prolog every JavaScript invocation via
some js_yield/1 ? Can this be improved?  Unfortuantely I cannot
help much, since I don't know much about WASM, and articles

like these are also not easy to understand. Maybe there are some
brand new ways to quickly call JavaScript, not only examples
such as `Math.random()` but also `setTimeout()/clearTimeout()`.

Here is an artice from 2018:

> Calls between JavaScript and WebAssembly are finally fast 🎉
https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%F0%9F%8E%89/

Quite a complicated landscape:

![landscape](https://user-images.githubusercontent.com/95891213/224103512-a5643cd9-cbd7-4292-8f82-c2395592dddf.png)

**Comment by guregu** [comment]
That map does a good job of explaining it, it is pretty complex!
We can definitely improve the JS callbacks to avoid the overhead with js_eval.
I'll submit a PR that makes sleep/1 faster to illustrate.
The simplest way is to export a function from the host to the guest, and call that from C. So you could implement `do_sleep(Time)` in JS and call that from C. This would avoid much of the current overhead which uses phrase/2 and eval. But a more flexible way is to let users register their own 'native' predicates as a map of predicate indicators to closures or something, which is how the Go port works.
