### ISSUE TITLE
Feature request, show LIPS measurement

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#137]
Concerning: The demo video here:
https://github.com/trealla-prolog/trealla/issues/134#issuecomment-1460146877

What does "Goals" count? I don't remember, does Trealla Prolog show LIPS?
Currently Trealla gives me:
```
/* Trealla Prolog 2.13.0 */
?- time((between(1,1000,_), fail; true)).
   % Time elapsed 0.000112s
   true.
```
But if you have a goal counter you can also show LIPS, like here:
````
/* Dogelog Player 1.0.5 */
?- time((between(1,1000,_), fail; true)).
% Time 1 ms, gc 0 ms, 3089000 lips
true.
`````
I am doing the computation like this:
```
/* R the measured time in milliseconds, T the measured goals, L = LIPS */
(R =\= 0 -> L is truncate(T*1000/R); L = 0)
```
SWI-Prolog shows also LIPS, Logical Inferences per Second. I think what is 
counted is usually the call port, see byrd box for info on what the call port is,
but I could be also mistaken. 

![original_byrd_box](https://user-images.githubusercontent.com/95891213/223880700-1717fa16-098c-4bee-a327-ccb5d8793104.png)

**Comment by Jean-Luc-Picard-2021** [comment]
I think there is still a small glitch in Dogelog Player,
during an auto-yield, the call port is counted twice?
But this happens only 60 times per second, so it doesn't

hurt the LIPS so much. You can query the call count if you want:
```
/* Dogelog Player 1.0.5 */
?- statistics(call_count, A),
   (between(1,1000,_), fail; true),
   statistics(call_count, B),
   C is B-A.
A = 45043, B = 48066, C = 3023.
```
Since I am using a 100% Prolog implementation of between/3,
the count is higher than for example in SWI-Prolog I guess,
which has a native implementation of between/3?

Usually the inarts of a built-in are not counted. But you could
do that as well. The none native between/3 has around 3 call 
ports per iteration, this is some arithmetic comparison and 

som evaluation in 100% Prolog.

**Comment by Jean-Luc-Picard-2021** [comment]
This here seems reasonable:

>% time(fib(29, _)) [auto-yield every 20ms / check every 10,000 goals]
> https://github.com/trealla-prolog/trealla/pull/136

You can use LIPS to calibrate the auto-yield rate. There is
the simple formula, if you want n-times auto-yield per second,
the LIPS/n is the number of counts that are the basis for your

LIPS, you have to wait, before the next auto-yield. I wrote an
auto tuning Prolog system for experimentation, but have it currently
hard coded. At the moment the values are:
```
/* Dogelog Player 1.0.5 */
GC_MAX_INFERS = 50000, JavaScript nodeJS
GC_MAX_INFERS = 30000, JavaScript browser
GC_MAX_INFERS = 15250, Python PyPy
```

**Comment by infradig** [comment]
Some tweaks to Goals measurements (excluded control constructs) and added
Lips count

~/trealla (devel) $ swipl
?- time((between(1,10000000,_), fail; true)).
% 10,000,002 inferences, 0.512 CPU in 0.512 seconds (100% CPU, 19529899
Lips)
true.
?- ^D

~/trealla (devel) $ tpl
?- time((between(1,10000000,_), fail; true)).
   % Time elapsed 0.874537s 11.435 MLips)
   true.
?-

**Comment by Jean-Luc-Picard-2021** [comment]
Seems to be available now:
```
?- time((between(1,1000,_), fail; true)).
% Time elapsed 0.000097s, 1002 Inferences, 10.330 MLips)
      true.
```
Wasn't sure whether its also available on the non-WASM version.
One could say its not needed? But maybe it comes handy
and your ideas of coroutines span both WASM and non-WASM?

Dunno exactly coroutines in Trealla are marked experimental.
And who knows, maybe the SWI-Prolog related library(engine) is
also experimental? At least the new "heatbeat" Prolog flag is 

very young, was only introduced a few months ago in release 8.5.15,
copied from Dogelog Player, which had the auto-yield first.

> **[Aug 6 2022]**
ADDED: heartbeat mechanism: by setting the Prolog flag heartbeat, 
the multifile predicate heartbeat/0 is called every N inferences.
https://www.swi-prolog.org/ChangeLog?branch=development&from=8.5.15&to=8.5.16

**Comment by Jean-Luc-Picard-2021** [comment]
Continutation of this historical excursion. Actually I published 
about auto-yield on medium.com in Feb 3, 2022:

> Non-Blocking Browser for Dogelog Player
> Feb 3, 2022 
> https://medium.com/@janburse_2989/non-blocking-browser-for-dogelog-player-b296ec832168

So the delay for adoption of Dogelog Player stuff by 
SWI-Prolog is around 6 months? Good to know. I will
soon make a little medium.com article about task contexts.

But since LIPS stuff works now in Trealla, closing this ticket.
