### ISSUE TITLE
Is there some call_later/2 for Trealla Prolog, maybe in WASM?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#138]
Was just skimming this here:

> **trealla-js**
https://github.com/guregu/trealla-js

Is there any way to schedule a callback inside Prolog?
This is easily done in JavaScript via [setTimeout()](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout).
I would like to run this example:
```
tick(0) :- !.
tick(N) :- M is N-1, write('tick '), flush_output,
    call_later(tick(M), 1000).
tock(0) :- !.
tock(N) :- M is N-1, write('tock '), flush_output,
    call_later(tock(M), 5000).
```
It should display something along:
```
?- tick(11), tock(3), sleep(12000).
tick tock tick tick tick tick tock tick tick tick tick tick tock tick true.
```

**Comment by Jean-Luc-Picard-2021** [comment]
The same works in Tau Prolog sandbox:
```
:- use_module(library(os)).
call_later(G, T) :-
   set_timeout(T, G, _).
```
I get this result:

![small_rizla](https://user-images.githubusercontent.com/95891213/224118074-6664bb94-db7f-43bf-abbf-10c60e52c3a8.PNG)

The predicate `set_timeout/3` is also mentioned here:

> **Web development with Tau Prolog**
José A. Riaza - June 13, 2022
[https://biblioteca.sistedes.es/submissions/descargas/2022/PROLE/2022-PROLE-006.pdf](https://biblioteca.sistedes.es/submissions/descargas/2022/PROLE/2022-PROLE-006.pdf)

**Comment by guregu** [comment]
Not yet, but I think it should be possible. I'll do some experimenting with it.
Question: what should this print?
```js
call_later(write(X), 1000), X = foo.
```

For Tau it prints an unbound variable like `_4`. If you're OK with that, we should be able to do the same for trealla-js. Making the variable bindings propagate will be a lot trickier, but seems theoretically doable.

**Comment by Jean-Luc-Picard-2021** [comment]
call_later/2 is not the same as freeze/2. There
is no requirement of some variable binding.

**Comment by infradig** [comment]
The closest would be something like...

~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.13.3-6-g3efa-dirty
?- task((delay(3000),writeln(here3))), task((delay(2000),writeln(here2))),
task((delay(1000),writeln(here1))), wait.
here1
here2
here3
   true.
?-

**Comment by guregu** [comment]
I think trealla-js currently has poor support for wait/0. It currently explodes with a scary JS runtime error for the example Andrew posted. I think I should be able to get it to work, though. It'd be ideal to have parity with the native version.

**Comment by Jean-Luc-Picard-2021** [comment]
Recently I was bootstrapping wait/0 as:
```
wait :-
   repeat, sleep(1000), fail.
```
But its not waiting for someting particular, except Ctrl-C and or the Abort button.
This is unlike Java Monitors which have for example wait(). But then Monitors
can have spurious yields, which makes one needing some looping programming

style with their Monitors. Meaning the above Prolog repeat loop is possibly as
good as a Java loop over a wait() with spurious yields.

**Comment by guregu** [comment]
I've been hacking at this over the weekend and made some good progress. I'll push the code to my fork later tonight. Got task/1 and wait/0 working. I'm also overhauling how the wasm host-guest interop works for trealla-js. You'll be able to define native predicates in JS instead of having to generate JS code as a string from Prolog and eval'ing it.

One thing I was thinking is, what if wait/0 binds the variables from task/1? In other words, what if this worked?
```prolog
slow_predicate(X) :- delay(500), X = 41.
other_slow_thing(X) :- delay(900), X = 1.

?- task(slow_predicate(X)), task(other_slow_thing(Y)), wait, Answer is X + Y, write(Answer).
   42 % output
```

I think it'd be pretty cool. Currently, if you want to share data between tasks in trealla-js you'd have to use the virtual filesystem. The alternative would be some kind of message passing system (I see there is send/1 and recv/1 already aimed at fork/0, haven't played around with these yet), or a promise-awaiting system like JS. Oh yeah, you can use assertz too, but not ideal.

**Comment by infradig** [comment]
The tasks should be able to do *send(Result)* then the parent, after
*wait*, do *recv(X)* and*recv(Y)*. Direct binding would be hard to do.

**Comment by Jean-Luc-Picard-2021** [comment]
> I think it'd be pretty cool.

You could adopt the future API from Tau Prolog:

> :- use_module(library(concurrent)).
> http://tau-prolog.org/documentation#concurrent

The example would the read, it gives you more fine control,
instead of a wait that waits for whatever? The below has
an await/2, which awaits a particular future:
```
?- future(X, slow_predicate(X), F1), 
    future(Y, task(other_slow_thing(Y), F2),
    await(F1, A),
    await(F2, B),
    Answer is A + B.
```

**Comment by Jean-Luc-Picard-2021** [comment]
The future/3 predicate has a similar signature like engine_create/3 in
SWI-Prolog, only the result is not an engine but a future. Tau Prolog
has also picked up ideas from JavaScript such as Promise.all() which

corresponds to a kind of TaskGroup in Python. So alternatively can
run the example also as well this way:
```
test(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    future_all([F1,F2], F),
    await(F, [A,B]),
    C is A + B.
```
Works also fine.

**Comment by guregu** [comment]
I like the idea of adapting Tau's library. IIRC there was even an experimental version of it in the old Trealla repo. It's a very good point that wait/0 is too general for fine-grained control. 

I'll do some more experimenting, with the goal of getting something like first_solution/3 from the Tau issue to work. It should definitely be possible to make promises cancelable. I can probably get send/1 and recv/1 working as well.

**Comment by Jean-Luc-Picard-2021** [comment]
I lost track of this issue. You would need to close it by yourself,
if you think the some call_later/2 has been adopted by Trealla Prolog or
has not yet been adopted. The outcome could be documented here.
