### ISSUE TITLE
What about futures API from Tau Prolog in Trealla Prolog?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#142]
> I think it'd be pretty cool.

You could adopt the futures API from Tau Prolog:

> :- use_module(library(concurrent)).
> http://tau-prolog.org/documentation#concurrent

The example would the read, it gives you more fine control,
instead of a wait that waits for whatever? The below has
an await/2, which awaits a particular future:
```
test(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    await(F1, A),
    await(F2, B),
    C is A + B.
``` 
Works fine:

![Unbenannt](https://user-images.githubusercontent.com/95891213/224657548-95cf25e5-d852-4bfc-9b61-f4b874c46326.PNG)

_Originally posted by @guregu in https://github.com/trealla-prolog/trealla/issues/138#issuecomment-1465702450_

**Comment by Jean-Luc-Picard-2021** [comment]
The future/3 predicate has a similar signature like engine_create/3 in
SWI-Prolog, only the result is not an engine but a future. Tau Prolog
has also picked up ideas from JavaScript such as Promise.all() and

Promise.any(), which corresponds to a kind of TaskGroup in Python. 
So alternatively can run the example also as well this way:
```
test(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    future_all([F1,F2], F),
    await(F, [A,B]),
    C is A + B.
```
Works also fine. But Promise.any() has a defect, since the futures of
Tau Prolog are not yet cancellable. It will settle the promise if at 
least one future gets stettled, but then the other futures do

continue running, they are not cancelled. So you cannot yet implement
something like first_solution/3 from SWI-Prolog. So unlike Python
TaskGroup, which does cancel tasks, Tau-Prolog cannot yet cancel

futures. I have opened an according feature request. I wonder
how Tau Prolog would do this:

> Feature request cancellable futures
https://github.com/tau-prolog/tau-prolog/issues/347

Maybe you can even provide cancellable futures? I got already cancellable
tasks in Dogelog Player running. This was a little tricky, but it works,
the API in Dogelog Player is os_task_abort/2.

**Comment by infradig** [comment]
Just a quick go...

```
~/trealla (devel) $ cat f.pl
:- use_module('../tpl-stuff/concurrent.pl').

test(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    future_all([F1,F2], F),
    await(F, [X,Y]),
    C is X + Y.

slow_predicate(X) :- delay(500), X = 41.
other_slow_thing(X) :- delay(900), X = 1.

~/trealla (devel) $ 
~/trealla (devel) $ 
~/trealla (devel) $ tpl f.pl
Trealla Prolog (c) Infradig 2020-2023, v2.13.11-11-g4ce9
?- test(C).
   C = 42.
?- 


$ cat ../tpl-stuff/concurrent.pl
:- module(concurrent, [
	future/3,
	future_all/2,
	future_any/2,
	future_done/1,
	await/2
	]).

:- use_module(library(apply)).

future(X, Goal, Future) :-
	Goal2 = [X,Goal],
	Future0 = (Goal2=[X2,GoalX],call(GoalX),send(X2)),
	copy_term(Future0, Future).

future_all(Goals, _) :-
	tasklist(call, Goals).

await(_, Vars) :-
	wait,
	findall(X, (member(_,Vars), recv(X)), L),
	L = Vars.

```

**Comment by Jean-Luc-Picard-2021** [comment]
I could also implement your `send/1` and `recv/1` like this:
```
:- dynamic queue/1.

send(X) :-
   assertz(queue(X)).

recv(X) :-
   retract(queue(Y)), !, X = Y.
```
Or is there more to it? If this is the semantics, than your future
implementation is not correct. Try this example, I have changed
`X + Y` into `2 * X + Y` and also mingle with the delay values:
```
test(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    future_all([F1,F2], F),
    await(F, [X,Y]),
    C is 2 * X + Y.

slow_predicate(X) :- delay(900), X = 41.
other_slow_thing(X) :- delay(500), X = 1.
```
Now I get:
```
?- test(C).
   C = 43.
```
But the expected result would be:
```
?- test(C).
   C = 83.
```

**Comment by infradig** [comment]
True, the order as given is not guaranteed. As I said a quick go, I didn't include it in the repo because of this. It won't be hard to fix. Jut pass an ordinal to each task with the variable X,Y etc, return the value with ordinal as a pair and keysort the result. or similar. But I have no time, alas.

**Comment by Jean-Luc-Picard-2021** [comment]
Yes, the effort increases. And a `future_all/2` is rather useless
compared to a `future_any/2`. `future_all/2` this here:
```
    future(X, G1, F1),
    future(Y, G2, F2),
    future_all([F1,F2], F),
    await(F, [X,Y]),
```
Is the same like this here, similar like how `thread.join()` can be used,
only not for multi-threading but for cooperative multitasking:
```
    future(X, G1, F1),
    future(Y, G2, F2),
    await(F1, X),
    await(F2, Y),
```
At least Tau Prolog shows such a behaviour. I am not 100% sure whether
JavaScript can show the same without a setImmediate() somewhere? But 
for Trealla Prolog, using send/1 and recv/1, there would be again an

assignment problem. Using different sleeps, It seems that I can provoke
different races between the two futures.

Program:
```
:- use_module(library(concurrent)).
:- use_module(library(os)).

run(S) :- sleep(S),  write('sleeping '), 
    write(S), write(' done'), nl.

both(S,T,X,Y) :-
    future(X, (run(S), X=1), F1),
    future(Y, (run(T), Y=2), F2),
    await(F1, X),
    await(F2, Y).
```
Result:

![tau_await](https://user-images.githubusercontent.com/95891213/224853374-0e294164-04a7-410d-9e76-08486ef1d306.png)

**Comment by infradig** [comment]
Another quick hack in devel branch. See samples/concurrent.pl (module file) and testconcurrent.pl

```
~/trealla (devel) $ cat samples/testconcurrent.pl 
:- use_module('samples/concurrent.pl').

test1(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    future_all([F1,F2], F),
    await(F, [A,B]),
    C is 2 * A + B.

test2(C) :-
    future(X, slow_predicate(X), F1),
    future(Y, other_slow_thing(Y), F2),
    await(F1, A),
    await(F2, B),
    C is 2 * A + B.

slow_predicate(X) :- delay(900), X = 41.
other_slow_thing(X) :- delay(500), X = 1.

~/trealla (devel) $ tpl samples/testconcurrent.pl 
Trealla Prolog (c) Infradig 2020-2023, v2.13.12-dirty
?- test1(C).
   C = 83.
?- test2(C).
   C = 83.
?- 
```

Again, this is just a quick demo as to how to proceed with this. It is not meant to be taken verbatim as an implementation attempt.

**Comment by Jean-Luc-Picard-2021** [comment]
Interestingly Tau Prolog allows to build an even greater
road map for a Prolog system in the browser. Besides 
future stuff, I now found the predicate bind/4:

> **Web development with Tau Prolog**
Jos´e A. Riaza - June 13, 2022
Sectuon 3. Event handling
https://biblioteca.sistedes.es/submissions/descargas/2022/PROLE/2022-PROLE-006.pdf

Could complete my own take on a bind/4 predicate
as well. But it turned out to become a bind/3 predicate,
taking a DOM element cursor as an implicit parameter,

from the task context. This landed in library(markup).

**Comment by infradig** [comment]
A bit of progress...

```
:- use_module(library(http)).

test4(C) :-
	future(Status, geturl("www.google.com", Status), F1),
	future(Status, geturl("www.bing.com", Status), F2),
	future(Status, geturl("www.duckduckgo.com", Status), F3),
	future_all([F1,F2,F3], F),
	await(F, StatusCodes),
	C = StatusCodes.

geturl(Url, Status) :-
	http_get(Url, _Data, [status_code(Code),final_url(Location)]),
	!,
	format("Job [~s] ~d ==> ~s done~n", [Url,Code,Location]),
	Status = Code.
```

```
/trealla (devel) $ tpl samples/testconcurrent.pl
Trealla Prolog (c) Infradig 2020-2023, v2.13.13-7-g7b76-dirty
?- test4(C).
Job [www.duckduckgo.com] 200 ==> https://duckduckgo.com/ done
Job [www.bing.com] 200 ==> www.bing.com done
Job [www.google.com] 200 ==> www.google.com done
   C = [200,200,200].
?- 
```

**Comment by infradig** [comment]
I think I ironed-out enough flaws so i've released it. Still experimental.

**Comment by guregu** [comment]
Nice! I'm going to try to match the API for the JS version.
I have it mostly working, but it directly binds variables instead of a findall-style template, [example here](https://php.energy/trealla.html?src=slow_predicate%28X%29+%3A-+delay%28500%29%2C+writeln%28%27i+should+be+killed+%28maybe%29%27%29%2C+X+%3D+123.%0Afaster_predicate%28X%29+%3A-+delay%2850%29%2C+writeln%28%27i+win%21%27%29%2C+X+%3D+42.%0A%0Atest_any%28X%29+%3A-%0A++++future%28slow_predicate%28X%29%2C+F1%29%2C%0A++++future%28faster_predicate%28X%29%2C+F2%29%2C%0A++++future_any%28%5BF1%2C+F2%5D%2C+F%29%2C%0A++++await%28F%29%2C%0A++++format%28%22answer+%3D+%7Ew%7En%22%2C+%5BX%5D%29.%0A%0Atest_race%28X%29+%3A-%0A++++future%28slow_predicate%28X%29%2C+F1%29%2C%0A++++future%28faster_predicate%28X%29%2C+F2%29%2C%0A++++await_any%28%5BF1%2C+F2%5D%2C+W%2C+Rest%29%2C%0A++++maplist%28future_cancel%2C+Rest%29%2C%0A++++format%28%22answer%3A+%7Ew%7Enwinner%3A+%7Ew%7Enrest%3A+%7Ew%7En%22%2C+%5BX%2C+W%2C+Rest%5D%29.%0A%0Atest_all%28%5BX1%2C+X2%5D%29+%3A-%0A%09future%28slow_predicate%28X1%29%2C+F1%29%2C%0A++++future%28faster_predicate%28X2%29%2C+F2%29%2C%0A%09time%28await_all%28%5BF1%2C+F2%5D%29%29.&q=test_race%28X%29.&v=0).

Internally, it works like this:
```prolog
future(answer(X), F) →
    future(answer(X), '$promise'(1, answer(X)) % 1 is the 'task id'
await(F) →
    await('$promise'(1, answer(X))) →
        [yield and await new subquery (__GOAL=answer(X),__GOAL) which returns {goal: {functor: "answer", args: [42]}, ...}] →
            await('$promise'(1, answer(42))) →
                [create a choice point if the JS async iterator is not done]
X = 42
```

I kinda like the direct binding but I think it should be possible to implement both.

**Comment by guregu** [comment]
Oh yeah, it includes some basic cancelation functionality as well. Unfortunately it's not possible to cancel an arbitrary JS promise, but we can prevent it from redoing and ignore its output/bindings (stdout is sandboxed per query in trealla-js). I'll implement signals soon and we should be able to interrupt it (but only when it yields, as JS is single-threaded).

```prolog
first_solution(Fs) :-
    await_any(Fs, _, Pending),
    maplist(future_cancel, Pending).

?- future(foo(X), F1), future(bar(X), F2), first_solution([F1, F2]).
   X = <whichever was faster>.
```

I think the findall-style template syntax would be better for this though, probably.

**Comment by infradig** [comment]
I thought of adding a future_cancel/1 but Tau didn't have it so I didn't
bother.

**Comment by Jean-Luc-Picard-2021** [comment]
On my side, cancelling was quite tricky. But its main application
was not cancelling futures, but rather cancelling through time out
or CTRL-C in the top-level. The test case is then:
```
?- time(time_out(sleep(1000), 500)), sleep(2000).
% Time 503 ms, gc 0 ms, 286 lips
Error: system_error(timelimit_exceeded)
        user:1
```
Note in the above the sleep doesn't carry on all 1000 ms,
time/1 measure shows that it stopped early on. This is the 
expected behaviour of a more advanced so called interruptible 

sleep/1 in multi-threading. For coroutining sleep/1 became not 
only a promise, but an abortable promise in Dogelog Player. I 
adopted the idea from SWI-Prolog, which discusses it here:

> **JavaScript Promise that can be aborted**
https://www.swi-prolog.org/pldoc/man?section=wasm-promise-abort

But my implementation is slightly different. Since my promises
don't use the reject path so far, I went for simply clearig the timeout
and not more. The sleep/1 then recognizes a signal, by its usual

signal checking routine, which is anyway in place. Further the abort
function is not stored inside the promise, but in the currently delayed
context. Maybe a better solution would be to use AbortSignal

and AbortController, but I didn't wanted to blow up the code and
had to implement the same for Python. So its simply a function point
name "interrupt" stored in the task context.

**Comment by guregu** [comment]
Yeah that makes a lot of sense, I think I can implement this in roughly the same way. trealla-js doesn't have support for interrupts/signals yet, but it should be relatively easy to add that and use it for cancelation.

**Comment by Jean-Luc-Picard-2021** [comment]
Do you have `time_out/2` in Trealla Prolog? Sometimes its also called 
call_with_time_limit/2. I adopted the shorter name for Dogelog Player.
Currently SWI-Prolog did not yet provide it in their WASM,

which is a pitty. Despite their talk about abortable promises.
But they have it for multi-threading and not for coroutines
already for a while:

> **Predicate call_with_time_limit/2**
https://www.swi-prolog.org/pldoc/man?predicate=call_with_time_limit/2

Its quite useful to abort search. But I thought I should also
abort other stuff with it, like animation or fetch download etc.. 
that uses pauses or is blocking.

Aborting a fetch is not yet implemented in Dogelog Player.
But it should be also possible in JavaScript via AbortController
and AbortSignal.

**Comment by infradig** [comment]
Yes, time_out/3 & call_with_time_Limit/2

**Comment by guregu** [comment]
Yep! Once I add support for SIGALARM to trealla-js those predicates should 'just work' (I hope).

**Comment by infradig** [comment]
I'm going to add future_cancel/1

**Comment by Jean-Luc-Picard-2021** [comment]
I lost track of this issue. You would need to close it by yourself,
if you think the futures API has been adopted by Trealla Prolog or
has not yet been adopted. The outcome could be documented here.
