### ISSUE TITLE
compare/3 thinks some terms equal, but they are not

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#147]
After updating Trealla Prolog I get:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.14.11
?- Y=(Y,b), Z=(Y,c), compare(B,Y,Z).
   Y = (Y,b), Z = Y, B = (=).
?- Y=(Y,b), Z=(Y,c), Y = Z.
   false.
```
I couldn't use `(==)/2` in the test case, since its also broken now.
So I showed the problem with the help of `(=)/2`. If `compare/3 `
returns `(=)/2` then we expect that the terms unify, which is violated.

**Comment by flexoron** [comment]
```
v2.14.12
?- [L|L] = [L|L], true.
   false. % Untrue
?-
```
@infradig, sorry, thnx, issue #148

**Comment by infradig** [comment]
Good catch, but nothing to do with compare/3.

**Comment by Jean-Luc-Picard-2021** [comment]
Release 2.14.17 helps here:
```
?- Y=(Y,b), Z=(Y,c), compare(B,Y,Z).
   Y = (Y,b), Z = (Y,c), B = (<).
```
