### ISSUE TITLE
json(true) isn't always JSON sympathetic

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#158]
[json.org](https://www.json.org/json-en.html) tells me that JSON has a `\uXXXX` string escape syntax.
I was expecting that the json(boolean) read option enables this syntax.
But it seems not to work:
```
/* Trealla Prolog 2.14.28 */
?- read_term(X, [json(true)]).
"abc\uFFFEdef".
   throw(error(syntax_error(illegal_character_escape),read_term/2)).
```
Is there an alternative to read JSON in Trealla Prolog. What about reading
streaming JSON, is it possible to read JSON without requiring the terminating
period ".". For example SWI-Prolog can do it, the escape and the streaming:
```
/* SWI-Prolog 9.1.7 */
?- use_module(library(http/json)).
true.

?- current_input(S), json_read(S, X).
"abc\uFFFEdef"
X = 'abc\uFFFEdef'.
```

**Comment by infradig** [comment]
It's in the parser but is disabled. It should be an easy change.

**Comment by Jean-Luc-Picard-2021** [comment]
Some indecisiveness, like its still in development stage?
Maybe because some pending issues concerning surrogate pairs.
Somehow the `\uXXXX` proposal from json.org is a little annonying.

What to do with codepoints above `0xFFFF`? It seems surrogate pairs
are the way forward. The ECMA-404 standard, 2nd edition, December 2017.
mentions surrogate pairs explicitly in section "9 String":

> Why does JSON encode UTF-16 surrogate pairs
> https://stackoverflow.com/q/38463038/17524790

> The JSON data interchange syntax
> https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

So if your strings are UTF-8 based, you need UTF-16 conversion.

**Comment by infradig** [comment]
No, I'll do it.

**Comment by Jean-Luc-Picard-2021** [comment]
This is also a nasty test case. Somehow I think a JSON sympathetic Prolog
parser isn't possible. There are too many differences between JSON and Prolog.
For example I get in Trealla Prolog:
```
/* Trealla Prolog 2.14.32 */
?- read_term(X, [json(true)]).
5E7.
   throw(error(syntax_error(operator_expected),read_term/2)).
```
Whereas SWI-Prolog gives me:
```
/* SWI-Prolog 9.1.7 */
?- current_input(S), json_read(S, X).
5E7
X = 50000000.0.
```
The number syntax is allowed according to [json.org](https://www.json.org/json-en.html). Right?

**Comment by infradig** [comment]
An easy enough fix, but there will probably be more.

**Comment by Jean-Luc-Picard-2021** [comment]
What about JSON sympathetic writing with more precision?
I currently get:
```
/* Trealla Prolog 2.14.32 */
?- X is 370370367037037036703703703670 / 123456789012345678901234567890,
write_term(X, []), nl.
3.0

?- X is 370370367037037036703703703670 / 123456789012345678901234567890,
write_term(X, [json(true)]), nl.
3.0
```
But for example nodeJS shows me:
```
/* nodeJS 19.4.0 */
> JSON.stringify(370370367037037036703703703670 / 123456789012345678901234567890)
'3.0000000000000004'
```
But there seems to be no agreement, since Python gives me:
```
/* CPython 3.11.0rc1 and PyPy 7.3.11 */
> json.dumps(370370367037037036703703703670 / 123456789012345678901234567890)
'3.0'
```

**Comment by Jean-Luc-Picard-2021** [comment]
Is there already a library where I could parse concatenated
JSON. Here is a test case:
```
?- read_json(X), read_json(Y).
{"foo": 123}[null]
X = {foo:123}, Y = [0rNone].
```
X and Y replaced by whatever your parser gives, but
Y must show up as a list.

See also:
[https://en.wikipedia.org/wiki/JSON_streaming#Concatenated_JSON](https://en.wikipedia.org/wiki/JSON_streaming#Concatenated_JSON)

**Comment by Jean-Luc-Picard-2021** [comment]
Do you work with a JSON test suite? I have added library(json) now
as a first class citizen to my Prolog systems. But didn't have time yet
to include a JSON test suite as well.

Regression testing could lead to the closure of this ticket. Unless
I have my test suite ready, I cannot help you. You would need to
make the testing yourself and close the ticket.
