### ISSUE TITLE
Feature request: (=@=)/2 or variant/2 builtin

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#166]
I wonder whether Trealla Prolog has a (=@=)/2 or variant/2 builtin?
So far doing a GitHub search didn't reveal anything. Its available
in SWI-Prolog and documented here:

> **+Term1 =@= +Term2**
> True if Term1 is a variant of (or structurally equivalent to) Term2.
> This predicate is known by the name variant/2 in some other Prolog systems.
> https://www.swi-prolog.org/pldoc/man?predicate=%3D@%3D/2

But when I start Trealla Prolog, none of the two work:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.15.17

?- f(A,B,A) =@= f(X,Y,X).
Error: syntax error, near '=@=', operator expected, user:1
   false.

?- variant(f(A,B,A), f(X,Y,X)).
   throw(error(existence_error(procedure,variant/2),top_level/0)).
```

**Comment by infradig** [comment]
Why not do as SWI docs state:

:-op(700,xfx,=@=).

A =@= B :-
        copy_term(A, Ac),
        copy_term(B, Bc),
        numbervars(Ac, 0, N),
        numbervars(Bc, 0, N),
        Ac == Bc.

**Comment by Jean-Luc-Picard-2021** [comment]
I don't know, already this one is a tick faster, uses
only one `copy_term/2` and not two `copy_term/2`.
But it might interfer with attributed variables:
```
A =@= B :-
        copy_term(A, Ac),
        numbervars(Ac, 0, N),
        \+ \+ (numbervars(B, 0, N),
             Ac == B).
```
But a `numbervars/2` based solution has the disadvantage that
it doesn't work for terms that already contain '$VAR'/1, because
there could be a clash.

Also there are a couple of other solutions to do it, one
based on `subsumes_term/2`, and one I figured out yesterday
based on `term_variables/2`.

P.S.: Also a copy_term/2 based solution might interfer with
attributed variables, depending on what copy_term/2 does.

**Comment by pmoura** [comment]
> Why not do as SWI docs state: :-op(700,xfx,=@=). A =@= B :- copy_term(A, Ac), copy_term(B, Bc), numbervars(Ac, 0, N), numbervars(Bc, 0, N), Ac == Bc.
> […](#)

I have been using the SWI-Prolog definition in the Logtalk compiler and in the `lgtunit::variant/2` public predicate for a long time. No issues ever found or reported. In the `types` library, I have a different (and quite old) definition based on the standard `subsumes_term/2` predicate (that I just simplified now that supported Prolog backends properly implement this predicate). This second alternative definition should be faster (less term traversals) and was already described in e.g. the Quintus Prolog documentation:

https://quintus.sics.se/isl/quintus/html/quintus/lib-tma-subsumes.html#lib-tma-subsumes

But standardization of the `subsumes_term/2` predicate was a bumpy road. E.g. the 2009 ISO Prolog Core revision proposal (I was the editor at that time) specified instead a `subsumes/2` predicate. This was accepted unanimously in the WG17 meeting that year. Semantics was different as it performed a one-way unification (thus requiring the double negation idiom when defining `variant/2`). Eventually, this was replaced by the current ISO Prolog standard `subsumes_term/2` predicate (some systems provided already a `subsumes_chk/2` predicate with the intended semantics). It took some time IIRC for all maintained systems to catch up on full compliance. It's possible that SWI-Prolog definition predates the `subsumes_term/2` predicate standardization? But you know where to ask.

P.S. The current Logtalk tests for the `variant/2` predicate pass with both definitions with most supported backends (didn't confirm with B-Prolog, which no longer runs on macOS, and Quintus Prolog, which would require dusting an old Windows version VM).

**Comment by infradig** [comment]
I added variant/2.

**Comment by Jean-Luc-Picard-2021** [comment]
I cannot test it. Did not yet have a business case to add it to
my Prolog systems. When I opened the ticket, I thought there is
a business case, but this did not yet emerge.

In as far I also do not have time to add it in advance for the
occasion to happen. In as far I don't have test cases, and cannot
do some regression testing and close the ticket.

You would need to do this by yourself.

**Comment by infradig** [comment]
I added variant/2 in.

**Comment by Jean-Luc-Picard-2021** [comment]
I mean by "I cannot test it.", I don't have test cases. I explained
that after "I cannot test it.". So what I wanted to say, you have to test 
by yourself, and close the ticket by yourself.

Its not a problem that I cannot make "git pull" and "make". And
that I wouldn't find variant/2. The problem is I don't have a test suite
with test cases for variant/2. So "I cannot test it.".

You would need to do this by yourself. I wish the situation would
be better on my side, that I could help in the matter. But I am 
afraid and really sorry that I cannot do the testing, not because

of a technical obstacle, but lack of resources right now.
