### ISSUE TITLE
How use the dialect flag for flexible directives

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#168]
It seems that Trealla Prolog has a dialect flag.
```
?- current_prolog_flag(dialect, X).
   X = trealla.
```
How can I use the dielect flag for conditional compilation?
For example this doesn't work in a Prolog text:
```
:- (current_prolog_flag(trealla, swi) ->
      set_prolog_flag(double_quotes, codes); true).
```
I get this error:
```
Warning: unknown directive: ;/2
```

**Comment by infradig** [comment]
Do you want the if directive?

:- if((current_prolog_flag(dialect, trealla)).
BLAH JUST TREALLA
:- endif.

or

:- if((current_prolog_flag(dialect, Name),memberchk(Name,[trealla,swi]))).
BLAH JUST TREALLA AND SWI
:- endif.

**Comment by Jean-Luc-Picard-2021** [comment]
Meanwhile I could resolve the issue. As a result I have now an automation of 
my benchmark suite. Using Ant Tasks and stuff, and I can fully automated
render benchmark results combining a variety of Prolog systems,

among you now find also Trealla Prolog:

> **tpl = Trealla Prolog results**
https://www.xlog.ch/izytab/doclet/docs/19_perform/core/result.html

So I was already about to close this ticket. But on the other hand 
what you suggest goes by the name "conditional compilation", and
has some advantage over the what I was asking, i.e.

use another mechanism, which was called SWI-Prologism by Scryer
Prolog People, namely that directives can be arbitrary goals, including
ordinary Prolog if-then-else (->)/2.

Now the solution I have obtained uses neither "conditional compilation"
nor directives that can be arbitrary goals. "conditional compilation"
seems to be quite old, I find an early mention here:

> **:- lib(ifdef).**
https://www.ics.uci.edu/~dechter/courses/ics-275a/fall-99/slides/node287.html

I have such a library ifdef for Jekejeke Prolog. But it has not yet
been ported to Dogelog Player. But since the automation problem has
been solved, its kind of postponed now.
