### ISSUE TITLE
include/1 from ISO core standard missing

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#171]
Strange, the current version of Trealla Prolog gives me:
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.17.7
?- include('foo.txt').
   throw(error(existence_error(procedure,include/1),top_level/0)).
```
But `include/1` is found in the ISO core standard. For example
GNU Prolog doesn't implement `ensure_loaded/1`, but it provides
`include/1`, so this is kind of a least resort.

**Comment by infradig** [comment]
It's a directive only.

**Comment by Jean-Luc-Picard-2021** [comment]
So I can use it inside a Prolog text?
Will try, and when it works will close the ticket.

**Comment by infradig** [comment]
Any consulted file, yes.
