### ISSUE TITLE
Top-level call issue

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#172]
#86 again
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.17.7

?- F = call, F.
   throw(error(existence_error(procedure,call/0),top_level/0)).

?- call(_) =.. [F|_], F.
   F = call. % unexpected

?- call(_) =.. [F|_], call(F).
   F = call. % unexpected

?- \+ halt.

$ echo halt not requested | xargs -l bash -c 'echo $1 $0 $2'
not halt requested # single-valued logic spot removal topic, unverified supposition.
```

**Comment by flexoron** [comment]
Cognitive-logical 'not halt' means no exit but true and continue. Please, rethink this.

**Comment by infradig** [comment]
Not it doesn't, halt is an extra-logical operation.

**Comment by infradig** [comment]
The ISO standard says the predicate neither succeeds nor fails... it just
terminates execution. There can be no further logical processing.

**Comment by flexoron** [comment]
ISO who? It is an contradiction! halt and not halt cannot/must not do the same.

**Comment by infradig** [comment]
It is not a contradiction.
THE MACHINE STOPS

**Comment by flexoron** [comment]
If you like it.

**Comment by infradig** [comment]
It's not about what *I* like. It's how the Prolog standard defines it.

**Comment by flexoron** [comment]
No doubt. Pro-Logic.
