### ISSUE TITLE
Performance blackout (killed)

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#178]
This is the program of issue #169
```
$ cat testgnu.pl

isl({L},N) :- L = (_ is _+N).

run(Lim) :-
       	testmem(Lim,M,M1),
        !,
	member(Q,M1), \+member(Q,M),
	findall([_,_,Q3], member([_,_,Q3],M),F),
        length(F,Lf), write(Lf), nl, fail.

testmem(Lim,M,M1) :-
       	findall(Z,(between(1,Lim,N), isl({X}, N),
                   X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
                M),
         M1 = [[2,3,3],[3,4,4],[4,5,5],[5,6,6],[6,7,7],[7,8,8]].

testmem(Lim) :-
       	findall(Z,(between(1,Lim,N), isl({X}, N),
                   X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
                M),
	M1 = [[2,3,3],[3,4,4],[4,5,5],[5,6,6],[6,7,7],[7,8,8]],
	!,
	member(Q,M1), \+member(Q,M),
	findall([_,_,Q3], member([_,_,Q3],M),F),
        length(F,Lf), write(Lf), nl, fail.
```
```
$ trealla/tpl testgnu.pl
Trealla Prolog (c) Infradig 2020-2023, v2.18.7
?- time(testmem(10000)). 
10000
10000
10000
10000
10000
10000
% Time elapsed 0.142s, 400072 Inferences, 2.818 MLips)
      false.

?- time(run(10000)).
10000
^Z
[1]+  Stopped                 trealla/tpl testgnu.pl
$ kill %1 && fg
trealla/tpl testgnu.pl
Terminated
```
Ten thousand elements.
run/1 and testmem/1 should do the same thing but run/1 hangs and must be killed.
run/1 consumes gigabytes of memory and get killed by OS. (Use top to see the growing).

Five thousand elements
?- time(testmem(5000)). 
% Time elapsed 0.075s

?- time(run(5000)).
% Time elapsed 2.797s % Unfortunately awfully bad

**Comment by flexoron** [comment]
Performance comparsion the other way around:
```
Trealla: run(5000).    2.7s Five thousand elements
SWIPL:   run(400000).  2.7s Four hundred thousand
GNU/BP:  run(1000000). 2.3s One million processed
```

**Comment by infradig** [comment]
It's this...

   findall([_,_,Q3], member([_,_,Q3],M),F)

change (again) to

   findall(X, member(X,M),F)

and Trealla is as fast as SWI.

I'll look into it.

**Comment by flexoron** [comment]
Ok, but its a bit strange.
It looks like it depends on where this findall/3 is called.
```
?- time(testmem(400000)). % findall(X, member(X,M),F)
% Time elapsed 4.504s, 16000072 Inferences, 3.552 MLips) % no diff

% Well said, here it does not show the issue.

?- time(testmem(400000)). % findall([_,_,Q3], member([_,_,Q3],M),F) 
% Time elapsed 5.499s, 16000072 Inferences, 2.910 MLips) % diff 1s

%%%

?- time(run(400000)). % findall(X, member(X,M),F)
% Time elapsed 4.518s, 16000073 Inferences, 3.541 MLips)

?- time(run(400000)). % findall([_,_,Q3], member([_,_,Q3],M),F) 
Tilt!
```

**Comment by infradig** [comment]
Interesting: if you run it from an initialization/1 call it goes lightning fast...

:-initialization(main).

isl({L},N) :- L = (_ is _+N).

run(Lim) :-
       	testmem(Lim,M,M1),
        !,
	member(Q,M1), \+member(Q,M),
	findall([_,_,Q3], member([_,_,Q3],M),F),
        length(F,Lf), write(Lf), nl, fail.

testmem(Lim,M,M1) :-
       	findall(Z,(between(1,Lim,N), isl({X}, N),
                   X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
                M),
         M1 = [[2,3,3],[3,4,4],[4,5,5],[5,6,6],[6,7,7],[7,8,8]].

testmem(Lim) :-
       	findall(Z,(between(1,Lim,N), isl({X}, N),
                   X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
                M),
	M1 = [[2,3,3],[3,4,4],[4,5,5],[5,6,6],[6,7,7],[7,8,8]],
	!,
	member(Q,M1), \+member(Q,M),
	findall([_,_,Q3], member([_,_,Q3],M),F),
        length(F,Lf), write(Lf), nl, fail.

% EndOfTestFile (end-of-test-gnu-file-dot-pl)

main :-
	run(5000);halt.



~/trealla (devel) $ time tpl -q -f testgnu.pl
5000
5000
5000
5000
5000
5000

real	0m0.117s
user 0m0.108s
sys	0m0.008s

**Comment by flexoron** [comment]
Wow! Indeed! Trealla performs miracles.

**Comment by infradig** [comment]
I may have to change how repl queries are run to be like initialisation.

**Comment by infradig** [comment]
You can also speed up Trealla here by using:

  myfindall(A, B, C) :- findall(A, B, C).

and replacing all occurrences of findall with myfindall. Why I don't know.

**Comment by flexoron** [comment]
```
isl({L},N) :- L = (_ is _+N).

run(Lim) :-
        M1 = [[2,3,3],[3,4,4],[4,5,5],[5,6,6],[6,7,7],[7,8,8]],
       	testmem(Lim,M),
        !,
	member(Q,M1), \+member(Q,M),
	findall([_,_,Q3], member([_,_,Q3],M),F),
        length(F,Lf), write(Lf), nl, fail.

testmem(Lim,M) :-
       	findall(Z,(between(1,Lim,N), isl({X}, N),
                   X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
                M).
```
You can also speed up Trealla when creating M1 at run/1.
?- time(run(100000)).
% Time elapsed 1.426s

I guess this excludes a findall/3 issue and reveals an argument issue?
(reminds me of Tcl upvar - Create link to variable in a different stack frame)
```
Third argument = Bomb impact!

run(Lim) :- ..., testmem(Lim, M, _), ...
testmem(Lim, M, _) :- ...

?- time(run(10000)).
10000
^Z
[1]+  Stopped
```

**Comment by flexoron** [comment]
v2.19.0
```
Within the framework of Trealla's advanced development process, that's a good piece of work.
Thank you very much!
```
