### ISSUE TITLE
#11: must_be/2 further errors

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#18]
[Item#11](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#11)

**Comment by infradig** [comment]
Sticking with this (as does Scryer)

?- L=[1|L], must_be(chars,L).
   error(type_error(list,[1|_1]),must_be/2).

for now.

**Comment by UWN** [comment]
Right, you have the choice here. 7.12 last par
