### ISSUE TITLE
Unreliable binding of variables

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#195]
[Item#24](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#24)

**Comment by infradig** [comment]
It's a top-level reporting problem. If you do a write of the variables you
can see the slot-numbers are correct. Will look into it.

**Comment by UWN** [comment]
Some top level issues may be involved. But the core of it is not a top level problem:

```
?- ti(G_0,_), G_0.
   false.
?- ti(_,R_0), R_0.
   R_0 = (unify_with_occurs_check([[_A,_A|_B]|_B],[[[_A|_B]|_B]|_B]),unify_with_occurs_check([[_A|_B]|_B],[[[_A|_B]|_B]|_B]),unify_with_occurs_check([[_A|_B]|_B],[_A|_B])).
```
So the problem here is that the second goal `R_0` succeeds, no matter what it is displaying. But it should fail like the first.
