### ISSUE TITLE
unexpected type_error(float,round/1)

### ISSUE THREAD

**Issue by josd** [trealla-prolog/trealla#196]
We are experiencing the following error
```
$ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.20.4
?- X is round(floor(1/2)).
   error(type_error(float,round/1),round/1).
```
and we would expect
```
$ scryer-prolog
?- X is round(floor(1/2)).
   X = 0.
```

Thanks for Trealla and all the work!

**Comment by pmoura** [comment]
Trealla Prolog is ISO Prolog compliant here. Scryer Prolog is not. The signature for `floor/1` is float -> integer. The signature for `round/1` is float -> integer. There's no additional integer -> integer signature for it that would make your goal valid.

Another example of ISO compliance:

```text
$ gprolog
GNU Prolog 1.6.0 (64 bits)
Compiled Jun 22 2023, 12:33:09 with /opt/local/bin/gcc-mp-12
Copyright (C) 1999-2023 Daniel Diaz

| ?- X is round(floor(1/2)).
uncaught exception: error(type_error(float,0),(is)/2)
```

Arguably, if you're trying to round an integer, your are either using mixed arithmetic (questionable by itself) or you have a programming error in your code.

**Comment by josd** [comment]
Thanks a lot and now it is clear!

**Comment by UWN** [comment]
As a minor issue, Trealla is not fully conforming as the `Culprit` of the `type_error` is not the actual integer value in question, but rather the functor. Similarly:

```
?- X is 0.5 mod 2.
   error(type_error(integer,0.5),(mod)/2). % good
?- X is (1/2) mod 2.
   error(type_error(integer,(mod)/2),(mod)/2), unexpected. % expected as above

**Comment by josd** [comment]
> Arguably, if you're trying to round an integer, your are either using mixed arithmetic (questionable by itself) or you have a programming error in your code.

Right, it was a very old error inherited from eye which is now fixed in retina at https://github.com/eyereasoner/retina/blob/a23fabe2d4c324526f96f788ebf1f05c7264c965/retina.pl#L835
