### ISSUE TITLE
Dropping cyclic-terms, consideration

### ISSUE THREAD

**Issue by infradig** [trealla-prolog/trealla#2]
I am considering dropping support in Trealla for working with cyclic-terms/rational-trees. Trealla would just detect cycles and error, like GNU Prolog does.

**Comment by UWN** [comment]
The standard talks about NSTO-unifications only. So this is in no way a standard related issue. However, more than a quarter century later we could have a tiny bit of progress, couldn't we? But note that cyclic terms are always a can of worms as it violates so many basic assumptions. Think of it: term-ordering is not fully defined for cyclic terms. (That is a term ordering that fits into the well defined ordering of finite terms). So this is not an implementation issue, it is a real problem that cannot be solved by saying `true` or `false`. You could produce an error for such cases, though.

If I am at it:

```
Trealla Prolog (c) Infradig 2020-2022, v1.34.22
?- -X = X.
   X = -X.
?- set_prolog_flag(occurs_check, true).
   true.
?- -X = X.
   false.
?- set_prolog_flag(occurs_check, error).
   true.
?- -X = X.
   error(instantiation_error,term), unexpected.
   representation_error(term). % expected
```
