### ISSUE TITLE
Incompleteness

### ISSUE THREAD

**Issue by triska** [trealla-prolog/trealla#204]
With the following program:

<pre>
f(g(a)).
f(g(b)).
</pre>

I get:

<pre>
<b>?- f(g(X)).</b>
   X = a, <b>unexpected, incomplete</b>.
<b>?- f(g(b)).</b>
   true. % expected
</pre>

**Comment by josd** [comment]
Is now working fine
```
$ cat /tmp/m1.pl
f(g(a)).
f(g(b)).
```
```
$ tpl /tmp/m1.pl
Trealla Prolog (c) Infradig 2020-2023, v2.20.10
?- f(g(X)).
   X = a
;  X = b.
?- f(g(b)).
   true.
?- f(g(a)).
   true.
?-
```

**Comment by triska** [comment]
Thank you a lot!
