### ISSUE TITLE
Redundant dif/2 constraints

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#208]
(This is the last thing from #185, better under this name)

[iso-prolog/dif#21](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dif#21)
[Item#32](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#32)
```
?- dif([],A), A = [B].
   A = [B], dif([],[B]), unexpected.
?- dif([],A), A = [[]|B].
   A = [[]|B], dif([],[[]|B]), unexpected.
?- dif([],A), A = [[]|B], B = [].
   A = [[]], B = [].
```

Trealla and Scryer are the only ones.
Suggested solution: https://github.com/mthom/scryer-prolog/issues/135#issuecomment-488348886

**Comment by UWN** [comment]
Note this has been solved in Scryer.

**Comment by infradig** [comment]
If I use the latest dif.pl from Scryer I get...

```
~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.27.37-5-g7646-dirty
?- dif([],A), A = [B].
   A = [B].
```

which is good, but...

```
?- dif(A,B),A=[A|A],B=[B|B].
   dif:dif([A|A],[B|B]).
?- 
```

which is bad.

**Comment by UWN** [comment]
Which might be related to [Item#61](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#61).
