### ISSUE TITLE
Unreliable NSTO-unifications

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#209]
[Item#33](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#33)

**Comment by UWN** [comment]
UWN_blocking

**Comment by UWN** [comment]
You seem to ignore this one, although it is much more important, as it remains in the NSTO range.

**Comment by UWN** [comment]
No difference

**Comment by infradig** [comment]
Try a make clean

**Comment by infradig** [comment]
Sorry, I was mising it up with a previous similar one. I see it now.

**Comment by infradig** [comment]
Is the use of the variab;e_D intentional here?
Just asking because, bizarrely, if you change it to D then it works. I
guess that's a clue for me.
