### ISSUE TITLE
freeze/2 uninstantiation_error

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#21]
v2.0.16
```
?- member(A,Z), freeze(B,B), B=!, writeq(A/Z/B).
_0/[_0|_4]/ !   Z = [A|_A], B = !
;   error(uninstantiation_error(frozen),'$put_attributes'/2).
?- 
```
At present I can't interpret the error message: uninstantiation_error(frozen)?

And if freeze freezes together it unfreezes:
```
?- member(A,Z), freeze(B,B), freeze(B,B), B=!, writeq(A/Z/B).
_0/[_0|_4]/ !   Z = [A|_A], B = !
; _0/[_5,_0|_7]/ ! Z = [_A,A|_B], B = !
; _0/[_5,_8,_0|_10]/ ! Z = [_A,_B,A|_C], B = !
;  ... .
?-
```

**Comment by infradig** [comment]
For some reason the attributed variable B is not being cleared on
backtracking....

?- member(A,Z), (attvar(B) -> write(oops); write(ok)), nl, freeze(B,B),
B=!, writeq(A/Z/B).
ok
_0/[_0|_4]/ !   Z = [A|_A], B = !
; oops
  error(uninstantiation_error(frozen),'$put_attributes'/2).

Odd, as it's ok with repeat or between/3 (but they are builtins).

**Comment by flexoron** [comment]
Who is the brain behind freeze.pl? Maybe there can be found a hidden vivacious idea.

**Comment by infradig** [comment]
There's nothing wrong with freeze.pl, Trealla is at fault here.

**Comment by flexoron** [comment]
```
?- append([B],[B],B),B=!.
   false.

?- append([B],[B],B), freeze(B,B), B=!.
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
Thanks, I have a fix for this. Exposed a fundamental flaw when setting attributes... it wasn't adding to the trail.

~/trealla (devel) $ tpl
?- member(A,Z), freeze(B,B), B=!, writeq(A/Z/B).
_0/[_0|_4]/ !   Z = [A|_A], B = !
; _0/[_5,_0|_7]/ ! Z = [_A,A|_B], B = !
; _0/[_5,_8,_0|_10]/ ! Z = [_A,_B,A|_C], B = !
; _0/[_5,_8,_11,_0|_13]/ ! Z = [_A,_B,_C,A|_D], B = !
;
~/trealla (devel) $ scryer-prolog 
?- member(A,Z), freeze(B,B), B=!, writeq(A/Z/B).
_1923230/[_1923230|_1923613]/!   Z = [A|_A], B = !
;  _1923230/[_1923612,_1923230|_1923616]/!Z = [_A,A|_B], B = !
;  _1923230/[_1923612,_1923615,_1923230|_1923619]/!Z = [_A,_B,A|_C], B = !
;  _1923230/[_1923612,_1923615,_1923618,_1923230|_1923622]/!Z = [_A,_B,_C,A|_D], B = !
;  ... .
?- 
~/trealla (devel) $

**Comment by flexoron** [comment]
v2.1.0
```
?- append([B],[B],B), freeze(B,B), B=!.
Segmentation fault (core dumped)
```
Can you try this with scryer, too? I don't have it in use right now.

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
?- append([B],[B],B), freeze(B,B), B=!.
   error(type_error(callable,[[[_82,_83],[_82,_83]],call]),maplist_/2).

~/trealla (devel) $ scryer-prolog 
?- append([B],[B],B), freeze(B,B), B=!.
   error(type_error(callable,[...,...]),call/1).
?- 
~/trealla (devel) $

**Comment by flexoron** [comment]
Great! Thank you.

**Comment by infradig** [comment]
No, thank you. It solved a long-standing issue with attvars and fixed a few
Logtalk test failures.

**Comment by flexoron** [comment]
```
?- freeze(A,B=b),freeze(B,A=a), freeze(C,D=d), C=go, freeze(D,B=b), frozen((A,B,C,D),X),writeq(A/B).
a/b   A = a, B = b, C = go, D = d, X = true.
```

**Comment by infradig** [comment]
I was looking for the bug, then realized it was good.

~/trealla (devel) $ swipl
?- freeze(A,B=b),freeze(B,A=a), freeze(C,D=d), C=go, freeze(D,B=b),
frozen((A,B,C,D),X),writeq(A/B).
a/b
A = a,
B = b,
C = go,
D = d,
X = true.

~/trealla (devel) $ tpl
?- freeze(A,B=b),freeze(B,A=a), freeze(C,D=d), C=go, freeze(D,B=b),
frozen((A,B,C,D),X),writeq(A/B).
a/b   A = a, B = b, C = go, D = d, X = true.
