### ISSUE TITLE
Version number noisy and unreliable

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#215]
Currently,
you are producing many versions per day, but still there are also
intermediate versions.  It so just happend with *.21. This renders the
version numbers useless.  They only fill up the notification box, so I
will turn it off, if this does not stop. Instead, <code>git
describe</code> should give a combination of an official version
number plus some counting integer plus a couple of hash bits just to
be safe.  The least noise inducing way to get updates is <code>git
pull && make && ./tpl</code>

**Comment by infradig** [comment]
I only do intermediates in devel branch.

**Comment by infradig** [comment]
It should be quiet the rest of the week as I'll be engaged on other things.

**Comment by UWN** [comment]
`git describe` now said 2.20.22, but `make` made 2.20.21. After a `make clean` all is in sync...
