### ISSUE TITLE
Unexpected additional initialization error

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#217]
[Item#40](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#40)

**Comment by UWN** [comment]
Can you reproduce these?

**Comment by UWN** [comment]
That is only half a solution as now the actual goal is no longer displayed.

**Comment by infradig** [comment]
Look it up in the file.

**Comment by UWN** [comment]
<s>Well, you are just hiding the problem behind.</s> (It was in devel)

**Comment by UWN** [comment]
Perfect!
