### ISSUE TITLE
Write options: wrong precedence

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#225]
```
?- write_term(T,[variable_names(['Bad'=T]),variable_names(['Good'=T])]). 
Bad   true.
```
See https://github.com/didoudiaz/gprolog/issues/46

**Comment by infradig** [comment]
Did not know that. Thought it was once only.

**Comment by UWN** [comment]
Shameless promotional link: [Get the original standard for USD 30](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/#access)

**Comment by infradig** [comment]
I have it, I just don't refer to it as much as I should.
