### ISSUE TITLE
Top level: Return should stop current query

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#226]
... but currently all further answers are displayed. Really irritating. Think of
```
?- length(L,N).
   L = [], N = 0
;  L = [_A], N = 1
;  L = [_A,_B], N = 2
;  
```
And now, I'm done, and I want to issue another query. Thus I enter <kbd>Return</kbd>. With Trealla now all further answers are produced.

In B, Ciao, ECLiPSe, GNU, Ichiban, IF, Minerva, SICStus, Scryer, SWI, YAP, XSB <kbd>Return</kbd> returns to the top level shell and certainly in many more.

**Comment by infradig** [comment]
So what gives all answers, not 'a' because that's abort now.

**Comment by UWN** [comment]
GNU, Scryer use `a` for all. This `a` for abort, doesn't it happen in an entirely different situation? (Otherwise `t` for total)
