### ISSUE TITLE
open/4 processing the reposition/1 option 

### ISSUE THREAD

**Issue by pmoura** [trealla-prolog/trealla#227]
More of a note than an issue. Consider the following query:

```text
?- open(rf, write, Stream, [reposition(true), reposition(false)]), stream_property(Stream, reposition(Reposition)).
   Stream = '<$stream>'(4), Reposition = true.
```

Not a bug as the ISO standard specification for this option is:

> `reposition(Bool)` - If `Bool` (7.1.4.2) is `true` then it shall be possible to reposition the stream, else if `Bool` is `false` it shall be implementation defined whether or not it is possible to reposition the stream.

Some other systems behave like Trealla Prolog (e.g. ECLiPSe, SWI-Prolog, or YAP). Others respect the user-specified option (e.g GNU Prolog, LVM, Scryer Prolog, or SICStus Prolog). I found the later behavior preferable as it's more inline with user expectations when specifying `reposition(false)`. Wondering if the current Trealla Prolog behavior here is intended or accidental.

I added a skipped test for this behavior to the latest Logtalk distribution tests:

```text
% lgt_open_4_40: skipped (implementation defined per ISO standard)
```

**Comment by infradig** [comment]
Not intended, just ignorance of the standard when i wrote that code. Just
ask UWN.

**Comment by pmoura** [comment]
As I wrote and quoted, not a bug. But Trealla's choice here should eventually be mentioned in its documentation.

**Comment by infradig** [comment]
I'll be changing it.
