### ISSUE TITLE
Arithmetic number test fails (and succeeds)

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#230]
```
?- X = -1, Y = +1, Z is X + Y, number(Y).
   false. % If Y is not a number why does the next query succeed?

?- X = -1, Y = +1, Z is X + Y.
   X = -1, Y = +1, Z = 0.
```

**Comment by infradig** [comment]
Because +1 is an evaluable expression not a number, unlike -1 which is the
latter.

**Comment by infradig** [comment]
I mean +1

**Comment by infradig** [comment]
Do a write_canonical(+1) to see for yourself.

**Comment by flexoron** [comment]
Oh, Ok then.

**Comment by flexoron** [comment]
Still I've a problem with -0.
```
?- number(-0), write_canonical(-0).
0   true.
?- number(-1), write_canonical(-1).
-1   true.
```
What is -0 good for?

**Comment by infradig** [comment]
Absolutely nothing.

**Comment by flexoron** [comment]
```
But - * - = +

?- X is -0 * -0.0.
   X = -0.0.

?- X is -1 * -0.0.
   X = 0.0.


```
I might be good for something

**Comment by infradig** [comment]
Looks like a floating point artefact.

**Comment by flexoron** [comment]
Not really:

If -0 is a number then - is a minus-sign and  - * - = +

?- number(-0).
   true.

Conclusion: Inconsequent or illogical implementation resp. specification

**Comment by flexoron** [comment]
?- X is -0 * -0.0.
   X = -0.0. % Prolog might be good for speculative mathematics research.

A good reason not opening an issue :)
