### ISSUE TITLE
write_canonical inconsistent print symbolism

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#231]
```
?- number(-1), write_canonical(-1).
-1   true.

?- number(-0), write_canonical(-0).
0   true. % unexpected; expecting -0 true.
```

**Comment by infradig** [comment]
There is no -0 value

**Comment by flexoron** [comment]
Bring into use then.

**Comment by flexoron** [comment]
I look at the sign and not at the value and if -0 is a number, the sign has a meaning.

**Comment by UWN** [comment]
```
?- 0 == -0.
    true.
```
This is well-defined like this in the standard. No ambiguity whatsoever. Not a single system non-conforming. Not even SWI.

**Comment by flexoron** [comment]
Flip-flopping so-called standards,
pure mathematicians do not define (-0) * (-0.0) = -0.0

**Comment by flexoron** [comment]
```
?- 0 == -0.
    true.

?- 0.0 == -0.0.
   true.
```
If -0 is a number then the minus-sign is an algebraic symbol and those bear a meaning.
Hint: Criterion of meaningfulness.

**Comment by flexoron** [comment]
Martin Heidegger just told me to close this issue: Das Nichts nichtet (The nothing nothings [here]).
