### ISSUE TITLE
It would be nice if we could have uuid like in Scryer

### ISSUE THREAD

**Issue by josd** [trealla-prolog/trealla#239]
It would be nice if we could have uuid like in Scryer:
```
:- use_module(library(uuid)).

    uuidv4_string(Genid)
```
There is a hacked version right now at https://github.com/KNowledgeOnWebScale/retina/blob/45c887486ff8ffed7b60c3e644cd991ddb0ef554/retina.pl#L1197

**Comment by pmoura** [comment]
Logtalk provides both UUID and ULID libraries that can be used with all supported backend Prolog systems, including of course Trealla Prolog:

```text
$ logtalk_tester -p trealla -s ~/Documents/Logtalk/
% Batch testing started @ 2023-07-03 23:05:50
%         Logtalk version: 3.67.0-b02
%         Trealla Prolog version: 2.21.8
%
% logtalk3/library/uuid
%         6 tests: 0 skipped, 6 passed, 0 failed (0 flaky)
%         completed tests from object tests in 2 seconds
%         clause coverage 91.8918918918919%
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 6 tests: 0 skipped, 6 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-07-03 23:05:52
```

```text
$ logtalk_tester -p trealla -s ~/Documents/Logtalk/
% Batch testing started @ 2023-07-03 23:06:50
%         Logtalk version: 3.67.0-b02
%         Trealla Prolog version: 2.21.8
%
% logtalk3/library/ulid
%         22 tests: 0 skipped, 22 passed, 0 failed (0 flaky)
%         completed tests from object tests in 11 seconds
%         clause coverage 91.0714285714286%
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 22 tests: 0 skipped, 22 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-07-03 23:07:02
```

**Comment by infradig** [comment]
Do you specificlyl require a UUIDv4? If not Trealla already has uuid/1.

**Comment by josd** [comment]
I know, but we use it in the N3 built-in `log:uuid` which should follow the standard https://datatracker.ietf.org/doc/html/rfc4122

**Comment by josd** [comment]
plus that we also propose to use it as genid in Skolem IRI's https://en.wikipedia.org/wiki/Well-known_URI

**Comment by infradig** [comment]
I have added Adrián Arroyo's library(uuid).

~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.21.9
?- use_module(library(uuid)).
   true.
?- uuidv4_string(X).
   X = "b9b0e66b-|...".
?-

**Comment by infradig** [comment]
?- uuidv4_string(X), write_term(X,[]), nl.
"291104c0-447a-483b-a086-a4d978fe1fe1"
   X = "291104c0-|...".
?-

**Comment by infradig** [comment]
Paulo is right, Retina could be in Logtalk and gain a lot in portablability.

**Comment by josd** [comment]
> I have added Adrián Arroyo's library(uuid).

Great and is now used in https://github.com/KNowledgeOnWebScale/retina
Thanks for Trealla!

**Comment by josd** [comment]
> Paulo is right, Retina could be in Logtalk and gain a lot in portablability.

A portable web logic is what we indeed aim for with [RDF Surfaces: Computer Says No](https://arxiv.org/pdf/2305.08476.pdf)
