### ISSUE TITLE
Question about compare/3 results

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#242]
```
?- compare(Op,A,B).
   Op = (<).

In this case it might be of advantage that Op = (@=<) ?
```

**Comment by infradig** [comment]
Stop trying to invent new stuff.

**Comment by flexoron** [comment]
Backatu.
?- sort([s(t),a,1,3.2,UV],S).
   S = [UV,3.2,1,a,s(t)].

**Comment by infradig** [comment]
Sort on types, then values within type. Looks as it's supposed to.

**Comment by flexoron** [comment]
?- compare(Op,A,B), A @=< B.
   Op = (<). % (@=<) disvalued, never mind!

**Comment by infradig** [comment]
Arg1 of compare is not an operator as such, it us an order <, > or =.
That's how it's defined and there is no point tilting at windmills.

**Comment by flexoron** [comment]
Tilting at windmills? Location-dependent ... Switz? Spyn? Gergory? Austrialius,a,um? Neverlands? You name it!

**Comment by infradig** [comment]
How about La Mancha?

**Comment by flexoron** [comment]
La Mancha = Lost Manna
Yes, of course, lets gather supernatural power there and your spirit will be thankful.
