### ISSUE TITLE
length/2 segfault with larger lists, limitation at 0x8000

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#242]
```
 ulrich@TU-Wien:/opt/gupu/trealla$ git pull&&make OPT=-std=c99 NOSSL=1&&kill%1;date;git describe;./tpl
Already up to date.
make: Nothing to be done for 'all'.
kill%1: command not found
Sa Aug 14 09:31:57 CEST 2021
fatal: No annotated tags can describe '0c49e94259afd52745cb5e8bf80472ecb9177e76'.
However, there were unannotated tags: try --tags.
Trealla Prolog (c) Infradig 2020-2021, v1.10.33
?- length(K, 0x7FFF).
Segmentation fault (core dumped)
```

This does not happen all the time which is odd. And then from `0x8000` on:

```
?- length(L,0x8000).
uncaught exception: error(resource_error(too_many_vars,32768),length/2)    % unexpected
false.
```

Of course, in 7.12.2:

> h) There shall be a Resource Error at any stage of execution when the processor has insufficient resources to complete execution."

But do you really have insufficient resources? I am not sure since even

```
?- length(K, 0x600),length(J,0x600), T=K+J.
```
works.

Could this be some skeleton-limitation? Is it possible to make a skeleton with 0x7FFD many variables and a rest that links to the next skeleton? I believe C-Prolog had a special 10 list elements skeleton.

I tried to trick `length/2` but to no avail:

```
?- length(K, N), N = 0x8000.
uncaught exception: error(resource_error(too_many_vars,32768),length/2)
```

**Comment by UWN** [comment]
And, to continue 7.12.2 h:

> It has the form
  resource_error(Resource) where Resource is an
  implementation dependent atom.

Therefore, `resource_error(too_many_vars,32768)` does have one argument too much.

**Comment by flexoron** [comment]
Something observed

The segfault happens here;

query.c:862
set_var (q=0x55555584cca0, c=0x7ffff72eb070, ... )

The problem:  c=0x7ffff72eb070
this cell address gets invalid(changed by realloc) 
:
alloc_grow
realloc
return
:
alloc_grow
realloc
return
:
after some rounds, realloc decides to call mremap
:
alloc_grow
realloc
   mremap 
return
:
alloc_grow
realloc
   mremap (changes \*addr)
\*addr:  0x7ffff6f93010 <- this is the new cell (c=0x...) address
return
:
hmm, I don't find where to set the new address, the old one is still in a structure
:
and so, set_var fails
segfault:
set_var (q=0x55555584cca0, c=0x7ffff72eb070 ...
Cannot access memory at address 0x7ffff72eb070

succeeds:
set_var (q=0x55555584cca0, c=0x7ffff6f93010 ...
access: \*(struct cell_ \*)0x7ffff6f93010
:
:
prints out N of length(N,0x7FFF)

btw
it has nothing to do with value 0x7FFF
for example 
length(N,31995) (7CFB) ok
length(N,31996) (7CFC) segfault

maybe 0x7ffff72eb070 is an access into an invalid page

**Comment by infradig** [comment]
Yeah, there's a problem with reallocating larger slot space. I have to work
out a solution. The problem, of course, is extant pointers.

**Comment by infradig** [comment]
I have up some limits. The crash was because a 16-bit number was used to track vars.

**Comment by UWN** [comment]
```
ulrich@TU-Wien:/opt/gupu/trealla$ git pull&&make OPT=-std=c99 NOSSL=1&&kill%1;date;git describe;./tpl
Already up to date.
make: Nothing to be done for 'all'.
kill%1: command not found
Mi Aug 18 09:45:34 CEST 2021
fatal: No annotated tags can describe 'b378b814dd4fecd037fb45dd8894c06b74e9d303'.
However, there were unannotated tags: try --tags.
Trealla Prolog (c) Infradig 2020-2021, v1.10.33
?- length(K, N), N = 0x8000.
Segmentation fault (core dumped)
```

I hope that by "core" you do not mean [General core](https://www.iso.org/standard/21413.html) :-)

**Comment by UWN** [comment]
Still in:

```
ulrich@TU-Wien:/opt/gupu/trealla$ git pull&&make OPT=-std=c99 NOSSL=1&&kill%1;date;git describe;./tpl
Already up to date.
make: Nothing to be done for 'all'.
kill%1: command not found
Mi Aug 18 11:26:34 CEST 2021
fatal: No annotated tags can describe 'd896575ef82c478a4ee700c37fa3cfc400e425d7'.
However, there were unannotated tags: try --tags.
Trealla Prolog (c) Infradig 2020-2021, v1.10.33
?- length(K, N), N = 0x8000.
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
You're living in the past Ulrich 😉

~/trealla$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.11.1-18-gd89657-dirty
?- length(L, N), N = 0x8000.
L =
[_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,_101,_102,_103,_104,_105,_106,_107,_108,_109,_110,_111,_112,_113,_114,_115,_116,_117,_118,_119,_120,_121,_122,_123,_124,_125,_126,_127,_128,_129,_130,_131,_132,_133,_134,_135,_136,_137,_138,_139,_140,_141,_142,_143,_144,_145,_146,_147,_148,_149,_150,_151,_152,_153,_154,_155,_156,_157,_158,_159,_160,_161,_162,_163,_164,_165,_166,_167,_168,_169,_170,_171,_172,_173,_174,_175,_176,_177,_178,_179,_180,_181,_182,_183,_184,_185,_186,_187,_188,_189,_190,_191,_192,_193,_194,_195,_196,_197,_198,_199,_200,_201,_202,_203,_204,_205,_206,_207,_208,_209,_210,_211,_212,_213,_214,_215,_216,_217,_218,_219,_220,_221,_222,_223,_224,_225,_226,_227,_228,_229,_230,_231,_232,_233,_234,_235,_236,_237,_238,_239,_240,_241,_242,_243,_244,_245,_246,_247,_248,_249,_250,_251,_252,_253,_254,_255,_256,_257,_258,_259,_260,_261,_262|...],
N = 32768
; ...
?-

**Comment by josd** [comment]
Well, living with the current latest tpl (both master and devel) we get
```
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.11.2
?- length(L, N), N = 0x8000.
Segmentation fault
```

**Comment by infradig** [comment]
Interesting.

**Comment by infradig** [comment]
Ok, thanks. I should have run this by valgrind first. Updated.

**Comment by josd** [comment]
Now it is fine
```
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.11.3-2-gc93fc
?- length(L, N), N = 0x8000.
L = [_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,_101,_102,_103,_104,_105,_106,_107,_108,_109,_110,_111,_112,_113,_114,_115,_116,_117,_118,_119,_120,_121,_122,_123,_124,_125,_126,_127,_128,_129,_130,_131,_132,_133,_134,_135,_136,_137,_138,_139,_140,_141,_142,_143,_144,_145,_146,_147,_148,_149,_150,_151,_152,_153,_154,_155,_156,_157,_158,_159,_160,_161,_162,_163,_164,_165,_166,_167,_168,_169,_170,_171,_172,_173,_174,_175,_176,_177,_178,_179,_180,_181,_182,_183,_184,_185,_186,_187,_188,_189,_190,_191,_192,_193,_194,_195,_196,_197,_198,_199,_200,_201,_202,_203,_204,_205,_206,_207,_208,_209,_210,_211,_212,_213,_214,_215,_216,_217,_218,_219,_220,_221,_222,_223,_224,_225,_226,_227,_228,_229,_230,_231,_232,_233,_234,_235,_236,_237,_238,_239,_240,_241,_242,_243,_244,_245,_246,_247,_248,_249,_250,_251,_252,_253,_254,_255,_256,_257,_258,_259,_260,_261,_262|...],
N = 32768
; ...
?-
```
and the `...` is great 😉

**Comment by flexoron** [comment]
Trealla v1.11.3

$ ./tpl -g "length(N,31996)."
Segmentation fault (core dumped)

**Comment by infradig** [comment]
Should be ok with 1.11.4

**Comment by flexoron** [comment]
1.11.4 performance lost

**Comment by infradig** [comment]
What does that mean?

**Comment by flexoron** [comment]
$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.11.4
?- length(N,X), X = 0x7FFF.
waiting

$ strace
[ Process PID=139644 runs in x32 mode. ]  ????????
after a while
[ Process PID=139644 runs in 64 bit mode. ]

**Comment by flexoron** [comment]
./tpl -g "length(N,X), X = 300."
N = [_6 .... ].
X = 300
;
hangs

there is a mmap, mremap problem

**Comment by pmoura** [comment]
That `length/2` goal will be returning incrementally bigger lists by backtracking. But only one of them will have length 300. After, the `X = 300` will always fail, forcing backtracking... until you run out of memory.

**Comment by flexoron** [comment]
seems the pointer fault has been fixed with 1.1.4
$ ./tpl -g "length(N,3196)." ok
$ ./tpl -g "length(N,0x7FFF)." ok
$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.11.4
?- length(N,3196). ok
?- length(N,0x7FFF). ok

**Comment by UWN** [comment]
```
Mi Aug 18 19:21:17 CEST 2021
fatal: No annotated tags can describe 'c93fc9b1dae0c8edbbd42ad4ebd635da0275bda3'.
However, there were unannotated tags: try --tags.
Trealla Prolog (c) Infradig 2020-2021, v1.10.33
?- length(K, N), length(J, N), K == J.
K = [],
N = 0,
J = [] 
; Killed
```

What is irritating how fast this Killed message is arriving. Whereas `length(K, N),` false takes its time

**Comment by flexoron** [comment]
could be no system swap, do you have some?

$ swapon -s
/dev/dm-1 ..........

**Comment by UWN** [comment]
@flexoron Thank you, in fact all my swap was used up. Reboot. Now I tried it again, and it ran longer before stopping the same way. As long as there is no robust overflow handling, this will not work as intended.

**Comment by flexoron** [comment]
?- length(K, N), length(J, N), write(N), write(' '), K == J, false.
0 1 .... 10000 (in words ten thousand) consumes memory fast, gets stuck into  system swapping.

?- length(K, N), write(N), write(' '), false.
0 1 ... 90000 ... ticks every second ...90001, tick, 90002,  CPU run hot.

**Comment by infradig** [comment]
Swap is a waste. Turn it off.

**Comment by flexoron** [comment]
forget the strange memory allocation behaviour,
blaming Linux Kernel v4 for it. v5 does a better job.

**Comment by infradig** [comment]
No worries, I had forgotten about strace. Informative tool!

**Comment by flexoron** [comment]
fyi: quick hack on Linux

%%%

heap.c

#include <unistd.h>
#include <sys/sysinfo.h>
:
alloc_grow() {
:
void* mem;

// inserted these two lines and the includes above
long mem_free = ((sysconf(_SC_PAGESIZE))*(sysconf(_SC_AVPHYS_PAGES)))/1048576;
if (mem_free < 1000) { return 0; }

do {
mem = realloc()
:

%%%

$ ./tpl
Trealla Prolog (c) Infradig 2020-2021, v1.11.4

?- length(K, N), length(J, N), K == J,false.
uncaught exception: error(resource_error(too_many_vars),length/2)
false.
?-

at that point:
N = 5692 (depends on os-system memory utilisation), 
trealla gives back allocated pages.

50 times repeated
?- length(K, N), length(J, N), K == J,false.
uncaught exception: error(resource_error(too_many_vars),length/2)
false.
?-
N = 5692
N = 5692
:

**Comment by UWN** [comment]
Now the limit is at:

```
?- length(L,0x1FFFF).
L = [_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65|...].
?- length(L,0x20000).
uncaught exception: error(resource_error(too_many_vars),length/2)
```

Is there really a resource `too_many_vars`?

**Comment by infradig** [comment]
There has to be some limit, or should it be allowed to consume all memory
and crash? Or do you object to the message itself?

**Comment by UWN** [comment]
It is somewhat unexpected since using twice as much memory still works:

```
?- length(L,0x1FFFF), length (K,0x1FFFF), T=L+K.
L = [_A, _B, _C, _D, _E, _F, _G, _H, _I|...],
K = [_F5041, _G5041, _H5041, _I5041, _J5041, _K5041, _L5041, _M5041, _N5041|...],
T = [_A, _B, _C, _D, _E, _F, _G, _H|...]+[_F5041, _G5041, _H5041, _I5041, _J5041, _K5041, _L5041, _M5041|...].
```
As to the message, `too_many_vars` isn't a resource. Which isn't the deepest problem, but it really looks odd that you set a limit when you still have enough resources present. Of course the standard only requires this atom to be an implementation *dependent* atom. So you can chose whatever atom you want. But then always recall that a standard is only a [*precondition* to a working system](https://stackoverflow.com/search?q=%5Biso-prolog%5D+precondition). If you are into token conformance only, just `main(){exit(1);}` will do. Er, no, it is rather

```
#include <stdlib.h>
int main(){exit(1);}
```

The reason I am so interested into these corner cases are indeed non-termination inference and analysis issues. As a side benefit to you such considerations often uncover general bugs as well.

**Comment by flexoron** [comment]
... uncover general bugs. this is true. here is an example concerning memory

Trealla is a kind of a malloc exerciser.

Under certain conditions it's not just that
you get Segmentation fault (core dumped)
but also ``Aborted (core dumped)  <-- This is a hidden bug which happens by chance!``

To catch the light, memory alloc/free/trim must be centralized and
handled for each system more or less differently.
So, unfortunately this is a step into system-programming and non-portable.

Why is this?
Because Trealla likes to run in unixoid(multi-tasking,multi-user) systems
and you never know how much memory is free without monitoring that in the
process itself(to decide if it makes sense to call malloc at all). 
At that point Trealla should pause prolog processing, inform the user and
try to force freeing memory and if this fails doing whatever is possible
without calling malloc until memory is available again.

**Comment by infradig** [comment]
Well swi & gprolog just give 'stack' resource errors at some some arbitrary
(but settable) point. Scryer runs until the system crashes it. I think a
crash is ultimately undesirable.

**Comment by UWN** [comment]
I completely [agree](https://github.com/mthom/scryer-prolog/issues/16) w.r.t your view on crashes. What is most desirable are capabilities to catch such overflows such that you can continue reasoning thereafter. Another possibility are timeouts but they are not always applicable.

**Comment by UWN** [comment]
There used to be a [`library(spaceout)`](https://sicstus.sics.se/sicstus/docs/3.12.11/html/sicstus/Spaceout.html#Spaceout) in some later SICStus 3.12 versions, but it was discarded in 4.

**Comment by flexoron** [comment]
No wonder. All attempts are somehow work-arounds doomed to fail:
Rust 1.57 stabilizes try_reserve for Vec, String, HashMap, HashSet, and VecDeque ... (lol, sorry) ...
However, Rust does not guarantee that the returned memory is actually allocated by the kernel

try_reserve is what I described above.
But there is a sharp distinction.
In 'C' programming everything is a byte (or bytes if you like)
and the programmer has those under control
and this is much better than implementing just try_reserve for different structures.
and one more thing: a user misterx process always runs limited, a user root process has more abilities (thats why the s-bit exist)

**Comment by UWN** [comment]
Now I get:

```
ulrich@p0:/opt/gupu/trealla$ ulimit -v 30000
ulrich@p0:/opt/gupu/trealla$ ulimit -v
30000
ulrich@p0:/opt/gupu/trealla$ ./tpl -f --version
Trealla Prolog (c) Infradig 2020-2022, v1.22.34
ulrich@p0:/opt/gupu/trealla$ ./tpl -f
?- length(K, 0x7FFF).
   false. % unexpected, expected resource_error
```

**Comment by UWN** [comment]
Above was Ubuntu 14. On Ubuntu 21 I get:

```ulrich@g1:/opt/gupu/trealla$ ulimit -v 30000
ulrich@g1:/opt/gupu/trealla$ time ./tpl -f --version
Trealla Prolog (c) Infradig 2020-2022, v1.22.37

real    0m0.011s
user    0m0.011s
sys     0m0.000s
ulrich@g1:/opt/gupu/trealla$ time ./tpl -f
?- length(K, 0x10000).
   K = [_A,_B,_C,_D,_E,_F,_G,_H,_I,_J,_K,_L,_M,_N,_O,_P,_Q,_R,_S,_T,_U,_V,_W,_X,_Y,_Z,...].
?- length(K, 0x10000).
   false.
?- 
```

**Comment by infradig** [comment]
Yes, reviewing out of memory when using ulimits.
