### ISSUE TITLE
#12: nth0/3 incorrect

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#25]
```
?- nth0(N, [[]|Es], Es), ground(Es).
   N = 0, Es = []
;  N = 2, Es = [2|2], unexpected
;  ... .

**Comment by UWN** [comment]
[Item#12](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#12)

**Comment by infradig** [comment]
Well it seems to work with optimisation off..

~/trealla (devel) $ tpl -O0
?- nth0(N, [[]|Es], Es), ground(Es).
   N = 0, Es = []
; ^C
Action or (h)elp: x

so something to look at there.

**Comment by UWN** [comment]
```
?- nth0(N, [[]|Es], Es), ground(Es).
   N = 0, Es = []
; █
```
Perfect!
