### ISSUE TITLE
(=)/2 displayed result divergence

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#255]
v2.22.0
```
?- X-Y= _-_ .
   true.

?- _-_=X-Y.
   X = _A, Y = _B.

?- X-_=_-Y.
   Y = _A.

?- X-_=_-Y, X=_A.
   Y = _A,  _A = X. % looks wrong, users don't know that tpl uses/generates _A internally.
?- X-_=_-Y, X=_A, _A=x.
   X = x, Y = _A, _A = X. % looks like Y=X but this is not true.


```
Why right-sided variables are printed but not those placed on the left side?

**Comment by flexoron** [comment]
v2.22.2
```
Minor divergence: An unmeant puzzlement.

?- X-_=_-Y, X=_1, write(X/Y).
_0/_1   _1 = X. % _1 = X but X written as _0 and Y = _1.

?-  X-_0=_1-Y, write(X/Y).
_0/_1   _1 = X, Y = _0. % A user might be confused by this.
```

**Comment by infradig** [comment]
Variables bind high (more recent) to low (older). So X is unbound and
retains it's original designation as the zeroth slot. The X=_1 unification
changes nothing for X.

**Comment by flexoron** [comment]
Yes, this is why I called it an unmeant puzzlement.
Perhaps an average user like me does not know
that _0 and _0 name different things in this case(which is tpl-specific).
I would call it a glitch or quirk or a classic case of documention.

**Comment by infradig** [comment]
I think using variables of the form _# (where # is an integer) is probably
unwise.

**Comment by flexoron** [comment]
Hmm ... spoofing SWI (v8.4.0) does not work:
?- X-_0=_1-Y, write(X/Y).
_13536/_13538
X = _1,
_0 = Y.

?- X-_13536=_13538-Y, write(X/Y).
_15658/_15660
X = _13538,
_13536 = Y.

And GNU does not print variables which begin with _
| ?- X-_0=_1-Y, write(X/Y).
_279/_280
yes
| ?

Whereas B-Prolog 'ignores' Y
| ?- X-_0=_1-Y, write(X/Y).
_198/_208X = _1
yes

ECLiPSe razzia
[eclipse 1]: X-_0=_1-Y, write(X/Y).
X / _0
X = X
_0 = _0
_1 = X
Y = _0
Yes (0.00s cpu)

Razzia continued with writeq
[eclipse 1]: X-_0=_1-Y, writeq(X/Y).
_59 / _67
X = X
_0 = _0
_1 = X
Y = _0

Completion. Trealla is in good company:
[eclipse 2]: X-_59=_67-Y,writeq(X/Y).
_59 / _67
X = X
_59 = _59
_67 = X
Y = _59
