### ISSUE TITLE
feature request ¤ should behave like $ during writing

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#26]
Trealla gives me:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2022, v2.0.16
$ ./tpl
?- X = $$$ .
   X = $$$ .
?- X = $$$6 .
Error: syntax error, near '6', operator expected
?- X = '$$$6' .
   X = '$$$6'.
```
But then it gives me:
```
$ ./tpl
?- X = ¤¤¤ .
   X = '¤¤¤'.
?- X = ¤¤¤6 .
Error: syntax error, near '6', operator expected
?- X = '¤¤¤6' .
   X = '¤¤¤6'.
```
So the reading seems no problem. But the writing, I am not sure about,
but if ¤ is in the same graphic char Prolog classification as $, there wouldn't
be a need to quote a sequence ¤ during output.

At least SWI-Prolog does the same, see also:

https://github.com/mthom/scryer-prolog/issues/1515

**Comment by Jean-Luc-Picard-2021** [comment]
On the other hand, in functor position, this looks a little
bit too careful to me:
```
?- op(400,fx,¬).
   true.
?- X = ¬foo, write_canonical(X), nl.
'¬'(foo)
   X = ¬foo.
?- X = ¬(foo).
   X = ¬foo.
```

**Comment by infradig** [comment]
Closing this as I believe it done.

**Comment by infradig** [comment]
Yes...

~/trealla (devel) $ tpl
?- X = ¤¤¤ .
   X = '¤¤¤'.

shouldn't be quoted on output.
