### ISSUE TITLE
Syntax too permissive

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#260]
```
?- var(a:-b).
Error: syntax error, parens needed around operator ':-', user:1 % very good
?- var(:-b).
   false, unexpected.
   syntax_error(_).
```
So the idea is that as arguments no operators with too high a priority are directly permitted.
[#92](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#92)

**Comment by UWN** [comment]
For [#92](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#92), systems that accept this as valid syntax interpret this differently. SWI succeeds and YAP fails.

**Comment by pmoura** [comment]
P.S. Added those two tests at https://github.com/LogtalkDotOrg/logtalk3/commit/f83acb846fd0dc8bfca4200927b0bd5fde7b2caa. As now expected post fd16d9f4124d4a15670911cfc030d23e99f5e221:

```text
$ logtalk_tester -p trealla
% Batch testing started @ 2023-07-13 10:55:02
%         Logtalk version: 3.68.0-b01
%         Trealla Prolog version: 2.22.10
%
% Documents/Logtalk/logtalk3/tests/prolog/syntax/terms
%         10 tests: 0 skipped, 10 passed, 0 failed (0 flaky)
%         completed tests from object tests in 2 seconds
%         clause coverage n/a
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 10 tests: 0 skipped, 10 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-07-13 10:55:04
```

**Comment by infradig** [comment]
Thanks Paulo.
