### ISSUE TITLE
Directives and queries mixed up

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#265]
In succession of #263 where too many issues are treated at the same time

In main (switching between main and devel takes too long...):

```
$ ./tpl -f
Trealla Prolog (c) Infradig 2020-2023, v2.22.18
?- (:-X).
   false, unexpected.
?- call((:-X)).
   X = pragma(apply,[once(true)]), unexpected
;  X = (meta_predicate maplist(1,?)), unexpected
;  ... .

**Comment by infradig** [comment]
Yeah, that once is going to take  a bit of extra work.

**Comment by UWN** [comment]
Just one question: why was there a difference? Was it the different representation of terms or was it rather a quirk in the top level loop (that is, an error on the Prolog level, not below)?

**Comment by infradig** [comment]
Accidentally directives were asserted yo the database.

**Comment by UWN** [comment]
But why did then `(:-X)` fail whereas `call((:-X))` succeded?

**Comment by infradig** [comment]
I don't know that one and didn't try to find out.

**Comment by UWN** [comment]
The reason I am asking is that I still have no intuition about the kind of errors that appear in Trealla. In structure copying systems variations in refchains and the precise arrangement of structures on the heap often uncover errors. So there is a relatively simple way to wade through such variations (always with call_nth/2 indeed). But with Trealla it seems (but I am not sure about this) that one needs skeletal variations. And I am not sure I am generating this all the time.
