### ISSUE TITLE
write_term_to_chars/3 writes invalid syntax sometimes.

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#269]
Here it is nice (actually, it is not nice because you are replacing a variable by `...`)

```
?- write_term_to_chars(_*_,[quoted(true),max_depth(1)],K).
   K = "... * ...".
```

but sometimes that very same term (at least the same on the Prolog level), yields the result

```
   K = "... *..."
```
thus lacking a space.

Not sure it makes sense to identify such errors as you seem to have decided to go againsr the conventions in SICStus.

**Comment by flexoron** [comment]
Also, issue #267 has reverted:
```
v2.22.27

?- write_term(+A - +B,[max_depth(2)]).
+... - +...   true.

or

?- write_term(-_* -_,[max_depth(2)]).
(-...)* -...   true.
```

**Comment by UWN** [comment]
Just to be sure to avoid any misunderstandings: You decide to go for

```
?- write_term_to_chars(A*A,[quoted(true),max_depth(1)],K).
   K = "... * ...", unexpected. % but currently found
   K = "_11 * _11"
|  similar.

**Comment by UWN** [comment]
The next spurious error is:

```
  error(type_error(evaluable,11669/0),(mod)/2).
```

I will narrow down such errors, after you have changed the processing of variables to SICStus style (which I believe is the better way).

**Comment by UWN** [comment]
Now:

```
?- write_term_to_chars(A*A,[quoted(true),max_depth(1)],K).
   K = "_0*_0". % good
?- write_term_to_chars([1|(A*[[]*B])],[quoted(true),max_depth(5)],K).
   K = "[1|(_0 *[ ... * ...])]", unexpected.
   K = "[1|(_0 *[ ... * _1])]" % expected, but not found
|  similar.
```
