### ISSUE TITLE
findall/3 perf test

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#27]
```
$ cat isl.pl

isl({L},N) :- L = (_ is _+N).

test1 :- time(findall(Z,(between(1,5,N), isl({X}, N),
                         X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
	              M)), write(M).

test2 :- time(findall(Z,(between(1,5_000_000,N), isl({X}, N),
                         X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
	              M)), length(M,L), L1 is L*3, write(L1), write(' Elements processed').
```
```
$ tpl

?- "isl".
   true.

?- nl,test1,nl,nl,test2.

Time elapsed 9.2e-05s
[[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]]   true.

Time elapsed 26.9s
15000000 Elements processed   true.
?-
```
Is this adequate? I've no idea.

**Comment by infradig** [comment]
~/trealla (devel) $ tpl is2.pl
?- nl,test1,nl,nl,test2.
Time elapsed 0.000436s
[[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]]
Time elapsed 33.8s
15000000 Elements processed   true.

?- swipl is2.pl
?- nl,test1,nl,nl,test2.
% 134 inferences, 0.000 CPU in 0.000 seconds (99% CPU, 2726459 Lips)
[[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]]

% 67,108,885 inferences, 11.888 CPU in 11.896 seconds (100% CPU, 5645110
Lips)
ERROR: Out of global stack
^  Exception: (12) setup_call_catcher_cleanup(system:true,
prolog_statistics:catch(user:findall(_3272,  (between(1, 5000000, _3290),
isl({_3306}, _3290), _3306=(...is...), findall(_3322,  (..., ...), _3272)),
_3276), _3384,  (report(t(1661306363.9455347, 0.131352769, 437671), 10),
throw(_3384))), _3884, prolog_statistics:(_3406=true)) ?

**Comment by flexoron** [comment]
And the other way around:
```
test3 :- time(findall(Z,(between(1,3,N), isl({X}, N),
                         X = (Y is B+_), findall(Y,(between(1,5_000_000,B),X),Z)),
	              M)), length(M,L), L1 is L * 5_000_000, write(L1), write(' Elements processed').
```
```
?- test3.
Time elapsed 8.39s
15000000 Elements processed   true.
```
Interesting!
