### ISSUE TITLE
bagof/3 issue

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#28]
v2.1.4
```
$ cat xyz.pl

isl({L},N) :- L = (_ is _+N).

testf :- findall(Z,(between(1,5,N),
                    (isl({X}, N), X = (Y is B+_), bagof(Y,X^B^(between(1,3,B),X),Z))
		   ),
	         M), write(M).

testb :- bagof(Z,N^X^Y^B^(between(1,5,N),
                          (isl({X}, N), X = (Y is B+_), bagof(Y,X^B^(between(1,3,B),X),Z))
	                 ),
	       M), write(M).
```
```
$ tpl xyz.pl
?- testf.
[[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]]   true.

?- testb.
[[2,3,4]]   true  % unexpected? expecting the whole list(see testf).
; [[3,4,5]] true
; [[4,5,6]] true
;  ... .
?-
```

testf: findall/3 works as expected and gathers up ``Z`` of  (sub-)bagof/3, which works as expected, into ``M``.

testb: bagof/3 does not collecting ``Z`` as findall/3 does but it should, shouldn't it?

**Comment by infradig** [comment]
It's the same with SWI Prolog.

- ~/trealla (devel) $ swipl xyz.pl
?- testf.
[[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7,8]]
true.

?- testb.
[[2,3,4]]
true ;
[[3,4,5]]
true ;
[[4,5,6]]
true ;
[[5,6,7]]
true ;
[[6,7,8]]
true.

**Comment by infradig** [comment]
The problem is the anonymous variable, replace it with W like this...

testb :- bagof(Z,N^X^Y^W^B^(between(1,5,N),
                          (isl({X}, N), X = (Y is B+W),
bagof(Y,X^B^(between(1,3,B),X),Z))
                ),
      M), write(M).

**Comment by flexoron** [comment]
True! N^X^W^ is good enough, Y^B^ not needed. Thanks a lot!

testb :- bagof(Z,N^X^W^(between(1,5,N),
                          isl({X}, N), X = (Y is B+W), bagof(Y,X^B^(between(1,3,B),X),Z)
	                 ),
	       M), write(M).
