### ISSUE TITLE
In win11: System Error -> libdl.dll was not found

### ISSUE THREAD

**Issue by no-e-in** [trealla-prolog/trealla#290]

**Comment by infradig** [comment]
Maybe @guregu has an idea.

**Comment by guregu** [comment]
I only have a Windows 10 machine to work with but I'll see if I can reproduce 🙏

**Comment by guregu** [comment]
Submitted a fix at #294, the next release after that's merged should have a working Windows release.

**Comment by infradig** [comment]
Hopefully fixed for you now.

**Comment by pmoura** [comment]
Btw, the Logtalk installer for Windows provide preliminary support for Trealla Prolog. But it's currently non-functional, most likely due to path representation issues on Windows. If those issues are solved, all the Logtalk distribution tests could be run.

**Comment by infradig** [comment]
Thanks, worth look into. I remember you once saying not to do anything
special for DOS/Windows paths, I may need to follow through on that.

**Comment by no-e-in** [comment]
ok
