### ISSUE TITLE
Windows issues: no version data

### ISSUE THREAD

**Issue by pmoura** [trealla-prolog/trealla#296]
Version not available in copyright message or from the `version_data` flag:

```text
PS C:\Users\Paulo Moura> tpl
Trealla Prolog (c) Infradig 2020-2023,
?- current_prolog_flag(version_data, VersionData).
   VersionData = trealla(0,0,0,[]).
?-
```

Testing on Windows 10 with Trealla Prolog v2.24.3.

**Comment by infradig** [comment]
The version is set from the makefile:

    GIT_VERSION := "$(shell git describe --abbrev=4 --dirty --always
--tags)"

Which I suppose is not working on the Windows build.

**Comment by guregu** [comment]
I'll take a look, probably a matter of tweaking the build script a bit

**Comment by guregu** [comment]
Latest release looks good:
![image](https://github.com/trealla-prolog/trealla/assets/131059/44d67bff-8399-4dca-8b8e-7978862c48ba)

Please feel free to report more Windows-related issues, I should be able to help with it.

**Comment by infradig** [comment]
Thanks.

**Comment by pmoura** [comment]
Thanks for the quick fix!
