### ISSUE TITLE
Does a make/0 exist for Trealla Prolog

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#304]
I am just reading:

> "The predicate make/0 is called after edit/1, automatically 
reloading all modified files. If the user uses an external editor 
(in a separate window), make/0 is normally used to update 
the program after editing."
https://www.swi-prolog.org/pldoc/man?predicate=make/0

Does a make/0 exist for Trealla Prolog?

**Comment by infradig** [comment]
No, but I imagine it would be simple enough. Just go ghtough the list of
consulted files to see if a file has changed, reconsult if so. If the
program is running? What then?

**Comment by Jean-Luc-Picard-2021** [comment]
Its like a sudo `apt update/upgrade`, but only for the memory 
images of the consulted Prolog texts. Question for me is some-
times, whether it should also include `sudo apt autoremove`.

**Comment by guregu** [comment]
Nice, this will make hacking on stuff easier.

BTW, it seems like modules don't get reloaded (with make/0 or reconsult).

```prolog
:- module(foobar, [test/1]).

test('hello world').
```

```console
$ tpl foobar.pl 
Trealla Prolog (c) Infradig 2020-2023, v0.19.46-58-g05a5d-dirty
?- test(X).
   X = 'hello world'.

% after changing test/1:

?- make.
% /Users/guregu/code/trealla/trealla/foobar.pl changed
   true.
?- test(X).
   X = 'hello world'. % expected changed value

**Comment by guregu** [comment]
Thanks, modules look good now 👍

**Comment by Jean-Luc-Picard-2021** [comment]
Formerly Jekejeke Prolog has also a `rebuild/0`. This is the analogue
to a "make clean", where all known "Source" are unconditionally 
reconsulted. This is useful when for example Syntax Operator change,

since Syntax Operator changes often require a larger reconsult than
what `make/0` can detect by means of changed time stamps for example.
If you have a Prolog Text A that ensure loades a Prolog Text B,

i.e. A <-- B, then if B has time stamps changed, make/0 can in the sense
of separate compilation, only reconsult B. This doesn't work if B has some
Syntax Operator changed. A "make clean" might be a way out.

Or you detect a Syntax Operator change, and have a more clever way
to do a kind of extended separate compilation, instead of a drastic
make clean. I didn't try that yet, and I don't know whether there 

are Prolog systems around that can do it. Might also apply to term and goal 
expansion rules changes, which do hinder a simple separate compilation for 
the Prolog language. Such changes have also a broader reach.

**Comment by Jean-Luc-Picard-2021** [comment]
Further note: SWI-Prolog also detects `include/1` time stamp changes,
and aggregates this to the known "Sources". Quite clever. A changed 
include/1 text might affected multiple "Sources", every source that

makes a corresponding include/1, there is no separate compilation.
I didn't implement that for formerly Jekejeke Prolog, I even don't track
include dependences, but for example Prolog systems such as GNU Prolog,

which don't have ensure_loaded/1 are more include/1 oriented, and now
I think supporting a build commands that can also handle include/1 changes, 
would allow me to better handle Prolog texts made for GNU Prolog.

**Comment by infradig** [comment]
Trealla make/0 should pick up include file changes.

**Comment by infradig** [comment]
Good idea.

**Comment by infradig** [comment]
Please check tjhis.
