### ISSUE TITLE
bagof/3 setof/3 findall/3 syntax analysis

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#31]
bagof/3, setof/3
```
GNU
| ?- B^bagof(Y,(between(1,3,B)),X).
uncaught exception: error(existence_error(procedure,(^)/2),top_level/0)

Swipl
?- B^bagof(Y,(between(1,3,B)),X).
ERROR: Unknown procedure: (^)/2
ERROR:   ^/2 can only appear as the 2nd argument of setof/3 and bagof/3


Trealla
?- B^bagof(Y,(between(1,3,B)),X).
   B = 1, X = [_A]
;  ... .
?-
```

findall/3
```
| ?- findall(Y,B^(between(1,3,B)),X).
uncaught exception: error(existence_error(procedure,(^)/2),findall/3)

?- findall(Y,B^(between(1,3,B)),X).
ERROR: Unknown procedure: (^)/2
ERROR:   ^/2 can only appear as the 2nd argument of setof/3 and bagof/3

?- findall(Y,B^(between(1,3,B)),X).
   X = [_A,_B,_C].
?-
```

**Comment by infradig** [comment]
The Trealla bagof/3 ( a version of O'Keefe's) defines (^)/2.

**Comment by flexoron** [comment]
I don't have a problem with it as long as results are correct.
O'Keefe's version? Maybe this explains the performance test result as well.
Not sure but I guess B-Prolog ... well, the same
| ?- B^bagof(Y,(between(1,3,B)),X).
B = 1
X = [_668] ?

Two-to-Two then (2:2)

**Comment by flexoron** [comment]
Prolog Programmer Nr. One cannot be Wrong.

**Comment by infradig** [comment]
It's very common to use the RoK version. I did a native one in Trealla but
don't use it because a) it's not faster than Prolog and b) it didn't handle
disjunction in the goal.

**Comment by flexoron** [comment]
deleted, see #29
