### ISSUE TITLE
Unification broken II

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#312]
[Item#46](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#46)

BTW, is there a way to reduce max_depth for the top level loop?

**Comment by infradig** [comment]
You mean like swipl?

$ swipl
?- numlist(1,1000,L).
L = [1, 2, 3, 4, 5, 6, 7, 8, 9|...].
?- set_prolog_flag(answer_write_options,[max_depth(3)]).
true.
?- numlist(1,1000,L).
L = [1,2|...].

Not currently. I suppose it would be useful.

**Comment by UWN** [comment]
With `max_depth(2)`, this makes the error much easier to spot!
