### ISSUE TITLE
Unification broken III

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#315]
[Item#48](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#48)

**Comment by infradig** [comment]
I've been doing some speculative reworking of unification in the *reflist* branch. You might try against that...

```
~/trealla (reflist) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.25.18-17-gce4a
?- A=B*1,B=B*A*B,A=B.
   false.
?- 
```

**Comment by UWN** [comment]
(plz enclose program text in triple backquotes...)

**Comment by UWN** [comment]
found a counterexample with reflist `v2.25.18-17-gce4a`. Downside: does not directly reproduce on the top level. Thus I will need to play around to get the ages of skeletons right.

**Comment by UWN** [comment]
Nailed it.

**Comment by infradig** [comment]
I've just noticed a difference running at top-level vs database as well.

**Comment by infradig** [comment]
```
/trealla (reflist) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.25.18-17-gce4a-dirty
?- A=B*1, B=B*A*B, A=B.
   false.
?- [user]. main :- A=B*1, B=B*A*B, A=B.
   true.
?- main.
   true.
?- 
```

**Comment by UWN** [comment]
This difference shows equally, when just the two goals are exchanged.

**Comment by infradig** [comment]
```
~/trealla (reflist) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.25.18-21-ge4f7-dirty
?- A=B*1,B=B*A*B,A=B.
   false.
?- [user]. main :- A=B*1, B=B*A*B, A=B, write(oops), nl.
   true.
?- main.
   false.
?- 
```

**Comment by UWN** [comment]
(will leave this open until the main branch is fixed)
