### ISSUE TITLE
Syntax: too many round brackets in tail

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#318]
[Item#49](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#49)

**Comment by UWN** [comment]
Added as [conformity_testing#320](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#320)

**Comment by UWN** [comment]
BTW, this branching... when it is time to branch back to main?

**Comment by infradig** [comment]
This is in main.

**Comment by UWN** [comment]
... this one happens to be fixed in reflist, too (as I see now). At the same time, the unification issues are still open in reflist, and the current ones like [Item#52](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#52) do not exist in main...

**Comment by infradig** [comment]
All the unification items are fixed in reflist, and 'make test' runs clean.
