### ISSUE TITLE
Odd answer write options 

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#323]
[Item#56](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#56)

**Comment by UWN** [comment]
This is odd: I am on branch `reflist` and now this problem is fixed, although I do not see your commit "Fix answer options" in the git log.

And now you have in addition to branches main and reflist also devel and reflist2. Believe me, you are not able to oversee so many branches at all. And for me it starts to be pointless to test all these branches. Recall that [Item#53](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#53) did cost me more than 53 CPU-minutes. I will thus go back to main only.

**Comment by infradig** [comment]
Good decision. These other branches are not for ongoing work, or testing. I
only meant you to try reflist as a one-off thing.
