### ISSUE TITLE
Unification broken IX

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#328]
[Item#61](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#61)

**Comment by infradig** [comment]
Same as #322?

**Comment by UWN** [comment]
Yes (I do not track closed issues)

**Comment by UWN** [comment]
... but in one area I might help: If you find good questions about what kind of terms should work. In particular which skeletons. So far, I never tested something more complex than `_*_*_` or `[[_|_]|_]`. Also, I am not sure how to generate skeletons dynamically, does assert do it?
