### ISSUE TITLE
Read option variable names

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#329]
[#47](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#47) and following

**Comment by infradig** [comment]
Can you give me an example of it not being correct?

**Comment by UWN** [comment]
See the above link. That is:

variable_names#47

```
?- VN_list = 42, read_term(T,[variable_names(VN_list)]).
   error(domain_error(read_option,variable_names(42)),read_term/2), unexpected.
   waits. % expected
```

**Comment by pmoura** [comment]
The domain error doesn't contradict the ISO Prolog Core standard, which arguably already supports it:

> 8.14.1.3 Errrors
> 
> e) An element `E` of the `Options`list is neither a variable not a valid read-option
> - `domain_error(read_option, E)`

But what's a _valid read-option_?

> 7.10.3 Read-options list
> 
> A read-options list is a list of read-options which affects `read_term/3` (8.14.1) and its bootstrapped built-in predicates. The read-options supported shall include:
> 
> `variables(Vars)` - After inputting a term, `Vars` shall be a list of variables in the term input, in left-to-right traversal order.
> 
> `variable_names(VN_list)` - After inputting a term, `VN_list` shall be unified with a list of elements where: ...
> 
> ...

_shall be_ cannot be if the option arguments are bound when calling the `read_term/2-3` predicates.

More important in practice, specially in any non-academic scenario (standards are for industry), this domain error flags programming errors; the absence of this domain error hides programming errors. This is the main reason more Prolog developers are or already have implemented this domain error. It's called progress.

**Comment by UWN** [comment]
The read option is just the functor `variables/1` etc. The argument has here no relevance.

There are three read-options in 7.10.3.  Two say *shall be unified* and thus this implies also a possible failure, whereas the first said originally *shall be a list of variables* which is just non-sensical and has been corrected in [Cor.3](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/WDCor3#C5) to read just as the two other options.

Not a single option states (or stated) something  what the argument *is*, like

`variables(Vars)` - Vars *is* a list or partial list of distinct variables

No, instead, the description uses procedural language (after inputting ...) to describe just what happens with that argument.

In any case, the following cases are even more inconsistent:
```
?- read_term(T,[variables([A])]).
   error(domain_error(read_option,variables([_2])),read_term/2), unexpected.
?- read_term(T,[singletons([A])]).
   error(domain_error(read_option,singletons([_2])),read_term/2), unexpected.
```
There is no theory (I see) under which that makes sense at all.

All of this is of relevance in particular in the context of options for clpz. There was a lengthy discussion leading to consistent behaviour both in `clpfd` of SICStus and `clpz`.

**Comment by pmoura** [comment]
Independently on the diverging interpretations of the standard here, there isn't any sensible scenario where calling the `read_term/2-3` predicate with options with bound arguments is anything other than a programming error. Your reading of the standard suggests hiding these programming errors with failures. That's not helpful for anyone using Prolog in practice. In my talks with Prolog maintainer, even those that have not yet implemented these domain errors agree with the point I'm conveying here. For quite some time, the trend on programming languages evolution is to make them increasingly stricter, with better error and warning reports. Here, Prolog is so far behind industry expectations that selling the idea of logic programing based solutions continues to be, for a language that just celebrated 50 years, an uphill battle.

**Comment by infradig** [comment]
Trealla does what Scryer & GNU Prolog does with this.

**Comment by UWN** [comment]
Thanks for pointing out the non-conformity in Scryer (added 17.7.).

The following non-conforming behaviour is unique to Trealla. Both Scryer and GNU wait conformingly (in these cases). All these domain errors are non-sensical, even if there would be an an error associated:

```
?- read_term(T,[singletons([])]).
   error(domain_error(read_option,singletons([])),read_term/2), unexpected.
?- read_term(T,[singletons([V])]).
   error(domain_error(read_option,singletons([_2])),read_term/2), unexpected.
?- read_term(T,[singletons(['K'=27])]).
   error(domain_error(read_option,singletons(['K'=27])),read_term/2), unexpected.

**Comment by triska** [comment]
I want to address a specific misconception I saw in this thread:

> there isn't any sensible scenario where calling the `read_term/2-3` predicate with options with bound arguments is anything other than a programming error.

This is not the case. One usage example is to use the `variable_names/1` option to assert that **no variables occur in the read&nbsp;term**, as in:

<pre>
<b>?- read_term(T, [variable_names([])]).</b>
</pre>

**Comment by pmoura** [comment]
You're not addressing a misconception but presenting an artificial case with no practical relevance and that can be trivially rewritten in a fringe case where it would actually be relevant. Meanwhile, far more likely programming errors would be masked as failures. Other similar cases exist in the Core standard and in current standardization proposals. Prolog continuing to be a too permissive language is not the path forward.

**Comment by UWN** [comment]
Options handling in particular when dealing with extensions was clarified in Cor.3 [5.5.12](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/WDCor3#5.5.12) and 8.1.3 Note 7. Regardless of the fact that these three read options just are those functors and thus have no restriction to their argument whatsoever,  a domain error can *never* be issued in a situation where an instance of the goal just works. However, again, this is still not the case in the new version of Trealla (2.27.12):

```
?- read_term(T,[variables([A])]).
   waits. % good
?- read_term(T,[variables([A|As])]).
   error(domain_error(read_option,variables([_3|_4])),read_term/2), unexpected.
   waits. % expected
```
And from there it gets even more complex for `singletons/1` and `variable_names/1`.
```
?- read_term(T,[singletons([non_eqpair])]).
   waits.
```
While this now is conforming, it is inconsistent with issuing a domain error in other situations. After all, this goal will at best fail just as the others will do.

So effectively a correct and consistent handling of read-options of these requires even more complexity (which so far has not been pointed out by those who seem to influence you who just make up their own "standard").

Error handling is complex in Prolog, but hearsay error handling is just the worst because it is in itself inconsistent.

**Comment by pmoura** [comment]
Clarifying in an upcoming corrigenda that the argument of a read term option must be unbound at the time of a `read_term/2-3` call (i.e. type-checking the options *before* attempting to read a  term) is both simple (from a specification perspective) and consistent (from an usage perspective).

**Comment by UWN** [comment]
Now:

```
?- read_term(T,[singletons(Es)]).
l.
   T = l, Es = [].
?- read_term(T,[singletons([S])]).
l.
   T = l, unexpected.
```
(I am more an more hesitating to pinpoint such inconsistencies, after all you go freestyle)

**Comment by UWN** [comment]
(v2.27.13)

**Comment by infradig** [comment]
> Now:
> 
> ```
> ?- read_term(T,[singletons(Es)]).
> l.
>    T = l, Es = [].
> ?- read_term(T,[singletons([S])]).
> l.
>    T = l, unexpected.
> ```
> 

I can't seem to reproduce this one.

**Comment by infradig** [comment]
Spoke too soon. I can, but it's random.

**Comment by UWN** [comment]
> Trealla does what Scryer & GNU Prolog does with this.

Only GNU Prolog is left with this non-conforming behaviour.

**Comment by pmoura** [comment]
> > Trealla does what Scryer & GNU Prolog does with this.
> 
> Only GNU Prolog is left with this non-conforming behaviour.

GNU Prolog and LVM. Conformance here is detrimental to safer programming. A good opportunity to improve the standard.

**Comment by UWN** [comment]
Where is LVM? Seems to be a non-public project.

**Comment by infradig** [comment]
Can no longer reproduce, closing.

**Comment by UWN** [comment]
Just read the original entry which is [#47](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#47):

```
?- VN_list = 42,read_term(T,[variable_names(VN_list)]).
   throw(error(domain_error(read_option,variable_names(42)),read_term/2)), unexpected.

**Comment by pmoura** [comment]
https://github.com/trealla-prolog/trealla/commit/247ab690d8576af72affafcb283dc148a55c5f42

Another step in the path to Prolog standard irrelevance. Instead of a standard evolving to make the language better, less permissive, and thus more resilient to programming errors, Prolog implementers are pressured to go with a flawed spec, useful for no one or for any programming scenario, by masking bugs with failures.

**Comment by flexoron** [comment]
v2.34.17
```
?- VN_list = A,read_term(T,[variable_names(VN_list)]).
A=_.
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
I knew this would make you unhappy. When the standard is changed to make
clear what you see I will change.

**Comment by infradig** [comment]
Seems a printing error...

**Comment by pmoura** [comment]
> I knew this would make you unhappy. When the standard is changed to make clear what you see I will change.

Masking programming errors with failures helps no one. But here is even more problematic as `read_term/3` is a predicate  whose side effects (reading a term) are not undone when backtracking. Depending on the calling context, the discarded term may no longer be available (to be read again) and thus lost forever.
