### ISSUE TITLE
clpz: unexpected instantiation error

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#333]
```
?- A=2,B in 0..1,A#=B.
   A = 2, B = A, unexpected
;   error(instantiation_error,callable), unexpected.
   false. % expected
```
(Does it really make sense to include one library after the other before fixing unification?)

**Comment by infradig** [comment]
The only general unification problem is with rational trees. This is
unrelated. But you're right that CLPZ in Trealla is flawed (as I pointed
out yesterday, my time).

**Comment by infradig** [comment]
```
$ tpl ~/scryer-prolog/src/lib/clpz.pl
Trealla Prolog (c) Infradig 2020-2023, v2.27.5
?- A=2,B in 0..1,A#=B.
   false.
?- A=1,B in 0..1,A#=B.
   A = 1, B = A.
?- 
```

**Comment by UWN** [comment]
> The only general unification problem is with rational trees.

The only compact and easy to reproduce problem is with rational trees.

At least this tells me my experience with other clpfd/clpz systems, like SICStus (since 1996).

> This is unrelated.

Not sure how you can conclude that.

> tpl ~/scryer-prolog/src/lib/clpz.pl

(after you removed `library(clpz)`), so this the way `clpz` should be used? (Yes, there are more errors, and they are always related to the term representation, so I really suggest you fix unification first)
