### ISSUE TITLE
lists somehow broken

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#336]
```
?- [a,b]=ABs, writeq((ABs=ABs)), nl.
[a,b]=[a,b]
   ABs = "ab".
?- append([a,b],[],ABs), writeq((ABs=ABs)), nl.
[a,b]=[a,b|_7]   % unexpected _7
   ABs = "ab".
```

**Comment by UWN** [comment]
Shorter:
```
?- ABs = [a|Bs],Bs = [b|Nil],Nil = [],writeq((ABs=ABs)), nl.
[a,b]=[a,b|_2] % unexpected _2
   ABs = "ab", Bs = "b", Nil = [].
```
Does this mean that each and every built-in sees the internal representation directly?

**Comment by infradig** [comment]
Yes, unless something is done to cause a copy to be made... then it
'collapses'. Wrap the writeq in a call/1 and the printing bug fixes itself.

**Comment by infradig** [comment]
And that's also the reason the answer won't show the bug, the top-level
does a temporary copy before printing.

**Comment by UWN** [comment]
Ok, but... why does `call/1` cause a copy? Isn't that the idea of structure sharing that it retains the skeletons as long as possible? Could it be because of goal expansion?

(In any case your explanation helps to get a new invariant to consider, just wrap a regular goal (no control construct) with `call/1`.)

**Comment by infradig** [comment]
The copy is not ideal, but i have to copy to append some control
instructions at the end of the goal.
