### ISSUE TITLE
clpz broken

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#339]
[Item#62](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item)

**Comment by infradig** [comment]
The non-determinism is coming from handling of include/3

```
include(_, [], []).
include(Goal, [L|Ls0], Ls) :-
        (   call(Goal, L) ->
            Ls = [L|Rest]
        ;   Ls = Rest
        ),
        include(Goal, Ls0, Rest).
```

The 2nd-arg [] should mean no further matching is possible, so no choice should remain. Obviously a bug in indexing there.

**Comment by infradig** [comment]
```
~/trealla (devel) $ cat x.pl
f(_, [], []).
f(_, [H|T], _) :- f(_,T,_).

~/trealla (devel) $ tpl x.pl
Warning: singleton: H, near x.pl:2
Trealla Prolog (c) Infradig 2020-2023, v2.27.21-1-g7212
?- f(a,[], _).
   true
;  false.
?- 
```

**Comment by UWN** [comment]
Update to distinguish the two errors. The `unexpected` leftover choicepoint is a minor issue. That some answers are `incomplete` is the actual problem.

**Comment by infradig** [comment]
Got that. To me the left-over choice-point was more pervasive and annoying
(and easier). The other is part of ongoing work on clpb/clpz.

**Comment by UWN** [comment]
Still
```
Trealla Prolog (c) Infradig 2020-2023, v2.27.23
?- A in 0..1, A#= -B.
   clpz:(-1*B#=A),clpz:(A in 0..1),clpz:(B in -1..0)
;  false.
```
(BTW, it's choicepoint (3.30))

**Comment by infradig** [comment]
Note to self...

```
$ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.27.24-3-g0b99-dirty
?- use_module(library(clpz)).
   true.
?- X #= Y + Z.
   false.   % unexpected
?- 
```
[x.log](https://github.com/trealla-prolog/trealla/files/12644088/x.log)

**Comment by UWN** [comment]
> ?- X #= Y + Z.
>   false.   % unexpected

So far, I did not test this case, much too complex.

**Comment by infradig** [comment]
May not be com-plex (sic) but it looks to a be a common factor with the
clpb error and the one in your #62.

**Comment by UWN** [comment]
Maybe this helps: here are all the simple test skeletons I tried. `bad` means there is definitely an error, `maybegood` means for the cases tried, no error was found.

```
   E = (_A#= -_B), Q = bad
;  E = (_A#=abs(_B)), Q = maybegood
;  E = (_A#=sign(_B)), Q = maybegood
;  E = (_A#=_B mod _C), Q = maybegood
;  E = (_A#=max(_B,_C)), Q = maybegood
;  E = (_A#=min(_B,_C)), Q = maybegood
;  E = (_A#=_B+_C), Q = bad
;  E = (_A#=_B-_C), Q = bad
;  E = (_A#=_B*_C), Q = bad
;  E = (_A#=_B//_C), Q = bad
;  E = (_A#=_B div _C), Q = bad
;  E = (_A#=_B/_C), Q = bad
;  E = (-_A#=_B), Q = bad
;  E = (abs(_A)#=_B), Q = maybegood
;  E = (sign(_A)#=_B), Q = maybegood
;  E = (_A mod _B#=_C), Q = maybegood
;  E = (max(_A,_B)#=_C), Q = maybegood
;  E = (min(_A,_B)#=_C), Q = maybegood
;  E = (_A+_B#=_C), Q = bad
;  E = (_A-_B#=_C), Q = bad
;  E = (_A*_B#=_C), Q = bad
;  E = (_A//_B#=_C), Q = bad
;  E = (_A div _B#=_C), Q = bad
;  E = (_A/_B#=_C), Q = bad

**Comment by infradig** [comment]
So, arithmetic operators = bad.

**Comment by infradig** [comment]
Curious about your first listed example, as I find it works...

$ tpl
?- use_module(library(clpz)).
   true.
?- A #= -B.
   clpz:(-1*B#=A).
?-

The others you list as bad give false.

**Comment by UWN** [comment]
> Curious about your first listed example

It's the case I originally reported. So I try a lot of variations with domains and then see what is going wrong.

**Comment by UWN** [comment]
Also a problem with positive numbers alone:

```
?- B = 0, A in 0..1, 2*A#=B.
   B = 0, A = B.
?-        A in 0..1, 2*A#=B.
   false, unexpected.
```

**Comment by UWN** [comment]
(I try to minimize aliasing and the number of variables involved, and keep domains finite and small)

```
?- A in 0..1, A*B#=1.
   A = 1, B = A.
?- B in 0..1, A*B#=1.
   B = 1, A = B.
?- A in 0..1, B in 0..1, A*B#=1.
   false, unexpected.
```

**Comment by infradig** [comment]
CLP(Z) puzzle example has become working (thus joining factorial & nqueens). Sadly not Sudoku though.

```
~/trealla (devel) $ tpl samples/npuzzle.pl
Trealla Prolog (c) Infradig 2020-2023, v2.27.29-3-gdb9a-dirty
?- puzzle(As+Bs=Cs), label(As).
   As = [9,5,6,7], Bs = [1,0,8,5], Cs = [1,0,6,5,2]
;  false.
?- 
~/trealla (devel) $ scryer-prolog samples/npuzzle.pl
?- puzzle(As+Bs=Cs), label(As).
   As = [9,5,6,7], Bs = [1,0,8,5], Cs = [1,0,6,5,2]
;  ... .
?- 
```

**Comment by infradig** [comment]
The sudoku example has started working. Good-O.

**Comment by infradig** [comment]
Seems to be problem with just prefix (arithmetic)  ops now...

```
?- [A,B] ins 0..1, A #= -B.
   false.
?- [A,B] ins 0..1, A #= 0-B.
   A = 0, B = A.
?- [A,B] ins 0..1, A #= B + 1.
   A = 1, B = 0.
?- [A,B] ins 0..1, A #= abs(B).
   clpz:(A#=abs(B)),clpz:(A in 0..1),clpz:(B in 0..1).
```

**Comment by UWN** [comment]
```
?- A#=B+C.
   false, unexpected.
```

**Comment by infradig** [comment]
Same symtoms in the trace as before: a call to cis_minus/3 then
it terminates.

**Comment by UWN** [comment]
Now, the original items are all solved due to a simpler implementation of unary minus (https://github.com/mthom/scryer-prolog/issues/2058). But the problem behind is not gone. So I am re-itemizing this as [Item#68](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#68).

**Comment by infradig** [comment]
Please recheck your item#68
