### ISSUE TITLE
Can't read from sockets

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#34]
I'm having some trouble getting the HTTP server example to run:

```bash
tpl samples/http_server.pl -g main
```

It seems to accept connections fine, but getline/3 repeatedly fails with EAGAIN, leaving the client hanging forever. I get this behavior with threads enabled and disabled.

Not sure if this is actually a bug or an issue with my environment. Could someone else give this a try? I'm on Ubuntu 20.04 under WSL.

**Comment by infradig** [comment]
Haven't tried it in a long time. I'll try and have a go soon.

**Comment by infradig** [comment]
I see accept failing and looping, when it should block waiting for a
connection.

**Comment by infradig** [comment]
Pushed a few fixes to devel.

Server:

~/trealla (devel) $ tpl -g main samples/http_server.pl
["GET","/","1.1",[]]
^C

Client:

~/trealla (devel) $ telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/"1.1" 200 Ok
Connection: close
Content-Type: text/html

<html><body><h1>Home</h1><h2>[]</h2></body></html>
Connection closed by foreign host.
~/trealla (devel) $

**Comment by guregu** [comment]
devel branch works great! Thanks for the quick fix :)

**Comment by infradig** [comment]
And it doesn't use threads. None of Trealla does.
