### ISSUE TITLE
Very long system/startup time for loading clpz

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#340]
```
ulrich@p0:/opt/gupu/new-trealla$ time ./tpl -f -g 'use_module(library(clpz)),halt'.

real	0m12.728s
user	0m8.488s
sys	0m4.075s
ulrich@p0:/opt/gupu/new-trealla$ time ./tpl -f -g 'halt'.

real	0m0.236s
user	0m0.207s
sys	0m0.023s
```
Compare this to Scryer:
```
ulrich@p0:/opt/gupu/scryer-prolog$ time target/release/scryer-prolog -f -g 'use_module(library(clpz)),halt'.

real	0m2.646s
user	0m2.461s
sys	0m0.059s
ulrich@p0:/opt/gupu/scryer-prolog$ time target/release/scryer-prolog -f -g 'halt'.

real	0m0.600s
user	0m0.497s
sys	0m0.012s
```

**Comment by infradig** [comment]
Probably goal_expansion / term_expansion. Never optimized for using that.

**Comment by infradig** [comment]
I notice the source uses both get_atts/2 & get_attrs/2 (SWI compatible, which uses goal_expansion to the former). This should probably be fixed in source.

**Comment by UWN** [comment]
Much better, still I do not understand all the system time, where does this come from? Like all these `clock_gettime` and `brk`calls...

**Comment by infradig** [comment]
Halved system time, but it just went to user. I haven't looked at what can be done with term_expansion yet.

**Comment by UWN** [comment]
```
ulrich@p0:/opt/gupu/new-trealla$ time ./tpl -f -g 'use_module(library(clpz)),halt'.

real	0m6.120s
user	0m4.277s
sys	0m1.632s   % where does this come from?
```

This is so extreme high. On the same machine, Scryer just uses (see above) `sys	0m0.012s`. System time is not so much relevant for its absolute value but it means that on a heavily loaded system, the Prolog will behave not very well.

**Comment by infradig** [comment]
For me...

~/trealla (devel) $ time tpl -f -g 'use_module(library(clpz)),halt'

real 0m1.045s
user 0m0.989s
sys 0m0.051s
~/trealla (devel) $ time scryer-prolog -f -g
'use_module(library(clpz)),halt'

real 0m0.513s
user 0m0.495s
sys 0m0.017s
~/trealla (devel) $

**Comment by UWN** [comment]
Sorry, I confused the numbers of Scryer (but there is still that big difference) Scryer uses `0m0.059s` system time, and Trealla `0m1.632s`. No remote file system involved. Should do this test on a newer machine.

**Comment by UWN** [comment]
g1:
Trealla

```
real    0m0.653s
user    0m0.621s
sys     0m0.032s
```
vs Scryer

```
real    0m0.396s
user    0m0.385s
sys     0m0.008s
```
```

**Comment by infradig** [comment]
Best I can do for now. Further improvement is of course possible.

```
~/trealla (devel) $ time tpl -f -g 'use_module(library(clpz)),halt'

real	0m0.586s
user	0m0.567s
sys	0m0.018s

~/trealla (devel) $ time scryer-prolog -f -g 'use_module(library(clpz)),halt'

real	0m0.513s
user	0m0.498s
sys	0m0.013s
```
