### ISSUE TITLE
Compilation error on OSX 10.14.2

### ISSUE THREAD

**Issue by triska** [trealla-prolog/trealla#341]
Currently, I get:

<pre>
<b>$ make NOFFI=1 NOSSL=1</b>
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/network.o src/network.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/parser.o src/parser.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/posix.o src/posix.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/predicates.o src/predicates.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
src/predicates.c:7449:25: warning: suggest braces around initialization of
      subobject [-Wmissing-braces]
        struct itimerval it = {0};
                               ^
                               {}
2 warnings generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/print.o src/print.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/prolog.o src/prolog.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/query.o src/query.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/skiplist.o src/skiplist.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
1 warning generated.
cc -Isrc -I/usr/local/include -DVERSION='"v2.27.32"' -std=gnu99 -O3  -D_GNU_SOURCE -Wall -Wextra -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-parameter -Wno-unused-but-set-variable -Wno-unused-variable   -c -o src/streams.o src/streams.c
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean
      '-Wno-unused-const-variable'? [-Wunknown-warning-option]
<b>src/streams.c:1098:38: error: use of undeclared identifier 'POSIX_SPAWN_SETSID'
                                posix_spawnattr_setflags(&attrp, POSIX_S...
                                                                 ^</b>
src/streams.c:1105:5: warning: implicit declaration of function
      'posix_spawn_file_actions_addchdir_np' is invalid in C99
      [-Wimplicit-function-declaration]
                                posix_spawn_file_actions_addchdir_np(&fi...
                                ^
2 warnings and 1 error generated.
make: *** [src/streams.o] Error 1
</pre>

**Comment by triska** [comment]
I now get:

<pre>
Undefined symbols for architecture x86_64:
  "_posix_spawn_file_actions_addchdir_np", referenced from:
      _fn_process_create_3 in streams.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tpl] Error 1
</pre>

**Comment by guregu** [comment]
I did some digging into this error. It looks like that function isn't available in older versions of macOS (https://github.com/ziglang/zig/issues/11562 looks to be the same issue).

Something like this should 'fix' it.

```diff
diff --git a/src/streams.c b/src/streams.c
index 36b4c25..5cdf7c3 100644
--- a/src/streams.c
+++ b/src/streams.c
@@ -1094,7 +1094,7 @@ static bool fn_process_create_3(query *q)
                                posix_spawnattr_setflags(&attrp, POSIX_SPAWN_SETSID);
 #endif
                        } else if (!CMP_STR_TO_CSTR(q, c, "cwd")) {
-#if defined(__GLIBC__) && (__GLIBC__ < 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ < 29))
+#ifndef posix_spawn_file_actions_addchdir_np
                                return throw_error(q, c, c_ctx, "not available", "posix_spawn_file_actions_addchdir_np");
 #else
                                cwd = C_STR(q, name);
```

**Comment by infradig** [comment]
Thanks, will put it in, though I don't have an old OSX.

**Comment by triska** [comment]
Thank you so much, it now compiles! This makes testing the system a lot easier for me.
