### ISSUE TITLE
CLP(ℤ): wrong all_distinct/1

### ISSUE THREAD

**Issue by triska** [trealla-prolog/trealla#342]
In continuation of #339, here is a test case for `all_distinct/1`, based on the following very simple idea: `all_distinct(Vs),label(Vs)` must yield **the same solutions** as `label(Vs),all_distinct(Vs)`.

<pre>
test_constraints(_, [])     --> [].
test_constraints(X, [_|Vs]) --&gt; test_constraints(X, Vs).
test_constraints(X, [V|Vs]) --&gt; [X #\= V], test_constraints(X, Vs).

all_constraints([], _)      --&gt; [].
all_constraints([V|Vs], Ns) --&gt;
        test_constraints(V, Ns),
        all_constraints(Vs, Ns).

run :-
        length(Vs, LVs),
        MaxLCs is LVs^2,
        between(1, MaxLCs, LCs),
        length(Cs, LCs),
        numlist(1, LVs, Ns),
        portray_clause(LVs-LCs),
        phrase(all_constraints(Vs,Ns), Cs),
        Vs ins 1..LVs,
        maplist(call, Cs),
<b>        findall(Vs, (label(Vs),all_distinct(Vs)), Ls1),
        findall(Vs, (all_distinct(Vs),label(Vs)), Ls2),</b>
        (   Ls1 == Ls2 -&gt; false
        ;   portray_clause(failed-Vs-Cs-Ls1-Ls2),
            false
        ).
</pre>

Currently, I get:

<pre>
<b>?- run.</b>
1-1.
2-1.
2-2.
2-3.
2-4.
3-1.
<b>failed-[A,B,C]-[C#\=3]-[[[2#\=3]|9],[[1#\=3]|9],[[2#\=3]|9],[[1#\=3]|9]]-[].
failed-[A,B,C]-[C#\=2]-[[[3#\=2]|9],[[3#\=2]|9],[[1#\=2]|9],[[1#\=2]|9]]-[].</b>
</pre>

And hence the test case:

<pre>
<b>?- Vs = [A,B,C], Vs ins 1..3, all_distinct(Vs), C #\= 3.</b>
   false, <b>unexpected, incomplete</b>.
</pre>

And generalizing:

<pre>
<b>?- Vs = [A,B,C], Vs ins 1..3, all_distinct(Vs).</b>
   false, <b>unexpected, incomplete</b>.
</pre>

And manually reduced:

<pre>
<b>?- Vs = [A], Vs ins 1..2, all_distinct(Vs).</b>
   false, <b>unexpected, incomplete</b>.
</pre>

Note also that something else seems fundamentally broken, because **the output has a completely unexpected form**. In particular, note that *`Ls1` is a list of instantiated `Vs`*, so **a term like `[[[2#\=3]|9],[[1#\=3]|9],[[2#\=3]|9],[[1#\=3]|9]]`must not arise as the output of `Ls1`**!

This unexpected output could be due to an issue involving unification (see also #328) or other fundamental mechanisms that need to be correct so that we can reliably use the output of such test cases for further reasoning.

**Comment by infradig** [comment]
Apropos of #341, i'd very much appreciate if you could find time (no hurry) and have a look at the trace and see if you can see where it is going wrong...

~/trealla (devel) $ tpl 2>x.log
Trealla Prolog (c) Infradig 2020-2023, v2.27.32-8-g8642a-dirty
?- use_module(library(clpz)).
   true.
?- trace, A in 0..1, 2*A#=B.
   false.
?- 

In common with a similar error and trace, once it hits cis_minus then things abruptly end.

[x.log](https://github.com/trealla-prolog/trealla/files/12680287/x.log)

**Comment by infradig** [comment]
I noticed with Scryer when i did CTRL-C...

4-8.
4-9.
4-10.
^Cthread 'main' panicked at 'index out of bounds: the len is 85022 but the index is 864691128455723391', src/machine/dispatch.rs:546:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by infradig** [comment]
> Apropos of #341, i'd very much appreciate if you could find time (no hurry) and have a look at the trace and see if you can see where it is going wrong...
> 
> ~/trealla (devel) $ tpl 2>x.log Trealla Prolog (c) Infradig 2020-2023, v2.27.32-8-g8642a-dirty ?- use_module(library(clpz)). true. ?- trace, A in 0..1, 2*A#=B. false. ?-
> 
> In common with a similar error and trace, once it hits cis_minus then things abruptly end.
> 
> [x.log](https://github.com/trealla-prolog/trealla/files/12680287/x.log)

There might be a problem with goal expansion as indicated in the call to domain_contract_. The cis_geq *else* path should get taken when it fails, but it seems that doesn't happen.

**Comment by triska** [comment]
I now get:

<pre>
<b>?- all_distinct([X]), all_distinct([A,X]), [A,X] ins 1..2.</b>
   false, <b>unexpected</b>.
</pre>

Expected: **success**, because there are solutions:

<pre>
<b>?- all_distinct([X]), all_distinct([A,X]), [A,X] ins 1..2, label([A,X]).</b>
   X = 2, A = 1
;  X = 1, A = 2.
</pre>

**Comment by triska** [comment]
This works as expected now, thank you a lot!
