### ISSUE TITLE
listing/0 string struggles 

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#346]
```
?- foo:assertz(a("Hello")), foo:listing.
a([H,e,l,l,o]).
```

listing/0,1 is missing quotes for e.g. uppercase atoms.

Forcing `q->double_quotes = true` during the listing call seems to do the trick.

**Comment by infradig** [comment]
I'll add it in, thanks.

**Comment by guregu** [comment]
Thanks!
