### ISSUE TITLE
O(retract/1) is O(N^2) in simple test case

### ISSUE THREAD

**Issue by stefan-kral** [trealla-prolog/trealla#35]
Keep up the **good work** and fix this issue:
<pre>
stefankral@Stefans-MacBook-Air trealla-main % ./tpl
?- time((between(1,<b>100000</b>,X),assertz(f(X)),false;true)).
Time elapsed 0.125s
   true.
?- time((retract(f(X)),false;true)).
Time elapsed <b>1.81s</b>
   true.
?- time((between(1,<b>200000</b>,X),assertz(f(X)),false;true)).
Time elapsed 0.217s
   true.
?- time((retract(f(X)),false;true)).
Time elapsed <b>7.12s</b>
   true.
?- time((between(1,<b>400000</b>,X),assertz(f(X)),false;true)).
Time elapsed 0.395s
   true.
?- time((retract(f(X)),false;true)).
Time elapsed <b>28.4s</b>
   true.
</pre>

**Comment by infradig** [comment]
Closing this as I believe it's done.
