### ISSUE TITLE
ISO incompatibility in (\+)/1 handling

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#381]
Now I am facing this test case:
```
p(a).
p(b).
q(b).
test(X,Y,Z) :- \+ (X,Y,Z).
```
GNU Prolog gives me:
```
/* GNU Prolog 1.5.0 */
?- \+((p(X),!,q(X))).
yes
?- test(p(X),!,q(X)).
yes
```
Trealla Prolog gives me:
```
/* Trealla Prolog v2.29.42 */
?- \+((p(X),!,q(X))).
   true.
?- test(p(X),!,q(X)).
   false.
```
I think GNU Prolog does it right, despite that SWI Prolog
and ECLiPSe Prolog have the same bug. Other Prolog
systems not yet tested.

**Comment by infradig** [comment]
Scryer, Ciao & XSB also agree with Trealla.

CxProlog & BProlog (older systems) agree with GNU Prolog.

**Comment by infradig** [comment]
If you feel strongly about it raise it on the Scryer Prolog site, it's
likely to get more attention there.

**Comment by Jean-Luc-Picard-2021** [comment]
There is already a ticket, Scryer Prolog has also some bugs:

**`\+` sometimes incorrect**
https://github.com/mthom/scryer-prolog/issues/2141

But you pass all these rather easy tests, since the involved predicates
`q1`, `q2` and `q3` don't have parameters:
```
/* Trealla Prolog v2.29.42 */
?- q1.
   true.
?- q2.
   true.
?- q3.
   true.
```
Things get an itch more complicated if the predicates have parameters,
which is what my test cases tests. I think GNU Prolog behaves correctly.
You can compare with:
```
negation(X) :- X, !, fail.
negation(_).
```
`(\+)/1` and `negation/1` should behave the same. Or as UWN phrased
it, "`(\+)/1` is not a control construct (7.8)". There are strategies around
to nevertheless inline it, but one has to be careful.

**Comment by infradig** [comment]
#2141 is a different issue, it's a bug that doesn't exist in Trealla.

**Comment by infradig** [comment]
> #2141 is a different issue, it's a bug that doesn't exist in Trealla.

Ignore my comment above.

**Comment by infradig** [comment]
Still, you should raise your issue on Scryer, it will get discussion there.

**Comment by Jean-Luc-Picard-2021** [comment]
If I use `negation/1` the bug goes away:
```
p(a).
p(b).
q(b).
negation(X) :- X, !, fail.
negation(_).
test(X,Y,Z) :- negation((X,Y,Z)).
```
Now Trealla Prolog behaves consistently:
```
/* Trealla Prolog v2.29.42 */
?- negation((p(X),!,q(X))).
   true.
?- test(p(X),!,q(X)).
   true.

**Comment by infradig** [comment]
Yes, thinking about it, you're probably right here.

**Comment by infradig** [comment]
Sicstus also agrees with GNU Prolog. So it seems SWI, Trealla, Scryer, Eclipse, Ciao & XSB are all wrong.

**Comment by infradig** [comment]
Interestingly Eclipse & XSB can be made to agree with GNU-Prolog & Sicstus by declaring test1/3 as dynamic before loading it.

**Comment by infradig** [comment]
Here's my test file for above...

```
p(a).
p(b).
q(b).

negation(X) :- X, !, fail.
negation(_).

:- dynamic(test1/3).

test1(X,Y,Z) :- \+ (X,Y,Z).
test2(X,Y,Z) :- \+ (X,Y,Z).
test3(X,Y,Z) :- negation((X,Y,Z)).
```

**Comment by infradig** [comment]
Of course we have to consider the difference between negation-by-failure (as in negation/1) vs. true negation ((\\+)/1. They may not be the same, in which case test1 should possibly fail, correctly.

**Comment by Jean-Luc-Picard-2021** [comment]
`(\+)/1` is supposed to be negation-as-failure. You can read this meaning
from the operator, which is a composition of "`\`" and "+":

- "`\`" and "+": Basically says **not succeed**.

The "`\`" is the same not like the not in bitwise operation. And "+" is
basically a call/1. What makes you think `(\+)/1` is true negation. 
How is even true negation defined? Do you have some references?

**Comment by infradig** [comment]
As usual I retract that.

**Comment by Jean-Luc-Picard-2021** [comment]
The bug is very simple, there are call/1 in the wrong place in test/3.
So test/3 is mostlikely executed as follows, at least this is what
SWI-prolog does, since it generates 3 times call/1:
```
?- \+ (call(p(X)), call(!), call(q(X)))
```
But `call(!)` has no more effect. But to allow nevertheless 
inlining, I was experimenting with:
```
sys_trans_allowed(V) :- var(V), !, fail.
sys_trans_allowed((A,B)) :- sys_trans_allowed(A), sys_trans_allowed(B).
sys_trans_allowed((A;B)) :- sys_trans_allowed(A), sys_trans_allowed(B).
sys_trans_allowed((A->B)) :- sys_trans_allowed(A), sys_trans_allowed(B).
sys_trans_allowed(A) :- callable(A).
```
Which would allow to replace `(\+ A)` by `(A -> fail; true)`. But
I haven't released this into production yet. Still in the process
of measuring whether there is a positive impact or not.

Also I am thinking about another solution, since calling
`sys_trans_allowed/1` might give quadratic effort to assert 
certain clauses? Still thinking about a solution without the

computation of such a guard of such a guard at compile time,
and making the compilation simpler. Working on it.

**Comment by infradig** [comment]
Relevant discussion... https://groups.google.com/g/comp.lang.prolog/c/kKQatfYsBxI

**Comment by Jean-Luc-Picard-2021** [comment]
A big Prolog system, that doesn’t consider (\+)/2 a control construct with
body conversion, unlike SWI-Prolog, is the XSB Prolog system. I get this
result, twice success, moving out a subterm doesn’t change anything:
```
/* XSB Version 5.0-beta */
?- \+((p(X),!,q(X))).
X = _h387
yes

?- Y=!, \+((p(X),Y,q(X))).
Y = !
X = _h465
```
Was using May 15, 2022 version of XSB. Don’t know whether
there are other versions that would behave differently. But
XSB is also a Prolog system that champions user define predicate

inlining in certain circumstance, if I am not mistaken.

**Comment by infradig** [comment]
XSB doesn't work thought if the clause is in a consulted file, unless you declare it dynamic.

**Comment by Jean-Luc-Picard-2021** [comment]
> Interestingly Eclipse & XSB can be made to agree with GNU-Prolog & 
> Sicstus by declaring test1/3 as dynamic before loading it.

Yes, this one goes wrong:
```
q1 :- \+((p(X),!,q(X))).
q2 :- Y=!, \+((p(X),Y,q(X))).

?- q1.
yes
?- q2.
no
`````
But besides dynamic the top-level works fine as well:
```
?- \+((p(X),!,q(X))).
X = _h387
yes

?- Y=!, \+((p(X),Y,q(X))).
Y = !
X = _h465
```

**Comment by Jean-Luc-Picard-2021** [comment]
Do you inline `(\+)/1` somehow in Trealla Prolog? Is there
a way to list the instructions generated by Trealla
Prolog. Below is a test case and some measurement. 

Quite amazing speed of SWI-Prolog negation as failure!
```
/* SWI-Prolog 9.1.17 */
?- time((between(1,1000000,_), solve(_), fail; true)).
% 45,999,999 inferences, 2.719 CPU in 2.712 seconds (100% CPU, 16919540 Lips)
true.

/* Trealla Prolog v2.29.42 */
?- time((between(1,1000000,_), solve(_), fail; true)).
% Time elapsed 10.888s, 54000002 Inferences, 4.960 MLips
      true.
```
Test case is this here:
```
yesterday(monday   , sunday   ).
yesterday(tuesday  , monday   ).
yesterday(wednesday, tuesday  ).
yesterday(thursday , wednesday).
yesterday(friday   , thursday ).
yesterday(saturday , friday   ).
yesterday(sunday   , saturday ).

lies(lion, monday   ).
lies(lion, tuesday  ).
lies(lion, wednesday).

lies(unicorn, thursday).
lies(unicorn, friday  ).
lies(unicorn, saturday).

contrary(S, T) :- S, \+ T.
contrary(S, T) :- \+ S, T.

solve(D) :- yesterday(D, Y), 
   contrary(lies(lion, D), lies(lion, Y)),
   contrary(lies(unicorn, D), lies(unicorn, Y)).

?- time((between(1,1000000,_), solve(_), fail; true)).
```

**Comment by Jean-Luc-Picard-2021** [comment]
Ok I was comparing apples with oranges when I looked
at SWI-Prolog and other Prolog systems. Since SWI-Prolog
creates a multi-argument index, which explains the speed:
```
?- jiti_list(lies).
Predicate                                     Indexed  Buckets Speedup Flags
============================================================================
user:lies/2                                     2            8     6.0   
true.
```
Can I manually switch off this index for a fairer comparison?
Whats even the logic behind choosing this index. Thats
a quite an amazing choice since the call of `lies/2` is ground.

**Comment by infradig** [comment]
Correct that it's an indexing speedup. Both SWI & SICStus can do this.

**Comment by infradig** [comment]
Easily verified by putting a body with just a cut on yesterday/2 & lies/2.
Trealla goes from 14s to 3s on my machine.

**Comment by infradig** [comment]
Then SWI also goes from 4s to 1s. So maybe multiple factors at play.

**Comment by Jean-Luc-Picard-2021** [comment]
Reordering a little bit, it doesn't use an extra index anymore, 
I guess it now uses only first argument indexing on SWI-Prolog.

Running the query and thus inspecting a hot Prolog system,
the command `jiti_list/0` doesn't show me any index anymore:
```
yesterday(monday   , sunday   ).
yesterday(tuesday  , monday   ).
yesterday(wednesday, tuesday  ).
yesterday(thursday , wednesday).
yesterday(friday   , thursday ).
yesterday(saturday , friday   ).
yesterday(sunday   , saturday ).

lies(monday   , lion).
lies(tuesday  , lion).
lies(wednesday, lion).

lies(thursday, unicorn).
lies(friday,   unicorn).
lies(saturday, unicorn).

contrary(S, T) :- S, \+ T.
contrary(S, T) :- \+ S, T.

solve(D) :- yesterday(D, Y), 
   contrary(lies(D, lion), lies(Y, lion)),
   contrary(lies(D, unicorn), lies(Y, unicorn)).
```

**Comment by infradig** [comment]
Mah, scrub that.

**Comment by Jean-Luc-Picard-2021** [comment]
The time measurements are now on my machine:
```
/* SWI-Prolog 9.1.17 */
?- time((between(1,1000000,_), solve(_), fail; true)).
% 46,000,001 inferences, 2.500 CPU in 2.501 seconds (100% CPU, 18400000 Lips)
true.

/* Trealla Prolog 2.29.44 */
?- time((between(1,1000000,_), solve(_), fail; true)).
% Time elapsed 10.674s, 54000002 Inferences, 5.059 MLips
      true.
```
I am trying to understand the magic behind all that.

**Comment by infradig** [comment]
Tweaking indexing here I have managed to scrape 1s off the time. Can't see what else I can do.

**Comment by Jean-Luc-Picard-2021** [comment]
Its not a bug if the Prolog system doesn't claim ISO compatiblity.

**Comment by Jean-Luc-Picard-2021** [comment]
Its not a bug if the Prolog system doesn't claim ISO compatibility.
I have added a couple of new test cases for `(\+)/1` and `once/1`, 
in my Novacore test suite. Mainly derived from what is 

already found in the ISO core standard:
```
/* ISO 7.8.3.4, ISO 7 */
?- Z = !, call( (Z=!, a(X), Z) ).
Z = !,
X = 1.

/* ISO 7.8.3.4, ISO 8 */
?- call( (Z=!, a(X), Z) ).
Z = !,
X = 1 ;
Z = !,
X = 2.
```
The test cases hare here in the file "reference | control | logical":

https://www.novacuor.ch/srctab/doclet/docs/13_comply/package.jsp
