### ISSUE TITLE
inference counting omitted for call/1 ?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#384]
Funny behaviour of `call/1` in Trealla Prolog:
```
/* Trealla Prolog 2.29.44 */
?- X = call(call(call(call(call(call(call(call(call(call(call(call(call(
call(call(call(true)))))))))))))))), time((between(1,1000000,_), X, fail; true)).
% Time elapsed 2.374s, 3 Inferences, 0.000 MLips
```
Compare to SWI-Prolog:
```
/* SWI-Prolog 9.1.17 */
?- X = call(call(call(call(call(call(call(call(call(call(call(call(call(
call(call(call(true)))))))))))))))), time((between(1,1000000,_), X, fail; true)).
% 17,000,000 inferences, 0.891 CPU in 0.880 seconds (101% CPU, 19087719 Lips)
```
Also it seems SWI-Prolog can execute `call/1` more swiftly?

I am not sure what the inference counting policy should be for `call/1`.
Currently thinking about some optimization, but this might easily then 
destroy my inference counting if I don't pay attention, so not yet sure.

P.S.: Test case generated with:
```
nasty(0, true) :- !.
nasty(N, call(X)) :- M is N-1, nasty(M, X).

?- nasty(16, X).
```

**Comment by infradig** [comment]
In other words...

?- time((between(1,1000000,_), true, fail; true)).
% Time elapsed 0.123s, 1000003 Inferences, 8.162 MLips
      true.
?- X = true, time((between(1,1000000,_), X, fail; true)).
% Time elapsed 0.169s, 3 Inferences, 0.000 MLips
      X = true.

**Comment by Jean-Luc-Picard-2021** [comment]
Interesting in SWI-Prolog I get:
```
/* SWI-Prolog 9.1.17 */
?- time((between(1,1000000,_), true, fail; true)).
% 999,998 inferences, 0.016 CPU in 0.028 seconds (57% CPU, 63999872 Lips)
true.

?- X = true, time((between(1,1000000,_), X, fail; true))
% 999,998 inferences, 0.031 CPU in 0.028 seconds (112% CPU, 31999936 Lips)
X = true.
```
I guess at the moment `time/1` makes `call/1` of the given goal,
the `true` gets anyway eliminated. I do the same in Dogelog Player,
its this trans rule, which is also applied inside call/1:
```
sys_trans_body(true, N, N) --> !.
```
I use some DCG to also flatten conjunctions. So calling `(A, true, B)` and 
calling `(A, B)` is the same. What gets counted is the call port of fail. I 
do not compile away fail, and possibly SWI-Prolog does the same, 

so that the call port of fail gets counted? Annoyingly I think SWI-Prolog
does not count the `(=)/2` call.

**Comment by Jean-Luc-Picard-2021** [comment]
Ha Ha, Dogelog Player counts what happens inside `between/3`, 
which isn't natively implemented, and which accounts a little
bit for the worse speed:
```
/* Dogelog Player, 1.1.3, JDK 21 */
?- time((between(1,1000000,_), true, fail; true)).
% Zeit 167 ms, GC 0 ms, Lips 17964652, Uhr 08.11.2023 14:15
true.

?- X = true, time((between(1,1000000,_), X, fail; true)).
% Zeit 168 ms, GC 0 ms, Lips 17857720, Uhr 08.11.2023 14:15
X = true.
```
I do not show the inference count, since you can use `Lips x Time` 
to get the inference count quite easily:
```
17857720 x 0.168 = 3’000’096.96
17964652 x 0.167 = 3’000’096.884
```
So it has 3-times higher inference count, since it also counts
the internals of between/3. And the 96 inferences are from
`time/1` and its `call/1` where the goal is prepared.

But otherwise no difference between `X = true` and `true` inside the 
goal, because it gets eliminated anyways.

**Comment by infradig** [comment]
Yes, but I don't see the point though.

**Comment by Jean-Luc-Picard-2021** [comment]
When I see a test case, thinking out loud, I always try to estimate whether its
a test case usable for other Prolog systems as well, or whether it runs into a 
special optimization deployed by some Prolog system, like the inference 

count would not be seen anymore. What about this test case:
```
/* SWI-Prolog 9.1.17 */
?- time((between(1,1000000,_), call(call(true)), fail; true)).
% 2,999,998 inferences, 0.141 CPU in 0.128 seconds (110% CPU, 21333319 Lips)
true.

?- X=call(true), time((between(1,1000000,_), call(X), fail; true)).
% 2,999,998 inferences, 0.109 CPU in 0.128 seconds (85% CPU, 27428553 Lips)
X = call(true).
```
For Trealla Prolog I get:
```
/* Trealla Prolog 2.29.50 */
?- time((between(1,1000000,_), call(call(true)), fail; true)).
% Time elapsed 0.245s, 3000004 Inferences, 12.232 MLips
      true.

?- X=call(true), time((between(1,1000000,_), call(X), fail; true)).
% Time elapsed 0.246s, 3000005 Inferences, 12.219 MLips
      X = call(true).
```
Same speed for both variants, and the inference counting bug is 
gone? Right? So that the ticket can now be closed?

**Comment by Jean-Luc-Picard-2021** [comment]
Thinking out loud resulted in something new, does
a Prolog system need to show inference count and LIPS.
SWI-Prolog does that as well, but it doesn't make any sense.

Also SWI-Prolog is cheating, it shows LIPS based on CPU
time and not on real time? Or is this not cheating? Whats the
non-CPU time, time spent in input/output? I cannot yet measure 

this time in Dogelog Player. I wish I could, this would be helpful.

**Comment by infradig** [comment]
They mean nothing to me. Good night.

**Comment by flexoron** [comment]
```
?- time((between(1,1000000,_), call(call(call(true))), fail; true)).
% Time elapsed 0.158s, 4000004 Inferences, 25.240 MLips
      true.

?- time((between(1,1000000,_), call(call,call(true)), fail; true)).
% Time elapsed 0.670s, 4000004 Inferences, 5.971 MLips
      true.
```

**Comment by Jean-Luc-Picard-2021** [comment]
> ?- time((between(1,1000000,_), call(call,call(true)), fail; true)).

Thats call/2, not call/1.
