### ISSUE TITLE
Checking if a predicate exists within a specific module

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#389]
Trealla's predicate lookup will scan all loaded modules as fallback, but is it possible to do a stricter check?

```prolog
% foo.pl
:- module(foo, []).

is_foo.
```

```prolog
% bar.pl
:- module(bar, []).

not_foo.
```

```console
$ tpl foo bar
?- foo:current_predicate(not_foo/0).
   true. % is there some check that makes this false?
```

I played around with hacking `search_predicate` to only do the global search when `q->st.m == q->pl->user_m` for `current_predicate/1` and it seems to work, but I have a feeling it might break something :-)

My use case is that I have a bunch of modules that may or may not define the same unexported predicates (something like entity definitions for a CRUD app), and I'd like to check if a particular module defines one, basically a crappy version of Logtalk protocols.

**Comment by infradig** [comment]
I'll  have a look, obviously too lax.

**Comment by infradig** [comment]
There's still work to do but as it currently stands...

~/trealla (devel) $ cat foo.pl
:- module(foo, [is_foo/0]).
is_foo.
private_foo.
~/trealla (devel) $ tpl foo
Trealla Prolog (c) Infradig 2020-2023, v2.30.2-dirty
?- current_predicate(is_foo/0).  
   false.    **% WRONG**
?- current_predicate(foo:is_foo/0).
   true.
?- foo:current_predicate(is_foo/0).
   true.
?- bar:current_predicate(is_foo/0).
   false.   **% WRONG, should be exception?**
?- current_predicate(bar:is_foo/0).
   false.
?-

**Comment by guregu** [comment]
Awesome, thank you. I'll play around with it tonight.

**Comment by guregu** [comment]
Tried it out a bit and it looks good, thanks!

**Comment by pmoura** [comment]
> My use case is that I have a bunch of modules that may or may not define the same unexported predicates (something like entity definitions for a CRUD app), and I'd like to check if a particular module defines one, basically a crappy version of Logtalk protocols.

I'm curious. Prolog modules are an [evolutionary dead-end](https://logtalk.org/rationale.html). Why try hacks around modules and spend time on crappy versions of Logtalk features when Logtalk fully supports Trealla Prolog?

**Comment by guregu** [comment]
> > My use case is that I have a bunch of modules that may or may not define the same unexported predicates (something like entity definitions for a CRUD app), and I'd like to check if a particular module defines one, basically a crappy version of Logtalk protocols.
> 
> I'm curious. Prolog modules are an [evolutionary dead-end](https://logtalk.org/rationale.html). Why try hacks around modules and spend time on crappy versions of Logtalk features when Logtalk fully supports Trealla Prolog?

No good reason, really. Part of it is trying to understand (and improve) quirks in Trealla. Part of it is because I don't have a good way of distributing Logtalk-based programs for browsers yet (this is no fault of Logtalk). I made an issue in trealla-js, let me know if you have any ideas: https://github.com/guregu/trealla-js/issues/26

**Comment by infradig** [comment]
I'm closing this.

**Comment by guregu** [comment]
Thanks @infradig!
