### ISSUE TITLE
Term expansion inside modules

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#390]
Is it possible to have `user:term_expansion/2` apply to the inside of modules? Or maybe there's a different technique? I'm not very familiar with the expansion stuff yet. The use case here is defining a custom directive that multiple modules can use.

Example:
```
?- [user].
user:term_expansion(T, _) :- 
    prolog_load_context(module, M),
    format("----- expand: ~w~n", [M:T]), fail.
^D
----- expand: user:end_of_file
   true.
?- [user].
----- expand: user:begin_of_file
:- module(aaa, []).
----- expand: user:(:-module(aaa,[]))   % it does seem possible to replace the whole module here
test.                                   % user:term_expansion not called
:- my_directive(x).       % same, not possible to define custom directives used inside modules from the outside?
Error: unknown directive: my_directive/1
   true.
```

(Sorry for the barrage of issues, finally got some time to collect reproduction cases for various things)

**Comment by infradig** [comment]
I don't think you can define a module using [user] input like that.

**Comment by guregu** [comment]
Good point. It works, but not sure if it's supposed to ;). The term expansion issue happens when loading files normally too (with consult or use_module).

Module from [user]:
```
?- [user].
:- module(foo, []).
bar(42).
   true.
?- foo:bar(X).
   X = 42.
```

Consulting a file with `user:term_expansion/2` and then a module:
```console
% ./tpl
Trealla Prolog (c) Infradig 2020-2023, v2.30.7
?- consult(expand).
---- expand: :-initialization writeln(loaded expand.pl)
---- expand: end_of_file
loaded expand.pl
   true.
?- consult(some_module).
---- expand: begin_of_file
---- expand: :-module(some_module,[])
loaded expand.pl
loaded some_module.pl
   true.
?- 
```

However loading it indirectly from `:- use_module(...)` doesn't expand anything
```console
$ ./tpl some_module
loaded expand.pl
loaded some_module.pl
Trealla Prolog (c) Infradig 2020-2023, v2.30.7
?- 
```

Code:
```prolog
% some_module.pl
:- module(some_module, []).
:- use_module(expand).

hello(world).

:- initialization((write('loaded some_module.pl\n'))).
```

```prolog
% expand.pl
:- module(expand, []).

user:term_expansion(T, _) :-
    write('---- expand: '),
    write(T),
    nl,
    fail.

:- initialization((write('loaded expand.pl\n'))).
```

For comparison, output from Scryer:
```console
$ scryer-prolog some_module.pl
---- expand: :-initialization(write(loaded expand.pl
))
loaded expand.pl
---- expand: hello(world)
---- expand: :-initialization(write(loaded some_module.pl
))
loaded some_module.pl
```

Output from SWI:
```console
$ swipl some_module.pl        
---- expand: :-initialization write(loaded expand.pl
)
---- expand: end_of_file
loaded expand.pl
---- expand: hello(world)
---- expand: :-initialization write(loaded some_module.pl
)
---- expand: end_of_file
loaded some_module.pl
```

Not sure what the behavior is supposed to be but SWI and Scryer seem to agree with each other at least (well, besides the end_of_file stuff).

**Comment by infradig** [comment]
Ok, trying to start simple so my brain can comprehend...

~/trealla (devel) $ swipl -q -g halt expand.pl
---- expand: hello(world_expand)
---- expand: :-initialization write(loaded expand.pl)
---- expand: end_of_file
loaded expand.pl

~/trealla (devel) $ tpl -q -g halt expand.pl
loaded expand.pl
---- expand: begin_of_file
---- expand: end_of_file

I'll try and work from that, since removing the module declaration makes it work.

**Comment by guregu** [comment]
Thanks, I can confirm clauses inside of modules are getting visited now. I'll do some more poking around and report back. Much appreciated!

**Comment by infradig** [comment]
Closing this.
