### ISSUE TITLE
 `format/2` crashing with a string > 65543 chars

### ISSUE THREAD

**Issue by haijinSk** [trealla-prolog/trealla#392]
From my “knowing nothing about the C implementation”, naive user’s point of view, this is the same issue as: https://github.com/trealla-prolog/trealla/issues/382

Except in this code example the crashing number is 65544 (for a string with 1-byte characters only).

A test file to consult:

```
str --> "e".
str --> "a", str.

run :- 
  length(S,65543), % + '\n' in format/2 = 65544.
  phrase(str,S),
  format("~s~n",[S]).

```

The crash examples:

```
$ tpl -g run,halt long-string-crash.pl 
malloc(): invalid next size (unsorted)
Canceled (core dumped)

```
or

```
[...] (my ellipsis)
aaaaaaaaaaaaaaaaaaaaaae
double free or corruption (!prev)
Canceled (core dumped)
```
I'm not sure whether the wording should be **“Canceled” or “Aborted”**, as the last line is my translation to English.

PS: In this context of “Trealla & the very long string”, predicates `phrase_to_stream/2` and `phrase_to_file/2` do work with a million chars long string nicely, I would say: of course; despite not knowing about the implementation details. Thank you.

**Comment by flexoron** [comment]
```
$ trealla/tpl -g run,halt long-string-crash.pl 
malloc(): invalid next size (unsorted)
Aborted (core dumped)

$ trealla/tpl long-string-crash.pl 
Trealla Prolog (c) Infradig 2020-2023, v2.30.5
?- run.
aa...aaae
double free or corruption (!prev)
Aborted (core dumped)

%%%
Because the process does not pick up the lost path(that is handle signal 6 and continue),
the right wording is "Aborted" which means the process has been killed.
```

**Comment by haijinSk** [comment]
@flexoron Thank you, thank you for the answer, Canceled/Aborted explanation...

**Comment by flexoron** [comment]
src/bif_format.c comment out  line 595 and the crashes are gone(and this should be verified why).  
// *dst = '\0';

It is not a fix! and with other length values crashing is back.

**Comment by infradig** [comment]
That line is need to prevent exponential buffer growth (as per Guregu's
issue). I'll find out why.

**Comment by flexoron** [comment]
@haijinSk : I cancelled starting the program because it is known that it does abort :-)

**Comment by infradig** [comment]
Ok, seems it's not needed anymore after all, so i'll remove it.

**Comment by infradig** [comment]
Oops, removing that line doesn't fix it, just defers it.

**Comment by flexoron** [comment]
Maybe len is blurred

line 591
dst += len;
nbytes -= len;

len is 0 all the time so for example CHECK_BUF if (n >= nbytes) has no chance to be true

**Comment by infradig** [comment]
Thanks for the clue. My bad. It should ideally be rewritten to use
stringbuf.

**Comment by flexoron** [comment]
@infradig : I don't know anything about stringbuf
and I try to avoid everything which ends with buf(fer)
except blockbuffer surrounded programming.
(Real programs don’t eat cache).
