### ISSUE TITLE
Top level: Answer substitution not shown

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#397]
```
?- dif(_A,_B),_A=_A*[],_B=_B*_B.
   _A = _A*[], unexpected.
   _A = _A*[], _B=_B*_B. % expected, but not shown
```
(related to this are other issues with constraints, but reproduction is difficult)

**Comment by infradig** [comment]
Problem seems to be with (\=)/2 ...

~/trealla (devel) $ tpl
Trealla Prolog (c) Infradig 2020-2023, v2.30.17-9-g7463-dirty
?- A=A*[],B=B*B,A \= B.
   false.
?-

~/trealla (devel) $ scryer-prolog
?- A=A*[],B=B*B,A \= B.
   A = A*[], B = B*B.
?-

**Comment by infradig** [comment]
Well actually the problem is (=)/2 which (\=)/2 uses ...

~/trealla (devel) $ tpl
?- A=A*[],B=B*B, A = B.
   A = A*[], B = [].
?-

**Comment by UWN** [comment]
In fact, that is [Item#61](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#61)

**Comment by UWN** [comment]
Also now [Item#72](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#72)

**Comment by infradig** [comment]
This is because the final application dif/2 (in both cases) is unbinding B,
for reasons I can't understand.
