### ISSUE TITLE
Cannot use \uXXXX to replicated JavaScript behaviour 

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#398]
Somehow the Trealla-Prolog \uXXXX character syntax doesn’t understand
surrogate pairs. So its difficult to replicate JavaScript stuff:

![284747393-8e108c48-5a9c-469c-87ec-f1967fdd8ee8](https://github.com/trealla-prolog/trealla/assets/95891213/28ee0e5a-a411-46c2-bf5d-6bf0153833f2)
![00daa94d886eb9bac455a67a784caf71bad4d6ba](https://github.com/trealla-prolog/trealla/assets/95891213/563e29cf-ccc0-494a-8f9a-02637ed0a0af)

Trealla-Prolog doesn't form a Unicode code point:
```
?- X = '\uD83D\uDE02', atom_codes(X, L).
   X = '����', L = [55357,56834].
```
The expectation was rather L = [128514].

**Comment by infradig** [comment]
Correct, Trealla does UTF8, not Unicode. The \u syntax is not Prolog
standard.

**Comment by Jean-Luc-Picard-2021** [comment]
Well it could do that for the `\uXXXX` syntax? Or where did you
borrow the `\uXXXX` syntax from, when not from JavaScript?

Officially if its UTF-8, you should have this behaviour, which
Scryer Prolog implemented, I guess based on RFC 3629:
```
?- X = '\xD83D\\xDE02\', atom_codes(X, L).
   error(syntax_error(utf8_conversion_error),read_term/3:0).
```
Because surrogates itself are not allowed in UTF-8. 
See also RFC 3629 since November 2003. 

>The definition of UTF-8 prohibits encoding character numbers between
   U+D800 and U+DFFF, which are reserved for use with the UTF-16
   encoding form (as surrogate pairs) and do not directly represent
   characters.

https://datatracker.ietf.org/doc/html/rfc3629

To encode input with surrogates you need either convert
the pair into a single code-point and then encode it as UTF-8,
or otherwise say you don't have UTF-8, but CESU-8 or WTF-8.

https://de.wikipedia.org/wiki/CESU-8

**Comment by Jean-Luc-Picard-2021** [comment]
But I am not pro or contra any of these approaches. Since I don't 
know what the best approach is. Although I am in favor of something 
between Trealla and Scryer. Which SWI-Prolog has implemented 

for their JSON, even on Windows now:

![pair_works](https://github.com/trealla-prolog/trealla/assets/95891213/a6262b5d-1e0d-43b4-bd05-b4eb5dcc44b6)

From SWI-Prolog 9.1.17, via `library(http/json)`. Cool!

**Comment by infradig** [comment]
\uxxxx was added because it's considered common, as is \Uxxxxxxxx

**Comment by Jean-Luc-Picard-2021** [comment]
You could add a further custom, '\uD83D\uDE02' = '\U0001F602'
Its actually the recommended way by Unicode consortium itself:

> The definition of UTF-8 requires that supplementary characters (those using 
surrogate pairs in UTF-16)  be encoded with a single 4-byte sequence. 
https://unicode.org/faq/utf_bom.html#utf8-4

Whats the UTF-8 of '\U0001F602', should be 4 bytes, right?

**Comment by Jean-Luc-Picard-2021** [comment]
The formula to join two surrogate pairs is not that
difficult, you find it in the SWI-Prolog source of their JSON reader.

There is a formula which computes '\UXXXXXXXX' from
'\uYYYY\uZZZZ'. Its a function f(YYYY,ZZZZ) = XXXXXXXX.
Its always the same formula, no table lookup needed.

**Comment by infradig** [comment]
I'm more inclined to remove it as support is actually varied (with
different results) across Prologs.

**Comment by Jean-Luc-Picard-2021** [comment]
If you remove it, i.e. \uXXXX support, then your
write_term/[1,2] and read_term/[1,2] option json/1 becomes
less useful. An alternative solution would be to

remove it, and provide separate write_json/[1,2]
and read_json/[1,2] which would then support \uXXXX,
inclusive surrogate pair decoding and encoding, 

since officially JSON doesn't have \UXXXXXXX.
Or did this change, does JSON support \UXXXXXXX ?

**Comment by infradig** [comment]
~/trealla (devel) $ tpl
?- X = '\uD83D\uDE02', atom_codes(X, L).
   X = '😂', L = [128514].

?- X = '\uD83D\uDE02', write_term(X, [json(true),quoted(false)]).
😂   X = '😂'.
?- 

?- X = '\uD83D\uDE02', write_term(X, [json(true),quoted(true)]).
'\uD83D\uDE02'   X = '😂'.

**Comment by triska** [comment]
I second removing it, so that Trealla becomes more useful as a reference implementation for testing what is Prolog syntax and what is not!

**Comment by infradig** [comment]
It's only enabled if the strict_iso flag is false (the default) or using
read_term/write_term with json(true).

**Comment by triska** [comment]
Every additional feature takes implementation attention away from others, and detracts from work on remaining correctness issues. Some features are certainly worthwhile to add to a Prolog system, syntax weakenings of this form seem to not fall into that category because they will lead to syntactically invalid Prolog&nbsp;programs.

Regarding the "only" in "only enabled if the strict iso flag is false": Most programmers and students who try it out will use your system with the default flags and never change any of the flags. Therefore, the default value of the flag carries heavy weight. Is there any chance that you would set it to true by default? That would be awesome for compatibility and interoperability!
