### ISSUE TITLE
Surrogate pair not working in JSON

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#399]
I just stepped over this test case. There is maybe
another glitch than in the [related ticket here](https://github.com/trealla-prolog/trealla/issues/398). It
shows me a digit 2 after the two surrogates. 

Where does this digit come from?
```
?- read_term(X, [json(true)]).
"The \uD83D\uDE02 dog".
   X = "The ����2 dog".
```
Also decoding surrogate pairs for JSON is more
or less mandatory, since officially JSON doesn't
have the \UXXXXXXXX syntax.

So you need to represent code points above
0xFFFF as pairs \uYYYY\uZZZZ. Maybe should
also test write_term/2 with json/1 option.

**Comment by Jean-Luc-Picard-2021** [comment]
Write term works if the input is already \UXXXXXXXX,
but if the input is \uYYYY\uZZZZ it doesn't work,
which is more Prolog atom handling to blame.

But it looks very cute where it works:

![cut_emoji](https://github.com/trealla-prolog/trealla/assets/95891213/a3b55531-8b45-4953-b051-ca4ec9d0b945)

Maybe should test a \UXXXXXXXX with a code
point that is invalid, not a assigned character in
Unicode. What should be the outcome for JSON?

**Comment by Jean-Luc-Picard-2021** [comment]
Also I believe read_term/[1,2] with json/1 true should
not require a terminating period when reading 
JSON with it? Can you use read_term/[1,2] with json/1 true

for so called streaming JSON? See here:

[https://en.wikipedia.org/wiki/JSON_streaming](https://en.wikipedia.org/wiki/JSON_streaming)

Or maybe more options need to be used. I didn't check.

**Comment by infradig** [comment]
Ok, I'll add support for surrogate pairs.

**Comment by Jean-Luc-Picard-2021** [comment]
There is an interesting article. This seems to be all brand new!

> **The WTF-8 encoding**
WTF-8 (Wobbly Transformation Format − 8-bit)
Simon Sapin, Mozilla - 23 February 2022
[https://simonsapin.github.io/wtf-8/](https://simonsapin.github.io/wtf-8/)

The article is very well written, could be from Browser living standard.
Didn't check yet. Or it might appear on Mozilla JavaScript docu website?
Since the author is from Mozilla. Don't know exactly.

**Comment by Jean-Luc-Picard-2021** [comment]
My thoughts and prayers to Prolog systems that
have under the hood UTF-8. This is a nasty test case
to a certain approach of surrogate pairs:

![nasty_concat](https://github.com/trealla-prolog/trealla/assets/95891213/50974d65-9e06-4447-b10b-46578727371d)

Could mean  3 bytes UTF-8 at the end of the first Prolog
atom and  3 bytes UTF-8 at the start of the second Prolog
atom are converted into  4 bytes UTF-8.
