### ISSUE TITLE
dif/2 top-level cosmetic

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#407]
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2023, v2.30.50-24-gea09

$  ./tpl
?- dif(A,+B), A=E+B, B=(+(E,F)).
   A = E+(E+F), B = E+F, . % comma_space_dot somehow unexpected, expecting 
                           % B = E+F. or ,dif:dif(E+(E+F),+(E+F)).           
?- 
```

**Comment by flexoron** [comment]
Unfortunately, I do compare Trealla and dated Scryer,SWI,Bprolog.
So I don't know what(who)s right and whats wrong.
```
$ release/scryer-prolog (v0.9.2-31-ga0b5a248-modified)
?- dif(A,+B), A=E+B, B=(+(E,F)).
   A = E+(E+F), B = E+F, dif:dif(E+(E+F),+ (E+F)).  % space printed: + (E+F).

$ swipl (version 9.0.4)
?- dif(A,+B), A=E+B, B=(+(E,F)).
A = E+(E+F),
B = E+F.
% does not print dif:dif
?-

$ BProlog/bp  (Version 8.1)
| ?- dif(A,+B), A=E+B, B=(+(E,F)).
A = E+(E+F)
B = E+F 
yes % does not print dif:dif
| ?-

$ tpl (v2.30.50)
?- dif(A,+B), A=E+B, B=(+(E,F)).
   A = E+(E+F), B = E+F, . % uncertain whether to print dif:dif or not.
```

**Comment by infradig** [comment]
Scryer has been fixed here. Trealla has the attributes set to [], which
shouldn't happen, that is why it is confused. One thing says it has (a list
of) attributes but when it goes to fetch them to print it's just the
empty list.

**Comment by flexoron** [comment]
Thank you for the explanation.
I guess you talking about this:
?- dif(A,+B), A=E+B, B=(+(E,F)), get_atts(E,X).
   A = E+(E+F), B = E+F, X = [[]].

Issue fixed with v2.30.56

**Comment by infradig** [comment]
Yes, exactly. Shouldn't happen. See SWI for example.

**Comment by infradig** [comment]
It should be fixed now.
