### ISSUE TITLE
Top level: depth restricted display incoherent

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#411]
```
?- length(L,20), maplist(=(a),L), phrase(L,M,M).
   L = "aaaaaaaaaaaaaaaaaaa"||... , M = [a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a|...].
```
Shouldn't both use the ||-notation?

**Comment by infradig** [comment]
This string one is just to be 1) an invalid string & 2) kind of obvious.
The list one seems to be more or less consensus.

**Comment by UWN** [comment]
But you are printing here with a depth limit. And from that viewpoint they are the same.

**Comment by UWN** [comment]
UWN_open
