### ISSUE TITLE
dif/2 as redundant constraint

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#413]
```
?- A=A*C,C=B*a,B=D*B,dif(A,B).
   A = A*(D*B*a), C = D*B*a, B = D*B.
?- dif(A,B),A=A*C,C=B*a,B=D*B.
   A = A*(D*B*a), B = D*B, C = D*B*a, dif:dif( ... * ... * ( ... * ...)*(D* ... * a)*(D*(D* ...)*a)*(D*(D*(D* ...))*a)*(D*(D*(D*(D* ...)))*a)*(D*(D*(D*(D*(D* ...))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a)*(D*(D*(D*(D*(D*B))))*a),D*(D*(D*(D*(D*B))))), unexpected.

**Comment by UWN** [comment]
```
?- call_residue_vars((dif(A,B),A=A*C,C=B*a,B=D*B),[]).
   false, unexpected.

**Comment by UWN** [comment]
Shorter:
```
?- A=A*B,B=C*C*[],dif(A,B).
   A = A*(C*C*[]), B = C*C*[].
?- dif(A,B),A=A*B,B=C*C*[].
   A = A*(C*C*[]), B = C*C*[], dif:dif(A*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[]),C*C*[]),
      unexpected.

**Comment by infradig** [comment]
As expected the attributes are on C...

?-  dif(A,B),A=A*B,B=C*C*[],get_atts(C,Attrs).
   A = A*(C*C*[]), B = C*C*[], Attrs =
[dif([A*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])\==C*C*[]])],
dif:dif(A*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[])*(C*C*[]),C*C*[]).
?-

Got nothing so far though as dif.pl is the same as Scryer.

**Comment by UWN** [comment]
> As expected the attributes are on C 

They are unexpected. Just look at the first query which does not contain any pending constraints.

```
?- A=A*B,B=C*C*[],dif(A,B).
   A = A*(C*C*[]), B = C*C*[].
```
*Because* there are no constraints here, no constraints must be there when reordering the three goals. That is, all 3! queries must produce the very same answer.

**Comment by infradig** [comment]
I meant the bug was with the attributes being C. I don't know why.

**Comment by UWN** [comment]
Not solved, look:

```
?- call_residue_vars((dif(A,B),A=A*C,C=B*a,B=D*B),Vs).
   A = _*(D*_*a), B = D*_, C = D*_*a, Vs = [D], unexpected.
```
So something is still attached, but Trealla seems to deny it. And all these `_`s...

**Comment by UWN** [comment]
Shorter version:

```
?- call_residue_vars((dif(A,B),A=A*B,B=C*C*[]),Vs).
   A = _*(C*C*[]), B = C*C*[], Vs = [C], unexpected.

**Comment by UWN** [comment]
Lest I forget: Please do not filter out such variables within `call_residue_vars/2` that only delays the problem to a later moment. Instead, like in Scryer, such attributed variables should be removed as early as possible.

**Comment by infradig** [comment]
That "filtering out" at the top-level was an accident that I have fixed.
How such variables should be "removed as early as possible" I don't get. It
only seems to affect cyclic terms.

**Comment by UWN** [comment]
I tried to produce a counterexample with terms (what you call acyclic terms) such that we do not consider examples with trees (including "infinite terms"). Yet, #420

**Comment by UWN** [comment]
... and there is sometime an unexpected `error(instantiation_error,number)` and in other situations there is a space leak after more than 93100000 tests ... (all with the occurs check enabled)

**Comment by infradig** [comment]
An example of such that I could run would be appreciated.

**Comment by UWN** [comment]
Will make new issue if I can reproduce the instantiation_error now with all the overflows fixed.
