### ISSUE TITLE
List more or less processable. Some core dumps.

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#414]
v2.30.54
```
$ cat murr.pl
murr([Z|...],Z).
murr([_|Y],Z) :- murr(Y,Z).

$ tpl murr.pl
?- murr([a,b,z|...],Z).
   Z = z
;  false.

?- murr("abz...",Z).
Segmentation fault (core dumped)

$ tpl murr.pl
?- murr("abz|...",Z).
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by infradig** [comment]
Let me simplify that...

$ cat murr.pl
murr([_|Y],Z) :- murr(Y,Z).

$ tpl murr.pl
?- murr("abcd",Z).
   false.
?- murr("abcde",Z).
Segmentation fault (core dumped)
~/trealla (devel) $

It seems after 4 characters it loops and crashes.

**Comment by infradig** [comment]
Change

   murr([_|Y],Z) :- murr(Y,Z).

to

   murr([X|Y],Z) :- write(X), nl, murr(Y,Z).


and it's ok. My guess is a temporary variable is being prematurely dropped,
causing a problem somehow.

**Comment by infradig** [comment]
Yes, with -O0 the original works.

**Comment by flexoron** [comment]
Trivia:
The functor 'murr' should not be confused with 'murren' which means grumble.
Murr is the name of a cat who has learned to write: 
https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_the_Tomcat_Murr
```
Test completion

$ cat murr.pl 
murr([Z|...],Z).
murr([Z,'|','.','.','.'|[]],Z). 
murr([_|Y],Z) :- murr(Y,Z).

$ tpl murr.pl 
?- murr("z|...Z|...",Z).
   Z = 'Z' % expected
;  false. 
?- 
```
