### ISSUE TITLE
What about milliseconds in posix_XXX time predicates?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#423]
I wonder whether I can model SWI-Prologs format_time/3 in Trealla Prolog:

> **format_time(+Out, +Format, +StampOrDateTime)**
https://www.swi-prolog.org/pldoc/man?predicate=format_time/3

But I am already banging my head that milliseconds are not supported,
but my time stamps are milliseconds:
```
$ ./tpl
?- posix_localtime(1699965488.687, X).
   error(type_error(integer,1699965488.687),posix_localtime/2).
?- posix_localtime(1699965488, X).
   X = tm(8,38,13,14,10,123,2,317,0).
```

**Comment by infradig** [comment]
The Posix localtime function takes an integer. If posix_localtime/2 allowed
a float arg it wouldn't be Posix.

**Comment by Jean-Luc-Picard-2021** [comment]
SWI-Prolog says `posix`, and it works somehow:
```
/* SWI-Prolog 9.1.17 */
?- format_time(atom(X), '%3f', 1699965488.687, posix).
X = '687'.
```
If I try the same via this bootstrapping:
```
format_time(atom(X), F, T) :-
   posix_localtime(T, L), 
   posix_strftime(F, X, L).
```
I get this result:
```
?- format_time(atom(X), '%3f', 1699965488.687).
   error(type_error(integer,1699965488.687),posix_localtime/2).
```

**Comment by Jean-Luc-Picard-2021** [comment]
Ok SWI-Prolog states:

> Modelled after POSIX strftime(), using GNU extensions.
https://www.swi-prolog.org/pldoc/doc_for?object=format_time/3
So its only modelled after, and it uses some GNU stuff.

**Comment by infradig** [comment]
From the link you provided:

f
Number of microseconds. The f can be prefixed by an integer to print the desired number of digits. E.g., %3f prints milliseconds. **This format is not covered by any standard**, but available with different format specifiers in various incarnations of the strftime() function.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok SWI-Prolog states:

> Modelled after POSIX strftime(), using GNU extensions.
https://www.swi-prolog.org/pldoc/doc_for?object=format_time/3

So its only modelled after, and it uses some GNU stuff.

**Comment by infradig** [comment]
Let me think about it.

**Comment by Jean-Luc-Picard-2021** [comment]
How about your WASM port? I just saw that JavaScript
has a Date constructor including milliseconds:
```
    /**
     * Creates a new Date.
     * @param ms A number from 0 to 999 that specifies the milliseconds.
     */
    new(year: number, monthIndex: number, date?: number, hours?: number, 
           minutes?: number, seconds?: number, ms?: number): Date;
```
Not yet using myself. Milliseconds are not yet supported
in my `sys_time_atom/3`.  Because Python strftime doesn't list
milliseconds, and it can possibly not deal with it, since it

takes a struct_time argument, which doesn't have milliseconds.
But one might ask, why not also nano seconds? Etc..
