### ISSUE TITLE
Abnormal memory usage running Logtalk's new haunted_wasteland example

### ISSUE THREAD

**Issue by pmoura** [trealla-prolog/trealla#424]
With Trealla Prolog v2.31.14 version, there's an abnormal memory usage running the new Logtalk [`haunted_wasteland`](https://github.com/LogtalkDotOrg/logtalk3/tree/master/examples/haunted_wasteland) example tests. By abnormal you mean quickly grabbing all available memory and some. Running this example tests using other Prolog systems show only modest amount of memory being used. I didn't tried to debug this issue yet and thus this is just an alert for now.

**Comment by infradig** [comment]
Yes, I noticed.

The problem seems to lie here...

```
steps_1('ZZZ', _, _, Steps, Steps) :-
	% final label found
	!.
steps_1(Label, [Instruction| Instructions], Nodes, Steps0, Steps) :-
	% otherwise continue to the next label
	lookup_next_label(Instruction, Label, Nodes, NextLabel),
	Steps1 is Steps0 + 1,
	steps_1(NextLabel, Instructions, Nodes, Steps1, Steps).
```

The Trealla parser tells me the predicate should be tail recursive but Logtalk seems to expand it into something that isn't, and memory use blows up. But even so I think Nodes is being copied and not released for each loop.

EDIT: well I don't know that's to blame, but it doesn't help.

**Comment by infradig** [comment]
Another factor is call/1 & friends make a copy before executing that. I've tried for a while to elimnate that copy, i'll try again as it's only some obscure cases where it's .

**Comment by infradig** [comment]
Yay, i have cracked it...

```
$ time ~/lgt3git/scripts/logtalk_tester.sh -p trealla -g "set_logtalk_flag(clean,off)" -w -t 240
% Batch testing started @ 2023-12-11 12:03:47
%         Logtalk version: 3.73.0-b08
%         Trealla Prolog version: 2.31.14
%
% lgt3git/examples/haunted_wasteland
%         5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%         completed tests from object tests in 119 seconds
%         clause coverage 100.0%
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-12-11 12:05:47

real	1m59.673s
user	1m59.208s
sys	0m0.216s
$ 
```

Slow, but runs to end with minimal memory use. Compare SWI runs in 2.6s.

A bit more work required to try and generalize the change.

**Comment by pmoura** [comment]
> The Trealla parser tells me the predicate should be tail recursive but Logtalk seems to expand it into something that isn't, and memory use blows up. But even so I think Nodes is being copied and not released for each loop.

Tail recursive predicates are compiled into tail recursive predicates when compiling in normal or optimized mode. But for testing the code is being compiled in debug mode (to collect code coverage stats) and the consequent code instrumentation makes the predicate non-tail recursive: the last call in the rule is a call to an internal debug predicate that meta-calls the recursive call. Still, I don't think that's the main issue here.

**Comment by pmoura** [comment]
> Another factor is call/1 & friends make a copy before executing that. I've tried for a while to elimnate that copy, i'll try again as it's only some obscure cases where it's .

The variable `Nodes` holds a dictionary with ~800 nodes. Copying it at each recursive call will indeed contribute to high memory usage.

**Comment by pmoura** [comment]
Btw, running the two big test queries after loading the example (the `loader.lgt` file compiles the code in optimized mode) shows good performance and memory usage around 43 MB (similar to other backends):

```text
$ tplgt -q
?- {loader}.
   true.
?- time(haunted_wasteland::steps_1('test_files/input', Steps)).
% Time elapsed 0.211s, 793798 Inferences, 3.759 MLips
   Steps = 21409.
?- time(haunted_wasteland::steps_2('test_files/input', Steps)).
% Time elapsed 0.705s, 3899151 Inferences, 5.534 MLips
   Steps = 21165830176709.
```

**Comment by infradig** [comment]
I'd upload fixes but unfortunately it currently breaks two tests in
library/sets 😞

**Comment by pmoura** [comment]
Thanks for the quick fix. Maximum memory usage running this example that I observed is now ~224 MB.

```text
$ logtalk_tester -p trealla
% Batch testing started @ 2023-12-12 09:26:20
%         Logtalk version: 3.73.0-b08
%         Trealla Prolog version: 2.31.15
%
% logtalk/examples/haunted_wasteland
%         5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%         completed tests from object tests in 77 seconds
%         clause coverage 100.0%
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-12-12 09:27:38
```

**Comment by infradig** [comment]
I still want to look into why it's so slow.

**Comment by infradig** [comment]
I have it down to 6s, in the same ballpark as others.

**Comment by pmoura** [comment]
Great progress! Thanks!

```text
$ logtalk_tester -p trealla
% Batch testing started @ 2023-12-12 14:50:45
%         Logtalk version: 3.73.0-stable
%         Trealla Prolog version: 2.31.16
%
% logtalk/examples/haunted_wasteland
%         5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%         completed tests from object tests in 5 seconds
%         clause coverage 100.0%
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2023-12-12 14:50:50
```
