### ISSUE TITLE
clpz: incorrect

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#430]
```
?- 1#>1.
   true, unexpected, unsound.
   false. % expected, but not found

**Comment by infradig** [comment]
Currently Trealla uses a modified version of clpz.pl with the goal-expansion of phrase/3 commented out. If i enable the  goal_expansion version then the above query gives the expected result, however other tests are failing (I guess that is a problem for me to look at). What I was wondering just now is why the predicate definition of phrase/3 differs from the goal_expansion definition?

**Comment by infradig** [comment]
@triska Ok, the fact that the goal_expansion version works is just coincidental. An unexpected failure that mimics a real result failure. Something very off here...

```
?- trace, 2#>1.
[user:3:cp0] EXIT trace
[user:4:cp0] CALL 2#>1
[clpz:5:cp0] EXIT 2#>1
[clpz:6:cp0] CALL 2#>=1+1
[clpz:7:cp0] EXIT 2#>=1+1
[clpz:8:cp0] CALL clpz_geq(2,1+1)
[clpz:9:cp0] EXIT clpz_geq(2,1+1)
[clpz:10:cp0] CALL clpz_geq_(2,1+1)
[clpz:11:cp0] FAIL clpz_geq_(2,1+1)
```

It seems clpz_geq_/2 didn't get expanded...

```
?- clpz:listing(clpz_geq_/2).
   true.
?- clpz:listing(clpz_geq/2).
clpz_geq(A,B) :-
   clpz_geq_(A,B),reinforce(A),reinforce(B).
   true.
?- 
```

EDIT: I have a pretty good idea what's wrong with goal expansion, will look into it.

**Comment by UWN** [comment]
Now:

```
?- 1#>1.
   clpz:(_A in inf..sup), unexpected.

**Comment by infradig** [comment]
Yes, still being worked on.

**Comment by infradig** [comment]
I feel i've woken up in bizarro world...

```
$ tpl 
?- use_module(library(clpz)).
   true.
?- 1#>1.
   true.
?- trace,1#>1.
[user:3:cp0] EXIT trace
[user:4:cp0] CALL 1>=1+1
[user:5:cp0] FAIL 1>=1+1
   false.
?- 1#>1.
   true.
?- trace,1#>1.
[user:3:cp0] EXIT trace
[user:4:cp0] CALL 1>=1+1
[user:5:cp0] FAIL 1>=1+1
   false.
?- 
```

And, it's a top-level problem it seems...

```
?- true,1#>1.
   false.
?- 
```

**Comment by UWN** [comment]
```
?- 1#>1.
   false.
?- findall(t,1#>1,Ts).
   Ts = [].
?- call(findall(t,1#>1,Ts)).
   Ts = "t", unexpected.
   Ts = []. % expected, but not found

**Comment by UWN** [comment]
```
?- G_0=(1#>1),G_0.
   G_0 = (1#>1), unexpected.
?- G_0=(1#>1),call(G_0).
   G_0 = (1#>1), unexpected.

**Comment by infradig** [comment]
Look like more goal expansion problems.

**Comment by UWN** [comment]
(So..., should this be a separate issue or not? You closed similar issues recently)

And if I am at it, there is [Item#75](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#75), which you ignore, but it only leads to less coverage.

**Comment by infradig** [comment]
Leave it.

**Comment by infradig** [comment]
Actually, *G_0=(1#>1),G_0* should not be subject to goal_expansion/2 right?
as seems to be the case. The static definitions are the ones being used and
not working.

**Comment by UWN** [comment]
Goal expansion is really out of scope.

And your case, I'd say that, if at all, it happens when `G_0` is called. That is, before  `G_0=(1#>1),G_0` is transformed to `G_0=(1#>1),call(G_0)`, and thus `call(1#>1)` will be executed. And in that moment, maybe, goal expansion is called.

**Comment by infradig** [comment]
I believe Scryer seems to do it in call. SWI doesn't do it and SICStus docs
say call etc DO NOT do it.

**Comment by infradig** [comment]
Scryer also does it in negation, SWI doesn't. Don't know about SICStus.

**Comment by UWN** [comment]
Clearly uncharted territory. Strictly speaking, the expansion should not influence the meaning whatsoever.

**Comment by infradig** [comment]
This should be fixed now.

**Comment by infradig** [comment]
I think fixed.
