### ISSUE TITLE
dif/2 with unexpected instantiation error II

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#433]
```
?- dif(A,B),B=C*A,B=[]*[].
   error(instantiation_error,atomic), unexpected.

**Comment by UWN** [comment]
Arg, what is so odd is, if I call it with `tpl -f`, the error is still here, but if I call it with my .tplrc it is gone.

**Comment by infradig** [comment]
$ tpl
?- dif(A,B),B=C*A,B=[]*[].
   error(instantiation_error,atomic).

?- use_module(library(clpz)).
   true.
?- dif(A,B),B=C*A,B=[]*[].
   A = [], B = []*[], C = [].
?- 

Odd.

**Comment by infradig** [comment]
Narrowed down to an optimization problem...

```
$ tpl 
?- dif(A,B),B=C*A,B=[]*[].
   throw(error(instantiation_error,atomic)).
?- 

$ tpl -O0
?- dif(A,B),B=C*A,B=[]*[].
   A = [], B = []*[], C = [].
?- 
```

**Comment by UWN** [comment]
(Note to self: do not use operator `*` in examples, when `/` is just as good.)
