### ISSUE TITLE
Syntax: variable skipped

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#435]
```
v1.20.31
Trealla Prolog (c) Infradig 2020-2022, v1.20.31
?- writeq(- = X).
- (=)   true. % unexpected, where is the variable?
```

Expected: syntax error. Note that identifying valid extensions qua 5.5.1 is a very hairy adventure. In particular, since a) such attempted extensions often overlap with existing valid syntax and b) are different from one system to another.

**Comment by UWN** [comment]
Did you skip this?

**Comment by infradig** [comment]
Haven't got around to it yet.

**Comment by UWN** [comment]
Maybe you are too ambitious, aiming at supporting also extensions apart from the ISO syntax. There is exactly one (1) system that achieved full conformity + conforming extensions. And that it SICStus. And it took quite some time.
Just after reading "- = " alone it is evident that this cannot be valid Prolog text. Both `-` and `=` are operators (regardless which ones) and thus one of them needs to be bracketed (apart from other constraints).

**Comment by UWN** [comment]
Now it's

```
Trealla Prolog (c) Infradig 2020-2022, v1.22.13
?- writeq(- = X).
(-)=_0   true.
```

which is an extension. I am sure that there will now be other such problems...

**Comment by infradig** [comment]
| ?- writeq(- = X).
| (-)=_0 true.

i'll look into it.

**Comment by UWN** [comment]
Impressed. You mean it.
