### ISSUE TITLE
clpb: unexpected instantiation error

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#437]
```
?- sat_count(X,C).
   error(instantiation_error,instantiation_error(unknown(_25),1)), unexpected.
   C = 1. % expected, but not found
```

**Comment by infradig** [comment]
Please no more clpb/clpz issues.

**Comment by UWN** [comment]
That is, no more clpb/clpz testing??

**Comment by infradig** [comment]
I have identified an issue with goal_expansion / term_expansion that needs
addressing. It seems pointless testing while that is ongoing.

**Comment by UWN** [comment]
That is my point: clpb is independent of goal expansion, whereas clpfd depends on it.

**Comment by infradig** [comment]
Doesn't clpb use goal_expansion of get_attr/3 & put_attr/3?

**Comment by UWN** [comment]
Oh... I was just thinking about the expansions in user code. There, clpb does nothing.
