### ISSUE TITLE
phrase/2: unexpected failure

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#438]
```
?- phrase({fail,1},L).
   false, unexpected.
   type_error(callable,...). % expected, but not found
```
like SICStus, Scryer, GNU, Ichiban, SWI, Tau, YAP, XSB

(As long as there are such errors, discussions about goal_expansions lead to nowhere)

**Comment by UWN** [comment]
Note that the `...` in `type_error(callable,...).` must *somehow* contain the culprit goal `1`. Many show a conjunction of goals like Scryer:
```
?- phrase({fail,1},L).
   error(type_error(callable,((fail,1),_612141=[])),(',')/2).
````

**Comment by infradig** [comment]
I think that was a recent change to call/1.

**Comment by infradig** [comment]
Ok, comes down to the module specification:

?- call(((fail,1),X=[])).
   error(type_error(callable,((fail,1),_1=[])),call/1).
?- call(user:((fail,1),X=[])).
   false.
?-

**Comment by infradig** [comment]
That example is extracted from the trace of your original example:

[dcgs:43:cp2] CALL dcg_cbody({fail,1},_0,[],_8)
[dcgs:44:cp2] EXIT dcg_cbody({fail,1},_0,[],((fail,1),_0=[]))
[dcgs:45:cp2] CALL !
[dcgs:46:cp1] EXIT !
[dcgs:47:cp0] CALL call(dcgs:((fail,1),_0=[]))
[dcgs:48:cp1] EXIT call(dcgs:((fail,1),_0=[]))
[dcgs:49:cp1] CALL dcgs:((fail,1),_0=[])
[dcgs:50:cp1] EXIT dcgs:((fail,1),_0=[])
[dcgs:51:cp1] CALL fail
[dcgs:52:cp1] FAIL fail
