### ISSUE TITLE
clpz: expands unrelated terms

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#442]
```
$ /opt/gupu/new-trealla/tpl -f
?- use_module(library(clpz)).
   true.
?- [user].
g_arithrel(#=(A1,A2), A1, A2).

   true.
?- g_arithrel(R,A1,A2).
   R = (integer(A1)->(true,var(A2)->A2 is A1;integer(A2)->A1=:=A2;_A is A1,clpz:clpz_equal(_A,A2));integer(A2)->(true,var(A1)->A1 is A2;_A is A2,clpz:clpz_equal(A1,_A));clpz:clpz_equal(A1,A2)),
         unexpected.
   R = (A1 #= A2). % expected, but not found
```

**Comment by UWN** [comment]
And there is no reason to expand it here:

```
?- [user].
q(X,X).
   true.
?- q((A1#=A2),R).
   R = (integer(A1)->(true,var(A2)->A2 is A1;integer(A2)->A1=:=A2;_18 is A1,clpz:clpz_equal(_18,A2));integer(A2)->(true,var(A1)->A1 is A2;_18 is A2,clpz:clpz_equal(A1,_18));clpz:clpz_equal(A1,A2)).

**Comment by UWN** [comment]
Expansion can only be done at term-to-body conversion time just for goals, not other arguments.

**Comment by infradig** [comment]
SICStus docs:

> Only goals appearing in the body of clauses when reading a source file are expanded using this mechanism, and only if they appear literally in the clause, **or as an argument to a defined meta-predicate that is annotated using‘0'** (see [meta_predicate/1](https://www.swi-prolog.org/pldoc/man?predicate=meta_predicate/1)). Other cases need a real predicate definition.

It seems I made Trealla too lax here as it's not checking for '0' annotation only.

**Comment by infradig** [comment]
Note: clpz.pl uses put_attr/3 goal expansion with member/2 on arg2.

EDIT: disregard this. I don't know why I said that.

**Comment by UWN** [comment]
Just a rule-of-thumb: The expansion as such must remain invisible except for `clause/2`.

**Comment by UWN** [comment]
And indeed meta-arguments.

**Comment by UWN** [comment]
For meta-arguments that represent a single goal (that is, that do not lack further arguments), it is OK. But for 1, 2, ... meta-arguments I'd rather wait until call/N time, if at all.
