### ISSUE TITLE
copy_term/3 list of goals expected ...

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#446]
... but I get a list of lists of goals:

```
?- freeze(X,false), copy_term(X,C,Rs).
   Rs = [[freeze(C,false)]]. % unexpected, expected: Rs = [freeze(C,false)]
?- freeze(X,false), copy_term(X,X,Rs).
   Rs = [[freeze(X,(false,false))]]. % unexpected as above, and why this duplication of `false`?
```

**Comment by UWN** [comment]
```
?- freeze(X,userpred), copy_term(X,C,Rs).
   Rs = [[freeze(C,userpred)]]. % unexpected
```

Apart from above `userpred` needs a module qualification.

**Comment by UWN** [comment]
It seems  [this](https://github.com/trealla-prolog/trealla/commit/1b2d53c513f36dacb1f0f13ed0b38cd69ce36e3b) is an *ad hoc* fix. If you really cannot fix it, leave it.

```
?- freeze(X,false), copy_term(X,X,Rs).
   Rs = [freeze(X,user:false)]. % expected
?- freeze(X,false), copy_term(-X,-X,Rs).
   Rs = [freeze(X,(user:false,user:false))]. % unexpected
?- freeze(X,false), copy_term(-X,Copy,Rs), -X = Copy.
   Copy = -X, Rs = [freeze(X,user:false)]. % expected
```

So where does this reduplication stem from? There must be something more fundamental behind.

Note that Scryer, SICStus, SWI all maintain `Copy` as a true output argument.

**Comment by UWN** [comment]
Ideally, also `can_be(list, Rs)`

**Comment by infradig** [comment]
| Ideally, also can_be(list, Rs)

Means???

**Comment by UWN** [comment]
`can_be(list, Rs)` means if there is no instance of `Rs`, such that `Rs` is a `list`, then produces `type_error(list, Rs)`.

**Comment by UWN** [comment]
Or, to use the standard terminology, it is the error condition

a) `Rs` is neither a partial list nor a list
— `type_error(list, Rs)`.

**Comment by infradig** [comment]
Trealla has can_be/2 ( is it in error.pl?).

**Comment by UWN** [comment]
```
ulrich@TU-Wien:/opt/gupu/scryer-prolog$ git grep '^can_be('
src/lib/error.pl:can_be(Type, Term) :-
```

**Comment by UWN** [comment]
Seems you are not interested.
