### ISSUE TITLE
dif/2 imperfect

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#448]
v2.32.13
```
?- dif(Y,[a|Y]), [X,Y] = [x,[X|Y]].
   Y = [x|Y], X = x. % expected

?- dif(Y,[x,a|Y]), [X,Y] = [x,[X|Y]].
   Y = [x|Y], X = x. % expected

?- dif(Y,[x,x,a|Y]), [X,Y] = [x,[X|Y]].
   false. % unexpected
```

**Comment by UWN** [comment]
What is even more irritating is that also

```
?- [X,Y] = [x,[X|Y]],dif(Y,[x,x,a|Y]).
   false, unexpected.
```

Or in other words, how do you detect such a case in a systematic manner?

What I do is to compare various rearrangements of equations and disequations (difs). And if there is an inconsistency I have found a bug. But here, you found a case where both are equally wrong (and thus they can conceal their incorrectness to my tests).

**Comment by UWN** [comment]
```
?- [X,Y] = [x,[X|Y]],Y==[x,x,a|Y].
   X = x, Y = [x|X], unexpected.

**Comment by UWN** [comment]
Shorter:
```
?- Y = [x|Y], Y == [x,x,a|Y].
   Y = [x|Y], unexpected.

**Comment by UWN** [comment]
Just thinking

```
?- Y = [x|Y], Y = [x,x,a|Y].
   false.
```
Thus detect non-unifiable terms that are nevertheless ==-identical. Pretty specific, but why not

**Comment by flexoron** [comment]
How about this rearrangement:
```
?- dif(Y,Z), Y = [x|Y].
   Y = [x|Y], dif:dif([x,x,x|Y],Z).
?- Y = [x|Y], dif(Y,Z).
   Y = [x|Y], dif:dif([x,x,x|Y],Z).

% Now (Y,Z) arguments swapped (Z,Y)

?- Y = [x|Y], dif(Z,Y).
   Y = [x|Y], dif:dif(Z,[x,x,x|Y]). % Answer like first two above

?- dif(Z,Y), Y = [x|Y].
   Y = [x|Z], dif:dif(Z,[x,x,x|Z]). % Oops! Rearrangement of parameters found something
```

**Comment by UWN** [comment]
But still both succeed conditionally (with some dif attached)! And I fail to see (I tried a bit, not too much) how this example can be extended such that you have one case of failure/unconditional success/conditional success and the other in one of the two other categories. After all, I do not test against a full implementation (which would be only a source of further errors), instead I test whether or not grosso modo commutativity of conjunctions holds.

**Comment by UWN** [comment]
So we have two different problems here. One is that `(==)/2` is incorrect, and the other is that the top level loop makes strange things like

```
?- dif(Z,Y),Y=[x|Y], Z = [].
   Z = [], Y = [x|Z], unexpected.
   Z = [], Y = [x], unexpected. % not found, but the consequence of above
```

(it is really the best to put these problems into different issues #449, otherwise, nothing will be closed)
