### ISSUE TITLE
dif/2 redundant with simple tree

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#456]
```
?- A=[A|B],dif([],A).
   A = [A|B].
?- dif([],A),A=[A|B].
   A = [A|B], dif:dif([],[[[A|B]|B]|B]), unexpected.
   idem. % expected as above

**Comment by infradig** [comment]
Somehow trace causes it to work properly.

~/trealla (devel) $ tpl
?- dif([],A),A=[A|B].
   A = [A|B], dif:dif([],[[[A|B]|B]|B]).
?-
~/trealla (devel) $ tpl -t 2>/dev/null
?- dif([],A),A=[A|B].
   A = [A|B].
?-
~/trealla (devel) $
