### ISSUE TITLE
Term producing useless rule

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#462]
v2.33.12
```
?- [user].
a --> \+b.
   true.

?- listing.
a(A,B) :-
   call(C).
   true.
?- 
```

**Comment by infradig** [comment]
Dup of #461

**Comment by infradig** [comment]
To be specific, if @uwn changes it in Scryer Prolog i'll copy it here. Otherwise the useless rule, as you call it, stands.

**Comment by UWN** [comment]
There are two options: Either recognize `(\+)//1` as a grammar control construct, then the translation should be as specified. Or you do not recognize it, then the rule should be translated as a regular non-terminal. But both share the same property w.r.t the argument of `(\+)//1` which is not analyzed at all (at least conceptually, of course you may also translate that argument provided it is safe to do so).

```
a --> \+ b, true.

a(S0,S) :- \+phrase(b, S0,_), S0=S1, true(S1,S). % as a control construct

a(S0,S) :- \+(b, S0,S1), true(S1,S). % as a regular non-terminal
```

**Comment by UWN** [comment]
> of course you may also translate that argument  it is safe to do so

This only applies to the option when you recognize it as a grammar control construct, indeed
