### ISSUE TITLE
[user]. end_of_file. broken

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#465]
```
?- [user]. end_of_file. % Hangs

```

**Comment by infradig** [comment]
$ tpl
?- [user]. end_of_file. write(ok). nl.
ok
   true.
?-

FYI... Scryer ignores anything on the line after 'end_of_file.'

**Comment by flexoron** [comment]
```
?- [user]. a. b. c. end_of_file.
$ % unexpected, end_of_file should be eof of [user], expecting ?-
```
Hint : #455 reopened

**Comment by infradig** [comment]
$ tpl
?- [user]. end_of_file. write(ok). nl.
ok
   true.
?-
