### ISSUE TITLE
Top level: _ variables mangled

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#467]
```
?- length(L,N), _A = something.
   L = [], N = 0
;  L = [_A], N = 1 % _A unexpected, expected _B
;  ... .
```
This answer suggests that _A can be anything, but

```
?- _A = anything, L = [_A], N = 1,  _A = something.
   false. % expected, but surprising w.r.t. above answer
```

So there are two issues here,

first, `_A` cannot be repurposed for something else, if it appears in the query.

and then the question whether answer substitutions for variables starting with `_` should be shown or not. This has been done traditionally (like SICStus), but it often collides with correctness considerations.

**Comment by UWN** [comment]
That _ variables are not shown, is (apart from correctness considerations) an internationalization problem for languages that do distinguish between upper and lower case. But I have to admit, that problem exists already with singleton variable warnings.

**Comment by infradig** [comment]
I wasn't thinking of languages that don't have upper/lower distinction when
i decided not to print underscored variables. I'll change that. As for
collisions...

**Comment by UWN** [comment]
Now:

```
?- length(L,N), _A = something.
   L = [], N = 0, _A = something
;  L = [_A], N = 1, _A = something % unexpected
;  ... .
```

**Comment by UWN** [comment]
```
Trealla Prolog (c) Infradig 2020-2022, v1.22.48
?- length(L,N), _A = something.
   L = [], N = 0, _A = something
;  L = [_A], N = 1, _A = something
;  ... .
```
