### ISSUE TITLE
Unexpected uninstantiation_error

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#468]

**Comment by UWN** [comment]
```
?- call_residue_vars(true,[]).
   error(uninstantiation_error([]),call_residue_vars/2), unexpected.
   true. % expected, but not found
```
Where do such errors come from?

Looks to me like [variable_names#47](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#47). Thus a deliberate non-conformity.

**Comment by UWN** [comment]
SICStus (originator), SWI, YAP, Scryer all agree here.

**Comment by UWN** [comment]
```
?- call_residue_vars(true,[_]).
   error(type_error(nil,[_1]),call_residue_vars/2), unexpected.
   false. % expected, but not found

**Comment by infradig** [comment]
This is not a standard function. Use it properly or don't use it, but don't
abuse it.

**Comment by UWN** [comment]
Not sure what you mean by "properly", but such uses do make sense.

```
?- call_residue_vars(true,[_|_]).
   error(type_error(nil,[_2|_3]),call_residue_vars/2), unexpected.
```

This means: I expect that some constraints will be left unresolved. This works in all above mentioned systems.

**Comment by UWN** [comment]
```
?- call_residue_vars(true,2).
   error(type_error(list,2),call_residue_vars/2). % agree
?- call_residue_vars(true,[a|2]).
   false. % why then?
```

It definitely makes sense to issue a type error list, but then, why not one for the second case?

In the meantime, you must have a can_be_list routine already (that is similar to library(si))

**Comment by UWN** [comment]
```
?- call_residue_vars(false, [_|1]).
   false, unexpected.
   type_error(list, [_|1]).

**Comment by UWN** [comment]
Perfect!
