### ISSUE TITLE
read_from_chars/2 leak

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#468]
```
ulrich@g1:/opt/gupu/trealla$ ulimit -v
30000
ulrich@g1:/opt/gupu/trealla$ ./tpl -f
?- [user].
ch('0').
ch('1').
ch('2').
ch('3').
ch('4').
ch('5').
ch('6').
ch('7').
ch('8').
ch('9').
   true.
?- N=8,length(Cs,N),maplist(ch,Cs),writeq(Cs),nl,catch(read_from_chars(Cs,T),error(syntax_error(_),_),fail),fail.
...
"00149178"
"00149179"
uncaught exception: error(resource_error(memory),read_from_chars/2)
```

I do have some old tpl's still running (for 98979m and 71464m) which are testing similar things but without any leak. So the leak must be new.

**Comment by UWN** [comment]
Rerun with `time` gives:

```
"00149179"
uncaught exception: error(resource_error(memory),read_from_chars/2)
?- 

real    0m32.997s
user    0m0.697s
sys     0m0.216s
```

**Comment by infradig** [comment]
It would seem to be the catch/3 that is leaking.

**Comment by UWN** [comment]
At least many different lists of chars are required to get this error. Calling the very same string all the time does not leak. Similar to other errors like

```
?- repeat, catch(_=.._,error(instantiation_error,_),fail).
no apparent leak VIRT = 25432   RES = 2620 
```

**Comment by infradig** [comment]
| At least many different lists of chars are required to get this error.
Calling the very same string all the time does not leak. Similar to other
errors like

Could be atoms being ceated by throw.

**Comment by UWN** [comment]
> Could be atoms being ceated by throw.

There is no throw involved. Look:

```
?- N=8,length(Cs,N),maplist(ch,Cs),writeq(Cs),nl,catch(read_from_chars(Cs,T),←
   error(syntax_error(_),_),fail).
``

**Comment by infradig** [comment]
Wouldn't have picked you for a Kath & Kim fan.

**Comment by infradig** [comment]
That's a lot of variables, whose names go in the atom table. About 4Gb.
