### ISSUE TITLE
Wrong result in (^)/2 bigint computation

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#47]
According to Corrigendum 2 I guess the idea of the evaluable predicate
`(^)/2` is to be exact for bigint arguments. But I find for example:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2022, v2.2.10
$ ./tpl
?- X is 51^10, Y is 51*51*51*51*51*51*51*51*51*51.
   X = 119042423827613008, Y = 119042423827613001.
```
Two different results! :-(

**Comment by infradig** [comment]
Interesting...

$ gprolog
GNU Prolog 1.4.5 (64 bits)
Compiled Feb 23 2020, 20:14:50 with gcc
By Daniel Diaz
Copyright (C) 1999-2020 Daniel Diaz
| ?- X is 51^10, Y is 51*51*51*51*51*51*51*51*51*51.

X = 119042423827613008
Y = 119042423827613001

yes
| ?-

**Comment by Jean-Luc-Picard-2021** [comment]
GNU Prolog doesn't have bigints. These Prolog systems 
cannot realize (^)/2 correctly. You can try yourself the 

ISO core standard Prolog flag "bounded", where 
"true = no bigints" and "false = bigints":
```
?- current_prolog_flag(bounded, X).
X = true
```
Or alternatively you can try:
```
/* GNU Prolog 1.5.0 */
?- X is 51^20-1.
uncaught exception: error(evaluation_error(int_overflow),(is)/2)
```

**Comment by Jean-Luc-Picard-2021** [comment]
Your result is probably a conversion back to integer
from float. To see that you need a precise float to
bigint conversion, which shows me that:
```
?- X is integer(1.1904242382761301E17).
X = 119042423827613008.
```
But the computation of a float is not that precise
as the computation of a bigint. Thats where the
precision is lost, and why the integer result shown

is not correct.

**Comment by Jean-Luc-Picard-2021** [comment]
As already mentioned in another ticket, the error is gone.
For example it is now:
```
Trealla Prolog (c) Infradig 2020-2022, v2.7.15
?- X is 39^9, Y is 39*39*39*39*39*39*39*39*39.
   X = 208728361158759, Y = X.
```
Closing this ticket.
