### ISSUE TITLE
Unicode printing unclean

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#470]
```
?- '🀱 ' = J. % This looks bad just here in this window but not when entered/displayed in the terminal.
   J = '🀱 '.

?- 🀱  = J.
   J = '🀱'. % This looks bad in the terminal. You have to cell spacing 2.00 x width to make the quoting visible
             % and why quoting anyway?

% SWI
?- 🀱  = J.
J = 🀱 .

```

**Comment by infradig** [comment]
Trealla speaks UTF-8 not Unicode. Using Unicode may or may not work as you expect.

**Comment by flexoron** [comment]
The 'char' above is taken from UTF-8 subset ( U+1F030 -- U+1F09F )
https://www.utf8icons.com/subsets/domino-tiles

(Linux, Gnome-Terminal, Monospace 12)
```
Vertical is ok:
?- 🁣 = C.
   C = '🁣'.
```

**Comment by infradig** [comment]
Yes, i retracted my comment.

**Comment by flexoron** [comment]
```
Other examples of uncleaned output:

?- ( 🀱 , 🀱 , 🀱  ) = J.
   J = (🀱 , 🀱 , 🀱) . % Issue visible in the terminal

?- { 🀱 , 🀱 , 🀱  } = J.
   J = {🀱 , 🀱 , 🀱} .

?- [ 🀱 , 🀱 , 🀱  ] = J.
   J = "🀱🀱🀱".

```

**Comment by infradig** [comment]
What's *uncleaned* about them?

**Comment by flexoron** [comment]
Overlapping: Third char, right bracket.
You see it in the terminal.

**Comment by infradig** [comment]
FWIW swipl does the same.

**Comment by infradig** [comment]
I'm tending to think it's a GNOME terminal problem.

**Comment by infradig** [comment]
As i'm also seeing a comma in the middle of the domino character.

**Comment by flexoron** [comment]
Yes and it is a terminal font problem.

Here it is ok but thats not standard:
Terminal: BlackBox
Font: Inconsolata weight=275 Ultra-Expanded 10 

The font name says it all.

GNOME Terminal solution: Monospace 10, Cell spacing 2.00 x width

**Comment by flexoron** [comment]
Tweak has no effect.

**Comment by infradig** [comment]
Not meant to be visible, fixing a Logtalk problem.
