### ISSUE TITLE
Sgementation fault after illegal UTF-8 in chars_urlenc

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#471]
Found this test case for Trealla Prolog:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2023, v2.33.26-13-gbfb6c

$ ./tpl
?- chars_urlenc(X, 'foo+bar%FF%FE%FDbaz', []).
   X = 'foo bar\x0\'.
?- chars_urlenc(X, 'foo+bar%FF%FE%FDbaz', []), atom_codes(X, L).
Segmentation fault
```
When I compare to Java `ByteArrayOutputStream.toString()` with
option `StandardCharsets.UTF_8` I get another result. Namely it seems 
that non UTF-8 sequence is mapped to Unicode code point 65533:
```
?- percent_encode(X, 'foo+bar%FF%FE%FDbaz'), atom_codes(X, L).
X = 'foo bar���baz', 
L = [102, 111, 111, 32, 98, 97, 114, 65533, 65533, 65533, 98, 97, 122].
```
This is one of the Unicode specials called [replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character).
It is not 2^16-1 but rather 2^16-3 or 0xFFFD. It is used to indicate 
problems when a system is unable to render a stream of data 

to correct symbols. I don't know whether this is the best choice.
Alternatively one could also throw an exception, that can be
handled by Prolog itself. But the segmentation fault

looks rather as something that cannot be handled?

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, did some testing with Scryer Prolog. This replacement character 
seems to be also the choice of Scryer Prolog, so that their routine 
`chars_utf8bytes/2` from library(charsio) isn't lossless:
```
$ target/release/scryer-prolog -v
v0.9.3-174-gf9a5c2d3

$ target/release/scryer-prolog
?- use_module(library(charsio)).
   true.
?- chars_utf8bytes(X, [255,254,253]), maplist(char_code,X,Y).
   X = "���", Y = [65533,65533,65533].
```
There is some loss of information, since all 3 different values 
255,254 and 253 are mapped to the same value.

**Comment by infradig** [comment]
$ tpl
?- chars_urlenc(X, 'foo+bar%FF%FE%FDbaz', []), atom_codes(X, L).
   error(representation_error(character_code),atom_codes/2).
