### ISSUE TITLE
Top level: Now inserting ← to break lines garbles input

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#473]
Within a terminal in default configuration (80 characters wide) I get now:

```
ulrich@p0:/opt/gupu/trealla$ ./tpl -f --version
Trealla Prolog (c) Infradig 2020-2022, v1.22.56
ulrich@p0:/opt/gupu/trealla$ ./tpl -f
?- L="123456789012345678901234567890123456789012345678901234567890123456789012←
   34567890".
   L = "12345678901234567890123456789012345678901234567890123456789012345678901234567890".
```
So this `←` is now inserted which when doing mark-paste (X11ish) or copy-paste, inserts this character which is `'\x2190\'`, just the `&larr;`. And not the Return Symbol ⏎ or `'\x23ce\'`. So my lines are garbled. The Return Symbol could make sense (I am not very good at Unicode, except for the [Unicode angst](http://www.personal.psu.edu/ejp10/blogs/gotunicode/2007/02/cjk-unicode-angst-in-japan-and.html)) but a left pointing arrow is clearly a symbol.

**Comment by infradig** [comment]
Compile with make NOISOCLINE=1

**Comment by UWN** [comment]
(OK, mumble mumble, where does this make sense...)
