### ISSUE TITLE
Display variable name issue

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#473]
v2.33.50
```
?- Y = f(Y).
   Y = f(Y). % expected

?- Y = [Y].
   Y = [A].  % unexpected
```

**Comment by infradig** [comment]
Not seeing this, I get...

~/trealla (devel) $ tpl
?- Y = f(Y).
   Y = f(Y).
?-

**Comment by flexoron** [comment]
Ok, but I see that you see what I see and I hope you seeing this, too
?- Y = [Y].
   Y = [A].

**Comment by infradig** [comment]
Ah, i see what you see now and not what i thought see.
