### ISSUE TITLE
Overflowing integer arithmetic cannot be caught

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#474]
Now, to be fair, as far as I know, this has [never been solved completely ](https://stackoverflow.com/q/13328409/772868) by any other Prolog. Except SICStus but which does not use gmp but its very own (not very fast for very big numbers) arithmetic library and thus it is not tested that much in that area. Seems Trealla uses a similar approach but with a library that is a bit faster.

I can only spread more rumors on this, like that [Mathematica has some agreement to use gmp](https://www.wolfram.com/legal/third-party-licenses/gmp.html) and at least what I know, there is no inelegant overflow there (I did not read the source code, and my own investigations were quite limited...). So this is kind of an indication that this is possible.

```
ulrich@p0:/opt/gupu/trealla$ ulimit -v
30000
ulrich@p0:/opt/gupu/trealla$ ./tpl -f
?- length(_,I), 9^9^I>0.
   I = 0
;  I = 1
;  I = 2
;  I = 3
;  I = 4
;  I = 5
;  I = 6
;tpl: src/imath/imath.c:1694: s_alloc: Assertion `out != ((void *)0)' failed.
Aborted (core dumped)
```

Expected is a `resource_error(memory)`

**Comment by infradig** [comment]
I still have to look into how the imath library handles allocation failures
(or specifically, how i can handle it's failure). I believe like GMP it
just aborts.

**Comment by UWN** [comment]
Nice, and be prepared that new issues will follow suit.
