### ISSUE TITLE
Cyclic term (display) error easy to see

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#475]
v.2.33.53
```
?- Y = [[_|Y]].
   Y = [[_,.]]. % unexpected
?- 
```

**Comment by flexoron** [comment]
v2.34.0
```
$ tpl
?- Y = [[_|Y]], Y = [[Y|_]].
   Y = [[_|Y]]. % Do we expect Y = [[Y|Y]] here?
?- Y = [[Y|_]], Y = [[_|Y]].
   Y = [[Y|_A]]. % unexpected?
?- halt.

$ swipl;scryer-prolog
?- Y = [[_|Y]], Y = [[Y|_]].
Y = [[Y|Y]].
?- halt.
?- Y = [[_|Y]], Y = [[Y|_]].
   Y = [[Y|Y]].
?- halt.
$
```

**Comment by infradig** [comment]
Substituting named variables for the anons is easier to see what's going on...

$ scryer-prolog
?- Y = [[X|Y]], Y = [[Y|Z]].
   Y = [[Y|Y]], X = [[Y|Y]], Z = [[Y|Y]].
 
~/trealla (devel) $ swipl -q
?- Y = [[X|Y]], Y = [[Y|Z]].
Y = X, X = Z, Z = [[Z|Z]].

~/trealla (devel) $ tpl
?- Y = [[X|Y]], Y = [[Y|Z]].
   Y = [[X|Y]], X = [[X|Y]], Z = [[X|Y]].
 
~/trealla (devel) $ yap -q
?- Y = [[X|Y]], Y = [[Y|Z]].
Y=[[A|A]],
X=[[B|B]],
Z=[[[[C|C]],[D|D]]],
D=[[D|D]],
C=[[C|C]],
B=[[B|B]],
A=[[A|A]]

Yap is certainly very inventive.

**Comment by flexoron** [comment]
Yep, easier.
```
$ tpl
?- ([[X|Y]]=[[Y|Z]])=A,A=(Z=X),A=(Z=Y),A=(X=Y).
   X = [[Y,[X|Y]]],
   Y = [[Y,[X|Y]]],
   Z = [[[[Y|Z]],[[.]|Z]]],               % [.]  unexpected
   A = ([[[[Y|Z]],[[.]|Z]]]=[[Y,[X|Y]]]). % [.]  unexpected

?- ([[X|Y]]=[[Y|Z]])=A,A=(Z=X),A=(Y=Z),A=(X=Y).
   X = [[[[X|Y]],[X,.]]],                 % [X,.] unexpected
   Y = [[[[Y|Z]]|Y]],
   Z = [[[[Y|Z]]|Y]],
   A = ([[[[Y|Z]]|Y]]=[[[[X|Y]],[X,.]]]). % [X,.] unexpected
```

**Comment by flexoron** [comment]
Resolution found in Mariana's Web Level 9.

**Comment by infradig** [comment]
If you say so.

**Comment by flexoron** [comment]
Why not keep a secret?
```
?- Y = [[Y|_]], Y = [[_|Y]].
   Y = [[Y|_A]].
```

**Comment by infradig** [comment]
It's something to do with how they're bound. Can't really tell how/why.

**Comment by flexoron** [comment]
Reminds me of Austrian Jodeller adores Germanic Mountain:
https://www.youtube.com/watch?v=3PqAppuqp6g
