### ISSUE TITLE
What are the brakes in freeze/2 ?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#479]
Just currious what are the brakes in freeze/2 ?
```
/* SWI-Prolog 9.1.21 */
?- above(2,L),sift(L,R), time(take(20,R,S)), write(S).
% 49,168,171 inferences, 2.125 CPU in 2.140 seconds (99% CPU, 23137963 Lips)

/* Trealla Prolog 2.34.8 */
?- above(2,L),sift(L,R), time(take(20,R,S)), write(S), nl.
% Time elapsed 32.966s, 250317943 Inferences, 7.593 MLips
```
Source code:

[primes.p.log](https://github.com/trealla-prolog/trealla/files/14045808/primes.p.log)

**Comment by infradig** [comment]
I don;t know. Have you tried Scryer...

$ tpl ../tpl-stuff/primes.pl
?- above(2,L), sift(L,R), time(take(20,R,S)), write(S), nl.
% Time elapsed 43.557s, 250317943 Inferences, 5.747 MLips
[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71]
   L = [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20|...], R = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67|...], S = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67|...].
?- 

$ scryer-prolog ../tpl-stuff/primes.pl
?- above(2,L), sift(L,R), time(take(20,R,S)), write(S), nl.
   % CPU time: 0.000s, 9 inferences
   error(existence_error(procedure,sift/2),sift/2).
?-

**Comment by infradig** [comment]
My guess is freeze/2 is a builtin in SWI-Prolog. It was originally in Trealla but changed when I added atts.

**Comment by Jean-Luc-Picard-2021** [comment]
> I don;t know. Have you tried Scryer...

I have tried Scryer Prolog, it cannot run the example:

**freeze/2 not working correctly?**
https://github.com/aarroyoc/scryer-playground/issues/21

Then I have tried my old formerly Jekejeke Prolog, its mid field:
```
/* formerly Jekejeke Prolog 1.6.6 :-( */
?- above(2,L),sift(L,R), time(take(20,R,S)), write(S), nl.
% Time 14411 ms, GC 90 ms, Wall 25/01/2024 03:04
```

**Comment by infradig** [comment]
Nothing specific can be done here, closing.

**Comment by Jean-Luc-Picard-2021** [comment]
I tried this alternative version, be careful, doesn't work for
all problems, like when a variable is instantiate with a variable,
but should work for the primes example: 
```
take(0,_,[]) :- !.
take(N,[X|L],[X|R]) :- M is N-1, take(M, L, R).

above(N,L) :- freeze(L, above2(N,L)).
above2(N,[N|L]) :- M is N+1, above(M,L).

filter(K,L,R) :- freeze(R, filter2(K,L,R)).
filter2(K,[X|L],R) :- X mod K=:=0, !, filter(K,L,R).
filter2(K,[X|L],[X|R]) :- filter(K,L,R).

sift(L,R) :- freeze(R,sift2(L,R)).
sift2([X|L],[X|R]) :- filter(X,L,H), sift(H,R).
```
In SWI-Prolog its an itch faster. 
In Trealla Prolog its an itch slower:
```
?- above(2,L),sift(L,R), time(take(20,R,S)), write(S), nl.
% Time elapsed 37.815s, 264384839 Inferences, 6.991 MLips
```
Isn't a `var/1` check that` freeze/2` does the first thing.
And then fast path calling the goal?

**Comment by infradig** [comment]
Good point there.
