### ISSUE TITLE
Top level: constants ignored, variables printed incoherently

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#483]
(Successor to #453)

```
?- append(X,non_list,Z).
   X = [], Z = non_list
;  X = [_A], Z = [_B|_C] % unexpected _B and _C, expected Z = [_A|non_list]
```

v1.23.8

**Comment by UWN** [comment]
v1.23.12 better but still these variables:

```
?- append(X,non_list,Z).
   X = [], Z = non_list % expected
;  X = [_A], Z = [_C|non_list] % better, but still _A and _C different variables
;  ... .
````

**Comment by infradig** [comment]
_A & _C are bound...

~/trealla (devel) $ tpl
?-  append(X,non_list,Z), write([X,Z]).
[[],non_list]   X = [], Z = non_list
;[[_2],[_2|non_list]]  X = [_A], Z = [_C|non_list]
;[[_2,_6],[_2,_6|non_list]]  X = [_A,_B], Z = [_E,_F|non_list]

, but I see what you mean.
