### ISSUE TITLE
Non-termination of reverse/2

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#484]
Argh, I [was](https://github.com/trealla-prolog/trealla/issues/482#issuecomment-1059915662) too optimistic.

```
?- reverse([a|_], "cbd").
uncaught exception: error(resource_error(memory),revzap_/3) % unexpected, expected failure
```

**Comment by infradig** [comment]
Try the latest devel

~/trealla (devel) $ tpl --version
Trealla Prolog (c) Infradig 2020-2022, v1.23.12-4-ga65c98-dirty
~/trealla (devel) $ tpl
?- reverse([a|_], "cbd").
   false.

**Comment by UWN** [comment]
This cannot be fast in the long term. It has cost which is always proportional of len(Xs), even for `Ys = []`.

**Comment by infradig** [comment]
Yes, I need another solution. It'll do while I work on it.

**Comment by infradig** [comment]
But still, it is fast thanks to skip_max_list...

~/trealla (devel) $ time tpl -g
"numlist(1,1000000,L1),reverse(L1,L2),time(sort(L2,L3)),write(ok),nl,halt."
Time elapsed 0.455 secs
ok

real 0m1.319s
user 0m1.136s
sys 0m0.180s
~/trealla (devel) $ time swipl -g
"numlist(1,1000000,L1),reverse(L1,L2),time(sort(L2,L3)),write(ok),nl,halt."
% 1 inferences, 0.204 CPU in 0.204 seconds (100% CPU, 5 Lips)
ok

real 0m0.827s
user 0m0.619s
sys 0m0.089s
~/trealla (devel)

**Comment by UWN** [comment]
Why this red cut? Currently, you do not accept issues on constraints, but nevertheless:

```
?- freeze(L,(L="a";L="b")), reverse([_],L).
   L = [_]. % unexpected; expected L = "a" ; L = "b".
```

This is incorrect on two grounds, first the freeze seems to be ignored and then second, because the cut in revzap_/3 will cut away ` L = "b"`

**Comment by infradig** [comment]
The cut may not be necessary.

**Comment by infradig** [comment]
As I thought, the cut in revzap_ wasn't needed. But that wasn't the source
of the problem. It seems freeze is not handling a disjunction in the goal..

~/trealla (devel) $ rlwrap scryer-prolog
?- freeze(M,(L=1;L=2)), M=3.
   M = 3, L = 1
;  M = 3, L = 2.
?-
~/trealla (devel) $ tpl
?- freeze(M,(L=1;L=2)), M=3.
   M = 3, L = 1.
?-

**Comment by UWN** [comment]
Even

```
?- L=[_], freeze(L,(L="a";L="b")).
   L = "a"
;  L = "b"
;  false. % unexpected leftover choicepoint
```

**Comment by UWN** [comment]
And better:

```?- L=[_], freeze(L,(L="a")).
   L = "a"
;  false. % unexpected
```
So this is unrelated to disjunction.
