### ISSUE TITLE
frozen/2 broken

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#490]
```
$ tpl # v2.36.26
?- freeze(X,X=Y), frozen(X,Y).
   Y = freeze(X,X=_). % unexpected
?-
```

**Comment by infradig** [comment]
I might take a leaf from Scryer and remove the frozen/2 predicate.

**Comment by flexoron** [comment]
Don't do that,pls. frozen/2 contains valuable (intermediate) information.
```
Perhaps I need these infos:

?- freeze(X,X=Y), frozen(Y,X).
   X = true, Y = true.

?- freeze(X,X=Y), dif(X,true), frozen(Y,X).
   false.

?- freeze(X,X=Y), dif(X,true), dif(Y,true), frozen(Y,X).
   X = dif:dif(dif:dif(_,true),true), Y = dif:dif(_,true).
?-
```
Hint: freeze/2 frozen/2 when/2 issues have been resolved in past #161

**Comment by flexoron** [comment]
A leaf from Scryer: Scryer Prolog is also a testbed for bleeding edge research in logic.
Oh, go on then. Oh, OK then not OK.

**Comment by infradig** [comment]
The bug, actually is in copy_term/3. It removes the constraints.

```
?- freeze(X,X < 10), copy_term(X, X2, Gs), X = 11.
   X = 11, Gs = [freeze(11,11<10)].
?- freeze(X,X < 10), copy_term(X, X2, Gs).
   Gs = [freeze(X,X<10)].
?- 
```

Amongst other complaints.

**Comment by infradig** [comment]
'''
$ scryer-prolog
?- freeze(X,X < 10), copy_term(X, X2, Gs), X = 11.
   false.
?- freeze(X,X < 10), copy_term(X, X2, Gs).
   Gs = [freeze:freeze(X2,X2<10)], freeze:freeze(X,X<10).
?- 
```

```
$ swipl
?- freeze(X,X < 10), copy_term(X, X2, Gs), X = 11.
   false.
?- freeze(X,X < 10), copy_term(X, X2, Gs).
   Gs = [freeze:freeze(X2,X2<10)], freeze:freeze(X,X<10).
?- 
```

**Comment by flexoron** [comment]
```
Trealla
?- freeze(X,X=Y), frozen(Y,X).
   X = true, Y = true.

?- freeze(X,X=Y), dif(X,true), frozen(Y,X).
   false.

% Right now I try to understand why this is not false:

?- freeze(X,X=Y), dif(X,true), dif(Y,true), frozen(Y,X).
   X = dif:dif(dif:dif(_,true),true), Y = dif:dif(_,true).
?-
```
```
SWI
?- freeze(X,X=Y), frozen(Y,X).
X = Y, Y = true.

?- freeze(X,X=Y), dif(X,true), frozen(Y,X).
false.

% Right now I try to understand why this is not false:

?- freeze(X,X=Y), dif(X,true), dif(Y,true), frozen(Y,X).
X = Y, Y = dif(Y, true).
```

**Comment by infradig** [comment]
Because frozen/2 us broken (because of copy_term/3).

**Comment by flexoron** [comment]
Broken in SWI and Trealla?

**Comment by flexoron** [comment]
Forgive me. Maybe I understand why you think about  removing frozen/2 then(but I don't like it).

**Comment by infradig** [comment]
Ok, I see. But I think it's a relic.

**Comment by infradig** [comment]
A relic from times when there was no other way to examine attributes.

**Comment by flexoron** [comment]
Vorwärts immer Rückwärts nimmer!
Forwards ever Backwards never!
