### ISSUE TITLE
append/3: variable change not indicated

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#494]
v1.23.32
```
?- append(A,B,[C|_]).

   A = [], B = [C|_]

;  A = [C], B = B  % show new value once which does not change any more. B = []

;  A = [C,_A]
;  A = [C,_A,_B]
:
?-
```

**Comment by flexoron** [comment]
seems that B = B means B = indefinite.

**Comment by flexoron** [comment]
Issue has been revised: #497
B = _

**Comment by infradig** [comment]
~/trealla (main) $ tpl --version
Trealla Prolog (c) Infradig 2020-2022, v1.23.43
~/trealla (main) $ tpl
?- append(X,Y,Z).
   X = [], Y = Z
;  X = [_A], Z = [_A|Y]
;  ... .
?- append([X],[Y],[A,B]).
   X = A, Y = B.
?-
~/trealla (main) $
