### ISSUE TITLE
What are Trealla threads?

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#495]
```
Just a question for or a better understanding:

Category:

Forth:          Threaded code
Concurrency:    Resume/Yield (Lua)
Multithreading: Exploiding Instruction-level parallelism

What kind of threading Trealla tries to implement?
```

**Comment by infradig** [comment]
```
	thread_create/3		# thread_create(:callable,-thread,+options)
	thread_create/2		# thread_create(:callable,-thread)
```

Uses system threads. It's currently under rewrite.

**Comment by infradig** [comment]
Compatible (or nearly, as much as I can tell) with SWI-Prolog threads.

**Comment by flexoron** [comment]
Cool futurism and to go one step further: Making distributed prolog micro services available.

**Comment by infradig** [comment]
Reopening this as a place for ongoing issues while multi-threading is under development. Logtalk threading is partially working again after the rewrite. 

Hopefully I can look into it next week, taking a break.

**Comment by flexoron** [comment]
You see, I asked because Trealla offers a lot here:

Concurrency (tasks)
Concurrency (linda)
Concurrency (futures)
Concurrency (engines)
Multi-threading (Prolog queries)
Multi-threading (Prolog instances)

Conclusion: Missing Fibers

FYI: To get a real kick out of this attempt I try to thread Trealla and Solaris this year(2024).

**Comment by infradig** [comment]
Pretty much working now, so closing this.
