### ISSUE TITLE
append/3 choicepoint needless

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#498]
v1.23.43
```
?- append(A,[],[]).
   A = []
;  false.  % ?
?-
```
On this question I don't know enough about prolog's idiosyncracies.

**Comment by infradig** [comment]
I note Scryer and SWI (surprisingly) leave a choicepoint.

**Comment by infradig** [comment]
Could do this..

append([], R, R) :- nonvar(R) -> ! ; true.
append([X|L], R, [X|S]) :- append(L, R, S).

**Comment by infradig** [comment]
Actually, that was wrong...

append([], R1, R2) :- (nonvar(R1), nonvar(R2), R1=R2) -> ! ; R1=R2.
append([X|L], R, [X|S]) :- append(L, R, S).

But is it worth it?

**Comment by infradig** [comment]
Or slightly better as it preserves the original code...

append([], R1, R2) :- nonvar(R1), nonvar(R2), R1=R2, !.
append([], R, R).
append([X|L], R, [X|S]) :- append(L, R, S).

**Comment by flexoron** [comment]
```
$ ./tpl
?- append(A,B,[]).  % defined as above
   A = [], B = A
;  false. % ? 
?-
```

Currently I have my detoxified system in operation. (others are broken).

So, I can compare Trealla with GNU only.
```
GNU Prolog 1.5.1 (64 bits)
| ?- append(A,[],[]).   % GNUs append

A = []

yes
| ?- append(A,B,[]). 

A = []
B = []

yes
| ?-
```

**Comment by infradig** [comment]
This...

append([], R1, R2) :- nonvar(R1), nonvar(R2), R1=R2, !.
append([], R1, R2) :- nonvar(R2), R2=[], R1=R2, !.
append([], R, R).
append([X|L], R, [X|S]) :- append(L, R, S).

**Comment by flexoron** [comment]
grasped, ok, thanks.
