### ISSUE TITLE
Predicate to get FD or alias from streams

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#50]
### Scryer
```
?- current_output(X), number(X).
   false.
```

### Trealla
```
?- current_output(X), number(X).
   X = <$stream>(1).
```

**Comment by guregu** [comment]
On the other hand, I do think it might be kind of useful to grab the FD from Streams where possible. Is there a way to get that as a number from them?

**Comment by infradig** [comment]
I could add something, might be useful.

**Comment by guregu** [comment]
Thanks! The use case behind grabbing the FD for the stream is to report something useful to the WASM toplevel output.
Maybe grabbing either the alias (if it exists) or FD (if it exists) would be better?

**Comment by guregu** [comment]
Thanks :-)
