### ISSUE TITLE
[user]. reputed keyword yields misguiding error message

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#502]
```
?- [user].
begin_of_file.
a.
Error: syntax error, operator expected '.', line 2, 'a.
'
   true.
?-

I cannot spot the syntax error.
```

**Comment by flexoron** [comment]
Just in case, a programmer thinks it should/could be a predicate:
```
$ cat be.pl
begin_of_file.
b.
e.
end_of_file.
```
```
$ tpl
?- [be].
   true.
?- listing.
b.
e.
   true.
?-
```
```
$ gprolog
| ?- [be].
compiling ...

| ?- listing.
begin_of_file.  % unexpected
b.
e.
yes
| ?-
```
I guess gprolog gone wrong.

One more thing:
```
$ tpl
?- end_of_file.
uncaught exception: error(existence_error(procedure,end_of_file/0),end_of_file/0)
?-

This should trigger a "halt".
```

**Comment by UWN** [comment]
What is `begin_of_file`? It is just a regular name. Why is it 'reputed'?

**Comment by UWN** [comment]
SICStus:

```
| ?- [user].
% compiling user...
| begin_of_file.
| 
% compiled user in module user, 100 msec 459424 bytes
yes
| ?- begin_of_file.
yes
```
And nothing else is expected.

**Comment by pmoura** [comment]
The begin_of_file is a **virtual** term introduced by Logtalk 3.00.7 (released on September, 2015) for its term-expansion mechanism. SWI-Prolog copied it (without attribution) after I posted an example using it to its public forum. Before Logtalk added this term, there was already (as I found later) SICStus Prolog `beginning_of_file` **virtual** term also for term-expansion (introduced on version 4.2.1).

**Comment by pmoura** [comment]
```text
$ sicstus
SICStus 4.7.1 (x86_64-darwin-18.7.0): Fri Jan 21 19:45:28 CET 2022
Licensed to Paulo Moura
% consulting /Users/pmoura/.sicstusrc...
% consulted /Users/pmoura/.sicstusrc in module user, 4 msec 50272 bytes
| ?- [user].
% compiling user...
| beginning_of_file.
| a.
| 
% compiled user in module user, 34 msec 434064 bytes
yes
| ?- beginning_of_file.
! Existence error in user:beginning_of_file/0
! procedure user:beginning_of_file/0 does not exist
! goal:  user:beginning_of_file
| ?- 
```

**Comment by UWN** [comment]
Thanks for the illustration. So `beginning_of_file.` is not `begin_of_file.`

**Comment by flexoron** [comment]
To enhance the discussion a bit:
It is not even a "directive"
```
$ cat be.pl
z.
begin_of_file.
a.
end_of_file.
m.

$ tpl
?- [be].
   true.
?- listing.
z.
a.
   true.
?-
```

**Comment by flexoron** [comment]
```
$ cat be.pl
end_of_file.
The obvious purpose of this file is to show that the directive "end_of_file"
allows to write many things subsequently about the purpose of this file.
$

$ tpl
?- [be].
   true.
?- listing.
   true.

?- end_of_file. % fixed!
$
```

**Comment by flexoron** [comment]
I guess "begin_of_file" flourish in obscurity.
(as long as it does not behave what its name suggests)

**Comment by pmoura** [comment]
It's well documented:
https://logtalk.org/manuals/userman/expansion.html#virtual-source-file-terms-and-loading-context

**Comment by flexoron** [comment]
@pmoura oh, I see, thank you.
Its time for me to enter the world of logtalk.
Be warned, I come sneaking up but handicapped.
(because I've learned the way of thinking object-oriented from "self", prototype-based)
https://en.wikipedia.org/wiki/Self_(programming_language)

**Comment by pmoura** [comment]
Logtalk supports prototypes, which, given your experience with Self, should help. I suggest you start with:
https://learnxinyminutes.com/docs/logtalk/
