### ISSUE TITLE
support `functor()` syntax

### ISSUE THREAD

**Issue by alephpi** [trealla-prolog/trealla#502]
Hi, I'm moving from swi-prolog to trealla-prolog and I found there is a difference on syntax of a functor with empty argument.

For trealla-prolog, functor with empty args is just an syntax error.
Here is a minimal reproduction:
https://php.energy/trealla.html?share=5fe36135-4405-4bcc-8b1c-9bf401ceb87c

But in swi-prolog, it accepts such syntax.
![image](https://github.com/trealla-prolog/trealla/assets/61275421/5cfdc764-635c-4ba2-bfd3-bdeab48c855e)

I just wonder if this is designed on purpose.
For the moment, I add a placeholder(e.g. `functor('null')`) as a workaround.

Thank you for your attention!

**Comment by infradig** [comment]
Hi,

It's because it's not ISO Prolog standard syntax. Only SWI prolog & XSB
(that I am aware) accept such syntax.

**Comment by alephpi** [comment]
Alright, I see.
