### ISSUE TITLE
Windows build issue

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#503]
Currently the Windows build is messed up, and you can see it failing all the tests here: https://github.com/trealla-prolog/trealla/actions/runs/7999088651/job/21846314568#step:8:1432
I tried running it and it immediately ends the process without showing the toplevel.

You can avoid the issue by building with `NOTHREADS=1`. I will poke at it a bit to see what's causing it. It might just be missing a DLL as in https://github.com/trealla-prolog/trealla/issues/290.

**Comment by infradig** [comment]
Threads can be turned off for Windows.

**Comment by guregu** [comment]
Probably best to disable them in Windows for the time being. You can add NOTHREADS=1 here https://github.com/trealla-prolog/trealla/blob/main/.github/workflows/build.yaml#L70 and it'll do the trick
I'll mess with it when I get some free time soon

**Comment by infradig** [comment]
Done. disabled in windows.

**Comment by guregu** [comment]
Thanks, I'll send a PR if I figure it out!

**Comment by flexoron** [comment]
Full-featured Trealla compilation here: #506 
This is done with msys2 installation on Windows 11. (no cross-compilation)

Private reason why clang:
Because openmp(omp) version v5.1 is supported while gcc supports just omp v4.5
