### ISSUE TITLE
Quadratic runtime cost for length/2

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#506]
```
?- length(_,E), E>8, N is 2^E, time(once((length(L,Ni),Ni=N))).
Time elapsed 0.0102 secs
   E = 9, N = 512, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;Time elapsed 0.0326 secs
  E = 10, N = 1024, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;Time elapsed 0.115 secs
  E = 11, N = 2048, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;Time elapsed 0.444 secs
  E = 12, N = 4096, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;Time elapsed 1.75 secs
  E = 13, N = 8192, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;Time elapsed 7.4 secs
  E = 14, N = 16384, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;Time elapsed 30.1 secs
  E = 15, N = 32768, L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], Ni = N
;^C
Action or (h)elp: e
  false.
?- time(length(L,32768)).
Time elapsed 0.0629 secs
   L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...].
```
So while the list size doubles, the runtime quadruples.

(This was [item 5](http://www.complang.tuwien.ac.at/ulrich/swi-prolog/#5) for SWI 2006-12-18)

**Comment by infradig** [comment]
It's the backtracking into it that causes the problem...

?- time(length(L,16384)).
Time elapsed 0.0159 secs
   L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...].


?- time((length(L,N),N=8192)), !.
Time elapsed 0.577 secs
   L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], N = 8192.

?- time((length(L,N),N=16384)), !.
Time elapsed 2.21 secs
   L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], N = 16384.

**Comment by UWN** [comment]
Maybe I was not clear enough, but `time(length(L,N))` and `time(once((length(L,Ni),Ni=N)))` should be apart by a factor independent of `N`.

**Comment by infradig** [comment]
Yes, clear. Seems unrelated to length/2 specifically. Seems an optimization issue with not reclaiming space.
