### ISSUE TITLE
Memory streams

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#51]
For the JS integration, it'd be nice if I could `set_output/1` to a memory buffer. This would make it a lot easier to wrangle the specially formatted output for the programmatic toplevel vs. user code writing to stdout. Currently there's some hairy logic using ASCII control codes to work around it.

```prolog
% kind of like this in SWI but without the implicit once/1?
with_output_to(chars(Cs), call(Goal)),
write({"stdout": Cs}).
```

I'd like to avoid the OS filesystem as some WASM runtimes may not have a FS at all.

**Comment by infradig** [comment]
Happy to add something in but I think will be a bit of work. Maybe on the weekend.

**Comment by guregu** [comment]
Much appreciated. The current workarounds are effective so please take your time 🙂

**Comment by infradig** [comment]
Turns out it was pretty easy to do once I started looking at it. Now providing a SWI-Prolog compatible...

```prolog
with_output_to(chars(Cs), Goal) :-
	setup_call_cleanup(
		'$capture_output',
		once(Goal),
		'$capture_output_to_chars'(Cs)
	), !.
```
but you can roll your own without once/1.

**Comment by guregu** [comment]
Excellent! I have one question, more of a Prolog question, but:

```prolog
query(Query, Status, Output) :-
	%'$capture_output',
	(   call(Query) % ← how can I get this to call $capture_output each time before backtracking?
	*-> Status = success
	;   Status = failure
	),
	'$capture_output_to_chars'(Output).
```

I can see why SWI shoves the `once/1` into there now, haha.
I feel like I am definitely fighting against what you are supposed to do in Prolog, but I'm not sure how to accomplish this otherwise 🤔

**Comment by infradig** [comment]
Can't you put a $capture_output/0 straight after the $capture_output/1 to
reprime it?

**Comment by guregu** [comment]
Good point... I tried that but I wasn't able to get it to work 🤔 
However, this does work (borrowing a technique from [SWI's manual](https://www.swi-prolog.org/pldoc/doc_for?object=undo/1)):

```prolog
js_ask :-
	setup_call_cleanup(
		'$capture_output',
		catch(
			( query(Query, Status, Output) ),
			Error,
			Status = error
		),
		'$capture_output_to_chars'(_) % eat spurious last capture
	)
% ...

query(Query, Status, Output) :-
	(   call(Query)
	*-> Status = success
	;   Status = failure
	),
	'$capture_output_to_chars'(Output),
	( true ; '$capture_output', fail ).
```

I'm probably just doing something dumb.

**Comment by guregu** [comment]
OK I can confirm it is working well. I will integrate it into the WASM stuff soon. Thanks a bunch.
I ran into this issue again: https://github.com/trealla-prolog/trealla/issues/46#issuecomment-1259576921 but still not able to isolate it. Something can trigger the backtracking to work strangely. Capture stuff is good though.
I will make a separate issue for that.

**Comment by infradig** [comment]
I have added '$capture_error'/0 and '$capture_error_to_chars'/1 to enable capture of user_error. It should be possible now to capture trace info (which goes to stderr) and display in a separate window.

**Comment by infradig** [comment]
You can output to an atom in several ways. I think open/3,4 allows opening
a stream to an atom, like:

?-open(atom(X),write,S),write(S,hello),write(S,world).
  X =  helloworld.
