### ISSUE TITLE
fairy finite memory cake

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#510]
v1.25.1
```
?- length([_|_],_).
   true
;  ... .

?- length([_=|_],_).
uncaught exception: error(resource_error(finite_memory),length/2)
?-
```

**Comment by infradig** [comment]
Parsing miss causes failure driven loop inside length/2, hence eventual
resource_error...

?- L=[_=|_].
   L = [_A=_B|dummy].

Will look into it.
