### ISSUE TITLE
acyclic_term/1 incredibly slow

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#515]
First,

```
?- ulrich@p0:/opt/gupu/trealla$ ulimit -v
99999
ulrich@p0:/opt/gupu/trealla$ ./tpl -f
?- length(_,I), I > 10,  N is 2^I, \+ \+ ( length(L,N), length(L, M), N == M ).
   I = 11, N = 2048
;  I = 12, N = 4096
;  I = 13, N = 8192
;  I = 14, N = 16384
;  I = 15, N = 32768
;  I = 16, N = 65536
;  I = 17, N = 131072
;  I = 18, N = 262144
;uncaught exception: error(resource_error(memory),(',')/2)
?- ulrich@p0:/opt/gupu/trealla$ 
ulrich@p0:/opt/gupu/trealla$ ./tpl -f
?- length(_,I), I > 10,  N is 2^I, \+ \+ ( length(L,N), length(L, M), N == M, acyclic_term(L) ).
   I = 11, N = 2048
;  I = 12, N = 4096
;  I = 13, N = 8192
;  I = 14, N = 16384
;  I = 15, N = 32768
;
```

Also, try to avoid using auxiliary space. The point of acyclic_term/1 is to rapidly check interfaces.

**Comment by infradig** [comment]
Yes, sometime I will replace the linear search with a lookup map.

**Comment by UWN** [comment]
Why is this so slow? I really don't get it. It should not cost much more than length/2 of it

**Comment by UWN** [comment]
(It seems you do not have mark bits anywhere, there must be some space for them on a 64-bit machine...)

**Comment by UWN** [comment]
Isn' this just special caseing for lists?

```
?- [user].
l_h([], nihil).
l_h([E|Es], E^Eh) :- l_h(Es, Eh).
   true.
?- length(_,I), I > 10,  N is 2^I, \+ \+ ( length(L,N), l_h(L,H), time(acyclic_term(H)) ).
Time elapsed 0.0293 secs
   I = 11, N = 2048
;Time elapsed 0.0997 secs
  I = 12, N = 4096
;Time elapsed 0.35 secs
  I = 13, N = 8192
;Time elapsed 1.37 secs
  I = 14, N = 16384
;Time elapsed 5.69 secs
  I = 15, N = 32768
;Segmentation fault (core dumped)
```


As for special caseing: The biggest problem with it is that it means that tests have to be even more complex. So chances to find problems get more and more costly. Why not mark things?

**Comment by infradig** [comment]
A proper solution will take more time. When I can I will.

**Comment by UWN** [comment]
That [used to be](http://www.complang.tuwien.ac.at/ulrich/sicstus_prolog_old/bug0.txt) a problem in SICStus too. Back in 1996.

**Comment by UWN** [comment]
And [SWI in 2006](http://www.complang.tuwien.ac.at/ulrich/swi-prolog/#13). Closing with a reminder UWN_open

**Comment by infradig** [comment]
You got me thinking, and how's this?

PS. Not pushed yet as there are few issues to deal with.

~/trealla (devel) $ tpl
?- length(_,I), I > 10,  N is 2^I, \+ \+ ( length(L,N), length(L, M), N ==
M, time(acyclic_term(L)) ), write([I,N]), nl, fail.
Time elapsed 6.7e-05 secs
[11,2048]
Time elapsed 0.000135 secs
[12,4096]
Time elapsed 0.000597 secs
[13,8192]
Time elapsed 0.000686 secs
[14,16384]
Time elapsed 0.000726 secs
[15,32768]
Time elapsed 0.00204 secs
[16,65536]
Time elapsed 0.00379 secs
[17,131072]
Time elapsed 0.00574 secs
[18,262144]
Time elapsed 0.012 secs
[19,524288]
Time elapsed 0.024 secs
[20,1048576]
Time elapsed 0.0619 secs
[21,2097152]
Time elapsed 0.0928 secs
[22,4194304]
Time elapsed 0.195 secs
[23,8388608]
^C
Action or (h)elp: x
~/trealla (devel) $

**Comment by infradig** [comment]
And...

~/trealla (devel) $ tpl
?- [user].
l_h([], nihil).
l_h([E|Es], E^Eh) :- l_h(Es, Eh).
   true.
?- length(_,I), I > 10,  N is 2^I, \+ \+ ( length(L,N), l_h(L,H),
time(acyclic_term(H)) ).
Time elapsed 0.000378 secs
   I = 11, N = 2048
;Time elapsed 0.000755 secs
  I = 12, N = 4096
;Time elapsed 0.000836 secs
  I = 13, N = 8192
;Time elapsed 0.00162 secs
  I = 14, N = 16384
;Time elapsed 0.00515 secs
  I = 15, N = 32768

**Comment by UWN** [comment]
A factor of two from one `I` to the next is ok. That's linear.

(BTW, Trealla has an excellent <kbd>a</kbd> command, no need for explicit `write([I,N]), nl, fail.`)
