### ISSUE TITLE
FYI: Trealla trashes effort to port a C-compiler

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#520]
```
Windows11/msys2/clang version 18.1.2
InstalledDir: C:/msys64/ucrt64/bin

$ CC=clang make test
Running tests/tests/test065.pl ...
Segmentation fault  

#0  0x00007ff6b0f66a10 in sl_set ()
#1  0x00007ff6b0f3a986 in copy_vars ()
#2  0x00007ff6b0f3acb8 in deep_copy_to_tmp_with_replacement ()
#3  0x00007ff6b0f3ae73 in deep_copy_to_heap ()
#4  0x00007ff6b0eeac7b in do_duplicate_term ()
#5  0x00007ff6b0f643f0 in start ()
#6  0x00007ff6b0f4d052 in run ()
#7  0x00007ff6b0f41e0a in load_fp ()
#8  0x00007ff6b0f3d251 in load_file ()
#9  0x00007ff6b0f5e0a3 in pl_consult ()
#10 0x00007ff6b0e71c16 in main ()

This happens after copy_term/2 (test065.pl Line 107) has been 'called' roughly 20.000 times
while Linux and Termux 'calls' copy_term/2 roughly 200.000 times finishing the test successful.

Interesting: Android/Termux/clang version 18.1.2 -- No problem!
Interesting: Windows/msys2//clang version 17.0.6 -- No problem!

Right now I do not have Linux/clang v18.1.2 but expecting to get it soon(Fedora40).
```

**Comment by infradig** [comment]
I can only try clang-16 & clang-17 on Ubuntu, and no problem. Also, valgrind doesn't show anything unusual.

**Comment by flexoron** [comment]
Neither clang-17 on Windows(and Linux) nor clang-18 on Android does produce the fault.
Clang-18 on Windows comes under suspicion.
Closing because it is an FYI (for now :)

**Comment by flexoron** [comment]
FYI:
I decided to discard Windows11/Msys2 as worthless.
After reinstalling msys2 and clang-18 I get four more unexplainable issues.

More crap work:
The msys2-independent installation of the provided Trealla/tpl-windows-x64.zip file
fails finishing test065.pl, too. It seems gcc-compiled stuff is infected as well.

And what more could one want? The pty device is unusable:
?- length(L,N).
   L = [], N = 0
; % Space is not passed on, you've to press the Enter key.
And if you configure tty(and all those workarounds) to get the space immediately other terminal-functionality is broken.
Conclusion: Who gives a sh.t.

**Comment by infradig** [comment]
Windows is meaningless to me.

**Comment by flexoron** [comment]
In contrast: The latest Linux/Intel/oneAPI C-Compiler performs flawlessly.

**Comment by infradig** [comment]
> And what more could one want? The pty device is unusable: ?- length(L,N). L = [], N = 0 ; % Space is not passed on, you've to press the Enter key. And if you configure tty(and all those workarounds) to get the space immediately other terminal-functionality is broken. Conclusion: Who gives a sh.t.

It should be possible to compile with GNU readline (remove ISOCLINE=1) if the msys2 version is installed. I found Isocline not very good, it was only there when I once played with the idea of a true native port to Windows. @guregu

**Comment by guregu** [comment]
I think the main reason I went with isocline for the Windows release is because distributing readline statically linked would cause some GPL issues… maybe? There are other readline alternatives that are probably better

**Comment by infradig** [comment]
I can't imagine any licensing issues with an open source program.

**Comment by flexoron** [comment]
Isocline is not good because the developer ignores all issues for a long time: https://github.com/daanx/isocline/issues/11
Isocline is good because it is a lot easier to implement an integrated, sophisticated(working) signal handling. 

Readline does not solve the Windows11/TTY issue either.
(msys2/bash and windows/powershell show the same behaviour).

**Comment by guregu** [comment]
Hmm, might be worth trying something like https://github.com/jart/bestline
I was looking into porting Trealla to cosmopolitan libc and got it mostly working besides the readline bits, which led me to bestline, but I haven't played with it yet. It says it supports cmd.exe though, so maybe better?
The WASM port also has issues due to the lack of raw terminal support, but things have changed a lot in the last year or so, so it's probably worth a revisit.

**Comment by flexoron** [comment]
@guregu Thank you for this link.
Very interesting! 
First thing I see is that ppl using bestline found same thing which I tried to address with Isocline:
https://github.com/jart/bestline/issues/22
Seems this issue has been solved with cosmopolitan libc (and worth examining it).
