### ISSUE TITLE
CLPZ: `#<==>/2` crashing (and consequently: `clpz_t/2`, `#=/3`, `#</3`) 

### ISSUE THREAD

**Issue by haijinSk** [trealla-prolog/trealla#522]
On Ubuntu using a binary release version "v2.50.20" (not the first release/version with this behavior).

Examples with clpz library already loaded.

Crashing:

```
?- 4 #= 4 #<==> #B.
realloc(): invalid next size
Aborted (core dumped)
```

By the way, no crash if `#` is removed from the `#B`:

```
?- 4 #= 4 #<==> B.
   B = 1. % as expected
```

But the "removed #" case is crashing with a variable in the left expression:

```
?- X #= 4 #<==> B.
realloc(): invalid next size
Aborted (core dumped)
```

Thank you.

**Comment by infradig** [comment]
I can't replicate this one.

**Comment by flexoron** [comment]
$ git clone ... && cd trealla
$ make
$ tpl -v
Trealla Prolog (c) Infradig 2020-2023, v2.50.21
```
$ tpl
?- use_module(library(clpz)).
   true.
?- 4 #= 4 #<==> #B.
free(): corrupted unsorted chunks
Aborted (core dumped)

$ tpl
?- use_module(library(clpz)).
   true.
?- 4 #= 4 #<==> B.
   B = 1.

?- X #= 4 #<==> B.
free(): invalid pointer
Aborted (core dumped)
```
I get other core-dump messages.

**Comment by infradig** [comment]
Yeah, my bad.

**Comment by haijinSk** [comment]
I thought, my hope was, that if the `(#<==>)/2` examples will work, the (`#=)/3` and `(#<)/3 `will work, not crashing. Now, in **v2.50.23b**, my `(#<==>)/2` examples here work. Now (v2.50.23b), the `(#=)/3` and `(#<)/3` work, thank you; unfortunately they work only in isolation. 

Used in `tfilter/3` from reif library, or in `maplist/3`, they are **still crashing**.

In isolation as expected:

```
?- #=(1,1,B).
   B = true.
?- #<(1,2,B).
   B = true.
```


But crashing if used in the metapredicate:

```
?- maplist(#=(3),[1,2,3],Bs).
realloc(): invalid next size
Aborted (core dumped)
```
```

?- maplist(#<(3),[1,2,3],Bs).
realloc(): invalid next size
Aborted (core dumped)
```

**Comment by infradig** [comment]
Ok, great, that's really useful. It seems somewhere in atts it's expanding
the slots improperly.

**Comment by haijinSk** [comment]
v2.50.26, no crash, the examples work; thank you!

**Comment by haijinSk** [comment]
v2.50.26, no crash, the examples work; thank you!
