### ISSUE TITLE
Top level indentation of errors

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#524]
```
?- ( true ; _=.._).
   true
;   error(instantiation_error,not_sufficiently_instantiated). % one space too much
%123
```

This is one tiny space too much in front. Just like:

```
?- ( true ; E = t ).
   true
;  E = t. % expected
%12
```

**Comment by UWN** [comment]
Just, because I see `not_sufficiently_instantiated` which seems to be a message to the other side of the top level loop (to the hu-men): If you want to produce helpful messages that are human readable you could put them after the error term in a comment line. But all of this gets so verbose...

**Comment by infradig** [comment]
I'm thinking of dropping indentation.

**Comment by UWN** [comment]
Perfect! What now is missing, is a (syntactically) clean way to interact with interrupts. Think of:

```

?- X = 1 ; repeat, false.
   X = 1
;^C
Action or (h)elp: e
  false.
```

Not sure how to do that.

**Comment by UWN** [comment]
You might have noted that I use `loops.` as a kind-of answer. Ideally, also meaning could be transferred...

Maybe it could be:

```
?- X = 1 ; repeat, false.
   X = 1
;^C
% Action or (h)elp: e
  ... .
