### ISSUE TITLE
Syntax: wrong reading

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#528]
[#90](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#90):

```
?-  write_canonical((-;-)). 
-(;)   true. % expected ; expected error
```

What is particularly odd here is that there are two tokens `-` in the input. And still only one is part of the resulting term.

**Comment by UWN** [comment]
Please do take such issues seriously too, after all, why shouldn't this happen also for valid Prolog text. And I cannot test everything.

**Comment by infradig** [comment]
Is a reading like this acceptable (as per SWI, Cx, Ciao & XSB)? Only Scryer
and GNU Prolog give a parsing syntax error.

?- write_canonical((-;-)), nl.
;(-,-)

**Comment by UWN** [comment]
It is not conforming. And look at SWI, Cx, Ciao and XSB: They are all not very conforming also in other areas. Making consistent extensions to ISO syntax is even more hairsplitting than conforming to ISO. SICStus managed it. As the only system. Within 30+ years. Why put this questionable creativity into this completely obscure place?

**Comment by infradig** [comment]
Ok, I just wanted to be sure what was correct. I'm sure there's a good
reason, though it eludes me.
