### ISSUE TITLE
Reading multiple terms from a string

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#53]
Is it possible to read multiple terms from a string? `read_term_from_chars/3` only returns one.
Maybe it could backtrack and return multiple terms.
Or maybe `position(Start,End)` could work for strings too?

```
% maybe like this?
?- read_term_from_chars(X, [], "foo. bar.").
   X = foo
;  X = bar.
```

```
% or this?
?- read_term_from_chars(X, [position(Start,End)], "foo. bar.").
   X = foo, Start = 0, End = 3.
```

Use-case: trying to execute Prolog code inside webpage templates. Currently look for `.` in a DCG but that breaks when a float has a dot in it.

**Comment by triska** [comment]
I think a DCG nonterminal `term//1` would be useful for this. With it, one could use `phrase/3` to read a term, and have the remainder available for further reasoning.

For example, one could read two terms with:

<pre>
?- phrase((term(T1),term(T2),...), Cs).
</pre>

or, using list differences, with:

<pre>
?- phrase(term(T1), Cs0, Cs1), phrase(term(T2), Cs1, Cs2).
</pre>

where `Cs2` is the remainder after `T1` and `T2` are read from the list of characters `Cs0`.

**Comment by triska** [comment]
By the way, as a workaround, until such a nonterminal is available, you can manually try every possible string prefix to read a term:

<pre>
?- append(Prefix, Rest, Cs), read_from_chars(Prefix, T).
</pre>

with suitable use of `catch/3` to catch syntax errors, failing if `Prefix` cannot (yet) be parsed. This incurs quadratic overhead, which is unacceptable for longer strings, but may be acceptable for the present use case, and until a faster (linear) construct is available.

**Comment by guregu** [comment]
A DCG nonterminal would be perfect. I'm currently using a DCG to look for delimiters (`<?` and `?>` in my case 😉) and then calling `read_from_chars/3`, but I could use `term//1` directly to do that quite elegantly. 

Thanks for the workaround as well @triska!

**Comment by triska** [comment]
Here is a quick and rather untested *ad hoc* definition of `term//1`:

<pre>
:- use_module(library(dcgs)).
:- use_module(library(charsio)).
:- use_module(library(lists)).

term(T) --&gt;
        call(term_(T)).

term_(T, Cs0, Cs) :-
        append(Prefix, Cs, Cs0),
        catch(read_from_chars(Prefix, T), error(syntax_error(_),_), false).
</pre>

Example:

<pre>
<b>?- phrase(("&lt;",term(T),"&gt;"), "&lt;  hello. &gt;").</b>
   T = hello
;  false.
</pre>

Tested with Scryer Prolog.

**Comment by infradig** [comment]
In Trealla that is...

```prolog
term(T) -->
        call(term_(T)).

term_(T, Cs0, Cs) :-
        append(Prefix, Cs, Cs0),
        catch(read_term_from_chars(T, Prefix), error(syntax_error(_),_), false).
```

```console
?- phrase(("<",term(T),">"), "<  hello. >").
   T = hello
;  false.
```

EDIT: note this is no longer correct. it is..  **catch(read_term_from_chars(Prefix,T), error(syntax_error(_),_), false).**
EDIT2: or use the code directly as provided by Markus.

**Comment by infradig** [comment]
```console
$ tpl
?- help(read_term_from_chars/2).
read_term_from_chars/2: read_term_from_chars(+chars,?term)
   true.

?- help(read_term_from_chars/3).
read_term_from_chars/3: read_term_from_chars(+chars,?term,+list)
   true.
```

**Comment by triska** [comment]
Personally, I think a good building block would be `read_from_chars_(T, Cs0, Cs)`, reading from `Cs0` the term `T`, leaving remainder `Cs`. This can be used (internally, since it relies on the implementation dependent order of arguments) in DCGs, and we can also (portably) implement `term//1` and `read_term_from_chars/3` on top of it.

For example, with this building block, `term//1` could be implemented as:

<pre>
term(T) --&gt; call(read_from_chars_(T)).
</pre>

**Comment by infradig** [comment]
Sounds good.

**Comment by infradig** [comment]
I have added ...

~/trealla (devel) $ tpl
?- '$read_term_from_chars'(T,"f(1). f(2).", Rest).
   T = f(1), Rest = "f(2).".
?- ~/trealla (devel) $

to see how it goes.

EDITED to reflect the 3rd arg now eats leading space first. Is that correct?

**Comment by guregu** [comment]
Is this supposed to happen?

```?- '$read_term_from_chars'(T,[],"abc.",Rest).
   T = abc, Rest = "abc.".
```

Puts my naïve DCG into an infinite loop.

**Comment by guregu** [comment]
Is this supposed to happen?

```prolog
?- '$read_term_from_chars'(T,[],"abc.",Rest).
   T = abc, Rest = "abc.".
```

Puts my naïve DCG into an infinite loop.

**Comment by infradig** [comment]
No that's no supposed to happen.

**Comment by guregu** [comment]
This is working quite nicely now. Very quick and no problem with decimal points. Thanks a bunch!

Here it is in action: https://php.energy/moon.html

**Comment by infradig** [comment]
Cool.
