### ISSUE TITLE
does this terminate, i.e. model finder

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#533]
Was trying this query:
```
?- counter(3).
```
Does it terminate? Was waiting more than 20 minutes,  SWI-Prolog 
does it in 12 minutes. But can Trealla Prolog also do it?

Source code:

[mace4.p.log](https://github.com/trealla-prolog/trealla/files/15194868/mace4.p.log)

**Comment by infradig** [comment]
$ swipl -q mace4.pl
?- time(counter(3)).
0*0-0 0*1-1 0*2-2 0*3-3 0*4-4 0*5-5 1*0-1 1*1-5 1*2-3 1*3-4 1*4-2 1*5-0
2*0-2 2*1-4 2*2-0 2*3-5 2*4-1 2*5-3 3*0-3 3*1-2 3*2-1 3*3-0 3*4-5 3*5-4
4*0-4 4*1-3 4*2-5 4*3-1 4*4-0 4*5-2 5*0-5 5*1-0 5*2-4 5*3-2 5*4-3 5*5-1
a-1
b-2
i(0)-0 i(1)-5 i(2)-2 i(3)-3 i(4)-4 i(5)-1
% 10,981,885,000 inferences, 1070.676 CPU in 1072.190 seconds (100% CPU,
10256962 Lips)
true

$ tpl mace4.pl
?- time(counter(3)).
0*0-0 0*1-1 0*2-2 0*3-3 0*4-4 0*5-5 1*0-1 1*1-5 1*2-3 1*3-4 1*4-2 1*5-0
2*0-2 2*1-4 2*2-0 2*3-5 2*4-1 2*5-3 3*0-3 3*1-2 3*2-1 3*3-0 3*4-5 3*5-4
4*0-4 4*1-3 4*2-5 4*3-1 4*4-0 4*5-2 5*0-5 5*1-0 5*2-4 5*3-2 5*4-3 5*5-1
a-1
b-2
i(0)-0 i(1)-5 i(2)-2 i(3)-3 i(4)-4 i(5)-1
% Time elapsed 4894.729s, 13584971414 Inferences, 2.775 MLips
   true
;

$ scryer-prolog mace4.pl
?- time(counter(3)).
0*0-0 0*1-1 0*2-2 0*3-3 0*4-4 0*5-5 1*0-1 1*1-5 1*2-3 1*3-4 1*4-2 1*5-0 2*0-2 2*1-4 2*2-0 2*3-5 2*4-1 2*5-3 3*0-3 3*1-2 3*2-1 3*3-0 3*4-5 3*5-4 4*0-4 4*1-3 4*2-5 4*3-1 4*4-0 4*5-2 5*0-5 5*1-0 5*2-4 5*3-2 5*4-3 5*5-1 
a-1 
b-2 
i(0)-0 i(1)-5 i(2)-2 i(3)-3 i(4)-4 i(5)-1 
   % CPU time: 7646.607s, 19_937_875_400 inferences
   true

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, I wasn't expecting a factor 4-5. Maybe should also check 
Scryer Prolog. For example Dogelog Player for Java does it in,
on a machine where SWI-Prolog takes 12 minutes:
```
/* Dogelog Player 1.2.0 */
?- time(counter(3)).
% Zeit 1497742 ms, GC 61 ms, Lips 8560942, Uhr 02.05.2024 12:06
true
```
Ciao Prolog beats SWI-Prolog by a factor 2-3:
```
/* Ciao Prolog 1.22.0 */
?- time(counter(3)).
% 295.658424 seconds
yes
````
What keeps Trealla that busy? Also Trealla LIPS going down?
(LIPS going down could indicate some pressure on built-ins,
or maybe something else, some pressure on garbage collection?)

**Comment by infradig** [comment]
Hard to say. If if compile with profiling I could run it overnight.

**Comment by infradig** [comment]
Uses a lot of (=..)/2, which can be expensive, something i've been meaning to revisit.

**Comment by Jean-Luc-Picard-2021** [comment]
After some wait, Scryer Prolog gives me:
```
/* Scryer Prolog 0.9.4 */
?- time(counter(3)).
   % CPU time: 2721.739s, 19_937_875_400 inferences
   true
```

**Comment by infradig** [comment]
It's now about 20% faster, not much more I can do.

**Comment by Jean-Luc-Picard-2021** [comment]
So close it?

**Comment by infradig** [comment]
No, don't. I have a speedy solution but don't know if it will anything else
yet.
