### ISSUE TITLE
Rational tree unification segv

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#533]
```
?- \B=A,B=[C|A],C=[B|A],\C=A, false.
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
Yes, unification (and copy_term & compare) still use the old method
(visitor lists) of cycle checking which is poor. I plan to rewrite them to
use mark/sweep methodology. But i'll see if there's a quick fix.

**Comment by UWN** [comment]
Please no quick fix. Instead a clean one.

(I do not understand why you are here into mark/sweep. Marking, yes. But why sweeping. That is not a GC. Or am I wrong?)

**Comment by infradig** [comment]
Poor terminology choice by me, I use sweep here to mean traverse the tree.
