### ISSUE TITLE
Application-specific Comparsion

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#534]
$ scryer-prolog -v
v0.9.4-46-g42a0d686
$ tpl -v
Trealla Prolog (c) Infradig 2020-2023, v2.51.8-5-gbcb2
```
$ scryer-prolog -f
?- use_module(library(lists)).
   true.
?- [user].
[a,b,c].
   error(permission_error(create,static_procedure,nameless_procedure),load/1).
?- a.
   error(existence_error(procedure,a/0),a/0).
?- halt.

$ tpl
?- use_module(library(lists)).
   true.
?- [user].
[a,b,c].
   true.
?- a.
   true.
?- halt.

% And
$ tpl
?- [user].
[[a]].
   true.
?- [user].
[[a]].
Warning: overwriting '.'/2 % Meaning?
   true.
?-
```
Where am I? Where are you off to?

**Comment by infradig** [comment]
I believe it appeared with term_expansion, which can return a list of terms. It's acceptance here is of course is unintended, though cute.

**Comment by infradig** [comment]
SWI accepts it with a warning...

$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.3.3-40-g6d3b1fa0b-DIRTY)
?- [user]. [a,b,c].
Warning: user://1:7:
Warning:    Clauses of a/0 are not together in the source-file
Warning:    Earlier definition at user://1:7
Warning:    Current predicate: c/0
Warning:    Use :- discontiguous a/0. to suppress this message
Warning: user://1:7:
Warning:    Clauses of b/0 are not together in the source-file
Warning:    Earlier definition at user://1:7
Warning:    Current predicate: a/0
Warning:    Use :- discontiguous b/0. to suppress this message
Warning: user://1:7:
Warning:    Clauses of c/0 are not together in the source-file
Warning:    Earlier definition at user://1:7
Warning:    Current predicate: b/0
Warning:    Use :- discontiguous c/0. to suppress this message
|: 
% user://1 compiled 0.00 sec, 6 clauses
true.

?- a.
true ;
true.

though how it is a redefinition elludes me.

**Comment by flexoron** [comment]
Due to weakness of brain I am inclined to the view that that is that is that.
Dominus vobiscum.

**Comment by flexoron** [comment]
```
$ swipl # 9.2.4
?- [user].
|: [[[[[[a]]]]]].
|: ^D% user://1 compiled 0.01 sec, 64 clauses
true.

?- a.
true ;
true ;
true ;
: 
: 
?-
```
Et cum spíritu tuo. 64 clauses?
```
$ tpl
?- [user].
[[[[[[a]]]]]].
   true.
?- listing.
[[[[[a]]]]].
   true.
?- [user].
[[[[[[a]]]]]].
Warning: overwriting '.'/2
   true.
?- a.
   throw(error(existence_error(procedure,a/0),a/0)).
?-
```
