### ISSUE TITLE
Invalid pointer with term_variables/2

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#536]
```
g1:/tmp> /opt/gupu/trealla/tpl -f
?- [user].
run :-
   length(Es, N),
   writeq(N),nl,
   term_variables(Es,_Vs),
   false.
   true.
?- run.
0
1
2
...
39
40
free(): invalid pointer
Abort (core dumped)
```

(This was originally a program that behaved odd (failed instead of continuing) after more than 220 minutes). That's why I was reporting nothing)

**Comment by UWN** [comment]
Shorter:

````
?- length(L,N), term_variables(L,Vars).
   L = [], N = 0, Vars = L
;  L = [_A], N = 1, Vars = L
...
;  L = [_A,_B,_C,_D,_E,_F,_G,_H,_I,...], N = 40, Vars = L
;free(): invalid pointer
Abort (core dumped)
```

**Comment by UWN** [comment]
Nice try, but the root of all evil is still here:

```
...
nth(ntv:4*760000000)
nth(ntv:4*761000000)
   false.
```

**Comment by infradig** [comment]
> ...
nth(ntv:4*760000000)
nth(ntv:4*761000000)
   false.

What's this?

**Comment by UWN** [comment]
> What's this?

Traces. I need to record this someplace. So the unexpected failure occurs after the 4761000000th answer of call_nth/2. I am trying to narrow it down to something reportable. Currently takes 125:16 to unexpected failure. On verra.

**Comment by UWN** [comment]
Followup #538
