### ISSUE TITLE
Odd parser bug

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#536]
```
?- X =.. ['.',-,[]].
   X = "-".

?- X = "-", X =.. Y.
   X = "-", Y = ['.',-,[]].

?- "-" =.. Y.
Error: syntax error, incomplete, needs parenthesis, user:1 % unexpected
?- 
```

**Comment by infradig** [comment]
Not univ per se...

$ tpl
?- "-" = Y.
Error: syntax error, incomplete, needs parenthesis, user:1

Odd parser bug.

**Comment by flexoron** [comment]
@infradig  Could you do me a favour and compare the results?
```
$ tpl
?- [(-,-)] = X.
   X = [((-),(-))].
?- halt.

$ scryer-prolog 
?- [(-,-)] = X.
   error(syntax_error(incomplete_reduction),read_term/3:1).
?- halt.
```

**Comment by infradig** [comment]
Well Scryer & GNU Prolog both reject it. SWI, B, Cx, Ciao, XSB, Yap &
Eclipse are all ok with it. I think strictly Scryer is right.

**Comment by flexoron** [comment]
```
$ tpl
?- [(--,--)] = X.
   X = [((--),(--))]. % Op detected
?- halt.

$ scryer-prolog
?- [(--,--)] = X.
   X = [(--,--)]. % No op, and accepted
?- halt.
```
This makes me think that Trealla is right.

**Comment by infradig** [comment]
(--)/1 is declared an op for mode declarations, don't remember where/why.

**Comment by flexoron** [comment]
```
$ scryer-prolog
?- op(100,fy,--).
   true.
?- [(--,--)] = X.
   error(syntax_error(incomplete_reduction),read_term/3:1).
?-
```
Scryer is not able to figure out that '--' is an op.

**Comment by infradig** [comment]
It's correct. It should be parenthesized. Trealla et al are just lax.

**Comment by flexoron** [comment]
Thank you very much for this accident analysis.
