### ISSUE TITLE
Unexpected failure (instead of infinite loop)

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#538]
```
run :-
      Run = rntv4_9,
		length(Es, N),
		writeq(Run:N),nl,
		alleq(Es),
      false.

alleq(Xs1) :-
   Xs1 = [_|_],
	phrase(spec(Xs2,[]),Xs1),
	alleq(Xs2).
alleq(_).

spec(Es0,Es) -->
	seq(_,_),
	[E],
	seq(Es0,Es1),
	rspec(E,Es1,Es).

rspec(E,Es0,Es) -->
	[E],
	seq(Es0,Es1),
	(	{Es1=Es}
	|	rspec(E,Es1,Es)
	).

seq(Es,Es) -->
	[].
seq([E|Es0],Es) -->
	[E],
	seq(Es0,Es).

?- run.
rntv4_9:0
rntv4_9:1
rntv4_9:2
rntv4_9:3
rntv4_9:4
rntv4_9:5
rntv4_9:6
rntv4_9:7
rntv4_9:8
rntv4_9:9
rntv4_9:10
rntv4_9:11
rntv4_9:12
rntv4_9:13
rntv4_9:14
   false. % unexpected
```

So this is a 100% pure program, and it must be an infinite loop due to `length(Es, N)`. But it fails.

<s>
And p-lease, do improve the top level even [further](https://github.com/trealla-prolog/trealla/issues/537#issuecomment-1100623191). This would have saved me a day or two. I hate being forced to write such otherwise unnecessary side-effects.
</s>

**Comment by UWN** [comment]
Total runtime was 21:01

**Comment by UWN** [comment]
Same for `v1.26.27-18-g274ab3`

**Comment by UWN** [comment]
Can you reproduce this? On my olde lab-top (p0) it takes 364:56 for:

```
?- length(_, N), ( true ; length(Es, N), alleq(Es), false ).
   N = 0
;  N = 1
;  N = 2
;  N = 3
;  N = 4
;  N = 5
;  N = 6
;  N = 7
;  N = 8
;  N = 9
;  N = 10
;  N = 11
;  N = 12
;  N = 13
;  N = 14
;  N = 15
;  false.

**Comment by infradig** [comment]
Mine halts N=14 after 30 mins

**Comment by UWN** [comment]
> that was the old one.

Which is so far the fastest.

I try to see after which answer of alleq/1 this happens. (This runs on my remote server)

Another way is to count instructions up to failure. Then rerun with a trigger to go into gdb a bit before. But this is extremely costly at least when gdb counts instructions (I did in such a situation use a always failing condition, where I then got the number of times it was checked etc.). PAPI is everywhere, that would be the very best way to do this...

**Comment by UWN** [comment]
```
?- Nth+\ ( length(Es, 15), call_nth(alleq(Es), Nth) ).
...
;  Nth = 439162245
;  Nth = 439162246
;  false.
```

**Comment by UWN** [comment]
And on another course:

```
?- length(_,N), N>= 15, ( true ; length(Es, N), alleq(Es) ).
   N = 15
;  N = 15, Es = [_A,_A,_A,_A,_A,_A,_A,_A,_A,...]
;  N = 15, Es = [_A,_A,_A,_A,_A,_A,_A,_A,_A,...]
...
;  N = 15, Es = [_A,_B,_C,_C,_C,_A,_D,_E,_F,...]
;  N = 15, Es = [_A,_B,_C,_C,_C,_A,_D,_E,_F,...]
;  false.

**Comment by UWN** [comment]
Exactly the same with the better query:
```
?- Nth+\ ( ( length(Es, 15), call_nth(alleq(Es), Nth) ; Finis=true ) ).
   Nth = 1
;  Nth = 2
...
;  Nth = 439162246
;  false.
```

Looks as if this would be reproducible - **not**!

The most logical query now was:
```
?- length(Es, 15), call_nth(alleq(Es), Nth), Nth >= 439162245.

?- length(Es, 15), call_nth(alleq(Es), Nth), Nth >= 439162245.
   Es = [_A,_B,_C,_A,_D,_D,_C,_D,_C,...], Nth = 439162245   % 46:35 up to this point
;  Es = [_A,_B,_C,_A,_D,_D,_C,_D,_C,...], Nth = 439162246
...
;  Es = [_A,_B,_C,_D,_E,_E,_B,_D,_D,...], Nth = 991176843
; ... .
```

But now there is no failure at all! I would have expected that with this devise one could 'rapidly' skip to the instantiations in question, but no...

**Comment by UWN** [comment]
v1.26.27-21-g68e6f still fails after  26:57 for rntv4_9

**Comment by infradig** [comment]
I have no lead on it yet.

**Comment by UWN** [comment]
> I have no lead on it yet.

There must be some state beyond an alternative. So 'failing back' does not eradicate it.

**Comment by UWN** [comment]
v1.27.2-5-g5b7bc8 still fails after 21:40 for rntv4_9

**Comment by UWN** [comment]
v1.27.4 still fails after 21:12  for rntv4_9

**Comment by UWN** [comment]
After 118:54, as similar test for term_singletons/2 now failed. That is, no further testing on this front.

**Comment by UWN** [comment]
UWN_blocking

**Comment by UWN** [comment]
Still here, as of v1.28.24

**Comment by UWN** [comment]
It seems something has changed.  Now for the first time output is longer:

```?- run.
rntv4_9:0
rntv4_9:1
rntv4_9:2
rntv4_9:3
rntv4_9:4
rntv4_9:5
rntv4_9:6
rntv4_9:7
rntv4_9:8
rntv4_9:9
rntv4_9:10
rntv4_9:11
rntv4_9:12
rntv4_9:13
rntv4_9:14
rntv4_9:15
rntv4_9:16 % new
                  % still running
```

**Comment by infradig** [comment]
I got to 16 after 5 hours, will leave it running overnight to see if it
gets to 17. I changed some generation counters from 32-bit to 64-bit, maybe
that made a difference on such a long-running evaluation.

**Comment by UWN** [comment]
24h. No 17 so far. What irritates me a bit is that you have this state lingering around. Even if it works (for the moment).

**Comment by UWN** [comment]
17 reached after less than 1848:13 m:s.

**Comment by UWN** [comment]
18 reached after less than 15023:56 m:s.

**Comment by infradig** [comment]
You have it still running?

**Comment by UWN** [comment]
> You have it still running?
Hof course. 15579:12

**Comment by UWN** [comment]
Just for the record: Sunday evening, g1 crashed. There were no checkpoints (due to the nature of the test), so it seems there is no point in repeating.
