### ISSUE TITLE
unify_with_occurs_check/2 loops

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#543]
(Actually, I wanted to test your new term_singletons/2 but got caught up with this loop)

```
ulrich@p0:/tmp/trealla$ cat s.pl
run :-
      skel1(A),
      skel2(B),
		EsG = (A,B),
		term_variables(EsG,Vs),
		alleqxx(Vs),
      call(EsG).
alleqxx([_,X,X,_,X]).

skel1(unify_with_occurs_check(_,s(_))).
skel2(unify_with_occurs_check(_,[_|_])).

ulrich@p0:/tmp/trealla$ /opt/gupu/trealla/tpl -v && /opt/gupu/trealla/tpl -f
Trealla Prolog (c) Infradig 2020-2022, v1.27.11
?- [s].
 true.
?- run.
   loops.
```

**Comment by infradig** [comment]
I don't actually like term_singletons. I think it should be an option in a
new term_variables/3. But anyway the above doesn't get very far...

$ tpl -t s.pl
?- run.
 [0:f1:cp0] EXIT run
 [1:f2:cp0] EXIT skel1(unify_with_occurs_check(_4,s(_5)))
 [2:f3:cp0] EXIT skel2(unify_with_occurs_check(_6,[_7|_8]))
 [3:f1:cp0] NEXT
_2=(unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_6,[_7|_8]))
 [4:f1:cp0] EXIT
(unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_6,[_7|_8]))=(unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_6,[_7|_8]))
 [5:f1:cp0] CALL
term_variables((unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_6,[_7|_8])),_3)
 [6:f1:cp0] EXIT
term_variables((unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_6,[_7|_8])),[_4,_5,_6,_7,_8])
 [7:f4:cp0] EXIT alleqxx([_4,_5,_5,_7,_5])
 [8:f1:cp0] NEXT
call((unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_5,[_7|_5])))
 [9:f1:cp1] EXIT
call((unify_with_occurs_check(_4,s(_5)),unify_with_occurs_check(_5,[_7|_5])))
 [10:f1:cp1] CALL unify_with_occurs_check(_4,s(_5))
 [11:f1:cp1] EXIT unify_with_occurs_check(s(_5),s(_5))
 [12:f1:cp1] CALL unify_with_occurs_check(_5,[_7|_5])
^C

**Comment by infradig** [comment]
If you do it like this it works...

run :-
      A = unify_with_occurs_check(_,s(_)),
      B = unify_with_occurs_check(_,[_|_]),
EsG = (A,B),
term_variables(EsG,Vs),
alleqxx(Vs),
      call(EsG).
alleqxx([_,X,X,_,X]).

It seems to go into a deref loop.

**Comment by UWN** [comment]
(Yes, I did had to put a lot of time to locate this error. After all, a simple trace did (and copying the text into a new query) did not help.
