### ISSUE TITLE
non-linear slowdown in A* search

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#544]
Now this here was a surprise. I am testing some A* search,
here is what SWI-Prolog gives:
```
?- start(X), time(astar(X, [], [], [], L)), length(L, N).
% 13,959,315 inferences, 0.938 CPU in 0.932 seconds (101% CPU, 14889936 Lips)
X = [6, 1, 3, 4, -1, 5, 7, 2, 0],
L = [left, left, up, right, right, down, left, left, up|...],
N = 26 .

?- X = [-1, 7, 6, 5, 4, 3, 2, 1, 0], time(astar(X, [], [], [], L)), length(L, N).
% 231,210,078 inferences, 15.844 CPU in 15.843 seconds (100% CPU, 14593141 Lips)
X = [-1, 7, 6, 5, 4, 3, 2, 1, 0],
L = [up, left, left, down, right, up, right, down, left|...],
N = 30 .
```
If I measure Trealla Prolog I see a non-linear slow down.
The first example is ca. 5-times slower. But the second  example
is ca. 10-times slower. 

  | Trealla |  
--|--:|--:
slago | 5221 | 560%
own | 157267 | 993%

Any idea how this happens? Some built-in like length/2 or
member/2 or append/3 that gets dominant? Or garbage 
collection which chokes on large lists?

Source code:

[puzzle.p.log](https://github.com/trealla-prolog/trealla/files/15438654/puzzle.p.log)

**Comment by infradig** [comment]
From the multi-gigabytes of memory being consumed i'd say that's a likely culprit.

**Comment by infradig** [comment]
Btw, you can use memberchk/2 here instead of member/2 for a speed boost.

**Comment by Jean-Luc-Picard-2021** [comment]
It runs fine with1 GB in SWI-Prolog:
```
?- current_prolog_flag(stack_limit, X).
X = 1073741824.
```
The Prolog code just creates a new state, but the old state
can practically immediately be reclaimed. But a garbage
collector might delay the reclamation a little bit.

I am currently testing variants of puzzle.p that use keysort/2
and/or library(heaps). I am testing across Prolog systems.
Have the feeling the non-linearity goes away with

generational garbage collection.

**Comment by infradig** [comment]
Yes, i know. I was just talking about Trealla.

**Comment by Jean-Luc-Picard-2021** [comment]
Same non-linearity when using keysort/2. But to some extend 
the same happens also to my Dogelog Player and Scryer Prolog:

  | SWI | Dogelog | Scryer | Trealla
-- | -- | -- | -- | --
slago | 719 | 1889 | 2689 | 4401
reverse | 13375 | 56973 | 72346 | 143648

**Comment by Jean-Luc-Picard-2021** [comment]
More investigation shows that the Prolog specific garbage
collection is only the icing on the cake. Testing shows that
I have often gc = 0ms, means the Prolog specific garbage

collection is even not triggered in my Prolog system. Not all
intermediate variables need the Prolog specific garbage
collection, some intermediate variables which get into

the register file in my Prolog system can be directly carbage 
collection by the native host system. So the non-lineary has 
something to do with the allocation speed and garbage collection

of the host system in my case. Still not 100% sure whats going.
For library(heaps) I have again little bit lower non-linearity than
the non-SWI-Prolog systems and its again highest for Trealla Prolog:

![image](https://github.com/trealla-prolog/trealla/assets/95891213/61b3ca4b-cc69-44a3-9a5f-abb83e32693f)

But maybe its wrong to even look into the issue. Since
it might be the case that the slago example is simply
a fast outlier for some reasons in SWI-Prolog?

**Comment by infradig** [comment]
It seems *insert/4* is the bottleneck here:

```
% insert(+Agenda, +Key, +Value, -Agenda)
insert([], K, V, [K-V]).
insert([J-W|L], K, V, [K-V,J-W|L]) :- K @=< J, !.
insert([P|L], K, V, [P|R]) :-
   insert(L, K, V, R).
```

as it's not TCO without some smarts, which obviously SWI has.

**Comment by Jean-Luc-Picard-2021** [comment]
Some say its TCO (Tail Call Optimization), usually identified
as a recursive call into the same predicate again, other call it 
LCO (Last Call Optimization), need not be the same predicate.

I think SWI-Prolog has specialized on TCO. But some Prolog
systems simply do something for LCO. LCO is basically the idea of
the "depart" instruction in this paper:

![image](https://github.com/trealla-prolog/trealla/assets/95891213/65699cd2-250c-4340-9099-627003723a74)

https://www.softwarepreservation.org/projects/prolog/lisbon/lpw83/p74-Bowen.pdf

I wasn't able to do LCO properly in formerly Jekejeke Prolog,
since I had the idea of maintaining a call stack. In Dogelog Player 
there is no more call stack, so LCO is better, slightly behind TCO:


  | SWI 9.3.8 | Doge 1.2.1 | Scryer 0.9.4 | TPL 2.53.50
--|--:|--:|--:|--:
slago | 934 | 2686 | 3383 | 4277
own | 15550 | 50444 | 66264 | 123535
  |   |   |   |  
  | SWI 9.3.8 | Doge 1.2.1 | Scryer 0.9.4 | TPL 2.53.50
slago | 100% | 288% | 362% | 458%
own | 100% | 324% | 426% | 794%
difference |   | 37% | 64% | 337%


I was redoing the benchmark to keep up with various changes.
As can be seen, Scryer Prolog has only a minor non-linearity 
problem, compared to SWI-Prolog. Since the "depart" trick

already existed in WAM, and Scryer Prolog is WAM, I guess 
they get it from there? Not sure.
