### ISSUE TITLE
_Vars are not printed

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#546]
v2.52.21
```
?- _X=0,Y=1.
   Y = 1. % _X cannot be displayed?
?- 
```

**Comment by infradig** [comment]
It's possible toplevel.c ignores vars with leading underscore.

**Comment by flexoron** [comment]
Oh, OK then.

**Comment by infradig** [comment]
I don't know whether it should do that though.

**Comment by flexoron** [comment]
It's just a bit confusing because it looks like _  = _X
?- _ = 0,  _X = 0.
   true.
?-
