### ISSUE TITLE
matrix: mat_lup_det/2 segfault

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#558]
v2.53.7-161-g7fbf
```
?- mat_create(M1,1,1,[]),mat_set(M1,0,0,4),mat_lup_det(M1,D),mat_list(M1,L1),mat_close(M1).
   M1 = '<$matrix>'(4), D = 4.0, L1 = [0:0:4.0].  % expected

?- mat_create(M1,1,1,[]),mat_set(M1,1,1,4),mat_list(M1,L1),mat_close(M1).
   M1 = '<$matrix>'(4), L1 = [0:0:0.0].  % unexpected, false? perhaps error out of range.

?- mat_create(M1,1,1,[]),mat_set(M1,1,1,4),mat_lup_det(M1,D),mat_list(M1,L1),mat_close(M1).
Cannot LUP_SOLVE matrix degenerate
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
Thanks, bounds check error left from when I switched from 1-based to 0-based indexing.

I don't know if this is worth your time, as 'matrix' may not make the cut. I think 'library(gsl)' will be the way to go. I was not aware of it when I started this. FFI has an overhead but complex linear algebra add-on routines can be written as C builtins.

**Comment by flexoron** [comment]
Sounds like a sagacious decision. So be it, gsl is well documented.

v2.53.7-162-g57bf
```
?- mat_create(M1,1,1,[]), mat_lup_det(M1,D), mat_close(M1).
Cannot LUP_SOLVE matrix degenerate
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
Also, some user-friendly wrappers around reading/writing/listing will be needed.

**Comment by flexoron** [comment]
Apropos reading/writing. Trying to read from a named pipe:

$ mkfifo /tmp/treafo

%%% test_matrix_det_fifo.pl example %%%
: 
main :-
	open('/tmp/treafo', read, S),
	mat_read(S, _, [alias(foo1)]),
: 
%%%

$ cat test_matrix_det.mat > /tmp/treafo &
$ tpl test_matrix_det_fifo.pl
1.0  % Should print 34637561460.0?
?-
