### ISSUE TITLE
Shouldn't tell(out),listing. output to file and not terminal?

### ISSUE THREAD

**Issue by LexCutch** [trealla-prolog/trealla#56]
I am probably doing something wrong. 
How do I save listing to a file instead of displaying it to terminal?

**Comment by flexoron** [comment]
```
Excuse me, Sire.
There is nothing worth desiring saved.
$ ./tpl
?- listing.
   true.
?-
```

**Comment by flexoron** [comment]
lol...why not...where does it come from?

**Comment by infradig** [comment]
Where does what come from? Try asserting something...

**Comment by infradig** [comment]
Or try

?- dcgs:listing.
