### ISSUE TITLE
Loading nonexistent shared lib should be an error

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#560]
This is an info concerning Linux/Fedora(and maybe other distros)

Now as before Fedora 40 installs gsl 2.7.1:
$ tpl
?- use_module(library(gsl)).
true.
?- gsl_matrix_calloc(10,10,M).
false.
?-

Workaround
Remove gsl 2.7.1 from the system.
Download src and compile/install  gsl 2.8:
$ tpl
?- use_module(library(gsl)).
true.
?- gsl_matrix_calloc(10,10,M).
M = 54232512.
?- 

**********************
Edit
Revision: System lib not loaded and not reported (see below).
Side-effect: gsl upgraded to the latest stable version.

**Comment by infradig** [comment]
You could also use _alloc followed by _set_zero on failure of _calloc

**Comment by flexoron** [comment]
To find the problem I changed library/gsl.pl

:- use_foreign_module('libgsllll.so', [ ... % this lib does not exist

but

$ make clean
$ make
$ tpl
?- use_module(library(gsl)).
   true.       % 'libgsllll.so' does not exist, it might be useful to report this instead of hmm 'true' ?
?- gsl_matrix_calloc(10,10,M).
   false.
?-

**Comment by infradig** [comment]
Interesting: Ubuntu 2404 is libgsl 2.7.1 as well but *calloc is included.
```
$ sudo apt search libgsl
Sorting... Done
Full Text Search... Done
libgsl-dbg/noble,now 2.7.1+dfsg-6ubuntu2 amd64 [installed]
  GNU Scientific Library (GSL) -- debug symbols package

libgsl-dev/noble,now 2.7.1+dfsg-6ubuntu2 amd64 [installed]
  GNU Scientific Library (GSL) -- development package

libgsl27/noble,now 2.7.1+dfsg-6ubuntu2 amd64 [installed]
  GNU Scientific Library (GSL) -- library package

libgslcblas0/noble,now 2.7.1+dfsg-6ubuntu2 amd64 [installed]
  GNU Scientific Library (GSL) -- blas library package

libocamlgsl-ocaml/noble 1.25.0-1 amd64
  GNU scientific library for OCaml

libocamlgsl-ocaml-dev/noble 1.25.0-1 amd64
  GNU scientific library for OCaml
```

**Comment by flexoron** [comment]
Fixed with v2.53.17

?- use_module(library(gsl)).
Error: foreign module creation failed: libgsllll.so, gsl
   false.
?-gsl_matrix_calloc(10,10,M).
   false.
?
I don't think it's a *calloc problem.

For some obscure reason the system-installed  /usr/lib64/libgsl.so was not found.
After compiling and installing here: /usr/local/lib/libgsl.so, Trealla's dlopen() handles it.

**Comment by flexoron** [comment]
callocs are available
$ strings /lib64/libgsl.so.27.0.0 | grep _calloc |wc -l
51

It is a problem with /lib64/libgsl.so.27.0.0 provided by Fedora
```
$ export LD_DEBUG=libs % The name says it all
$ tpl
?- use_module(library(gsl)).

      5845:	find library=libgsl.so [0]; searching
      5845:	 search cache=/etc/ld.so.cache
      5845:	  trying file=/lib64/libgsl.so
      5845:	
      5845:	/lib64/libgsl.so: error: symbol lookup error: undefined symbol: cblas_ctrmv (fatal)

Error: foreign module creation failed: libgsl.so, gsl
?-
```
Fedora solution: see below.

**Comment by infradig** [comment]
Ok, thanks

**Comment by flexoron** [comment]
I guess, I found the real problem:

v2.53.26
```
$ tpl samples/test_matrix_det.pl
?- main.
tpl: symbol lookup error: /usr/local/lib/libgsl.so: undefined symbol: cblas_idamax
?-
```
Solution: Load libgslcblas.so, too
```
$ vi library/gsl.pl
: 
:- use_foreign_module('libgslcblas.so', []).
:- use_foreign_module('libgsl.so', [
: 
$ make
$ tpl samples/test_matrix_det.pl
?- main.
34637561460.0
```
I don't know whether other Linux (libgsl) distros need to use/load libgslcblas.so as well.

**Comment by infradig** [comment]
I see, I think CBLAS usage depends on how libgsl is built.

**Comment by infradig** [comment]
I'll look into it tomorrow.

**Comment by flexoron** [comment]
Result of countercheck using a 'housetrained' Fedora 40 Server machine:

$ dnf info gsl.x86_64
Installed Packages
Name         : gsl
Version      : 2.7.1

On Fedora both libs must be loaded (gsl.pl).

:- use_foreign_module('libgslcblas.so', []).
:- use_foreign_module('libgsl.so', [ ... ]).

$ ./tpl samples/test_matrix_det.pl
?- main.
34637561460.0
   true.
