### ISSUE TITLE
Superflous parenthesis for fy mode

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#565]
Was using:
```
?- op( 600, fy, !).

?- current_op(X,Y,:).
   X = 600, Y = xfy
```
Just compare:
```
/* SWI-Prolog */
?- X = ![Y]:a.
X = ![Y]:a.

/* Trealla Prolog */
?- X = ![Y]:a.
   X = ! ([Y]:a).
```
Its from [TPTP syntax](https://tptp.org/TPTP/SyntaxBNF.html). I think SWI-Prolog is
correct in that it doesn't use parenthesis.

**Comment by Jean-Luc-Picard-2021** [comment]
Scryer Prolog doesn't put parenthesis during ouput, but it has 
other issues with the bang (!) when it has a prefix definition:
```
/* Scryer Prolog */
?- X = ![Y]:a.
   X = ![Y]:a.

?- X = (!, b).
   error(syntax_error(incomplete_reduction),read_term/3:1).
```
Trealla does it fine:
```
/* Trealla Prolog */
?- X = (!, b).
   X = ((!),b).
```

**Comment by infradig** [comment]
Scryer is correct here in rejecting X = (!, b) & other Prologs are too lax.

EDIT: actually, i'll retract that statement.

**Comment by Jean-Luc-Picard-2021** [comment]
But Scryer Prolog is dead. Not a single code commit for 1 month.
