### ISSUE TITLE
silent give up while testing deep taxonomy via rdfs:subClassOf

### ISSUE THREAD

**Issue by josd** [trealla-prolog/trealla#565]
For the files at https://github.com/josd/josd.github.io/tree/master/temp the following happens:
```
$ tpl -g run,halt dt-10.pl
true
$ tpl -g run,halt dt-100.pl
true
$ tpl -g run,halt dt-1000.pl
true
$ tpl -g run,halt dt-10000.pl
?-
$ tpl -g run,halt dt-100000.pl
?-
```
So for a depth deeper than 1000 the rdfs:subClassOf triples are not loading or so.

We would expect the same as
```
$ swipl -g run,halt dt-10.pl
true
$ swipl -g run,halt dt-100.pl
true
$ swipl -g run,halt dt-1000.pl
true
$ swipl -g run,halt dt-10000.pl
true
$ swipl -g run,halt dt-100000.pl
true
```

**Comment by UWN** [comment]
Could be the same problem as #538

**Comment by josd** [comment]
Maybe it is first argument indexing related?
The following works fine:
```
$ tpl dt-1000.pl
?- 'http://www.w3.org/2000/01/rdf-schema#subClassOf'(X,'https://josd.github.io/ns#N1000').
   X = 'https://josd.github.io/ns#N999'.
?- 'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N999',Y).
   Y = 'https://josd.github.io/ns#N1000'
;  Y = 'https://josd.github.io/ns#I1000'
;  Y = 'https://josd.github.io/ns#J1000'.
?-
```
but the following first goal silently fails:
```
$ tpl dt-10000.pl
?- 'http://www.w3.org/2000/01/rdf-schema#subClassOf'(X,'https://josd.github.io/ns#N10000').
   false.
?- 'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N9999',Y).
   Y = 'https://josd.github.io/ns#N10000'
;  Y = 'https://josd.github.io/ns#I10000'
;  Y = 'https://josd.github.io/ns#J10000'.
?-
```

**Comment by infradig** [comment]
Yes, it's indexing related.

**Comment by infradig** [comment]
I have pushed a fix, It's a temporary and slow solution to the problem. It
needs more thinking about. No reason it shouldn't be as fast as SWI on this.

**Comment by infradig** [comment]
Yes, see my comment.

**Comment by josd** [comment]
I saw but was't believing it would be that much slower ;-)

**Comment by infradig** [comment]
The cause of the slowness is having a variable in the arg1 position of the
search term.

**Comment by josd** [comment]
Right, we had similar issues a year ago or so.
The thing with `rdf:type` is that in some use cases the `element` (arg 1) can be a variable and in some other use cases the `class` (arg 2) can be a variable.

**Comment by josd** [comment]
Could first instantiated argument indexing help?

**Comment by josd** [comment]
Take your time, here it is time to sleep ;-)

**Comment by josd** [comment]
This issue seems to reappear with https://raw.githubusercontent.com/josd/josd.github.io/master/temp/edt.pl
```
$ tpl -g run,halt edt.pl
?-
```
whereas we expect
```
$ scryer-prolog -g run,halt edt.pl
true
```

**Comment by infradig** [comment]
Yes, not getting far...

~/trealla (devel) $ tpl -t -g run,halt edt.pl
 [0:f1:cp0] EXIT run
 [1:f1:cp0] FAIL '
http://www.w3.org/1999/02/22-rdf-syntax-ns#type'('http://example.org/ns#i10000
','http://example.org/ns#N10000')
?-

**Comment by josd** [comment]
Yes, also tried that ;-)

**Comment by infradig** [comment]
Although, it seems to work if you take out the 'dynamic' directive...

~/trealla (devel) $ time swipl -g run,halt edt.pl
true

real 0m1.246s
user 0m1.233s
sys 0m0.013s
~/trealla (devel) $ time tpl -g run,halt edt.pl
true

real 0m24.836s
user 0m24.806s
sys 0m0.025s

**Comment by josd** [comment]
as well as `-O0`

**Comment by josd** [comment]
Well, a week ago or so I found that the speed for a similar case was much improved when adding that directive

**Comment by josd** [comment]
it felt as if indexing was switched on while adding that directive

**Comment by josd** [comment]
thanks for looking at it and talk to you later

**Comment by infradig** [comment]
It's triggering something to fail the index lookup. I don't know what it is
at the  moment. Very odd.

**Comment by infradig** [comment]
From 27mins for 10K down to 0.27secs! The power of 2nd arg indexing.

~/trealla (devel) $ time tpl -g run,halt dt-10000.pl
true

real	0m0.271s
user	0m0.245s
sys	0m0.025s

~/trealla (devel) $ time tpl -g run,halt dt-100000.pl
true

real	0m2.554s
user	0m2.481s
sys	0m0.073s
~/trealla (devel) $

**Comment by josd** [comment]
Very well, and is indeed impressive!

In the mean time we worked on an "extended deep taxonomy" and for a [depth of 1000](https://raw.githubusercontent.com/josd/josd.github.io/master/temp/edt-1000.pl) it works nice and fast
```
$ time tpl -g run,halt edt-1000.pl
'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'('http://example.org/ns#i1000','http://example.org/ns#N1000').

real    0m0.142s
user    0m0.141s
sys     0m0.000s
```
but for a [depth of 10000](https://raw.githubusercontent.com/josd/josd.github.io/master/temp/edt-10000.pl) it again silently fails
```
$ time tpl -g run,halt edt-10000.pl
?- 
```

**Comment by josd** [comment]
Waw, now it is running fine and really fast
```
$ time tpl -g run,halt ~/github.com/josd/josd.github.io/temp/edt-100000.pl
'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'('http://example.org/ns#i100000','http://example.org/ns#N100000').

real    0m2.993s
user    0m2.902s
sys     0m0.090s
```
and is even faster than
```
$ time swipl -g run,halt ~/github.com/josd/josd.github.io/temp/edt-100000.pl
'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'('http://example.org/ns#i100000','http://example.org/ns#N100000').

real    0m7.539s
user    0m7.498s
sys     0m0.040s
```
Thank you so much and https://github.com/josd/handshake is now running with Trealla!
