### ISSUE TITLE
univ =.. string as list not processed

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#567]
```
tpl
?- L = "fa", S =.. L.
   error(type_error(list,"fa"),(=..)/2).

scryer -f
?- L = "fa", S =.. L.
   L = "fa", S = f(a).
```

**Comment by infradig** [comment]
Too easy.

**Comment by flexoron** [comment]
I guess Scryer does it wrong here?
```
scryer -f
?- L = "f   a", S = f(' ',a).
   L = "f   a", S = f(' ',a).

tpl
?- L = "f   a", S =.. L.
   L = "f   a", S = f(' ',' ',' ',a).
```

**Comment by flexoron** [comment]
Something not so easy:
```
?- L = [f,[_|L]], X =.. L.
   L = [f,[_A,f,[_A,f,[_A,f...]]]]], X = f([_A,[=('L',L),=('_',_),=('X',X)]|dummy]).
```

**Comment by infradig** [comment]
I think you made a typo above, scryer is correct...

~/trealla (devel) $ scryer-prolog -f
?- L = "f   a", S =.. L.
   L = "f   a", S = f(' ',' ',' ',a).

**Comment by flexoron** [comment]
Yes, sorry.
Should I close this issue?
Im unsure how to name this other issue above. Maybe related to #555

**Comment by infradig** [comment]
| $ scryer-prolog -f
| ?- L = [f,[_|L]], X =.. L.
|   L = [f,[_A|L]], X = f([_A,f,...]).

 Scryer is wrong here.

**Comment by infradig** [comment]
The cyclic one needs work in Trealla, so keep it open.

**Comment by infradig** [comment]
Actually, maybe Scryer is not wrong. Just not ideal.

**Comment by infradig** [comment]
Actually, close it. It's really a printing issue now for cyclic terms (i
think).
