### ISSUE TITLE
arg/3 constant treated as variable

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#568]
```
tpl (v1.28.25)
?- functor(F,f,2),arg(1,F,F),arg(2,F,x).
   F = f(_A,_B).
?- functor(F,f,2),arg(1,F,x),arg(2,F,F).
   F = f(_A,_B).

scryer -f
?- functor(F,f,2),arg(1,F,F),arg(2,F,x).
   F = f(F,x).
?- functor(F,f,2),arg(1,F,x),arg(2,F,F).
   F = f(x,F).
```

**Comment by infradig** [comment]
It's there, you just can't see it...

?- functor(F,f,2),arg(1,F,F),arg(2,F,x),F=f(A,Y).
   F = f(_A,_B), A = F, Y = x.

**Comment by flexoron** [comment]
Ah ... good to know how to unpent the caged ... F=f(A,Y) ... many thanks.

**Comment by UWN** [comment]
But, that **is** an error of the top level...

**Comment by infradig** [comment]
It's just to do with printing cyclic terms. I'll address it when I can.
