### ISSUE TITLE
getting answers that are just a variable

### ISSUE THREAD

**Issue by josd** [trealla-prolog/trealla#571]
https://github.com/josd/cigol/blob/main/cases/graph.pl is giving
```
$ tpl -g run,halt graph.pl
'https://josd.github.io/cigol#path'('http://example.org/#angers','http://example.org/#nantes').
_0.
_0.
_0.
```
instead of
```
$ scryer-prolog -g run,halt graph.pl
'https://josd.github.io/cigol#path'('http://example.org/#angers','http://example.org/#nantes').
'https://josd.github.io/cigol#path'('http://example.org/#paris','http://example.org/#nantes').
'https://josd.github.io/cigol#path'('http://example.org/#chartres','http://example.org/#nantes').
'https://josd.github.io/cigol#path'('http://example.org/#lemans','http://example.org/#nantes').
```

**Comment by josd** [comment]
this is with
```
$ tpl -v
Trealla Prolog (c) Infradig 2020-2023, v2.54.6
```

**Comment by josd** [comment]
(maybe also update to 2024 :))

**Comment by infradig** [comment]
A problem with TCO here:
```
'https://josd.github.io/cigol#path'(A,C) :-
    'https://josd.github.io/cigol#oneway'(A,B),
    'https://josd.github.io/cigol#path'(B,C).
```

for now either -O0 or change to:
```
'https://josd.github.io/cigol#path'(A,C) :-
    'https://josd.github.io/cigol#oneway'(A,B),
    'https://josd.github.io/cigol#path'(B,C), true.
```
I'll look into it further soon.

**Comment by josd** [comment]
Thx and with the added `true` now we get https://github.com/josd/cigol/blob/main/cases/output/graph-trealla.pl

**Comment by josd** [comment]
It now works fine with the fix https://github.com/trealla-prolog/trealla/commit/3763b0ce2a91ed8ca811fc8c66ef0b862096590d
Thx

**Comment by josd** [comment]
The issue is back using `v2.55.4`, this time for the https://github.com/josd/cigol/blob/main/cases/control.pl case where we get https://github.com/josd/cigol/commit/12f93953291a8e5119463704e27950dccfce785d

**Comment by josd** [comment]
Thanks for the fix and now it works fine 👍

**Comment by josd** [comment]
the cases in this issue are now moved to https://github.com/eyereasoner/see/tree/main/cases

**Comment by josd** [comment]
We get it again with https://github.com/eyereasoner/color/blob/main/examples/fourcolor.pl

To reproduce it, you can
```
git clone https://github.com/eyereasoner/color
cd color
./color examples/fourcolor.pl
```
and it will give
```
% running examples/fourcolor.pl
B => true.
C => true.
D => true.
E => true.
F => true.
G => true.
H => true.
I => true.
...
```
When using some other IRI's like in https://github.com/eyereasoner/color/blob/16e313cb787c039627e5682a6f3fd68ef1f5a07f/examples/fourcolor.pl it works https://github.com/eyereasoner/color/blob/16e313cb787c039627e5682a6f3fd68ef1f5a07f/result.pl#L48-L96
