### ISSUE TITLE
[] not an atom that can be used as an operator

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#572]
I am expecting this to work:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.55.2
$ ./tpl
?- [user].
:- op( 600, fy, []).    % necessity
```
But I get this error:
```
?- X = [] p.
Error: syntax error, near 'p', operator expected, user:1
```
The parsing is a little tricky but relatively straight forward doable.

**Comment by Jean-Luc-Picard-2021** [comment]
Amazing Ciao Prolog can do it correctly.

Even if the mode “fy” is correctly honored, it might nevertheless
be a challenge. Since for example this here works also,  note
the space inside the empty list atom:
```
/* Ciao Prolog 1.23.0 */
?- op( 100, fy, []).
yes

?- X = [ ] p.
X = []p ?
```
Took me a while to figure out how to do it. But its rather
straight forward to do. You find it in the source code of Novacore.

**Comment by Jean-Luc-Picard-2021** [comment]
SWI-Prolog did just fix, so that it works again! But
I didn't test it yet. Also don't know what Scryer Prolog does.

But Scryer Prolog is dead, so possibly no use in testing it.

**Comment by infradig** [comment]
There is a specific test to exclude it which I assume is there for a reason.

**Comment by infradig** [comment]
SWI also has non standard lists so it can do what it likes.

**Comment by infradig** [comment]
Trealla handles it fine if I disable that test (bif_predicates.c line 2754), but the question remains why exactly is it there.

**Comment by infradig** [comment]
I think now it can be an operator, just not an infix operator, will look at changing.

**Comment by UWN** [comment]
Please note that [Cor.2](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#C2) explicitly excluded `[]` as an operator. It makes syntax much more brittle. Jan Burse (here known as Jean-Luc Picard-2021) does know that.

**Comment by UWN** [comment]
Also note that `op( 100, fy, []).` is highly ambiguous, because the third argument can be a list too.

**Comment by infradig** [comment]
> Please note that [Cor.2](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#C2) explicitly excluded `[]` as an operator. 

Ok thanks, I thought there was a reason it was explicitly excluded.

**Comment by UWN** [comment]
Just for the record an example of the brittleness of having `[]` an operator.

`[]-X.` is intended to mean `-([],X).`, but with `[]` a fitting prefix, this would change to `[](-(X)).`
