### ISSUE TITLE
Does Trealla Prolog detect cyclic lists?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#579]
Sometimes:
```
?- X=[a,b|X], length(X, N).
   throw(error(resource_error(finite_memory),length/2)).
```
But not here:
```
?- VN = ['U'=X,'V'=Y | VN], write_term(f(X,g(Y,X),Y), [variable_names(VN)]), nl.
^C
```
Also Ctrl-C doesn't work in the above example.

**Comment by Jean-Luc-Picard-2021** [comment]
Scryer Prolog seems to detect the cyclic list, but their
error messages doesn't make any sense:
```
?- VN = ['U'=X,'V'=Y | VN], write_term(f(X,g(Y,X),Y), [variable_names(VN)]), nl.
   error(domain_error(write_option,variable_names(['U'=_79764,'V'=_79769|...])),write_term/3).
```

**Comment by infradig** [comment]
The error message makes perfect sense, it's not a valid list.

**Comment by Jean-Luc-Picard-2021** [comment]
I am not so sure, the test case is not yet listed here:

https://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#73

So you are still free to choose an error term? I was rather
expecting that length/2 and write_term/2 have the same
error term for cyclic list arguments.

Didn't test Trella Prolog update yet.

**Comment by Jean-Luc-Picard-2021** [comment]
So this can be closed?
