### ISSUE TITLE
Tail recursion and garbage collection

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#580]
Strange it can allocate one run:
```
$ ulimit -m 2000000
$ ulimit -v 2000000
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.55.18
$ ./tpl
?- ['bomb.p'].
true
?- garbage(12,_).
   true.
```
But not repeatedly:
```
?- foo.
   throw(error(resource_error(memory),app/3)).
```
SWI-Prolog has no problems with the test case,
it somehow can reclaim the annonymous variable term.

Source code:

[bomb.p.log](https://github.com/user-attachments/files/16573200/bomb.p.log)

**Comment by Jean-Luc-Picard-2021** [comment]
Disclaimer: Maybe the ulimit of 2 Gigabyte is too tight,
I am currently experimenting on my side a little bit. It 
depends on how much memory the Prolog terms need.

**Comment by infradig** [comment]
See also #305

**Comment by Jean-Luc-Picard-2021** [comment]
#305 tests possible something different. Between does
not produce a lot of objects during tail recursion,
it only decrements one integer. The between example

might be ok, wherea this example here might be neverthelesss
not ok, especially since unlike in the between example,
this example has also an "intermediate" variables.

The "intermediate" variable is "_":
```
foo :- garbage(12,_), foo.
```
The between example has no such variable. All variables
in the between example are either in the head or in the tail 
recursice call,  making it a more trivial example than this here.

**Comment by Jean-Luc-Picard-2021** [comment]
Here some results on a Lenovo Yoga with
Windows 11 for xbetween:
```
/* SWI-Prolog 9.3.11 */
?- time((xbetween1(1,1000000000,_),fail)).
% 2,000,000,002 inferences, 72.688 CPU in 72.790 seconds (100% CPU, 27515047 Lips)
false.

/* Dogelog Player 1.2.3, WSL2, JDK 21 */
?- time((xbetween1(1,1000000000,_),fail)).
% Time 160451 ms, GC 4 ms, Lips 24929729, Wall 24/09/2024 17:01
fail.
```
Dang, still ca. 2x times slower. But no
memory problem at all. Prolog specific GC is
very low, only 4 ms, because the Prolog system

doesn't allocate some logical variables for
this example. The extended neck here is semi-det
builtins, that are already evaluated only using

native stack and no Prolog stack, when the
clause is instantiated:
```
xbetween1(L, U, N) :- L < U, M is L+1, xbetween1(M, U, N).
                      \---- neck ----/
```
So overhead in Dogelog compared to SWI-Prolog
is among the fact that it abandons and creates a choice
point in every backtracking. Haven't found a way

yet to elegantly avoid this unecessary effort.

**Comment by infradig** [comment]
xbetween is now TCO in Trealla.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, some progress I guess? Testing on the same machine again,
where I already tested SWI-Prolog and Dogelog Player in this thread:
```
/*  Trealla Prolog 2.56.35 */
?- time((xbetween(1,1000000000,_),fail)).
% Time elapsed 265.081s, 5000000005 Inferences, 18.862 MLips
   false.
```
