### ISSUE TITLE
must_be/2 is slow

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#584]
Hi, I just tried:
```
% numbervars2(+Term, +Integer, -Integer)
numbervars2(T, N, M) :-
   term_variables(T, L),
   numbervars_list(L, N, M).

% numbervars_list(+List, +Integer, -Integer)
numbervars_list(['$VAR'(N)|L], N, M) :-
   H is N+1,
   numbervars_list(L, H, M).
numbervars_list([], N, N).

?- time((between(1,1000000,_), numbervars(f(X,g(Y,X),Y), 0, M), fail; true)).
Time elapsed 8.92 secs
   true.
?- time((between(1,1000000,_), numbervars2(f(X,g(Y,X),Y), 0, M), fail; true)).
Time elapsed 1.39 secs
   true.
```
It seems that the must_be/2 eats a lot of time, its even not the catch/3
inside the numbervars/3 implementation. One can try:
```
?- time((between(1,1000000,_), numbervars_(f(X,g(Y,X),Y), 0, M), fail; true)).
Time elapsed 7.76 secs
   true.
```

**Comment by Jean-Luc-Picard-2021** [comment]
Somehow I have the feeling must_be/2 is even not necessary,
since numbervars_list/3 calls `H is N+1` which would anyway catch
a non-number, but it would also allow a float, so there is a little dilemma.

**Comment by infradig** [comment]
Yes, must_be/2 & can_be/2 from error.pl are slow. I will change to use my
own implementations in the builtins.

**Comment by Jean-Luc-Picard-2021** [comment]
I think must_be/2 can be made faster, it has must_be_(type, Type),
but the type is known. Wouldn't it be valid to call must_be_/2 directly
in trusted code?

Not sure what the way out is...
