### ISSUE TITLE
Confused existence

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#584]
v2.55.32
```
?- 'V'.
   throw(error(existence_error(procedure,'V'/0),'V'/0)).
?- listing.
   true.

?- [user].
v:V.
Warning: singleton: V, near user:1
   true.
?- listing.
A.        % Fake
   true.

?- module(v).
Info: created module 'v'
   true.
?- listing.
   true.

?- [user].
v:V.
Warning: singleton: V, near user:1
   true.
?- listing.
A.        % Fake
   true.
?- 'A'.
   throw(error(existence_error(procedure,'A'/0),'A'/0)). % Listing lists something like 'A'.
?- 'V'.
   true.  % ok, listed fake = 'V'. And I thought it is a singleton?

?- m:'V'.
   throw(error(existence_error(module,m),(:)/2)).  % true
?- v:'V'.
   throw(error(existence_error(procedure,'\x3\D$5b'/0),'\x3\D$5b'/0)). % Ignis fatuus
?- 
```

**Comment by flexoron** [comment]
v2.55.33
```
$ tpl

?- module(v).
Info: created module 'v'
   true.

?- [user]. v:v. end_of_file.
   true.
?- listing.
v.
   true.

?- v:v.
   true.

?- [user]. v:'V'. end_of_file.
   true.
?- listing.
v.
'V'.
   true.

?- v:v.
   true.
?- v:'V'.
   throw(error(existence_error(procedure,''/0),''/0)). % unexpected

?- [user]. v:''. end_of_file.
   true.
?- listing.
v.
'V'.
''.
   true.

?- v:v.
   true.
?- v:'V'.
   throw(error(existence_error(procedure,''/0),''/0)). % unexpected
?- v:''.
   throw(error(existence_error(procedure,''/0),''/0)). % unexpected
?- 
```

**Comment by infradig** [comment]
So:

~/trealla (devel) $ tpl
?- [user]. v. 'V'. end_of_file.
   true.
?- listing.
v.
'V'.
   true.
?- v.
   true.
?- 'V'.
   true.
?-
~/trealla (devel) $ tpl
?- module(v).
Info: created module 'v'
   true.
?- [user]. v:v. v:'V'. end_of_file.
   true.
?- listing.
v.
'V'.
   true.
?- v.
   true.
?- 'V'.
   throw(error(existence_error(procedure,'V'/0),'V'/0)).
?-

**Comment by infradig** [comment]
Quoted predicate names in modules, hmmm:

~/trealla (devel) $ tpl
?- module(v).
Info: created module 'v'
   true.
?- [user]. v:'w'. end_of_file.
   true.
?- listing.
w.
   true.
?- w.
   throw(error(existence_error(procedure,w/0),w/0)).
?- 'w'.
   throw(error(existence_error(procedure,w/0),w/0)).
?-

**Comment by flexoron** [comment]
```
?- [user]. ''. end_of_file.
   true.
?- listing.
''.
   true.
?- ''.  % Interposed question: What is the name of this fact?
   true.
```

**Comment by infradig** [comment]
It works if it has arity:

~/trealla (devel) $ tpl
?- module(v).
Info: created module 'v'
   true.
?- [user]. v:'w'(1). end_of_file.
   true.
?- listing.
w(1).
   true.
?- w(1).
   true.
?- 'w'(1).
   true.
?-

**Comment by infradig** [comment]
Narrow down more:

~/trealla (devel) $ tpl
?- [user]. user:u. user:'w'. end_of_file.
   true.
?- u.
   true.
?- w.
   throw(error(existence_error(procedure,w/0),w/0)).
?-

**Comment by flexoron** [comment]
v2.55.35
```
?- module(v).
Info: created module 'v'
   true.
?- [user]. v:'V'. end_of_file.
   true.
?- 'V'.
   true.
?- v:'V'.
   throw(error(existence_error(procedure,' O>V'/0),' O>V'/0)).
?- 
```
