### ISSUE TITLE
DCG: (-->)/2 unprotected

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#590]
Sames as https://github.com/mthom/scryer-prolog/issues/1508 So the best seems to be to also export `(-->)/2` just to avoid these unexpected results.

```
?- asserta((a-->b)).
   true, unexpected.
?- asserta((a-->b)).
   permission_error(modify,static_procedure,user:(-->)/2). % this is expected
?- (LHS-->RHS).
   LHS = a, RHS = b, unexpected.
?- (LHS-->RHS).
   permission_error(access, private_procedure, user:(-->)/2). % this is expected

**Comment by UWN** [comment]
Now:

```
?- asserta((a-->b)).
   error(permission_error(modify_static_procedure,(a-->b)),asserta/1), unexpected. % because of `(a-->b)` which should be a predicate indicator.
?- (LHS-->RHS).
   false, unexpected.
?- inconnu.
   error(existence_error(procedure,inconnu/0),inconnu/0).
```

**Comment by UWN** [comment]
Now good:

```
?- asserta((a-->b)).
   error(permission_error(modify_static_procedure,(-->)/2),asserta/1).
?- (LHS-->RHS).
   error(existence_error(procedure,(-->)/2),(-->)/2).
```
So there is a slight minor inconsistency here, as there is a permission and an existence error at the same time. But I think we can live with that. The alternative would be a permission error access (as originally proposed) (which has a tiny bit of inconsistency as well, why is this a clause-like access?) or a new kind of permission error, just for this case.

Some minor issue: invisible reverting (as you did it here) disrupts keeping versions up-to-date. Also it hampers reproducibility, should this be of interest some time in the future. Is it such a problem that such a change shows in `git log`?

**Comment by infradig** [comment]
Agreed on the inconsistency.
