### ISSUE TITLE
Parser is too permissive

### ISSUE THREAD

**Issue by notoria** [trealla-prolog/trealla#591]
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2022, v1.30.13
$ ./tpl
?- read_from_chars(";;!.", T).
   T = ((';');=('T',";;!.")). % Expected error.
?-
```

**Comment by UWN** [comment]
There is also an other problem with this case, writing `(';')` is problematic. It should be `(;)` in its stead.

**Comment by notoria** [comment]
```
$ ./tpl --version
Trealla Prolog (c) Infradig 2020-2022, v1.33.2
?- read_from_chars(";;!.", T).
   T = ((';');!).
?- writeq(;), nl.
';'
   true.
?-
```
Only the printing issue remains.

**Comment by UWN** [comment]
Since`;;!.` is non-nonforming syntax, it would be much better to produce a syntax error. These "hand crafted" extensions are only stealing time. Just look at SWI, they still debate such cases. In the very same way as 10 years ago, and much earlier as well.
