### ISSUE TITLE
segmentation fault while running lubm010 benchmark

### ISSUE THREAD

**Issue by josd** [trealla-prolog/trealla#595]
[lubm010.zip](https://github.com/trealla-prolog/trealla/files/8962511/lubm010.zip) contains files to run the [lubm010 benchmark](http://swat.cse.lehigh.edu/projects/lubm/) in prolog and Trealla currently gives a segmentation fault
```
$ time tpl -g "consult('rules.pl'), consult('facts.pl'), run, halt." > result.pl
Segmentation fault

real    0m7.773s
user    0m7.572s
sys     0m0.200s
```
We rather expect
```
$ time swipl -g "consult('rules.pl'), consult('facts.pl'), run, halt." > result.pl

real    0m52.772s
user    1m12.567s
sys     0m2.686s
```
`$ time scryer-prolog -g "consult('rules.pl'), consult('facts.pl'), run, halt." > result.pl` also runs fine but I didn't wait till it finishes as it would probaly take 9 hours.
`$ time taupl -g "consult('rules.pl'), consult('facts.pl'), run, halt." > result.pl` also starts well but would probably take 36 hours.

@doerthe told me that with https://github.com/karmaresearch/vlog and N3 files it took `4.3 sec`.

**Comment by josd** [comment]
Thanks @infradig it now runs fine and indeed takes a while 
```
$ time tpl -g "consult('rules.pl'), consult('facts.pl'), run, halt." > result.pl
real    34m2.529s
user    34m0.683s
sys     0m1.640s
```

**Comment by infradig** [comment]
Not as long as I feared though.

**Comment by infradig** [comment]
It should be a lot faster now, down from 54m on my machine...

~/trealla (devel) $ time tpl -g "run, halt." -f stuff/rules.pl stuff/
facts.pl >/dev/null

real 2m4.629s
user 2m3.616s
sys 0m0.988s

~/trealla (devel) $ time swipl -g "run, halt." -f stuff/rules.pl stuff/
facts.pl >/dev/null

real 1m20.596s
user 1m42.277s
sys 0m1.721s

**Comment by josd** [comment]
That is rocking!
Here the gap is even closer
```
$ time tpl -g "run, halt." -f rules.pl facts.pl >/dev/null

real    1m20.685s
user    1m19.552s
sys     0m1.130s
```
```
$ time swipl -g "run, halt." -f rules.pl facts.pl >/dev/null

real    1m2.208s
user    1m27.836s
sys     0m0.874s
```

**Comment by josd** [comment]
With `Trealla Prolog (c) Infradig 2020-2022, v1.34.11` it is like 5 times slower:
```
$ time tpl -g "run, halt." -f rules.pl facts.pl >/dev/null

real    6m48.989s
user    6m48.076s
sys     0m0.900s
```

**Comment by josd** [comment]
and now ...
```
$ time tpl -g "run, halt." -f rules.pl facts.pl >/dev/null

real    0m6.601s
user    0m6.571s
sys     0m0.030s
```
which is **62 times faster**
Really impressive is that https://github.com/trealla-prolog/trealla/commit/4e80b9607b10ff5a452ecf467f7f33c120bed3c1
🚀🚀

**Comment by infradig** [comment]
That doesn't  seem right. It should be as before. Mine took 2m and does
again now.

**Comment by josd** [comment]
Right, I was running it for https://github.com/josd/retina/tree/master/lubm which is 12 times smaller ;-)
With the original facts.pl we now get
```
$ time tpl -g "run, halt." -f rules.pl facts.pl >/dev/null

real    1m4.148s
user    1m2.965s
sys     0m1.041s
```
which is indeed similar to https://github.com/trealla-prolog/trealla/issues/595#issuecomment-1166479583
