### ISSUE TITLE
nth0/3 faster

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#600]
```
fastnth0(N, Es0, E) :-
   nonvar(N),
   '$skip_max_list'(N, N, Es0,Es),
   !,
   Es = [E|_].
fastnth0(N, Es, E) :-
   nth0(N, Es, E).
```

**Comment by infradig** [comment]
9 millionth entry in 10Mlist, very sexy!

?- numlist(1,10000000,L), time(nth0(9000000,L,E)).
Time elapsed 5.71 secs
   L = [1,2,3,4,5,6,7,8,9,...], E = 9000001.
?- numlist(1,10000000,L), time(fastnth0(9000000,L,E)).
Time elapsed 0.163 secs


   L = [1,2,3,4,5,6,7,8,9,...], E = 9000001.

**Comment by UWN** [comment]
Just because I see it: `0.163 secs` should read `0.163 s`.

**Comment by UWN** [comment]
Very secsy, indeed!

**Comment by flexoron** [comment]
Modest remark: Negative values redoubles
```
?-  numlist(0,10000001,L), time(nth0(10000000,L,E)).
Time elapsed 0.202 s
   L = [0,1,2,3,4,5,6,7,8,...], E = 10000000.

?-  numlist(-10000000,10000001,L), time(nth0(10000000,L,E)).
Time elapsed 0.406 s
   L = [-10000000,-9999999,-9999998,-9999997,-9999996,-9999995,-9999994,-9999993,-9999992,...], E = 0.

?- time(numlist(0,10000001,L)).
Time elapsed 3.57 s
   L = [0,1,2,3,4,5,6,7,8,...].

?- time(numlist(-10000000,10000001,L)).
Time elapsed 7.07 s
   L = [-10000000,-9999999,-9999998,-9999997,-9999996,-9999995,-9999994,-9999993,-9999992,...].
```

**Comment by infradig** [comment]
Flex, the time doubles because the list length doubles, does it not?

**Comment by flexoron** [comment]
```
Yes it does.

I was thinking of N = Summand in numlist(0,N,L).

So I get numlists this way:

?- numlist(5,-5,L).
   L = [5,4,3,2,1,0].

?- numlist(-5,5,L).
   L = [-5,-4,-3,-2,-1,0].

?- numlist(-5,-5,L).
   L = [-5,-6,-7,-8,-9,-10].
```

**Comment by UWN** [comment]
@flexoron: What above improving upon the current implementation of `nth0/3`? After all, there are cases where the list is visited twice * gasp *. Think of it. I believe that such cases could be avoided, but I have not thought about it in detail. Most complex are cases where the list is infinite and the index is given and is already located within a loop.

**Comment by flexoron** [comment]
I'm sorry, UWN. I got something wrong(relevant for numlist/2, #606).
Hmm, as yet I don't know how to construct an infinite object.
Finitism owns the howto simply by denying transfinitism.

nth0/3 is stunning, and for me as a learner another great example to study.

**Comment by UWN** [comment]
> I don't know how to construct an infinite object.

Qua STO-unifications. like `L = [a|L]`.

`'$skip_max_list'(Skip, Max, Es0,Es)` the real input here is `Max` (but only if instantiated otherwise it is ignored) and `Es0`. `Es` is the suffix of `Es0` that appears after skipping `Skip` many elements.

```

?- '$skip_max_list'(2,2,"0123",Es).
Es = "23".
?- '$skip_max_list'(2,2,"01234",Es).
Es = "234".
```

For both queries, two elements are skipped which form the list prefix `"01"`. Note that `Skip` is really an output argument. That is, it can influence success or failure but it cannot influence the value of `Es`.
