### ISSUE TITLE
Feature request library(aggregate) 

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#603]
Wanted to run Numbrix Puzzle. Banged my head here:
```
?- time(aggregate_all(count, (length(_L, 16), line(_L)), C)).
   throw(error(existence_error(procedure,aggregate_all/3),aggregate_all/3)).
```
I know that I can use countall/2 instead:
```
?- time(countall((length(_L, 16), line(_L)), C)).
% Time elapsed 0.163s, 1138078 Inferences, 6.989 MLips
   C = 552.
```
But the countall/2 looks a little limited to me. Its
not future proof. What if we want i.e. failure driven loop 
summing or failure driven multiplication,

does this mean for every new aggregate there will
be a new predicate sumall/2, predall/2, etc... Not
sure whether this is a  way ahead,

since library(aggregate) usually offers more. In
the world of aggregates there are equivalents of
aggregates to findall/3 and bagof/3 which can 

reuse the same aggregates. So what the library
offers is only 2-3 predicates such as aggregate_all/3
and aggregate/3, plus a set of aggregates.

**Comment by infradig** [comment]
Try copying aggregate.pl over on your system. I won't include it in Trealla as it seems to be the sole work of Jan.

I couldn't access your numbrix attachment.

**Comment by Jean-Luc-Picard-2021** [comment]
Not sure whether you can run SWI-Prolog `library(aggregate)`
on your system. To realize failure driven versions of count, sum, etc..
it uses `nb_setarg/3`, which is an implementation specific feature 

of SWI-Prolog. I don't find `nb_setarg/3` listed here for Trealla:

https://github.com/trealla-prolog/trealla

So simply copying over aggregate.pl is possibly not an option.

BTW: Second try to upload Numbrix:

[numbrix.p.log](https://github.com/user-attachments/files/17268793/numbrix.p.log)

**Comment by Jean-Luc-Picard-2021** [comment]
With `nb_setarg/3` you can also easily program `call_nth/2` 
in Prolog itself. Or even bootstrap another useful library,
which is `library(solution_sequences)`.

I introduced `nb_setarg/3` in the form of `change_arg/3` in
Dogelog Player. It turned out a little nightmare implementing
it, especially garbage collection issues. But I used it to bootstrap 

`library(sequence)` which has call_nth/2. So `nb_setarg/3` is quite handy!
But it seems you have things like limit/2 and offset/2 already
implemented natively. So its maybe to late for this synergy.

**Comment by infradig** [comment]
I won't be adding setarg/3 or nb_setarg/3.

**Comment by Jean-Luc-Picard-2021** [comment]
Since you have findall/3 and bagof/3:
```
?- findall(X, between(1,3,X), L).
   L = [1,2,3].
?- bagof(X, (between(1,3,Y), between(1,Y,X)), L).
   Y = 1, L = [1]
;  Y = 2, L = [1,2]
;  Y = 3, L = [1,2,3].
```
You could use this one, it works without nb_setarg/3:

[aggregate.p.log](https://github.com/user-attachments/files/17278552/aggregate.p.log)

**Comment by infradig** [comment]
The question is, does it work?

**Comment by Jean-Luc-Picard-2021** [comment]
Of course:
```
~/trealla$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.57.1

~/trealla$ ./tpl
?- ['aggregate.p'].
   true.
?- aggregate_all(sum(X), between(1,3,X), S).
   S = 6.
?- aggregate(sum(X), (between(1,3,Y), between(1,Y,X)), S).
   Y = 1, S = 1
;  Y = 2, S = 3
;  Y = 3, S = 6.
```

**Comment by infradig** [comment]
And what's the provenance?

**Comment by Jean-Luc-Picard-2021** [comment]
You can also bootstrap setof/3:
```
bagof(X, G, L) :- 
    aggregate(set(X), G, L)
```
I think this was all already present in DEC-10 Prolog.

**Comment by Jean-Luc-Picard-2021** [comment]
Aggregates are for example found in **SICStus Prolog**:

https://sicstus.sics.se/sicstus/docs/4.1.0/html/sicstus/lib_002daggregate.html

I am toying around with this file and Trealla Prolog now:

[aggregate.p.log](https://github.com/user-attachments/files/17278907/aggregate.p.log)

There is not much in it, which wouldn't be Prolog folklore.

But it uses a lot of space, if you don't have fast paths for count/0, 
sum/1. A findall/3 solution that counts a million witnesses will
first materialize a list of length one million.

The fast path solutions don't do that, and make aggregate_all/3
competitive with countall/3 when the aggregation function count/0
is used. But you have the benefit you can also use sum/1, etc..

There are different ways to build fast path solutions, like SWI-Prolog
using `nb_setarg/3`. But other solutions are also conceivable.

**Comment by infradig** [comment]
I'll look at it tomorrow.

**Comment by Jean-Luc-Picard-2021** [comment]
You put label "wontfix", but you can also Close with wont-fix:

![image](https://github.com/user-attachments/assets/0bb98da4-5ed5-4845-8de7-4ea70022bbcf)

I think the label "wontfix" is not needed anymore in GitHub issues.

Thats a new feature that I see the recent weeks.

**Comment by Jean-Luc-Picard-2021** [comment]
More earlier reference than SICStus Prolog:

Copyright 1986, Fernando C.N. Pereira and David H.D. Warren
https://www.swi-prolog.org/pack/file_details/prologmud_I7/prolog/chat80/aggreg.pl?show=src

But wasn't Chat80 recently donated to the community?

**Comment by infradig** [comment]
Can we close this now?
```
$ tpl numbrix.pl
?- use_module(library(aggregate)).
   true.
?- time(aggregate_all(count, (length(_L, 16), line(_L)), C)).
% Time elapsed 0.241s, 1139737 Inferences, 4.733 MLips
   C = 552.
?- 
```

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, it landed here. That was quick:

https://github.com/trealla-prolog/trealla/blob/main/library/aggregate.pl

 Do you need test cases? I got some here, awful file name:

https://www.novacuor.ch/srctab/doclet/docs/13_comply/frequent/extend/struct.html

**Comment by Jean-Luc-Picard-2021** [comment]
It has a small discontiguous predicate error:
```
sys_aggr_init(A, _) :-
   throw(error(type_error(aggregate,A),_)).
```
The above should read:
```
sys_aggr_init(A, _, _) :-
   throw(error(type_error(aggregate,A),_)).
```
Also I am currently preparing a new version with fast path.

**Comment by Jean-Luc-Picard-2021** [comment]
Here is a version with fast path. I only treated `aggregate_all/3`.
It would be also possible to treat `aggregate/3`, but this has to
wait until I got my head around a hash table and variant records.

Meanwhile an enhancement with fast path for `aggregate_all/3`:

[aggregate2.p.log](https://github.com/user-attachments/files/17347648/aggregate2.p.log)

You can run it in GNU Prolog using this bridge:
```
change_arg(N, X, T) :- setarg(N, X, T, false).
```
But GNU Prolog only supports atomic via the above approach, 
so `bag/1` and `set/1` aggregate will not work. But they still work,
in Dogelog Player even with the fast path:
```
?- ['aggregate2.p'].

?- aggregate_all((bag(X),set(X)), (between(1,3,X);between(1,3,X)), L).
L = ([1, 2, 3, 1, 2, 3], [1, 2, 3]).
```
The `bag/1` and `set/1` aggregate use some routines from the
Dogelog Player findall/3 realization. The later realization is
also based on change_arg/3 plus it uses copy_term/2.

**Comment by Jean-Luc-Picard-2021** [comment]
The test cases are the same. But you see a performance difference:

Without fast path:
```
?- ['aggregate.p'].

?- time((between(1,1000,_), aggregate_all(count, between(1,1000,_), X), fail; true)).
% Zeit 848 ms, GC 0 ms, Lips 13009549, Uhr 11.10.2024 23:51
true.

?- time((between(1,1000,_), aggregate_all(sum(X), between(1,1000,X), _), fail; true)).
% Zeit 878 ms, GC 1 ms, Lips 12565031, Uhr 11.10.2024 23:51
true.
```
With fast path, 2x times faster:
```
?- ['aggregate2.p'].

?- time((between(1,1000,_), aggregate_all(count, between(1,1000,_), X), fail; true)).
% Zeit 409 ms, GC 1 ms, Lips 17173833, Uhr 11.10.2024 23:56
true.

?- time((between(1,1000,_), aggregate_all(sum(X), between(1,1000,X), _), fail; true)).
% Zeit 402 ms, GC 0 ms, Lips 17472880, Uhr 11.10.2024 23:56
true.
```
The fast path also uses less memory, and hence less garbage collection.

**Comment by infradig** [comment]
Is that speedup linear with the number of items?

**Comment by Jean-Luc-Picard-2021** [comment]
In SWI-Prolog you can try:
```
aggregate_all2(Template, Goal0, Result) :-
    aggregate:template_to_pattern(all, Template, Pattern, Goal0, Goal, Aggregate),
    findall(Pattern, Goal, List),
    aggregate:aggregate_list(Aggregate, List, Result).
```
Without fast path:
```
?- aggregate_all2(sum(X), between(1,100000000,X), Y).
ERROR: Stack limit (1.0Gb) exceeded
```
With fast path:
```
?- aggregate_all(sum(X), between(1,100000000,X), Y).
Y = 5000000050000000.
```

**Comment by Jean-Luc-Picard-2021** [comment]
Here is a test case where I get an Killed because
aggregate_all/3 without fast path consumes too much memory:
```
/* Trealla Prolog */
?- test.
% Time elapsed 0.043s, 464977 Inferences, 10.807 MLips
552
% Time elapsed 3.068s, 41680528 Inferences, 13.588 MLips
8648
Killed
```
SWI-Prolog doesn't crash and recent version of Dogelog Player
with fast path doesn't crash either. Its a version of Numbrix:

[numbrix.p.log](https://github.com/user-attachments/files/17349603/numbrix.p.log)

Disclaimer: I didn't really check whether the Trealla abort
is inside aggregate_all/3 or somewhere else. It could be 
somewhere else, but still cause by aggregate_all/3.

**Comment by Jean-Luc-Picard-2021** [comment]
In case you want to add `meta_predicate/1` declarations,
you could use the same as from SWI-Prolog. But I am
not sure whether Trealla Prolog supports the (^)/0 specifier:
```
:- meta_predicate
    foreach(0,0),
    aggregate(?,^,-),
    aggregate(?,?,^,-),
    aggregate_all(?,0,-),
    aggregate_all(?,?,0,-).
```
Only my library doesn't implement `foreach/2`, `aggregate/4` and 
`aggregate_all/4`. But you could adopted the implementation 
from SWI-Prolog as well. But a SWI-Prolog based foreach/2 

would require `'$unbind_template'/1`, and a SWI-Prolog 
aggregate/3 would require `nb_setarg/3`.
