### ISSUE TITLE
nth0/3 incorrect (unrelated to #600)

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#603]
```
?- Es=[a|Es], nth0(N, Es, b).
   Es = [a|Es], N = 1, unexpected
;  Es = [a|Es], N = 2, unexpected
;  ... .
```

I believe the best would be to loop, thus:
```
?- Es=[a|Es], nth0(N, Es, b).
   loops   % like SICStus
|  resource_error(finite_memory). % unclear if this can be done cheaply
```

**Comment by UWN** [comment]
Maybe this helps:

```
?- Es=[a|Es], nth0(N, Es, E).
   Es = [a|Es], N = 0, E = a
;  Es = [a|Es], N = 1, unexpected
;  Es = [a|Es], N = 2, unexpected
;  ... .

**Comment by infradig** [comment]
?- Es=[a|Es], nth0(N, Es, E).
   Es = [a|Es], N = 0, E = a
;  Es = [a|Es], N = 1, unexpected
;  Es = [a|Es], N = 2, unexpected

; ... .

Is it the absence of *E* on backtracking that you are referring to? It is
indeed unexpected.

**Comment by infradig** [comment]
I believe the best would be to loop, thus:

?- Es=[a|Es], nth0(N, Es, b).
   loops   % like SICStus
|  resource_error(finite_memory). % unclear if this can be done cheaply

Ok, I see. Should be possible.

**Comment by UWN** [comment]
> Is it the absence of *E* on backtracking that you are referring to?

Right. The answer `Es = [a|Es], N = 1` is unexpected, because it includes the solution `E = b` and many more.

**Comment by UWN** [comment]
Just to be sure, `|` means one of those two answer descriptions.

**Comment by UWN** [comment]
And, ..., one more concerning quads: all these answers descriptions are `sto`!

**Comment by infradig** [comment]
| Is it the absence of *E* on backtracking that you are referring to?

| Right. The answer Es = [a|Es], N = 1 is unexpected, because it includes
the solution E = b and many more.


It's not intentional, i'll have to look into why it's dropped.
