### ISSUE TITLE
Feature request library(sequence)

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#606]
I see that Trealla Prolog has a few bifs such as
`call_nth/2`, `limit/2` and `offset/2`. These bifs are 
usually explained as inspired by the corresponding

SQL database querying language equivalents.
But what about a `distinct/1` meta predicate?
The predicate is somehow missing:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.57.9-5-gcd77

$ ./tpl
?- distinct((X=1;X=2;X=1)).
   throw(error(existence_error(procedure,distinct/1),distinct/1)).
```
On the other hand in SWI-Prolog I get:
```
/* SWI-Prolog 9.3.11 */
?- distinct((X=1;X=2;X=1)).
X = 1 ;
X = 2 ;
false.
```

**Comment by infradig** [comment]
You could do *distinct/1* something like...
```
distinct(Goal) :-
	distinct(Goal, Goal).

:- meta_predicate(distinct(0)).

distinct(Witness, Goal) :-
	term_variables(Witness, Vars),
	Witness1 =.. [v|Vars],
	setup_call_cleanup(
		true,
		(
			Goal,
			\+ clause('$distinct'(Witness1, Goal), _),
			assertz('$distinct'(Witness1, Goal))
		),
		retractall('$distinct'(Witness1, _))
	),
	true.

:- meta_predicate(distinct(0,0)).
```

**Comment by Jean-Luc-Picard-2021** [comment]
I guess it will pass this test case, right?
```
/* SWI-Prolog, eagerness */
?- distinct(repeat), !.
true.
```
But it wont pass this test case, right?
```
/* SWI-Prolog, non-variant enumerating */
d(f(A,A)).
d(f(a,a)).
d(f(B,B)).

?- distinct(d(X)).
X = f(_70321, _70321);
X = f(a, a);
fail. 
```
And this test case will also fail, right?
```
/* SWI-Prolog, reentrant */
?- distinct((distinct(X=1);distinct(X=1))).
X = 1 ;
false.
```

**Comment by infradig** [comment]
This one now works for that example...
```
distinct(Goal) :-
	distinct(Goal, Goal).

:- meta_predicate(distinct(0)).

distinct(Witness, Goal) :-
	term_variables(Witness, Vars),
	Witness1 =.. [v|Vars],
	setup_call_cleanup(
		copy_term(Witness1, Witness2),
		(
			Goal,
			\+ (clause('$distinct'(Witness1, Goal), _), compare(=, Witness1, Witness2)),
			assertz('$distinct'(Witness1, Goal))
		),
		retractall('$distinct'(Witness1, _))
	),
	true.

:- meta_predicate(distinct(0,0)).
```

```
$cat x.pl
d(f(A,A)).
d(f(a,a)).
d(f(B,B)).

$ tpl x.pl
?- distinct(d(X)).
   X = f(_A,_A)
;  X = f(a,a)
;  X = f(_A,_A).
?- 
```

**Comment by infradig** [comment]
Maybe for the future.

**Comment by Jean-Luc-Picard-2021** [comment]
The future is now. How would one solve Advent of Code 2024, Day 8?

> **Day 8: Resonant Collinearity**
https://adventofcode.com/2024/day/8

> **SWI-Prolog Solution by tatut**
https://swi-prolog.discourse.group/t/advent-of-code-2024/8641/22

![foo](https://github.com/user-attachments/assets/e296ff41-21bd-4ab7-a1f2-6ba233227447)

But implementing `distinct/1` has become increasingly competitive.
SWI-Prolog recently made a new stab at it, using tries. And I have
also a new version using hash tables.

Alternatively one could indeed implement aggregate_all/4, but
I never did that, was always ticking along with aggregate_all/3 alone,
so cannot offer you some pure implementation,

maybe the SWI-Prolog system has a pure implementation based
on sort/2 or keysort/2. But somehow I prefer the building block
distinct/1 which corresponds to the SQL keyword DISTINCT.
