### ISSUE TITLE
Answer substitution has problems with (=..)/2 and cyclic terms

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#607]
I must admit I was currious whether some problems
that bugged Scryer Prolog in the past, also bug
Trealla Prolog. This here works now in Scryer Prolog:
```
/* Scryer Prolog 0.9.4-193 */
?- Y = [x,Y], W =.. Y.
   Y = [x,Y], W = x([x,Y]).
```
But a simple repaste test tells me the output in
Trealla Prolog is not correct:
```
/* Trealla Prolog 2.57.16 */
?- Y = [x,Y], W =.. Y.
   Y = [x,Y], W = x([x,[x,[x,W]]]).

?- Y = [x,Y], W =.. Y, W = x([x,[x,[x,W]]]).
   false.
```
The 2nd query should succeed if the answer substitution
`W = x([x,[x,[x,W]]])` were correct.

**Comment by Jean-Luc-Picard-2021** [comment]
Maybe [pmoura](https://github.com/pmoura) can create some test
cases for that?

**Comment by Jean-Luc-Picard-2021** [comment]
Closed because Ozzy Osbourne birthday and nobody is working on this bug.

**Comment by infradig** [comment]
Now you're making me paranoid.

**Comment by infradig** [comment]
It's just a printing issue, i'll try and look tomorrow.

**Comment by infradig** [comment]
```
$ tpl
?- Y = [x,Y], W =.. Y.
   Y = [x,Y], W = x([x,[x,[x,Y]]]).
```

I don't know why it's shows down 3 levels but it's equivalent.
