### ISSUE TITLE
nth0/3 problem

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#608]
Playing a bit for a better understanding , not sure if I get it right.
v1.33.14
```
1.) Generate list (somehow)
?- T = [T|Xs], length(T,N).
   T = [T|Xs], Xs = [], N = 1
;  T = [T|Xs], Xs = [_A], N = 2
;  T = [T|Xs], Xs = [_A,_B], N = 3
;  ... .

2.) Now I want access Elements of Xs.
?- T = [T|Xs], length(T,N), nth0(N,Xs,E).  % Invalidated because of  broken nth0/3
   T = [T|Xs], Xs = [E], N = 2
;  T = [T|Xs], Xs = [E,_A], N = 3
;  T = [T|Xs], Xs = [E,_A,_B], N = 4
;  ... .

3.) Now just Element Nr 2
?- T = [T|Xs], length(T,N), nth0(2,Xs,E).
   T = [T|Xs], Xs = [E], N = 2
;  T = [T|Xs], Xs = [_A,_B,E], N = 4  % missing N = 3 and Xs is different from Xs of example 2.)
;  T = [T|Xs], Xs = [_A,_B,E,_C], N = 5 % 
;  T = [T|Xs], Xs = [_A,_B,E,_C,_D], N = 6
;  ... .
```
Missing "E = " in 2.) and 3.) as well
because
```
?- nth0(0,[a],E).
   E = a.
?- nth0(1,[a],E).
   false.
?- nth0(2,[a],E).
   E = a. % unexpected
?- nth0(3,[a],E).
   E = a. % unexpected
?-

or

?- Xs = [_A,_B], N = 3, nth0(N,Xs,E).
   Xs = [_A,_B], N = 3, E = _A.  % unexpected
?-
```

**Comment by UWN** [comment]
First of all, please make it a habit to include the integral interaction. You are always leaving out the line `; ... .` which indicates that **you** stopped the interaction and not Prolog. Without it this is not clear at all.

> Missing "E = " in 2.) and 3.) as well because  ...

That is not a reason at all. In the original situation you had a list with new variables that have not occurred in the query. So Prolog is free to give them either a new name like _A or, in the case of the second element, just the name that appeared in the query.

And, if the index goes beyond the list, failure is expected thus:

```
?- nth0(3,[a],E).
   E = a, unexpected.
   false. % expected answer
```

**Comment by flexoron** [comment]
Ok, corrected.
Hmm, so I wait until the list has a length and then acccess a spot
```
?- T = [T|Xs], length(Xs,N), N > 3, nth0(2,Xs,E).
   T = [T|Xs], Xs = [_A,_B,E,_C], N = 4
;  ... .
?-
```
Instead of giving me E = , E is placed into the list at this position. That is tricky.
I thought list Xs exists like so [_A,_B,_C,_D] before entering nth0/3.
```
