### ISSUE TITLE
nth1/3 faster

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#609]
```
nth1faster(N, Es, E) :-
   N \== 0,
   nth0(N, [_|Es], E),
   N \== 0.
```

Exercise: Why is it impossible to replace `_` by some constant, like `t`? Also note that for the current point in time, `nth0/3` is broken, since (beside other things), skip_max_list is broken. Consider:

```
?- '$skip_max_list'(Skip, 2,"xab",E).
   Skip = 2, E = "b".
?- '$skip_max_list'(Skip, 2,[x|"ab"],E).
   Skip = 3, E = [], unexpected.
```

**Comment by infradig** [comment]
| nth1faster(N, Es, E) :-
|   N \== 0,
|   nth0(N, [_|Es], E),
|   N \== 0.

So you don't think nth1/3 should throw an error if 1st arg is zero?

**Comment by infradig** [comment]
Yes, it doesn't like mixing iso lists with strings. Something yo look at
later.

**Comment by UWN** [comment]
> So you don't think nth1/3 should throw an error if 1st arg is zero?

Exactly the same situation as with `arg/3`. The domain of relevance is `not_less_than_zero`.

**Comment by UWN** [comment]
BTW, why not introducing the domain `not_less_than_zero` into `must_be`? The complexity that it generates both a type and a domain error is then hidden therewithin. See also [Scryer](https://github.com/mthom/scryer-prolog/issues/1309) on this.

**Comment by UWN** [comment]
I do not quite understand why you changed the definition of `nth1/3` from the one suggested above. By this you are introducing hard to debug errors.

```
?- L=[1,2|L],nth1(4,[0|L],E).
   L = [1,2|L], E = 1.
?- L=[1,2|L],nth1(5,[0|L],E).
   L = [1,2|L], E = 1, unexpected.
?- L=[1,2|L],nth1(5,[0|L],E).
   L = [1,2|L], E = 2. % expected
```

**Comment by UWN** [comment]
Also, your definitions are quadratic in `N` for the case

```
?- nth0(N,L,_), N = 10000.
``

**Comment by UWN** [comment]
```
?- nth0(10000,L,_).
   L = [_A|_B], unexpected. % but very fast indeed
```

**Comment by infradig** [comment]
> I do not quite understand why you changed the definition of `nth1/3` from the one suggested above. By this you are introducing hard to debug errors.
> 
> ```
> ?- L=[1,2|L],nth1(4,[0|L],E).
>    L = [1,2|L], E = 1.
> ?- L=[1,2|L],nth1(5,[0|L],E).
>    L = [1,2|L], E = 1, unexpected.
>    L = [1,2|L], E = 2. % expected
> ```

How does this work?

**Comment by UWN** [comment]
> How does this work?

Just take the original definition. For that, an infinite list is just a repetition of that cycle.

**Comment by UWN** [comment]
Why did you close it? Your definition is completely incorrect.

**Comment by UWN** [comment]
UWN_open

**Comment by infradig** [comment]
I have reverted nth0/3 & nth1/3 to original forms. Added fastnth0/3 for
those that need speed.

**Comment by UWN** [comment]
>  Added fastnth0/3 for those that need speed.

So you are making the interface to the programmer more complex.

Why not just make one correct & fast definition? Now:

```
?- nth0(N,L,E),N=10000.
   very_slow.
?- freeze(E,(writeq(trying(E)),nl,false)), nth0(0,[a|L],E).
trying(a)
trying(a)
   false.
```
