### ISSUE TITLE
Parsing components of the structure of a functor causes abnormal process termination + core dump

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#612]
v1.33.15
```
?- arg(1, (a) * \, ).
Segmentation fault (core dumped)
```

**Comment by infradig** [comment]
Parser error.

**Comment by flexoron** [comment]
Whoops!....That emoji seems laughing at you and I thought it is a smile.
Pardon me. I'm not good at decipher modern hieroglyphics.(btw Egyptians did all that much better).

And here is the winner of The Cultural Prize (2022-2042): Our terminals/consoles :1st_place_medal: 
https://github.com/dankamongmen/notcurses
