### ISSUE TITLE
 '$skip_max_list'/4 skips more than max

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#613]
```
?- '$skip_max_list'(Skip, 2,"xab",E).
   Skip = 2, E = "b".
?- '$skip_max_list'(Skip, 2,[x|"ab"],E).
   Skip = 3, E = [], unexpected.
```

The problem here is that

1mo, `Skip` must never be larger than `Max`

2do, there is a difference between "xab" and [x|"ab"]

(This is to keep it a separate issue from #609).

**Comment by infradig** [comment]
I think I said, skip_max_list doesn't deal with mixed lists like that yet.
On the 2do list.
