### ISSUE TITLE
Relative Prolog text file not found

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#615]
Somehow either a file is silently not consulted, or a predicate 
doesn't become visible. Could be a backward compatibility problem
form ISO modules to ISO core. Since non-modules should have all 

predicates automatically exported? If I do in Trealla Prolog I get:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.59.1-22-g5aa60f

$ ./tpl
?- ['mod/foo.p'].
   true.

?- bar.
   throw(error(existence_error(procedure,bar/0),bar/0)).
```
If I do in SWI-Prolog I get:
```
$ swipl --version
SWI-Prolog version 9.0.4 for x86_64-linux

$ swipl

?- ['mod/foo.p'].
true.

?- bar.
hello
true.
```
The test case is relatively simple, a directory mod, with two files:

[bar.p.log](https://github.com/user-attachments/files/17585279/bar.p.log)
[foo.p.log](https://github.com/user-attachments/files/17585281/foo.p.log)

**Comment by Jean-Luc-Picard-2021** [comment]
LoL, its even worse in Scryer Prolog:
```
$ target/release/scryer-prolog -v
v0.9.4-201-gc39ea481

$ target/release/scryer-prolog
?- ['mod/foo.p'].
   error(domain_error(directive,todo_insert_invalid_term_here),load/1).
```

**Comment by infradig** [comment]
Trealla doesn't support random predicate calls as directives, like SWI-Prolog does.

**Comment by infradig** [comment]
I expect Scryer doesn't either.

**Comment by Jean-Luc-Picard-2021** [comment]
Make `[_|_]` a directive, or else throw an error.

Now it is silent and hence very difficult to debug.

Especially when porting code that works in SWI-Prolog.

**Comment by pmoura** [comment]
Top-level **shortcuts** should never be used in source files. Throwing an error is the best **and** compliant option here.

**Comment by Jean-Luc-Picard-2021** [comment]
Some error is thrown, but it has still a bug somewhere.
Just compare Treealla Prolog with Scryer Prolog. Trealla
Prolog does not lookup use_module/1 argument relative to 

the parent file, or maybe its an extension problem:
```
~/trealla$ ./tpl
?- ['../scryer-prolog/foo'].
Warning: module file not found: bar
   true.
?-
```
Scryer Prolog can lookup use_module/1 argument correctly:
```
~/trealla$ ../scryer-prolog/target/release/scryer-prolog
?- ['../scryer-prolog/foo'].
   true.
?- bar.
hello
   true.
?-
```
The test cases are:

[bar.pl.log](https://github.com/user-attachments/files/17604463/bar.pl.log)
[foo.pl.log](https://github.com/user-attachments/files/17604464/foo.pl.log)

**Comment by Jean-Luc-Picard-2021** [comment]
Some error is thrown, but it has still a bug somewhere.
Just compare Trealla Prolog with Scryer Prolog. Trealla
Prolog does not lookup `use_module/1` argument relative to 

the parent file, or maybe its an file name extension problem?
```
~/trealla$ ./tpl
?- ['../shared/foo'].
Warning: module file not found: bar
   true.
```
Scryer Prolog can lookup `use_module/1` argument correctly:
```
~/scryer-prolog$ target/release/scryer-prolog
?- ['../shared/foo'].
   true.

?- bar.
hello
   true.
```
The test cases are, placed it in a **~/shared** folder:

[bar.pl.log](https://github.com/user-attachments/files/17604463/bar.pl.log)
```
bar :- write(hello), nl.
```
[foo.pl.log](https://github.com/user-attachments/files/17604464/foo.pl.log)
```
:- use_module('bar').
```
The bug is a little annoying, since I cannot share Prolog text files among
two Prolog systems. Have always to copy the stuff or otherwise
modify it to fix the bug.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok!
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.59.5

~/trealla$ ./tpl
?- ['../shared/foo'].
   true.
?- bar.
hello
   true.
```
