### ISSUE TITLE
Backslash misinterpreted

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#616]
v1.34.2
```
?- op(300,xfx,\\).
   true.
?- Y = [arg(2, \1  \\ (\2), \2)].
   Y = [arg(2,\1\\\2,\2)]. % non-applicable

?- arg(2,\1\\\2,\2).
Error: syntax error, near '\\\', operator expected

```

**Comment by infradig** [comment]
Am i missing something?


$ gprolog
GNU Prolog 1.4.5 (64 bits)
| ?- op(100,xfx,\\).
yes
| ?- Y = [arg(2, \1  \\ (\2), \2)], write_canonical(Y), nl.
'.'(arg(2,\(\\(1,\(2))),\(2)),[])
Y = [arg(2,\1\\(\2),\2)]
yes

~/trealla (devel) $ scryer-prolog
?- op(100,xfx,\\).
   true.
?- Y = [arg(2, \1  \\ (\2), \2)], write_canonical(Y), nl.
'.'(arg(2,\(\\(1,\(2))),\(2)),[])
   Y = [arg(2,\ 1\\(\ 2),\ 2)].

~/trealla (devel) $ tpl
?- op(100,xfx,\\).
   true.
?- Y = [arg(2, \1  \\ (\2), \2)], write_canonical(Y), nl.
'.'(arg(2,\(\\(1,\(2))),\(2)),[])
   Y = [arg(2,\ (1\\(\2)),\2)

**Comment by flexoron** [comment]
I'm sorry..wrong cut/paste
This is the issue:
```
?- op(300,xfx,\\).
   true.
?- Y = [arg(2, \1  \\ (\2), \2)].
   Y = [arg(2,\1\\\2,\2)]. % non-applicable

?- arg(2,\1\\\2,\2).
Error: syntax error, near '\\\', operator expected
```
