### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#618]
Hello. First I'd like to say this project is awesome, thanks a bunch!

Are you interested in supporting WebAssembly? With [WASI](https://github.com/WebAssembly/WASI) there are only minimal changes needed to get things running.

I have successfully built Trealla with wasi-sdk and it seems to runs nicely on wasmtime. Here is a very rough branch to get an idea of the changes needed: https://github.com/guregu/trealla/pull/1

The only major difference so far I can see is that WASM doesn't like it when you call e.g. strcmp with extra arguments, so I had to add some helper functions for skiplist's cmpkey. The rest is just ifdef wrangling to disable things that it doesn't support.

I would be happy to clean this up and make a proper PR. I'm very rusty with C so apologies for anything dumb I've written.

### Why?

My main motivation for this is I'd like to experiment with other Prolog runtimes for my [worker-prolog](https://github.com/guregu/worker-prolog) project, which provides a serverless Prolog RPC thing via Cloudflare Workers. It currently uses Tau but I'd like more performance. Trealla looks to be the most promising candidate. This would also be a big step towards running in browsers. Ultimately I'd like to be able to run Trealla on browsers and on the backend so I can share a Prolog runtime for server/client webapps.

I found a couple references to WASM here (cc @jacobfriedman @josd) but I couldn't find more details, so if this is duplicated effort please let me know 🙏

**Comment by infradig** [comment]
Cool, I know nothing of WASM and in-the-browser so that's great. I have put
a wrapper around the strcmp uses with skiplist. Let me know if there's
anything else I can do. A PR would be great.

**Comment by guregu** [comment]
Thanks a bunch @infradig! I've made some good progress. Currently we can get a mostly working toplevel under WASI, but the readline bits are janky (doesn't print prompt, can't handle redos -- WASI lacks `termios.h`). I'll need to add some fixes to isocline to get it to play nicely with WASI, but it should be totally doable. I will submit a draft PR soon.

**Comment by infradig** [comment]
So how is i/o normally done?

**Comment by guregu** [comment]
I believe it has most facilities for I/O. It just lacks terminal-specific bits such as `tcgetattr`, so if we treat WASI like a dumb terminal everything should "just work" (I hope).

This isn't strictly necessary for being useful and getting Trealla running in the browser. I think a minimal browser API would just call Trealla with `-q -g` and receive standard output (this part is already working). But it would be cool to have a REPL.

**Comment by guregu** [comment]
Success! It turns out I was overthinking things. No need to touch isocline at all, just needed to add a super simple implementation of `history_readline_eol` that uses `getline`. This project is really beautifully structured.

You can play around with it in your browser here: https://wapm.io/guregu/trealla/tree/0.0.1 (click the "Open in the shell" button in the bottom right, then type `tpl`).
![2022-08-02](https://user-images.githubusercontent.com/131059/182190162-6f1b865e-d529-48c0-93a0-46cd4f831f59.png)

It's a little weird (press `r<enter>` instead of `r` for retry, etc.) and I haven't tested it much, but we have a REPL in the browser now.

Seems the main issue with WASI is that it simply cannot get single character input, and so getchar-like functions return chars from a buffered line instead, which always includes a newline(? I think). There's an issue tracking it here: https://github.com/WebAssembly/WASI/issues/161. It's pretty easy to work around this by treating newlines in the toplevel a little bit differently for WASI.
I think games that use WebAssembly, for example, use functions from Javascript-land to handle input, and this is the best we have standardized at the moment for terminal I/O. 

I'll clean my changes up and send a PR soon! They should be minimally invasive.

**Comment by josd** [comment]
Am deeply impressed!
After installing
```
sudo apt install libtinfo5
curl https://get.wasmer.io -sSfL | sh
```
the following worked first time right
```
$ wasmer run wapm_packages/guregu/trealla@0.0.1/tpl.wasm
?- [user].
% Socrates is a mortal

'<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'('<http://example.org/ns#Socrates>','<http://example.org/ns#Man>').

'<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'(X,'<http://example.org/ns#Mortal>') :-
    '<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'(X,'<http://example.org/ns#Man>').

% query
query('<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'(_IND,_CLASS)).

run :-
    query(Q),
    Q,
    writeq(Q),
    write('.\n'),
    fail;
    true.
   true.
?- run.
'<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'('<http://example.org/ns#Socrates>','<http://example.org/ns#Man>').
'<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'('<http://example.org/ns#Socrates>','<http://example.org/ns#Mortal>').
   true.
?-
```

**Comment by infradig** [comment]
Great work!

**Comment by guregu** [comment]
Thank you for the kind words @josd and @infradig. I'm excited to see what we can do with this.
I'll keep posting updates here on progress.

Next step is to write a little Javascript library (depending on [wasmer-js](https://github.com/wasmerio/wasmer-js) probably) that runs Trealla in quiet mode and grabs results from stdout. With something vaguely like [MQI](https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/mqi.html%27)) we could wrangle a programmatic query API out of it.
From there we can make fancier online REPLs and sandboxes using JS/HTML for input rather than relying on WASI's readline. We could host a nice website for Trealla on GitHub pages once everything comes together.
I'll do some experimenting. Maybe we could put the JS stuff in another repository under the trealla-prolog organization.

Also I think a few more of the more OS-specific APIs can probably be supported with some tinkering. It could be cool to experiment with `$dlopen` like functionality for WASM/JS. With the JS shim library we could add support for HTTP calls and all of that, which would be awesome.

**Comment by josd** [comment]
Did some test with the examples in https://github.com/josd/retina native tpl versus wasm tpl
```
$ time ~/trealla/tpl -g run,halt gps/gps.pl
'<https://josd.github.io/eye/ns#findpath>'('<http://example.org/ns#map_be>',['<https://josd.github.io/eye/ns#location>'('<http://example.org/ns#i1>','<http://example.org/ns#oostende>'),['<http://example.org/ns#drive_gent_brugge>','<http://example.org/ns#drive_brugge_oostende>'],2400.0,0.01,0.9408,0.99,[5000.0,5.0,0.2,0.4,1]]).
'<https://josd.github.io/eye/ns#findpath>'('<http://example.org/ns#map_be>',['<https://josd.github.io/eye/ns#location>'('<http://example.org/ns#i1>','<http://example.org/ns#oostende>'),['<http://example.org/ns#drive_gent_kortrijk>','<http://example.org/ns#drive_kortrijk_brugge>','<http://example.org/ns#drive_brugge_oostende>'],4100.0,0.018,0.903168,0.9801,[5000.0,5.0,0.2,0.4,1]]).

real    0m0.016s
user    0m0.016s
sys     0m0.001s

$ time wasmer run --dir . ~/github.com/trealla-prolog/trealla/tpl -- -g run,halt gps/gps.pl
'<https://josd.github.io/eye/ns#findpath>'('<http://example.org/ns#map_be>',['<https://josd.github.io/eye/ns#location>'('<http://example.org/ns#i1>','<http://example.org/ns#oostende>'),['<http://example.org/ns#drive_gent_brugge>','<http://example.org/ns#drive_brugge_oostende>'],2400.0,0.01,0.9408,0.99,[5000.0,5.0,0.2,0.4,1]]).
'<https://josd.github.io/eye/ns#findpath>'('<http://example.org/ns#map_be>',['<https://josd.github.io/eye/ns#location>'('<http://example.org/ns#i1>','<http://example.org/ns#oostende>'),['<http://example.org/ns#drive_gent_kortrijk>','<http://example.org/ns#drive_kortrijk_brugge>','<http://example.org/ns#drive_brugge_oostende>'],4100.0,0.018,0.903168,0.9801,[5000.0,5.0,0.2,0.4,1]]).

real    0m0.095s
user    0m0.074s
sys     0m0.021s
```
```
$ time ~/trealla/tpl -g run,halt tak/tak.pl
'<https://josd.github.io/eye/ns#tak>'([34,13,8],13).

real    0m0.395s
user    0m0.344s
sys     0m0.051s

$ time wasmer run --dir . ~/github.com/trealla-prolog/trealla/tpl -- -g run,halt tak/tak.pl
'<https://josd.github.io/eye/ns#tak>'([34,13,8],13).

real    0m1.974s
user    0m1.913s
sys     0m0.061s
```
```
$ time ~/trealla/tpl -g run,halt edt/edt.pl
'<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'('<http://example.org/ns#i100000>','<http://example.org/ns#N100000>').

real    0m2.271s
user    0m2.181s
sys     0m0.090s

$ time wasmer run --dir . ~/github.com/trealla-prolog/trealla/tpl -- -g run,halt edt/edt.pl
'<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>'('<http://example.org/ns#i100000>','<http://example.org/ns#N100000>').

real    0m8.729s
user    0m8.636s
sys     0m0.091s
```

So the good news is that it works fine but the bad news is that the speed drops with a **factor 4 to 5**.

There are also cases that run into trouble
```
$ time ~/trealla/tpl -g run,halt mi/mi.pl
'<https://josd.github.io/eye/ns#mi>'(['<https://josd.github.io/eye/ns#mi>'(['<https://josd.github.io/eye/ns#mi>'(['<https://josd.github.io/eye/ns#mi>'(['<https://josd.github.io/eye/ns#mi>'([factorial(s(s(s(s(s(s(0)))))),s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(s(0)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))],true)],true)],true)],true)],true).

real    0m0.095s
user    0m0.076s
sys     0m0.019s

$ time wasmer run --dir . ~/github.com/trealla-prolog/trealla/tpl -- -g run,halt mi/mi.pl

Action or (h)elp: e
error: failed to run `/home/jdroo/github.com/trealla-prolog/trealla/tpl`
│   1: RuntimeError: out of bounds memory access
           at dlmalloc (tpl[962]:0x259857)
           at malloc (tpl[961]:0x257ed2)
           at print_term_to_stream (tpl[584]:0x196100)
           at fn_iso_writeq_1 (tpl[720]:0x1db948)
           at start (tpl[654]:0x1a6d01)
           at execute (tpl[666]:0x1abc46)
           at run (tpl[326]:0xbb8c2)
           at pl_eval (tpl[599]:0x1978ba)
           at main (tpl[27]:0x1d78)
           at __main_void (tpl[1028]:0x25c608)
           at _start (tpl[25]:0xd2b)
           at _start.command_export (tpl[1222]:0x26b91c)
╰─▶ 2: heap_get_oob
```
