### ISSUE TITLE
Incorrect handling of the `use_module/2` export list argument

### ISSUE THREAD

**Issue by pmoura** [trealla-prolog/trealla#622]
Using v2.59.9:

```text
$ cat data1.pl 
:- module(data1, [a/1]).

a(1).
a(2).
a(3).
```

```text
$ cat data2.pl 
:- module(data2, [a/1]).

a(4).
a(5).
a(6).
```

Loading the first module, `data1`, without importing anything:

```text
$ tpl
?- use_module(data1, []).
   true.
?- a(X).
   X = 1
;  X = 2
;  X = 3.
```

But expected is a predicate existence error for the `a(X)` query as the predicate should not be visible in `user` given that we didn't import it (the import list is empty). Also:

```text
$ tpl
$ tpl
?- use_module(data1, []).
   true.
?- use_module(data2, []).
   true.
```

In this case, Trealla is behaving correctly as there are no clashes due to the same predicate being exported by the two modules as the import list is empty. But when using `use_module/1` instead there should be an error, which is missing as we get:

```text
$ tpl
?- use_module(data1).
   true.
?- use_module(data2).
   true.
```

**Comment by pmoura** [comment]
P.S. This bug causes the test failure observed with the Logtalk `module_aliases` example.

**Comment by infradig** [comment]
Yes, unfortunately Trealla doesn't respect import lists.

**Comment by pmoura** [comment]
I updated the Logtalk `module_aliases` example so that it will be skipped when using Trealla as the backend.

**Comment by infradig** [comment]
Ok, but keep this issue open. I intend to address it sometime.

**Comment by infradig** [comment]
But the way Trealla no longer has a module apply (currently breaking examples/symbiosis).

**Comment by pmoura** [comment]
The Logtalk `symbiosis` example requires Trealla to (also) fix the bug reported here.

**Comment by infradig** [comment]
Aware, but it also needs Logtalk to remove use_module(apply)

$ tplgt -q -g "{tester}, halt."
Warning: module file not found: /home/andrew/logtalk3/examples/symbiosis/.lgt_tmp/../library/apply
Warning: Initialization goal failed: $lgt_set_compiler_flag(report,warnings),$lgt_logtalk_load(lgtunit(loader),/home/andrew/logtalk3/examples/symbiosis/,c(user,user,r(user,user,[],[]))),$lgt_logtalk_load(loader,/home/andrew/logtalk3/examples/symbiosis/,c(user,user,r(user,user,[],[]))),$lgt_logtalk_load(tests,[hook(lgtunit)],/home/andrew/logtalk3/examples/symbiosis/,c(user,user,r(user,user,[],[]))),tests::run
~/logtalk3/examples/symbiosis (master) $

**Comment by pmoura** [comment]
Fix to use instead the `lists` module pushed.

**Comment by infradig** [comment]
BTW Paulo, there's a typo/error in symbiosis.lgt:

```
 	:- elif(current_logtalk_flag(prolog_dialect, trella)).
		:- use_module(lists, [maplist/2, maplist/3]).
```

**Comment by pmoura** [comment]
Fixed the typo.

**Comment by pmoura** [comment]
All tests for the Logtalk `module_aliases` example now pass with v2.59.17. But the tests for the `symbiosis` example still fail due to `predicate_property/2` not returning the `meta_predicate/1` property:

```text
?- predicate_property(lists:maplist(_,_,_), P).
   P = imported_from(lists).
?- lists:predicate_property(maplist(_,_,_), P).
   P = imported_from(lists).
```

This bug prevents Logtalk of properly compiling the calls to the `lists:maplist` predicates.

**Comment by pmoura** [comment]
```text
$ logtalk_tester -p trealla
% Batch testing started @ 2024-11-10 09:30:34
%         Logtalk version: 3.85.0-b01
%         Trealla Prolog version: 2.59.21
%
% logtalk/examples/symbiosis
%         5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%         completed tests from object tests in 2 seconds
%         clause coverage n/a
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 5 tests: 0 skipped, 5 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2024-11-10 09:30:37
```
