### ISSUE TITLE
Problems with sub_atom/5 in mode (+,-,-,-,+)

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#627]
I tried this code:
```
tokenize(X, [A|L]) :- sub_atom(X, P, _, Q, ' '), !,
    sub_atom(X, 0, P, _, A),
    sub_atom(X, _, Q, 0, B),
    tokenize(B, L).
tokenize(X, [X]).
```
And this query:
```
?- tokenize('не смог бы', L).
   false.
```
It shouldn't fail. Probably some problems with `sub_atom/5`:
```
/* Trealla Prolog */
?- sub_atom('не смог бы', P, _, Q, ' ').
   P = 4, Q = 13
;  P = 13, Q = 4.

/* SWI-Prolog */
?- sub_atom('не смог бы', P, _, Q, ' ').
P = 2, Q = 7 ;
P = 7, Q = 2 ;
false.
```

**Comment by Jean-Luc-Picard-2021** [comment]
Woa! Scryer Prolog is more lucky with sub_atom/5,
```
?- tokenize('не смог бы', L).
   L = [не,смог,бы]
;  false.
```
but otherwise panics later on:
```
?- tokenize('не смог бы', L), term(X, M, L, []), write_canonical(X), nl.
thread 'main' panicked at src/machine/system_calls.rs:4033:26:
we should only get valid values != YF here
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The full example in case you are interested:

[horsh.p.log](https://github.com/user-attachments/files/17724942/horsh.p.log)
[parser.p.log](https://github.com/user-attachments/files/17724943/parser.p.log)

**Comment by infradig** [comment]
Ciao gives same as Trealla. I'll look into it...

**Comment by Jean-Luc-Picard-2021** [comment]
The `sub_atom(X, P, _, Q, ' ') `call should then work together with the 
`sub_atom(X, 0, P, _, A)` call, and thats where the first problem happens:
```
$ ./tpl -v
Trealla Prolog (c) Infradig 2020-2024, v2.59.27

$ ./tpl
?- sub_atom('не смог бы', P, _, Q, ' ').
   P = 4, Q = 13
;  ... .

?- sub_atom('не смог бы', 0, 4, _, A).
   A = 'не с'.
```
The expected result would be rather `A = 'не'`.

**Comment by infradig** [comment]
I agree it's wrong

**Comment by infradig** [comment]
Problem was with code that was to eliminate a redundant choice-point. Just removed it for now.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, looks better now:
```
?- tokenize('не смог бы', L).
   L = [не,смог,бы].
```
