### ISSUE TITLE
One errorneous clause throws away whole predicate?

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#629]
Was trying to consult the attached file. It gives me an error:
```
?- ['horsh.p'].
Error: syntax error, operator expected unfinished input '.', horsh.p:88
   true.
```
Does parsing completely give up upon one error? 
I don't find any `test/1` clauses:
```
?- test(_).
   throw(error(existence_error(procedure,test/1),test/1)).
```
Wouldn't be more Prolog-ish to sync at the next terminating
period. And continue consulting clauses?

[horsh.p.log](https://github.com/user-attachments/files/17731979/horsh.p.log)

**Comment by infradig** [comment]
It stops on first error, deliberately.
