### ISSUE TITLE
bagof/3 solution missed

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#629]
v1.34.22
```
?- Data = [['1',2,'3'],['1',4,'5']], bagof([A,_,C],member([A,_,C],Data),D), findall([E,_,G],member([E,_,G],Data),H).
   Data = [['1',2,'3'],['1',4,'5']], D = [['1',_A,'3']], H = [['1',_B,'3'],['1',_C,'5']]
;  false.      % unexpected, missing D = [['1',_A,'5']], H = [['1',_B,'3'],['1',_C,'5']]
?-

**Comment by flexoron** [comment]
Preparatory work done! Great! Thanks!

Target tracking reconsidered.

There was/is a really staggering issue concerning sqlite3 tables and subsequent Prolog list processing.
Depending on how many records the database contains (between 6 and 12 and thats not that many),
Trealla does this (a mysterious loop btw):
Generating the expected result or (adding a row)
Prints result intermingled with sql-statements or (adding a row)
Dumps core due to tcache malloc error(core dump) or (adding a row)
Reports double linked list destroyed(core dump) or, and now adding one more row
Generating the expected result.

Because this issue here (#629) has been resolved, the core dumps are gone,
still there is this issue printing list results intermingled with sql-statements.
(Depends on how many rows the table contains, the rows/tables are created outside via cmd sqlite3).
I try to prepare the issue somehow comfortable next week.

**Comment by infradig** [comment]
I have never done any more than a simple query. I don't know how adding
rows to an SQLite database impacts shared C-strings. It probably screws
with ref-counting & frees. I simple example would be useful.

**Comment by flexoron** [comment]
Forget it!
The (experimental) ffi/sql-interface Trealla provides  works quite good.
Table(s) manipulation statements are Error-free and do not corrupt the database-file.

**Comment by infradig** [comment]
Ok. I added a simple example of using sqlite3_exec to do an insert command.
