### ISSUE TITLE
We get it again with https://github.com/eyereasoner/color/blob/main/examples/fourcolor.pl

### ISSUE THREAD

**Issue by infradig** [trealla-prolog/trealla#630]
We get it again with https://github.com/eyereasoner/color/blob/main/examples/fourcolor.pl

To reproduce it, you can
```
git clone https://github.com/eyereasoner/color
cd color
./color examples/fourcolor.pl
```
and it will give
```
% running examples/fourcolor.pl
B => true.
C => true.
D => true.
E => true.
F => true.
G => true.
H => true.
I => true.
...
```
When using some other IRI's like in https://github.com/eyereasoner/color/blob/16e313cb787c039627e5682a6f3fd68ef1f5a07f/examples/fourcolor.pl it works https://github.com/eyereasoner/color/blob/16e313cb787c039627e5682a6f3fd68ef1f5a07f/result.pl#L48-L96

_Originally posted by @josd in https://github.com/trealla-prolog/trealla/issues/571#issuecomment-2473846517_

**Comment by infradig** [comment]
I don't understand what i'm seeing here. Can you point out exactly what's wrong and what should be.

**Comment by infradig** [comment]
Never mind, I can see it now.

**Comment by josd** [comment]
Don't you need to sleep ;-)
Happy that you saw it and even more happy that you solved it!
It now works fine and the fourcolor example now gives the expected https://github.com/eyereasoner/color/blob/90c2b595bd21310f98d51bfc11afd5d5955444ca/result.pl#L62-L110
