### ISSUE TITLE
issue with writing lists containing conjunctions

### ISSUE THREAD

**Issue by josd** [trealla-prolog/trealla#633]
We get
```
tpl
?- use_module(library(lists)).
   true.
?- op(1150,xfx,=>).
   true.
?- write([(p(a),p(b) => c(c))]).
[p(a),p(b)=>c(c)]   true.
?- member(X,[p(a),p(b)=>c(c)]).
   X = p(a)
;  X = (p(b)=>c(c)).
?-
```
but expect
```
scryer-prolog
?- use_module(library(lists)).
   true.
?- op(1150,xfx,=>).
   true.
?- write([(p(a),p(b) => c(c))]).
[(p(a),p(b)=>c(c))]   true.
?- member(X,[(p(a),p(b) => c(c))]).
   X = (p(a),p(b)=>c(c)).
?-
```

**Comment by infradig** [comment]
Check the member/2 queries in the two examples, they are not the same!

**Comment by josd** [comment]
Indeed but the problem is not with member but with write which is writing `write([(p(a),p(b) => c(c))]).` wrongly and we pick up that result in another run wrongly.

**Comment by infradig** [comment]
Ah, ok, missed that. As someone over there likes to say, put 'unexpected' after something that is unexpected.

**Comment by josd** [comment]
We need this for our proof_step in eye3 but In the mean time we changed from `[]` to `()` in https://github.com/eyereasoner/eye3/blob/main/etc/output/workplace.pl

**Comment by josd** [comment]
and that is written correctly :-)

**Comment by josd** [comment]
Thanks a lot, it now works fine with `Trealla Prolog (c) Infradig 2020-2024, v2.60.16`.
All other tests work fine too and I'm very impressed with the performance of [workplace-benchmark](https://github.com/mthom/scryer-prolog/discussions/2665#discussioncomment-11353720).
So [scaling it to 30000 emplyees](https://github.com/eyereasoner/eye3/blob/main/etc/workplace-benchmark.pl) is fine and takes about 3 sec for eye3, that is with [proof](https://github.com/eyereasoner/eye3/blob/main/etc/output/workplace-benchmark.pl) and that is also about the same for eye with [explain the reasoning](https://github.com/eyereasoner/eye/blob/master/reasoning/workplace-benchmark/workplace-proof.n3).

**Comment by infradig** [comment]
Does eye3 supercede eye?

**Comment by josd** [comment]
Not yet, but who knows, one day it might🤷
