### ISSUE TITLE
evaluable bigint confusion

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#635]
It looks like `ceiling/1` creates bigints when smallints could do. This can lead to the bigint's pointer being misinterpreted as an integer as with length/2.
```prolog
?- X is ceiling(3.0), between(1, X, N).
   throw(error(domain_error(small_integer_range,3),between/3)).

?- trace, X is ceiling(3.0), length(L, X).
...
[0:0x14d863400:97:f2:fp3:cp0:sp11:hp54:tp6] CALL '$det_length_rundown'(_1,3)
[0:0x14d863400:99:f2:fp3:cp0:sp47284235:hp94568449:tp7] EXIT '$det_length_rundown'([_11,_12,_13,_14,_15,_16,_17,_18,_19,_20|...],3) 
^--- huge alloc!
```

This happens older versions too, so probably unrelated to the other issue from today.

**Comment by infradig** [comment]
I get...
```
$ tpl
?- X is ceiling(3.0), between(1, X, N).
   X = 3, N = 1
;  X = 3, N = 2
;  X = 3, N = 3.
?- 
```

**Comment by infradig** [comment]
And...
```
$ tpl
?- X is ceiling(3.0), length(L, X).
   X = 3, L = [_A,_B,_C].
```

**Comment by guregu** [comment]
Might be something on my end, I'll double check

**Comment by guregu** [comment]
Very strange, I can only trigger it if I load a bunch of my project's modules first. Fresh interpreter is fine. I'll try and isolate it further and report back.

**Comment by infradig** [comment]
Hmm, ceiling/1 can never generate a bigint. It's not in the code to do so.

**Comment by guregu** [comment]
Oh, I think I see a connection now.

```prolog
% blah.pl
blah(2370192597.037).
```

```console
% ~/code/trealla/trealla/tpl blah  
?- X is ceiling(3.0), between(1, X, N).
   throw(error(domain_error(small_integer_range,3),between/3)).
```

Maybe it has to do with the last number parsed?
(edited to a smaller ver)

**Comment by guregu** [comment]
Sweet, looks good now. Appreciate it. Thought I was haunted for a sec there
