### ISSUE TITLE
`initialization` and `multifile` directives

### ISSUE THREAD

**Issue by mnieper** [trealla-prolog/trealla#644]
Consider the files `bar.pl` given by

```prolog
:- include(foo).
:- multifile(foo/0).

foo :- write(bar), nl, halt.
```

and `foo.pl` given by

```prolog
:- initialization(foo).
:- multifile(foo/0).

foo :- fail.
```

Running
```shell
$ tpl bar.pl
```

gives an error that goes away if the `initialization` directive is moved from `foo.pl` to `bar.pl`. The expected result is that the program works regardless where the `initialization` directive is located. See section 7.4.2.6 in the ISO Prolog standard.

**Comment by mnieper** [comment]
Thank you for fixing it so quickly! The example code does work now. However, when `include(foo)` is replaced by `ensure_loaded(foo)`, the error persists.

By ISO Prolog, the goals mentioned in `initialization` directives "shall be executed immediately after the Prolog text has been prepared for execution", and "[the] directive `ensure-loaded(P-text)` specifies that the Prolog text being prepared for execution shall include the Prolog text denoted by `P-text`". In other words, the processing of the `initialization` directive has to be deferred to after `ensure_loaded` as well.

**Comment by mnieper** [comment]
I can confirm that it works now in the cases I tested. Thanks again for your hard work and this wonderful Prolog implementation. I think we can close this issue.

**Comment by infradig** [comment]
Thanks for keeping finding this!
