### ISSUE TITLE
SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by lbuczkow** [trealla-prolog/trealla#65]
I started to play with https://raw.githubusercontent.com/SWI-Prolog/swipl-devel/master/library/clp/clpfd.pl in Trealla, just to see how far I can go without diving into the code. After commenting out a few lines:

```
~/prolog % diff clpfd.pl clpfd_mod.pl
169,171c169,171
< :- public                               % called from goal_expansion
<         clpfd_equal/2,
<         clpfd_geq/2.
---
> %% :- public                               % called from goal_expansion
> %%        clpfd_equal/2,
> %%        clpfd_geq/2.
2884,2887c2884,2887
< :- multifile
<         system:goal_expansion/2.
< :- dynamic
<         system:goal_expansion/2.
---
> %% :- multifile
> %%        system:goal_expansion/2.
> %% :- dynamic
> %%        system:goal_expansion/2.
```

I've got this:

```
~/prolog % tpl clpfd_mod.pl          
Warning: unknown directive: encoding
Warning: unknown directive: create_prolog_flag
Warning: unknown directive: if
Warning: unknown directive: if
zsh: segmentation fault  tpl clpfd_mod.pl
```

And under gdb:

```
Thread 2 received signal SIGSEGV, Segmentation fault.
0x0000000100043598 in find_predicate (m=0x0, c=0x10288dc38) at src/module.c:536
536   miter *iter = map_find_key(m->index, &tmp);
```

The context (src/module.c:536) is:

```
predicate *find_predicate(module *m, cell *c)
{
  cell tmp = *c;
  tmp.tag = TAG_INTERNED;
  tmp.flags = 0;
  tmp.nbr_cells = 1;

  if (is_cstring(c)) {
    tmp.val_off = index_from_pool(m->pl, C_STR(m, c));
  }

  miter *iter = map_find_key(m->index, &tmp);
  predicate *pr = NULL;

  while (map_next_key(iter, (void*)&pr)) {
    if (pr->is_abolished)
      continue;

    map_done(iter);
    return pr;
  }

  map_done(iter);
  return NULL;
}
```

Tested on macos 12.6 with trealla v2.4.24.

**Comment by infradig** [comment]
The status with CLP is this...

1) CLPFD unlikely to get working at all as the SWI hook model is totally
different. Trealla attempts to follow the Sicstus model (see 2 & 3)

The following refer to the Scryer Prolog versions.

2) CLPB is not working

3) CLPZ is partially working, there is a problem with constraint
propagation. When I have time to look at it again I will.

**Comment by infradig** [comment]
$ cat f1.pl
:- use_module(library(clpz)).

n_factorial(0, 1).
n_factorial(N, F) :-
        N #> 0,
        N1 #= N - 1,
        n_factorial(N1, F1),
        F #= N * F1.

$ tpl ~/scryer-prolog/src/lib/clpz.pl f1.pl -g
"n_factorial(5,F),write(F),nl,halt"
120
$

This is not a very interesting example though and doesn't really test
anything much out. This more so...

$ cat .f2.pl
:- use_module(library(clpz)).

n_factorial(0, 1).
n_factorial(N, F) :-
        N #> 0,
        N1 #= N - 1,
        F #= N * F1,
        n_factorial(N1, F1).

But doesn't trigger on the final unification. However...

$ cat f3.pl
:- use_module(library(clpz)).

n_factorial(0, Fresh) :- Fresh = 1.
n_factorial(N, F) :-
        N #> 0,
        N1 #= N - 1,
        F #= N * F1,
        n_factorial(N1, F1).

This does, but incorrectly, and finds nothing queued.

**Comment by guregu** [comment]
TBH I have no idea if this is supposed to work or if it is related to CLPZ, but found this:

```
?- freeze(X, is_list_or_partial_list(X)), append([a], [b], X).
   false. % unexpected?
?- append([a], [b], X), freeze(X, is_list_or_partial_list(X)).
   X = "ab".
```

Maybe more related to #10. Seems to be something funky happening around unification with lists + attrvars.

**Comment by infradig** [comment]
Let's simplify it...

?- freeze(X, nonvar(X)), append([a], [b], X).
   false.   # BAD

?- freeze(X, nonvar(X)), append([a], [b], Y), X = Y.
   X = "ab", Y = X. # GOOD

**Comment by infradig** [comment]
I think without use of a fresh variable the hook is called in the wrong
context.

**Comment by guregu** [comment]
I think the latest changes are causing some memory corruption (at least in the WASM stuff). Still trying to isolate it, shows up as some corrupted string terms and memory access violations.

https://github.com/guregu/trealla/compare/v0.11.1...v0.11.2

This log is from the trealla-prolog/go tests, it seems to only happen after running [`tak.pl`](https://github.com/trealla-prolog/go/blob/main/trealla/testdata/tak.pl), and then another query on the same `*prolog`.

```
=== RUN   TestQuery/tak_&_WithLibraryPath
2022/10/24 16:29:36 query: use_module(library(tak)), run.
2022/10/24 16:29:38 {"result":"success","answer": {}}
2022/10/24 16:29:38 redo: 24585232 use_module(library(tak)), run.
2022/10/24 16:29:36 query: use_module(library(tak)), run.
2022/10/24 16:29:38 {"result":"success","answer": {}}
2022/10/24 16:29:38 redo: 24585232 use_module(library(tak)), run.
=== RUN   TestQuery/bigint
2022/10/24 16:29:38 query: X=9999999999999999, Y = -9999999999999999, Z = 123.

# first indication of problem
2022/10/24 16:29:38 {"result":"\u0000\u0000>\u0000","answer":{"X":{"number":"9999999999999999"},"Z":{"number":"-9999999999999999"},"Z":123}}
    query_test.go:237: trealla: unexpected query status: >

# probably collateral damage from here on
2022/10/24 16:29:38 query: X = [].
    query_test.go:237: trealla: query error: out of bounds memory access
=== RUN   TestQuery/empty_atom
2022/10/24 16:29:38 query: X = foo(bar, '').
    query_test.go:237: trealla: query error: out of bounds memory access
=== RUN   TestQuery/residual_goals
    query_test.go:237: out of bounds memory access
```

`result` here is getting turned into a corrupted string, but the rest of the JSON is fine. Could definitely be my fault with the WASM stuff, just thought I'd report it.
Apologies if this makes zero sense. I'll do some more digging and try to reproduce from native tpl, grab some traces, etc :-)

**Comment by guregu** [comment]
Actually upon looking at that more closely it looks like something's wrong with my redo logic, sorry.
Seems like it's redoing tak twice when it should only happen once.
Here's a normal log:

```
=== RUN   TestQuery/tak_&_WithLibraryPath
2022/10/24 16:52:26 query: use_module(library(tak)), run.
2022/10/24 16:52:28 {"result":"success","answer": {}}
2022/10/24 16:52:28 redo: 24586048 use_module(library(tak)), run.
```

Probably just an issue with the Go stuff 🤔

**Comment by guregu** [comment]
Disabling tpl's optimization with `-O0` avoids the above issue, hmm...

**Comment by infradig** [comment]
Can you go back a bit in the history and identify where it went wrong?

**Comment by guregu** [comment]
Tried a bunch of different cherry-picks and I think I narrowed it down to this commit:
https://github.com/trealla-prolog/trealla/commit/1f9102ded177476c1df55c687eef8591b1f34969

Cherry-picking the freeze/2 fixes is fine (this is OK: 395dea85369fcdb3ec69ab054bd4839e5284a647).

**Comment by infradig** [comment]
Ok, I reversed the only likely looking change candidate and pushed it to
*devel*. If you could try that.

**Comment by guregu** [comment]
It works! Thanks a bunch.
