### ISSUE TITLE
#3: dif/2, findall/3: unexpected overflow

### ISSUE THREAD

**Issue by UWN** [trealla-prolog/trealla#7]
[#3](http://www.complang.tuwien.ac.at/ulrich/trealla-prolog/Item#3)

**Comment by flexoron** [comment]
True.

Processing a finite list of 5994 elements(which are lists with 3 elements).

At the moment I get:

$ tpl
findall/3 Time elapsed 12s

$ tpl
bagof/3  error(resource_error(finite_memory),top_level/0).

But I guess this is an interim stage of tpl development.

**Comment by flexoron** [comment]
"The resource finite_memory is here to indicate that any finite memory would not be enough"
Commenting 'any': This is not true. A creative mathematician discovers (and solves) some of these problems.

**Comment by UWN** [comment]
*Any finite memory* certainly means any finite memory of this processor.
