### ISSUE TITLE
Modulo with negative values 

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#78]
Negative modulo is kind of a weird thing, but it seems like most other systems act differently. Looks like they agree on `rem/2` but differ on `mod/2`.

```prolog
% Trealla
?- X is -1 mod 3.
   X = 1.
?- X is -1 rem 3.
   X = -1.

% Scryer, SWI, Tau
?- X is -1 mod 3.
   X = 2.
?- X is -1 rem 3.
   X = -1.
```

Some discussion here: https://groups.google.com/g/comp.lang.prolog/c/KzOk4NS3c9U/m/llxDdaYwZzUJ

It's easy enough to do a workaround, but maybe we should match up?

**Comment by infradig** [comment]
Running these tests from:

  https://github.com/dtonhofer/prolog_notes/blob/master/swipl_notes/various_code/division_and_remainder.pl

Thanks @dtonhofer

The tests all pass clean as does SWI-Prolog.

Note: I had to fix up a format/3 statement(s) to use list format args. Not
to do so is non-portable SWIism.


$ tpl -g test,halt library/yall.pl ../tpl-stuff/division_and_remainder.pl
( -6 mod 3) =  0, ( -6 div 3) = -2, OK : 3*-2+0=-6
( -5 mod 3) =  1, ( -5 div 3) = -2, OK : 3*-2+1=-5
( -4 mod 3) =  2, ( -4 div 3) = -2, OK : 3*-2+2=-4
( -3 mod 3) =  0, ( -3 div 3) = -1, OK : 3*-1+0=-3
( -2 mod 3) =  1, ( -2 div 3) = -1, OK : 3*-1+1=-2
( -1 mod 3) =  2, ( -1 div 3) = -1, OK : 3*-1+2=-1
(  0 mod 3) =  0, (  0 div 3) =  0, OK : 3*0+0=0
(  1 mod 3) =  1, (  1 div 3) =  0, OK : 3*0+1=1
(  2 mod 3) =  2, (  2 div 3) =  0, OK : 3*0+2=2
(  3 mod 3) =  0, (  3 div 3) =  1, OK : 3*1+0=3
(  4 mod 3) =  1, (  4 div 3) =  1, OK : 3*1+1=4
(  5 mod 3) =  2, (  5 div 3) =  1, OK : 3*1+2=5
(  6 mod 3) =  0, (  6 div 3) =  2, OK : 3*2+0=6

( -6 mod -3) =  0, ( -6 div -3) =  2, OK : -3*2+0=-6
( -5 mod -3) = -2, ( -5 div -3) =  1, OK : -3*1+-2=-5
( -4 mod -3) = -1, ( -4 div -3) =  1, OK : -3*1+-1=-4
( -3 mod -3) =  0, ( -3 div -3) =  1, OK : -3*1+0=-3
( -2 mod -3) = -2, ( -2 div -3) =  0, OK : -3*0+-2=-2
( -1 mod -3) = -1, ( -1 div -3) =  0, OK : -3*0+-1=-1
(  0 mod -3) =  0, (  0 div -3) =  0, OK : -3*0+0=0
(  1 mod -3) = -2, (  1 div -3) = -1, OK : -3*-1+-2=1
(  2 mod -3) = -1, (  2 div -3) = -1, OK : -3*-1+-1=2
(  3 mod -3) =  0, (  3 div -3) = -1, OK : -3*-1+0=3
(  4 mod -3) = -2, (  4 div -3) = -2, OK : -3*-2+-2=4
(  5 mod -3) = -1, (  5 div -3) = -2, OK : -3*-2+-1=5
(  6 mod -3) =  0, (  6 div -3) = -2, OK : -3*-2+0=6

Below with current_prolog_flag(integer_rounding_function,toward_zero)

( -6 rem 3) =  0, ( -6 // 3) = -2, OK : 3*-2+0=-6
( -5 rem 3) = -2, ( -5 // 3) = -1, OK : 3*-1+-2=-5
( -4 rem 3) = -1, ( -4 // 3) = -1, OK : 3*-1+-1=-4
( -3 rem 3) =  0, ( -3 // 3) = -1, OK : 3*-1+0=-3
( -2 rem 3) = -2, ( -2 // 3) =  0, OK : 3*0+-2=-2
( -1 rem 3) = -1, ( -1 // 3) =  0, OK : 3*0+-1=-1
(  0 rem 3) =  0, (  0 // 3) =  0, OK : 3*0+0=0
(  1 rem 3) =  1, (  1 // 3) =  0, OK : 3*0+1=1
(  2 rem 3) =  2, (  2 // 3) =  0, OK : 3*0+2=2
(  3 rem 3) =  0, (  3 // 3) =  1, OK : 3*1+0=3
(  4 rem 3) =  1, (  4 // 3) =  1, OK : 3*1+1=4
(  5 rem 3) =  2, (  5 // 3) =  1, OK : 3*1+2=5
(  6 rem 3) =  0, (  6 // 3) =  2, OK : 3*2+0=6

( -6 rem -3) =  0, ( -6 // -3) =  2, OK : -3*2+0=-6
( -5 rem -3) = -2, ( -5 // -3) =  1, OK : -3*1+-2=-5
( -4 rem -3) = -1, ( -4 // -3) =  1, OK : -3*1+-1=-4
( -3 rem -3) =  0, ( -3 // -3) =  1, OK : -3*1+0=-3
( -2 rem -3) = -2, ( -2 // -3) =  0, OK : -3*0+-2=-2
( -1 rem -3) = -1, ( -1 // -3) =  0, OK : -3*0+-1=-1
(  0 rem -3) =  0, (  0 // -3) =  0, OK : -3*0+0=0
(  1 rem -3) =  1, (  1 // -3) =  0, OK : -3*0+1=1
(  2 rem -3) =  2, (  2 // -3) =  0, OK : -3*0+2=2
(  3 rem -3) =  0, (  3 // -3) = -1, OK : -3*-1+0=3
(  4 rem -3) =  1, (  4 // -3) = -1, OK : -3*-1+1=4
(  5 rem -3) =  2, (  5 // -3) = -1, OK : -3*-1+2=5
(  6 rem -3) =  0, (  6 // -3) = -2, OK : -3*-2+0=6

**Comment by guregu** [comment]
Thanks! Working nicely 🙂
