### ISSUE TITLE
Reconsulting a file

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#89]
I noticed reconsulting a changed file seems to ignore it.

Let's say I have `a.pl` like this:
```prolog
% a.pl
a(1).
```

and then I consult it in tpl:
```console
?- consult(a), a(X).
   X = 1.
```

Then I change `a.pl` to read like this:
```prolog
% a.pl (changed)
a(5).
```

If I reconsult the same file, the predicate doesn't change:
```
?- consult(a), a(X).
   X = 1.
```

However, if I have a file with a different name, say `b.pl`, and the same predicate, it will get overwritten (which is good):
```prolog
% b.pl
a(123).
```

```console
?- consult(b), a(X).
Warning: overwriting a/1
   X = 123.
```

Would it be possible to have this overwriting behavior for the same file, as well? My use-case is exploratory REPL-based development, where I'd be reloading the file with `make/0` in SWI.

This isn't a huge deal because we can always just restart the interpreter, but it'd be a nice little quality-of-life feature to have.

**Comment by infradig** [comment]
Yes, it's wrong and should be fixed.

**Comment by guregu** [comment]
Thanks for the fix! Works nicely 👍
