### ISSUE TITLE
Fast JSON predicates

### ISSUE THREAD

**Issue by guregu** [trealla-prolog/trealla#92]
Problem: `library(json)` is slow: https://github.com/mthom/scryer-prolog/issues/1566

I have a [terrible hacky solution](https://github.com/guregu/trealla/issues/5) that abuses term reading to parse JSON, but I realized that inputs with negative numbers like `{"a":-1}` break it because of the `(:-)/2` operator. I tried to work around it with `op(0, fx, :-)` but that doesn't seem to work and sounds like a bad idea to be constantly altering the ops table anyway.

Some ideas:
- Use a C library. [jsmn](https://github.com/zserge/jsmn) seems pretty good, MIT license and small footprint.
- Use a different Prolog implementation.
  - Logtalk's is Apache license
  - SWI's is BSD
- Hack in an option to ignore certain operators in `read_term_from_chars/3`?

Any of these sound good to you?

**Comment by infradig** [comment]
I have a C parser lying around somewhere from another old project.

**Comment by infradig** [comment]
Although maybe the parser hack option is simplest.

**Comment by guregu** [comment]
Either way works for me!
I should probably mention that another thing needed for the hacky solution is to avoid the `\x00\`-style escapes in `write_term_to_chars`. In my experimental WASM fork I'm currently just #ifdefing that part out, which works fine. Definitely not the cleanest solution but does the trick.

**Comment by infradig** [comment]
I've added a json(boolean) option to bot hread_term, write_term & friends,
it's in devel branch only. See what you can do with this. Let me know or
send patches.

**Comment by guregu** [comment]
@infradig Awesome. It works great! I found one minor issue and sent a patch here: #93 
This new JSON option eliminates most of the weirdness with my fork, so it should be much easier to upstream changes now.
Much appreciated :)
