### ISSUE TITLE
Mathematical check

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#94]
v2.7.15
```
?- X is 6.7.
   X = 6.7.
?- X is 7.7.
   X = 7.7.
?- X is 8.7.
   X = 8.6999999999999993.  % tell me more
?- X is 9.7.
   X = 9.6999999999999993.  % oh well
?- X is 10.7.
   X = 10.7.
?- X is 11.7.
   X = 11.7.
```
```
?- 7.7000000000000008 > 7.7.
   true.
?- 7.7000000000000007 > 7.7.
   true.
?- 7.7000000000000006 > 7.7.
   false. % boo-boo
?-
```

**Comment by infradig** [comment]
Actually Trealla is correct. It could be prettier.

**Comment by flexoron** [comment]
That's how it goes
```
$ ./tpl
Trealla Prolog (c) Infradig 2020-2022, v2.7.15
?- X is 7.7-0.6-0.0000000000000004.
   X = 7.1000000000000005.
?- halt.

$ bc
bc 1.07.1
This is free software with ABSOLUTELY NO WARRANTY.
7.7-0.6-0.0000000000000004
7.0999999999999996
```

**Comment by infradig** [comment]
They both epsilon around the same point that has no exact decimal
representation in floating point. One day I might look at how others pretty
print these things.

**Comment by infradig** [comment]
Or maybe bc uses unlimited precision.

**Comment by flexoron** [comment]
Yes ... perhaps BigDecimal, and maybe worth considering in the (distant) future.

https://github.com/ShigeoKobayashi/bigdecimal/

vpc is written in C and demonstrates how to use this C++ stuff.
```
$ vpc
VPC(Variable Precision Calculator) of Bigdecimal(V11)
  Copyright (c) 2018 by Shigeo Kobayashi. Allrights reserved.

Enter command
? = a 7.7
  a= 0.77E1
? = b 0.6
  b= 0.6E0
? = c 0.0000000000000004
  c= 0.4E-15
? - d a b
  d= 0.71E1
? - e d c
  e= 0.7099999999 9999996E1
? quit
```

**Comment by infradig** [comment]
I don't know of any Prologs that don't use IEEE floats. The ISO standard
doesn't preclude it though.

VPC has two problems,.. 1) it's in C++ but compiled as C, which limits
compilers (no TCC for example). 2) License.

**Comment by flexoron** [comment]
ISO? hmm ...  Idiotic Syndicate Organisation?
Never mind ...  Bankers Trust says: Transfer Bonus!

And you are right: Government says: yes no yes no ... yesno ... yes
