### ISSUE TITLE
Importing a non-existing library causes abort

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [trealla-prolog/trealla#95]
If I remove the use_module/1 of non-existing library I get:
```
?- ['approx.p'].
   true.
```
If I keep the directive, I get:
```
?- ['approx.p'].
malloc(): corrupted top size
Aborted
```
The test case would be:

[approx.p.log](https://github.com/trealla-prolog/trealla/files/10341628/approx.p.log)

**Comment by infradig** [comment]
I don't understand. Can you be more specific.

**Comment by Jean-Luc-Picard-2021** [comment]
Tested with WSL and version 2.7.15 of Trealla.
If I comment out this line in the Prolog text **approx.p**, like so:
```
% :- use_module(library(standard/compat)).
```
All works fine. If I don't comment it out, I get the abort.

My expectation would be rather an error message along **"file**
**not found"**, and not some hard abort based on some malloc() error.

**Comment by flexoron** [comment]
Note: More core dumps
```
$ cat core.pl
:- use_module(library(core/dumps)).

$ tpl core.pl
Error: module file not found: /run/media/nox/Elements SE/T/tools/prolog/trealla/library//
realloc(): invalid next size
Aborted (core dumped)
```
```
$ cat core.pl
:- use_module(library(core/dumps)).
core :- dump.
dump.

$ tpl core.pl
Error: module file not found: /run/media/nox/Elements SE/T/tools/prolog/trealla/library//
Trealla Prolog (c) Infradig 2020-2022, v2.7.15
?- core.
   true.

?- halt.
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
Looks like it is the library (path?) name (abc/xyz), for example just library(xyz) does not crash.
