### ISSUE TITLE
Wrong list rendering

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#96]
```
$ tpl
Trealla Prolog (c) Infradig 2020-2022, v2.7.15

?- L = [a|(b|c)].
   L = [a|b|c]. % unexpected (displayed)
?-
```

**Comment by flexoron** [comment]
I'm afraid there is more about this matter
```
$ trealla/tpl
Trealla Prolog (c) Infradig 2020-2022, v2.7.16
?- L = [a|(b,c)].
   L = [a|b,c]. % ?
?- L = [a|(b;c)].
   L = [a|b;c]. % ?
?-

$ BProlog/bp 
B-Prolog Version 8.1, All rights reserved, (C) Afany Software 1994-2014.
| ?- L = [a|(b,c)].
L = [a|(b,c)]
yes
| ?- L = [a|(b;c)].
L = [a|(b ;  c)]  % interesting to see how an 'old' system replies (related to printing spaces)
yes
| ?-
```

**Comment by flexoron** [comment]
a swipl space (lol)
```
?- L = [a|(b,c)].
L = [a|(b, c)].
```

**Comment by flexoron** [comment]
$ ./tpl
Trealla Prolog (c) Infradig 2020-2022, v2.7.17
?- L = [a|(b;c)].
   L = [a|(b;c)].
?- L = [a|(b,c)].
   L = [a|(b,c)].
?- halt.
$ echo "many thanks"
many thanks
$

**Comment by infradig** [comment]
No worries.

**Comment by infradig** [comment]
Interesting...

~/trealla (devel) $ cxprolog
CxProlog version 0.98.2 [development]
[main] ?- L=[a|(b|c)].
L = [a|(b;c)]
[main] ?- L=[a|(b,c)].
L = [a|(b,c)]
[main] ?- L=[a|(b;c)].
L = [a|(b;c)]
[main] ?-
% CxProlog halted.

**Comment by infradig** [comment]
And...

/trealla (devel) $ ~/XSB/bin/xsb
[xsb_configuration loaded]
[sysinitrc loaded]
[xsbbrat loaded]

XSB Version 5.0.0 (Green Tea) of May 15, 2022
[x86_64-pc-linux-gnu 64 bits; mode: optimal; engine: slg-wam; scheduling: local]
[Build date: 2023-01-03]

| ?- L=[a|(b|c)].
L = [a|(b;c)];
no
| ?-

**Comment by infradig** [comment]
Maybe they define | as a synonym for disjunction for some reason.
